### ISSUE TITLE
Create the OpenCTI connector for default datasets

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#1]
## Problem to Solve

For default datasets such as sectors, countries, regions and cities. An OpenCTI connector can be a good solution to maintain up-to-date entities.

## Current Workaround

Create those entities manually.

## Proposed Solution

Create an OpenCTI connector and the associated datasets.

## Additional Information

None.

**Comment by richard-julien** [comment]
As a replacement for import/export feature of the UI ?

**Comment by jabesq** [comment]
test

**Comment by jabesq** [comment]
test

**Comment by jabesq** [comment]
placeholder
