### ISSUE TITLE
How do I enable connectors in the platform?

### ISSUE THREAD

**Issue by Rickozono** [OpenCTI-Platform/connectors#100]
I configured de yml file and execute the python file.
I see the connectors in the platform but in the "Data Import" sección there aren't any connecteros enabled, how do I enable connectors?
Do I have to do something more?
![Connectors](https://user-images.githubusercontent.com/51711170/80024883-19346580-84b6-11ea-8694-3ca37dbcc77c.jpg)

**Comment by cvdsouza** [comment]
does the worker log show that data is being pulled and parsed and pushed ?

**Comment by Rickozono** [comment]
Sorry but, where can I find the connectors logs?

**Comment by cvdsouza** [comment]
I usually start my worker manually ``` python3 worker/worker.py``` , and observer the logs, which tells me if the data is getting parsed. 


I have noticed that when I start 3 workers, the system detects only 2. But the rabbitMQ shows three consumers and the worker logs show all three working.

**Comment by Rickozono** [comment]
Thanks for your help!
I didn't start the worker, my bad.

**Comment by Rickozono** [comment]
Another question, in the ipinfo config.yml file, is the same token of opencti?
opencti:
  url: 'http://localhost:8080'
  token: 'ChangeMe'

connector:
  id: 'ChangeMe'
  type: 'INTERNAL_ENRICHMENT'
  name: 'IpInfo'
  scope: 'ipv4-addr'
  confidence_level: 3
  log_level: 'info'

**ipinfo:
  token: 'ChangeMe'**
  max_tlp: 'TLP:AMBER'

**Comment by rhaist** [comment]
IpInfo is a commercial service. You need to buy API access from them.

https://ipinfo.io/

**Comment by Rickozono** [comment]
Thanks for your help!
