### ISSUE TITLE
OpenCTI API is not reachable from AlienVault Connector

### ISSUE THREAD

**Issue by jbfeldman** [OpenCTI-Platform/connectors#103]
## Description
I'm looking at developing a connector for openCTI, and I was trying to get the AlienVault connector working so I could understand how it worked and model on it. However, I ran into the error `ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...` 

openCTI appears to be working fine on my machine, it's just that AlienVault can't connect to it. I haven't done any other testing of my openCTI instance API besides just poking around with it in my browser, so entirely possible that something is misconfigured in my instance

For reference, in AlienVault's docker-compose.yml I set `OPENCTI_URL=http://localhost:8080` and `OPENCTI_TOKEN` to the value of `OPENCTI_ADMIN_TOKEN` in my .env file. 

EDIT: using the python client health_check function returns True
Also, I was able to successfully instantiate an instance of OpenCTIConnectorHelper class using the
 my localhost url and OPENTI_ADMIN_TOKEN, and that connector is visible on my front-end. I haven't tested with any of the other official connectors but I strongly suspect that the problem might be with the alienvault connector, not my openCTI instance

EDIT 2: I'm unable to get it to work with any of the dockerized connectors, but just directly running the AlienVault connector with python3 main.py works. 

I think the problem is that my docker containers can't talk to each other. Sudo docker network ls reveals that each connector creates its own bridge network, which might be causing a problem. Can any docker whizzes give me some advice as to how to fix this?
## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: OpenCTI 3.1.0 running docker
3. OpenCTI client: frontend web server running in localhost 
4. AlienVault Connector running standalone in docker

## Reproducible Steps

1. Install  OpenCTI
2. git clone https://github.com/OpenCTI-Platform/connectors.git && cd connectors/alienvault
3. sudo docker-compose up

## Expected Output

AlienVault Connector enabled

## Actual Output

`connector-alienvault_1  | Traceback (most recent call last):
connector-alienvault_1  |   File "main.py", line 7, in <module>
connector-alienvault_1  |     connector = AlienVault()
connector-alienvault_1  |   File "/opt/opencti-connector-alienvault/alienvault/core.py", line 60, in __init__
connector-alienvault_1  |     self.helper = OpenCTIConnectorHelper(config)
connector-alienvault_1  |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 181, in __init__
connector-alienvault_1  |     self.opencti_url, self.opencti_token, self.log_level
connector-alienvault_1  |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 111, in __init__
connector-alienvault_1  |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
connector-alienvault_1  | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...`

**Comment by rhaist** [comment]
Hi. I usually run into this when opencti itself has not started properly yet. So:

1. elastic needs to start completely
2. grakn needs to start without throwing an error
3. check opencti if its started and lets you log in.

I check the log output of those containers with `docker logs <container name>`.

Hope that helps.

**Comment by jbfeldman** [comment]
@rhaist thanks for the tip. Grakn logs look good. Found this in the elasticsearch logs which doesn't look good

`{"type": "server", "timestamp": "2020-04-23T21:33:11,357Z", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "docker-cluster", "node.name": "bbe7225dc6c7", "message": "All shards failed for phase: [query]", "cluster.uuid": "9KXfECBmQ2eCVzrDaYQlDA", "node.id": "8Gai8jIzTLm2MjAqEwjdWw" , 
"stacktrace": ["org.elasticsearch.index.query.QueryShardException: No mapping found for [entity_type.keyword] in order to sort on",
"at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:403) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:153) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.search.SearchService.parseSource(SearchService.java:775) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.search.SearchService.createContext(SearchService.java:600) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:554) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:351) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:343) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:146) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.2.jar:7.6.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:830) [?:?]"] }
`

**Comment by rhaist** [comment]
If you use the example docker-compose.yml from the repo:

https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml

all containers should be together in the `default` network. If you want to create your own custom network you can follow the guide over here:

https://docs.docker.com/compose/networking/#specify-custom-networks

**Comment by jbfeldman** [comment]
@rhaist I was specifically trying to avoid the first solution bc during development I won't have a prebuilt image on dockerhub to pull from for my new connector. But the second solution seems feasible, I'll consider this closed

**Comment by anavitgo** [comment]
I am having the same problem! Can't make the AlienVault connector talk to the opencti container, even though that I have created a custom network just like rhaist indicated above.
