### ISSUE TITLE
[misp-connector] current_page type None

### ISSUE THREAD

**Issue by valpet93** [OpenCTI-Platform/connectors#1037]
## Description

testing the latest commit version of misp connector rolling version I faced a problem that restarts the container. I think a control on the type has to be placed in line 423.

## Environment

1. OS: Centos 7
2. OpenCTI docker version: 5.5.4
4. Other environment details: both opencti/connector-misp:5.5.4 and opencti/connector-misp:rolling

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run docker Opencti 5.5.4
2. Run MISP with just one feed and one event
3. Compose the connector at rolling release (5.5.4 suffers a bug fixed with latest github commint only)

## Expected Output

Start flawlessly: no restarts

## Actual Output

Connector keeps restarting.
These are the logs from container:
Here the log from container:

```
Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 2151, in <module>
    mispConnector.run()
  File "/opt/opencti-connector-misp/misp.py", line 423, in run
    current_state["current_page"] = current_page
TypeError: 'NoneType' object does not support item assignment
Terminated
```

**Comment by Bella-chris** [comment]
I have a similar issue and I'd like to know why it is not ingesting:
![image](https://user-images.githubusercontent.com/92671957/220992435-4082c66f-fb9a-49ca-a615-bb2259239943.png)

**Comment by human4357** [comment]
Received error using the 5.5.4 connector as noted in #1040
Upon upgrading to rolling release the same issue is received as above. 

Issue also noted on the commit (https://github.com/OpenCTI-Platform/connectors/commit/624a6d0c2b727c8377ead8f52d41995237432cea)
