### ISSUE TITLE
Mitre Connector is not ingesting data 

### ISSUE THREAD

**Issue by Bella-chris** [OpenCTI-Platform/connectors#1039]
## Description

I have a single node setup for my OpenCTI and Mitre Att&ck connector like the below in the docker-compose.yml:
  connector-mitre:
    image: opencti/connector-mitre:5.5.4
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=uuid v4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE Datasets
      - CONNECTOR_SCOPE=tool,report,malware,identity,campaign,intrusion-set,attack-pattern,course-of-action,x-mitre-data-source,x-mitre-data-component,x-mitre-matrix,x-mitre-tactic,x-mitre-collection
      - CONNECTOR_CONFIDENCE_LEVEL=75
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_INTERVAL=1 # In days
    restart: unless-stopped 

The connector container is running and there is no error logs, however; I can't find any mitre information in my platform:
![image](https://user-images.githubusercontent.com/92671957/221026974-52adbb56-cea4-44da-98a0-9d88af60576e.png)

Connector successfully running logs:
![image](https://user-images.githubusercontent.com/92671957/221027169-c12973e2-d81d-46f2-8059-14e307aeec01.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.6 LTS
2. OpenCTI version: OpenCTI 5.5.4
3. OpenCTI client: docker single node

Please let me know: 
1. Why I can't find any Mitre info
2. If Mitre connector is running should it reflect in the Threat Actor tab? or it will remain empty like the below:
![image](https://user-images.githubusercontent.com/92671957/221028504-e368ca80-814c-4a46-98a8-0797b6e213a5.png)

**Comment by Bella-chris** [comment]
@nor3th @richard-julien @SamuelHassine

**Comment by ckane** [comment]
mitre connector populates the Intrusion Sets, Attack Patterns, and other data sets. There will be no Threat Actors created by it. Here is OASIS documentation that attempts to explain why these are "Intrusion sets" and not "Threat actors": https://oasis-open.github.io/cti-documentation/examples/defining-campaign-ta-is.html

**Comment by ckane** [comment]
Check Intrusion Sets, Attack Patterns, and also the Analysis Reports, to see if data is being consumed from the MITRE source

**Comment by Bella-chris** [comment]
@ckane Thank you for this elaboration. I believe connector is working, I'll proceed with closure :)
