### ISSUE TITLE
MISP Instance Key

### ISSUE THREAD

**Issue by Woody90** [OpenCTI-Platform/connectors#104]
What kind of value should be put as "MISP Key", and how to get it?

**Comment by Woody90** [comment]
So do I have to deploy and install MISP from scratch, to have a web interface, in order to get a key ?

**Comment by rhaist** [comment]
I don't know if I understand you correctly. As MISP is an PHP application there is no headless version of it. Any MISP instance should have a web-ui. Also any normal user on a MISP platform has an API key. 

Just log into the MISP instance you want to import into OpenCTI and go to the Automation page.

**Comment by Woody90** [comment]
I tried PyMISP, as per your suggestion, but I still need a MISP URL to access the automation page. I tried the same localhost as MISP URL which I installed PyMISP on it (OpenCTI server), but it does not seem to work that way. That is why I am wondering if I will need a standalone MISP server, and deploy it from scratch, like OpenCTI.

**Comment by cvdsouza** [comment]
Yes you need a standalone MISP server that has events in it , OR access to a MISP server with an account and an automation key. For details please see here : https://www.circl.lu/doc/misp/automation/#automation-key

The MISP server can be deployed on the same server as OpenCTI via docker but I wouldn't recommend it, as it can impact performance.

**Comment by Woody90** [comment]
Thank you cvdsouza and rhaist
