### ISSUE TITLE
[CrowdStrike] Sometimes, PDF is not attached to the report

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#1048]
## Use case

[CrowdStrike] Sometimes, PDF is not attached to the report. Be sure that we get the PDF each time is possible.

**Comment by nino-filigran** [comment]
@rlynch-ironnet I see that I some point, you worked on this connector (https://github.com/OpenCTI-Platform/connectors/commit/1209140f78eb9a16baea36b463112afb4191c79e) would you mind having a look at this connector?

**Comment by helene-nguyen** [comment]
It will be fixed by #2154
