### ISSUE TITLE
Python Math Error: 'NoneType' object is not subscriptable, while enabling connectors

### ISSUE THREAD

**Issue by Woody90** [OpenCTI-Platform/connectors#105]
I have OpenCTI interface up and running. As well as worker, but every time I try to enable any connector, I got below error.
![Error01](https://user-images.githubusercontent.com/6297379/80198044-d393ac00-861f-11ea-8a8a-5658e4117e53.PNG)

**Comment by rhaist** [comment]
If you want to start the connector from the commandline please make sure you copy the `config.yml.sample` to `config.yml` and fill in the necessary details.

**Comment by Woody90** [comment]
Yes, I have already done that, it does not work.

Here is the config.yml 
[Config.txt](https://github.com/OpenCTI-Platform/connectors/files/4530006/Config.txt)

**Comment by SamuelHassine** [comment]
Hello @Woody90,

I know the error is not really helpful, can you just confirm that your OpenCTI is running on localhost:4000 and the token is correct?

**Comment by Woody90** [comment]
@SamuelHassine 
Yes, confirmed.
OpneCTI is running on localhost:4000
Token is correct.

**Comment by rhaist** [comment]
I can only guess from this data, sorry.
Every connector has python3 requirements did you install all of them?

**Comment by 15271843622** [comment]
Python3 and components are installed correctly, but this problem is also encountered
![mite error](https://user-images.githubusercontent.com/41221477/83600192-9caaa180-a5a0-11ea-8f19-8caf33691677.png)
![cve error](https://user-images.githubusercontent.com/41221477/83600196-9ddbce80-a5a0-11ea-97fb-c08d4bcb09f4.png)

**Comment by SamuelHassine** [comment]
Hello, please @15271843622 can you copy/paste here your `config.yml` file?

**Comment by SamuelHassine** [comment]
Solved in the upcoming V4.
