### ISSUE TITLE
Error collecting MISP events

### ISSUE THREAD

**Issue by G4fanhoto** [OpenCTI-Platform/connectors#1050]
Good morning people, everything fine ?

I'm having trouble collecting MISP events for openCTI I have this error in the console, if anyone can guide me, thank you

![image](https://user-images.githubusercontent.com/122449332/222911049-6809d8a8-c0f5-40b2-93d9-d788ee02eaf4.png)

![image](https://user-images.githubusercontent.com/122449332/222910496-a82b27d0-6d44-40cb-a137-da3ccdb25c2f.png)

#

**Comment by RonV666** [comment]
same error for me. I see https://github.com/OpenCTI-Platform/connectors/issues/1052 seems to be the same, closed but no comments ?!

**Comment by buzz13** [comment]
My bad. Iclosed #1052. After cleared all the works for the MISP connector and reseted connector state error changed into the same as #1040 , #1045 , #1050.

**Comment by SamuelHassine** [comment]
Hello,

This is a known issue which has been solved in 5.6.2.

Kind regards,
Samuel
