### ISSUE TITLE
MISP Connector with thousands of events

### ISSUE THREAD

**Issue by alirf81** [OpenCTI-Platform/connectors#1063]
I am using MISP connector and my MISP instance has more than 7000 events with around 100 new events daily.
Creating the first `work` takes time (more than 1 day) to import all existing events with more than 140 pages and 17 million operations.
If new events are added while creating this first `work`, would it miss some of those recent events?

**Comment by SamuelHassine** [comment]
Hello,

Depending on your import start date, the first work can be huge. But we've enhanced the connector in 5.6.2 so you will not miss any event.

Kind regards,
Samuel
