### ISSUE TITLE
external-import/mandiant : Fix start_epoch proposal

### ISSUE THREAD

**Issue by cyrilyxe** [OpenCTI-Platform/connectors#1072]
## Description
Hello,
The variable start_epoch used in the APIv4 request is sometime empty (empty string) but the API require an **int** that is equal or greater to **1,167,609,600**

- The log message :

![error](https://user-images.githubusercontent.com/57862760/227493933-dfb82cbf-af1d-48fc-83ca-fd49eaa3c91e.PNG)
- The bad request message (params obtained from debug messages set before and after the query in the def '**_query**' :
![error_bad_request](https://user-images.githubusercontent.com/57862760/227493902-5fbc2fed-5b94-4d54-9306-e50bf8f9c817.PNG)

I fixed it and proposed a merge request but blocked by circle,
Cause i am not familiar with git and my local docker image work, i rather propose you the code here :

1. Add the func :

```
def parseInt(valInput, valDefault = 0):
    if isinstance(valInput,int):
        valOutput = valInput
    elif isinstance(valInput,str):
        valOutput = int(valInput.strip() or valDefault)
    else:
        valOutput = valDefault
    return valOutput
```
Call it at line 619, 711 and 855
Example line 855 : `start_epoch = current_state["report"]` change to `start_epoch = parseInt(current_state["report"], 1167609600)`

2. I also proposed to add an other error message more detailed at line 170~

from
```
        else:
            result = r.json()
            if result and "error" in result:
                if "future" in result["error"]:
                    return None
            raise ValueError("An unknown error occurred")
```
to 
```
        else:
            result = r.json()
            if result and "error" in result:
                if "future" in result["error"]:
                    return None
                if "message" in result["error"]:
                    raise ValueError((result["error"])["message"])
                else:
                    raise ValueError("An unknown error occurred")
```

## Environment

1. OS (where OpenCTI server runs): _red hat_
2. OpenCTI version: _OpenCTI 5.5.2_
3. OpenCTI client: _frontend_
4. Other environment details: _Mandiant Connector 5.6.2_

## Reproducible Steps
just red the logs message in Debug from the container, extract the parameters or value that may cause the issue and fixed it

## Expected Output

No errors caused by a wrong start_epoch

## Actual Output

Errors caused by a wrong start_epoch configuration/manipulation

**Comment by SamuelHassine** [comment]
Solved in 5.11.
