### ISSUE TITLE
[VirusTotal] Changing Observable ID in case of merging

### ISSUE THREAD

**Issue by reset2277** [OpenCTI-Platform/connectors#1099]
## Description

In case of multiple hashes for one file without any relation between them the VirusTotal connector tries to merge them but after that the ID of hash (where was the enrichment applied) is changed. 
It cause that the page shows _This page is not found on this OpenCTI application._ error.

Solution is to find newly created Observable object and reapply enrichment. 

## Environment

1. OS (where OpenCTI server runs): Docker Ubuntu
2. OpenCTI version: OpenCTI 5.6.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open Observable of File type
2. Click on Enrichment
3. Apply VirusTotal

## Expected Output

Switch to newly created Observable automatically without Error

## Actual Output

ERROR
This page is not found on this OpenCTI application.

## Additional information
After the merge is done, additional steps of enrichment cannot be applied on non-existent Observable and that raised an error in log file.

**Comment by SamuelHassine** [comment]
Issue tracked here: https://github.com/OpenCTI-Platform/opencti/issues/2078.
