### ISSUE TITLE
Developing new connectors

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/connectors#110]
This is not a bug request but a question. I just dont know where to post... 

Hi, I am planning to develop a connector. and looking at example of IPInfo connector and I have a few question, hope you can help addressing.

1. `_process_message` function
- here is defination 

```
def _process_message(self, data):
        entity_id = data["entity_id"]
        observable = self.helper.api.stix_observable.read(id=entity_id)

```

- but while calling, I dont see you put `data` parameter as defined.
`       self.helper.listen(self._process_message)`

2. The `self.helper.listen` method
- While running this, it will lookup for all current observable in database and search them on Ipinfo, is this correct? On virustotal, if these data exit, will it create related indicators?
- So is there any time interval or something like this to config?? I make a testing by creating 3 observable only and using IPINFO and VIRUSTOTAL connectors in my env. But I am not sure when I will have enrichment data.

Thanks a lot.

**Comment by phucsnguyenv** [comment]
I am also taking a look at this https://github.com/OpenCTI-Platform/connectors/pull/107 as well

**Comment by richard-julien** [comment]
Hi @phucsnguyenv , 

* but while calling, I dont see you put data parameter as defined.
A lot of mechanics are done under the hood by the helper by defining your connector as a INTERNAL_ENRICHMENT connector. At startup the connector will create a specific queue in rabbitMQ to listen elements defined in the configured scope (ipv4-addr for ipinfo). Then your connector just have to call the self.helper.listen(self._process_message) function that will give you a callback to every messages that openCTI will push in your connector queue. So for IpInfo, every creation of ipv4-addr element.

* While running this, it will lookup for all current observable in database and search them on Ipinfo, is this correct?
Like explained just before your connector will received un def _process_message(self, data) every element created in the platform according to your scope config.

* On virustotal, if these data exit, will it create related indicators?
In fact its up to you to create/delete/update elements in the platform according to the event you received.

* So is there any time interval or something like this to config?? I make a testing by creating 3 observable only and using IPINFO and VIRUSTOTAL connectors in my env. But I am not sure when I will have enrichment data.
The helper listen a queue so no need for a time interval, its an event stream

Hope this help.

**Comment by phucsnguyenv** [comment]
Hi @richard-julien , 

Thanks for your explanation. 
In short, if I run an INTERNAL_ENCRICHMENT with scope `ipv4-addr`, so everytime I add an observable  type `ipv4-addr` it calls the `self.helper.listen(self._process_message)` with data is the element that has just been created. The same thing will happen with other scope config. 

I think I can understand this scenario. Thank you very much.
