### ISSUE TITLE
Create an enrichment connector for urlscan.io

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#1103]
## Use case

Create an enrichment connector for urlscan.io.

**Comment by sudesh0sudesh** [comment]
I have partially built the connector, I can make a pull request after completion,but not specific to language_refs. It is mainly for URL submission and extracting information from the submission

**Comment by nino-filigran** [comment]
Please feel free to do so. As mentioned here, since we plan to work on it anyway, you work may be helpful !
