### ISSUE TITLE
[TheHive] Reword the connector to import case as case and ease migration

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#1104]
## Use case
Need to cover TheHive4 and TheHive5.

`**MVP:**`
- [ ] Import TheHive Cases as OpenCTI Cases with all attributes (except
- [ ] Import TheHive Tasks (possible ressource : https://docs.thehive-project.org/thehive/api/task/create/)
- [ ] Import the possible status of a TheHive tasks as a Status Template
    - Info:The `status` can be `Waiting`, `InProgress`, `Completed` or `Cancel`.
- [ ] Link imported Cases and Tasks in OpenCTI
- [ ] Import TheHive Observables linked to TheHive Cases as Observables contained in OpenCTI Cases
See associated Notion page for more details

**Comment by Jipegien** [comment]
description updated

**Comment by SamuelHassine** [comment]
Issue solved by multiple enhancements in 5.8.4.
