### ISSUE TITLE
taxii2.py fails to get date_added from manifest since objects list is empty, since version 5.7.0

### ISSUE THREAD

**Issue by af3i3** [OpenCTI-Platform/connectors#1123]
## Description

TAXII feed only works in version 5.6.2. I cannot get it to run in the latest versions post 5.7.0. 5.7.3 didn't fix it. I tried modifying some things myself, but did not work still.
In general, it is not getting the object by ID from line 271.
When you print out the manifest variable, it says `objects: []`, even though if you print out the variable at line 270, it gives you the last IOC information with an `id` that is supposed to be used in the following variable.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04, OpenCTI is dockerized.
2. OpenCTI version: 5.7.3
3. OpenCTI client: 5.7.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Modify the docker-compose.yml for the taxii2 connector to fit the requirements
2. run `docker-compose -f connectors/external-import/taxii2/docker-compose.yml up --build`
3. After running a while, it will show the error message.

## Expected Output

Expected output shall be the message about re-running it after X amount of hours.

## Actual Output

```
connector-taxii2_1  | Traceback (most recent call last):
connector-taxii2_1  |   File "/opt/opencti-taxii2/taxii2.py", line 379, in <module>
connector-taxii2_1  |     raise e
connector-taxii2_1  |   File "/opt/opencti-taxii2/taxii2.py", line 377, in <module>
connector-taxii2_1  |     taxii2Connector.run()
connector-taxii2_1  |   File "/opt/opencti-taxii2/taxii2.py", line 157, in run
connector-taxii2_1  |     self.poll_all_roots(coll_title)
connector-taxii2_1  |   File "/opt/opencti-taxii2/taxii2.py", line 189, in poll_all_roots
connector-taxii2_1  |     self.poll_entire_root(root)
connector-taxii2_1  |   File "/opt/opencti-taxii2/taxii2.py", line 218, in poll_entire_root
connector-taxii2_1  |     self.poll(coll)
connector-taxii2_1  |   File "/opt/opencti-taxii2/taxii2.py", line 276, in poll
connector-taxii2_1  |     date_added = manifest["objects"][0]["date_added"]
connector-taxii2_1  | IndexError: list index out of range
connector-taxii2_1  | Terminated
```

## Additional information

I've tried modifying the taxii2.py and running it with `build: .` however it takes a while to debug.
I've tried to do the following:
```
if not manifest["objects"]:
    continue
```
before the date_added line. Skips everything
I tried writing out the last object, and it does see the indicator alongside the id, which is used for get_manifest. However, get_manifest is returning nothing, the objects list is empty, which is being used by date_added -> completely failing -> terminating. 

```
connector-taxii2_1  | {"timestamp": "2023-05-02TXX:XX:XX.XXXXXXZ", "level": "INFO", "name": "pycti.connector", "message": "{'type': 'bundle', 'objects': []}"}
```

This is acquired by doing the following after manifest is set:
```
self.helper.log_info(
  f"{manifest}"
)
```

**Comment by annoyingapt** [comment]
Hey, is the taxii server you are using public? Can you post a redacted version of the variable? Do other taxii servers work?

**Comment by af3i3** [comment]
Unfortunately no, it's paid. Do you have a sample of a free taxii server? I guess I can try it with the AlienVault taxii. However, I've seen some stix json files out there, but they're not technically servers.
Which variable are you referring to?
`last_obj` on line 270 has data on it.
`collection` parameter has data in it as well, however on 271, when it passes the ID of the last_obj to the get_manifest, the result of line number 272 `manifest["objects"]` is empty, hence why it says `list index out of range` as it cannot get `[0]`

Maybe what I can do is use 5.6.2, but I've had some issues with OpenCTI not displaying IOCs from that collection in the feed that you can expose as a file. Same with the CVEs, can't search them right, as they're aggregated. I'm assuming this is fixed in the 5.7.X versions, but yeah.
I'll run some tests and debugs with the raw data and see if I can patch it perhaps to work with the service I'm using. I wonder if they have a different keyword somewhere.

**Comment by annoyingapt** [comment]
Ah, im wondering if manifest["objects"] only has a single object in it. Can you confirm?

**Comment by annoyingapt** [comment]
Whats data is in the variable manifest, is there anything else if objects? Just confirming as well, is this the first time manifest is being run? By that I mean is it running a few times but failing on a certain indicator?

**Comment by annoyingapt** [comment]
does it look something like this?
{
  "more": false,
  "next": 0,
  "objects": [
    {
      "id": "indicator--29aba82c-5393-42a8-9edb-6a2cb1df070b",
      "date_added": "2016-11-04T03:04:05.000Z",
      "version": "2016-11-03T12:30:59.000Z",
      "media_type": "application/stix+json;version=2.1"
    },
    {
      "id": "indicator--ef0b28e1-308c-4a30-8770-9b4851b260a5",
      "date_added": "2016-11-04T10:29:06.000Z",
      "version": "2016-11-04T10:29:06.000Z",
      "media_type": "application/stix+json;version=2.1"
    },
    {
      "id": "indicator--ef0b28e1-308c-4a30-8770-9b4851b260a5",
      "date_added": "2016-11-04T10:29:06.000Z",
      "version": "2017-01-22T00:00:00.000Z",
      "media_type": "application/stix+json;version=2.1"
    }
  ]
}

**Comment by annoyingapt** [comment]
Sorry my bad, you mentioned that before. Apparently this is normal. I need to think this through, I might be able to use the created date, but I don't want to skip any indicators. Use 5.6.2 in the meantime, it doesn't have pagination, so it will only pull the first 100 then drop the rest. You might be able to increase the poll frequency, so you are less likely to reach over 100.
http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#_Toc496542742

**Comment by annoyingapt** [comment]
The idea about this portion of code is to grab a date to use to search after for the next query. filters["added_after"] will need a date before get_objects can run again.

**Comment by af3i3** [comment]
Hmm alright, I might try to see if I can do anything about it as well, but the reason I wanted to use the latest version was because in OpenCTI, this specific feed gets bundled in specific locations, thus rendering it un-searchable via the OpenCTI UI. For example, exposing the feed via Data Sharing -> Feeds (CSV). It was only able to show like 4 indicators instead of the whole thing. I wonder if it's because it's containing the indicators within "folders" or "bundles"? I wonder if the pagination feature would solve this issue.
I'll see what I can do to get around it for now. I'll dedicate some hours towards it later today.

**Comment by annoyingapt** [comment]
Pretty sure OpenCTI latest version will work fine with taxii connector v5.6.2. I haven't tried it though.

**Comment by annoyingapt** [comment]
I'll keep you posted on how it is going.

**Comment by annoyingapt** [comment]
@af3i3 can you hit me up on the Filigran Slack
