### ISSUE TITLE
Export a report(as json/stix) throws error

### ISSUE THREAD

**Issue by itayas123** [OpenCTI-Platform/connectors#1129]
When trying to export a report I get this error:
![image](https://github.com/OpenCTI-Platform/connectors/assets/51032370/dcd2b9c8-3276-4118-a87f-b5510394bbe0)

probably the error comes from the connector that uses pycti

**Comment by SamuelHassine** [comment]
Hello,

This is a bug and this has been fixed in 5.10.0.
