### ISSUE TITLE
TheHive connector is not working properly after upgrading opencti platform

### ISSUE THREAD

**Issue by iman006** [OpenCTI-Platform/connectors#1133]
## Description

The hive connector is not working properly after upgrading opencti platform ، the hive connector and pycti from version 5.5.3 to 5.7.4 and the cases created in the hive platform are not being transferred to opencti.
@SamuelHassine 
## Environment

1. OS (where OpenCTI server runs): { ubuntu 20.04 }
2. OpenCTI version: { OpenCTI 5.7.4 }
3. OpenCTI client: { 5.7.4 }
4. TheHive connector version: { 5.7.4 }

## Expected Output

Transfer cases form TheHive platform to OpenCTI as before on version 5.5.3

## Actual Output

Cases created in the hive platform are not being transferred to opencti

## Additional information
TheHive connector logs: 
{"timestamp": "2023-05-13T05:57:18.848109Z", "level": "INFO", "name": "pycti.connector", "message": "Connector state has been remotely reset to: \"None\""}
{"timestamp": "2023-05-13T05:57:54.360621Z", "level": "INFO", "name": "pycti.connector", "message": "Connector has no last_case_date"}
{"timestamp": "2023-05-13T05:57:54.361082Z", "level": "INFO", "name": "pycti.connector", "message": "Get cases since last run (2022-01-01 08:00:00)"}
{"timestamp": "2023-05-13T05:57:54.363632Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Starting new HTTP connection (1): 10.17.32.60:9000"}
{"timestamp": "2023-05-13T05:57:54.697486Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://10.17.32.60:9000 \"POST /api/case/_search?range=0-100&sort=updatedAt HTTP/1.1\" 200 None"}
{"timestamp": "2023-05-13T05:57:54.849382Z", "level": "INFO", "name": "pycti.api", "message": "Initiate work for 41e0d791-b602-4b23-872a-4c4b84faeff3"}
{"timestamp": "2023-05-13T05:57:54.853058Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Resetting dropped connection: opencti"}
{"timestamp": "2023-05-13T05:57:55.465877Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 97"}
{"timestamp": "2023-05-13T05:57:55.647430Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Starting new HTTP connection (1): 10.17.32.60:9000"}
{"timestamp": "2023-05-13T05:57:55.755297Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://10.17.32.60:9000 \"POST /api/case/artifact/_search?range=all HTTP/1.1\" 200 None"}
{"timestamp": "2023-05-13T05:57:55.757409Z", "level": "ERROR", "name": "pycti.connector", "message": "'message'"}
{"timestamp": "2023-05-13T05:57:55.757753Z", "level": "INFO", "name": "pycti.connector", "message": "Connector successfully run, storing last_run as 1683957474"}
{"timestamp": "2023-05-13T05:57:55.758040Z", "level": "INFO", "name": "pycti.api", "message": "Reporting work update_received work_41e0d791-b602-4b23-872a-4c4b84faeff3_2023-05-13T05:57:54.868Z"}
{"timestamp": "2023-05-13T05:57:56.361053Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 107"}
{"timestamp": "2023-05-13T05:57:59.102709Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 126"}
{"timestamp": "2023-05-13T05:58:39.108404Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Resetting dropped connection: opencti"}
{"timestamp": "2023-05-13T05:58:39.573400Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 126"}
{"timestamp": "2023-05-13T05:58:56.376630Z", "level": "INFO", "name": "pycti.connector", "message": "Connector last_case_date: 2023-05-13 05:57:54"}
{"timestamp": "2023-05-13T05:58:56.377016Z", "level": "INFO", "name": "pycti.connector", "message": "Get cases since last run (2023-05-13 05:57:54)"}
{"timestamp": "2023-05-13T05:58:56.379962Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Starting new HTTP connection (1): 10.17.32.60:9000"}
{"timestamp": "2023-05-13T05:58:56.666313Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://10.17.32.60:9000 \"POST /api/case/_search?range=0-100&sort=updatedAt HTTP/1.1\" 200 None"}
{"timestamp": "2023-05-13T05:58:56.668905Z", "level": "INFO", "name": "pycti.api", "message": "Initiate work for 41e0d791-b602-4b23-872a-4c4b84faeff3"}
{"timestamp": "2023-05-13T05:58:56.671606Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Resetting dropped connection: opencti"}
{"timestamp": "2023-05-13T05:58:58.069997Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 97"}
{"timestamp": "2023-05-13T05:58:58.072288Z", "level": "INFO", "name": "pycti.connector", "message": "Connector successfully run, storing last_run as 1683957536"}
{"timestamp": "2023-05-13T05:58:58.072593Z", "level": "INFO", "name": "pycti.api", "message": "Reporting work update_received work_41e0d791-b602-4b23-872a-4c4b84faeff3_2023-05-13T05:58:57.091Z"}
{"timestamp": "2023-05-13T05:58:58.162840Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 107"}
{"timestamp": "2023-05-13T05:59:19.579998Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "Resetting dropped connection: opencti"}
{"timestamp": "2023-05-13T05:59:23.906848Z", "level": "DEBUG", "name": "urllib3.connectionpool", "message": "http://opencti:8080 \"POST /graphql HTTP/1.1\" 200 126"}

## Screenshots
![Capture](https://github.com/OpenCTI-Platform/connectors/assets/79222802/9c5ce391-c3bc-41f5-8031-4b9a8a87a906)

**Comment by iman006** [comment]
@SamuelHassine

**Comment by iman006** [comment]
> Remembered having this issue with Thehive It happens when a Thehive Observable has no description, the connector is trying to retrieve `observable["message"]` (which is its description).
> 
> ![image](https://user-images.githubusercontent.com/127124531/239477308-1cd6abbf-0138-42f1-b8bd-1e18383dc5eb.png)
> 
> You can hotfix this issue by adding a custom Description on your Thehive instance > case > observable but they should implement a check to verify that the object has a "message" field

@FormindMPO Thanks for your guidance in resolving my issue. The problem was solved exactly through this method 👍 :)

**Comment by SamuelHassine** [comment]
Issue solved by multiple enhancements in 5.8.4.
