### ISSUE TITLE
[import-file-stix] Bug: STIX 1.1 XML Files can't be imported

### ISSUE THREAD

**Issue by CyberKaizen** [OpenCTI-Platform/connectors#1139]
## Description

One of our analysts tried to upload a STIX file from the CISA advisory for PaperCut. CISA is still using STIX 1.1. So the connector needs to convert the file to 2.x.

The problem is that any file ending with .xml is not allowed to be imported. Even when the correct mime type is configured on the connector.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
3. OpenCTI version: OpenCTI 5.6.2
4. OpenCTI client: { e.g. frontend or python }
5. Other environment details: Dockerized

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import a STIX 1.1 XML file at the Data Import and Analyst Workbenches page.
2. Attempt to import the STIX 1.1 file

## Expected Output

It is expected that the import button is not greyed out for XML files.

## Actual Output

The import button is greyed out, therefore there is no way import the STIX 1.1 XML file.
![image](https://github.com/OpenCTI-Platform/connectors/assets/78124503/ce8caba5-dd42-433f-982d-89c694da6c0d)

## Additional information

When I use this Github project: https://github.com/oasis-open/cti-stix-elevator to convert the STIX 1.1 file to STIX 2.1, I'm able to then import it into OpenCTI, but only because it is a JSON file.

**Comment by CyberKaizen** [comment]
I just test that this issue is also present on the latest release, 5.7.4 at the time of writing.

**Comment by SamuelHassine** [comment]
Did you try to put text/xml or application/xml in your connector scope?

**Comment by SamuelHassine** [comment]
https://github.com/OpenCTI-Platform/connectors/commit/1dd6e3da67d0d188f22e127dcfac251bce7f504b
