### ISSUE TITLE
external-import/taxii2 : 

### ISSUE THREAD

**Issue by abangsihar** [OpenCTI-Platform/connectors#1140]
## Description

Hello,
I got an error many time during the running of taxii2 connector;
Please help.

Here is the logs:
```
INFO Listing Threat-Actors with filters null. | timestamp=2023-05-19T15:06:38.574711Z name=pycti.entities
INFO Listing Threat-Actors with filters null. | timestamp=2023-05-19T15:06:38.666957Z name=pycti.entities
INFO Connector registered with ID: 19b852a1-1237-4628-a11c-c1ccd170e681 | timestamp=2023-05-19T15:06:38.927774Z name=pycti.connector
INFO Starting ping alive thread | timestamp=2023-05-19T15:06:38.928262Z name=pycti.connector
INFO Connector has never run | timestamp=2023-05-19T15:06:40.067894Z name=pycti.connector
Traceback (most recent call last):
  File "/opt/opencti-taxii2/taxii2.py", line 375, in <module>
    raise e
  File "/opt/opencti-taxii2/taxii2.py", line 373, in <module>
    taxii2Connector.run()
  File "/opt/opencti-taxii2/taxii2.py", line 154, in run
    root_path, coll_title = collection.split(".")
ValueError: too many values to unpack (expected 2)
Terminated
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: OpenCTI 5.7.4
3. OpenCTI client: 
4. Other environment details: connector taxii2 (source from Cyware Intel)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
OpenCTI running

## Additional information

The endpoint of the collections is from Cyware Threat Intelligence Feeds (https://cyware.com/)

**Comment by SamuelHassine** [comment]
Hello,

Native built-in TAXII consumer will be available in 5.10. But still taking a look.
