### ISSUE TITLE
How to delete bundle with a connector

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/connectors#117]
Hi team, 

I am trying to develop a connector to add IP blacklist. I am thinking about updating the list:
- pull the new list
- delete all indicators (from source) that added to OpenCTI
- update the new list

So I think I will create a stix bundle to ship all indicator `ipv4-addr` at a same time and store the bundle ID then at the next update, I can deleted the previous bundle. 

Is this possible with `pycti` module? If yes, please guide me how to delete a bundle. If not, could u please suggest me another approach.

Thank you very much!

**Comment by richard-julien** [comment]
Hi @phucsnguyenv ,

Can you explain a bit more the concept? Im not sure to clearly see what you want to do.
Do you want to delete ipv4 in openCTI because they are blacklisted? Do you want to listen every ipv4 from opencti, ask a remote source if the ip is blacklisted and then add a blacklisted tag in opencti for this ipv4?

Thanks

**Comment by phucsnguyenv** [comment]
Hi @richard-julien 

Thanks for getting back.

`ask a remote source if the ip is blacklisted and then add a blacklisted tag in opencti for this ipv4` this is  nearly correct, as a remote source if the ip is blacklisted then add it to opencti as an indicator.

and I want to delete this IPv4 in case if the remote host  remove it from the blacklist in the blacklist. So I afraid that, an indicator will be duplicated if keep send new bundle as the code runs everyday. 

But actually, when I sent bundle with `update_existing_data=true` it runs correctly, no duplicate indicators. So I think everything is going good for now. 

Thanks for your team on this wonderful project.

**Comment by phucsnguyenv** [comment]
Hi @richard-julien 

Could you please address me this question https://github.com/OpenCTI-Platform/connectors/issues/110

Thanks.

**Comment by richard-julien** [comment]
Lets continue on https://github.com/OpenCTI-Platform/connectors/issues/110 or Slack.
