### ISSUE TITLE
Flashpoint Connector Does Not Implement Import_Indicators

### ISSUE THREAD

**Issue by AliceGrey** [OpenCTI-Platform/connectors#1263]
## Description

The Flashpoint connector does not currently pull any indicator data but the config makes it seems like it does. You can find the full Flashpoint IOC API docs here: https://help.fp.tools/en/articles/5803017-technical-indicators-api-documentation

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 5.8.4
3. OpenCTI client: frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Read through flashpoint.py connector
2. It doesn't implement pulling indicators from the API

## Expected Output

Flashpoint connector should pull all available IOC's and properly tag them.

## Actual Output

Flashpoint connector only pulls APT & Malware data.

## Additional information

The current workaround is to load Flashpoints api data into MISP and then pull MISP data into OpenCTI.

**Comment by richard-julien** [comment]
Will be handled by https://github.com/OpenCTI-Platform/connectors/issues/1988
