### ISSUE TITLE
Problem with Tweetfeed connector

### ISSUE THREAD

**Issue by V1D1AN** [OpenCTI-Platform/connectors#1264]
## Description

The connector tweetfeed don't work for the moment.

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: 5.8.5
3. OpenCTI client: Frontend
4. Other environment details:

## The Problem

You must change in your entrypoint.sh the line with "python3 sata_ioc.py" and put "python3 /opt/tweedfeed/tweetfeed.py"
"

**Comment by aaarghhh** [comment]
Thank you @V1D1AN, later I'll fix it and I'll PR.

**Comment by aaarghhh** [comment]
I saw that @SamuelHassine has already fixed it. 
Thank you. 
I think this Issue could be closed.
