### ISSUE TITLE
[VirusTotal] Error with internal enrichment

### ISSUE THREAD

**Issue by peasead** [OpenCTI-Platform/connectors#1271]
## Description

When I try to perform a manual or automated enrichment with the VirusTotal internal enrichment, it partially fails.

It doesn't collect labels and other values...but it seems to know it came from VT? When looking at the connector, it has this error.

```
Retry.__init__() got an unexpected keyword argument 'method_whitelist'
```

I don't know if it's related to [this Issue](https://github.com/OpenCTI-Platform/connectors/pull/1260) based on this comment

> Removed deprecated Retry options method_whitelist, DEFAULT_REDIRECT_HEADERS_BLACKLIST (#&#8203;2086 <https://github.com/urllib3/urllib3/issues/2086>__).

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: `8.5.7`
3. OpenCTI client: Frontend
4. Other environment details:

<img width="934" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/7442091/09249e38-32b6-4d81-a1e5-0038f43c0596">

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download an EICAR file
2. Upload it as an Artifact, it returns the following

<img width="2053" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/7442091/e07b5a05-b17c-4bb5-9443-baa76617523c">

Similar things happen if I use the hash and manually create a File entity.

<img width="2004" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/7442091/954ca211-500b-4283-9aa6-6c9346f36a53">

## Expected Output

Add the VT enrichment data.

## Actual Output

Stated above

## Additional information

I've tried to restart the VT connector, clear the state, etc.

I'm not sure what version the VT connector is at (not sure how to check that).

**Comment by FIying-Scotsman** [comment]
Having the exact same issue on 5.8.7. Full error below - reproduced by attempting to enrich an IP but an identical error is thrown for hashes as well (get_ip_info is swapped out for the method which handles hashes):-

`2023-07-04T12:08:51.681209243Z ERROR Error in message processing, reporting error to API | timestamp=2023-07-04T12:08:51.680924Z name=root exc_info=Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 235, in _process_message
    json_data["internal"]["work_id"], message_task.result()
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/opencti-connector-virustotal/virustotal/virustotal.py", line 365, in _process_message
    return self._process_ip(observable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-virustotal/virustotal/virustotal.py", line 228, in _process_ip
    json_data = self.client.get_ip_info(observable["observable_value"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-virustotal/virustotal/client.py", line 201, in get_ip_info
    return self._query(url)
           ^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-virustotal/virustotal/client.py", line 51, in _query
    retry_strategy = Retry(
                     ^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist' `
