### ISSUE TITLE
[VirusTotal] error with internal enrichment

### ISSUE THREAD

**Issue by peasead** [OpenCTI-Platform/connectors#1286]
## Description

When I try to perform a manual or automated enrichment with the VirusTotal internal enrichment, it partially fails.

It doesn't collect labels and other values...but it seems to add the VT link? When looking at the connector, it has this error.

<img width="412" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/7442091/2f007560-cbcf-4a65-8ffd-1245153058de">

```
jsonPayload: {
timestamp: "2023-07-10T19:27:59.550957Z"
level: "ERROR"
exc_info: "Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 235, in _process_message
    json_data["internal"]["work_id"], message_task.result()
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/opencti-connector-virustotal/virustotal/virustotal.py", line 363, in _process_message
    return await self._process_file(observable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-virustotal/virustotal/virustotal.py", line 199, in _process_file
    builder.create_indicator_based_on(
  File "/opt/opencti-connector-virustotal/virustotal/builder.py", line 178, in create_indicator_based_on
    valid_until = now_time + datetime.timedelta(
                             ^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: NoneType"
message: "Error in message processing, reporting error to API"
name: "root"
}
```

## Environment

OS (where OpenCTI server runs): Ubuntu
OpenCTI version: 5.9.0
OpenCTI client: Frontend
Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download an EICAR file
1. Upload it as an Artifact, it returns the following
2. Manually creating causes the same error

<img width="2560" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/7442091/cdf8f517-7298-4755-b906-be3e81545384">

## Expected Output

Add the VT enrichment data.

## Actual Output

Stated above.

## Additional information

VT connector is at version `5.9.0`.

**Comment by FIying-Scotsman** [comment]
After a very quick look around - it appears either VT doesn't report a "valid until" value or the platform itself doesn't know how to handle an EICAR file (which is just a .txt file according to VT - which should fall under the `virustotal_file_indicator_valid_minutes` config value but I was unable to fully debug this live) - thus the config value is ignored/set to null which throws the error above.

One workaround may be to check if the value is null and replace it with a default value (2880 minutes (48 hours) is the default value in the config) although I'm not sure if that's something the project would be happy with or whether it would be better to get the platform to associate EICAR files with the "file" indicator although that may open up further work down the line if other files are needed to be added to the list when the "default" 48 hours would work for all "unknown" files going forward regardless of type.
