### ISSUE TITLE
[import-file-pdf] Import PDF reports with sanitized data

### ISSUE THREAD

**Issue by powerade661** [OpenCTI-Platform/connectors#129]
## Problem to Solve

OpenCTI currently will not ingest data with [.] It is very common for reports to sanitize their URLs and IPs. e.g. 191[.]XXX[.]XXX[.]XXX hxxps://totallynotmalicious[.]com

## Current Workaround

Remove [.] And then import data into OpenCTI 

## Proposed Solution

Remove [.] And replace with nothing. To make the URL unsanitized https://totallynotmalicious.com vs hxxps://totallynotmalicious[.]com

**Comment by SamuelHassine** [comment]
@CGarat do you think you can upgrade your connector? As @powerade661 said, we have implemented in the latest version REGEX on observables to normalize data in OpenCTI. Is it possible for you to re-militarize demilitarized observables?

**Comment by CGarat** [comment]
@SamuelHassine Sure, this seems like a high priority issue. However, I'm working on other projects right now, not sure I'll be able to deal with this myself shortly. Additionally, this connector could be improved in a few more ways (lower priority), as it was initially developed almost a year ago (e.g. adding relationships, tags, detecting a TLP if there's any in the report...).

**Comment by SamuelHassine** [comment]
Thanks a lot @CGarat for your work!
