### ISSUE TITLE
Misp connector sync sightings

### ISSUE THREAD

**Issue by rbnor** [OpenCTI-Platform/connectors#131]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Sightings should be synced between openCTI and MISP. 

## Current Workaround

Add both places
## Proposed Solution

Add a sync on this 

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
This will be in the next version of the MISP connector.

**Comment by rbnor** [comment]
Awesome, you guys really are unstoppable!
