### ISSUE TITLE
OpenCTI workers and connectors showing error in dashboard "An unknown error occurred. Please contact your administrator or the OpenCTI maintainers." 

### ISSUE THREAD

**Issue by razzeshsingh** [OpenCTI-Platform/connectors#133]
![error](https://user-images.githubusercontent.com/47380145/81655651-3c826e80-93eb-11ea-9c10-ecd027ee02ee.jpg)
OpenCTI workers and connectors showing error in dashboard "An unknown error occurred. Please contact your administrator or the OpenCTI maintainers." 

here is the output of MISP Connector:

[root@localhost src]# **python3 misp.py**
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Starting ping alive thread
INFO:root:Connector has never run
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "date_from": "2010-01-01 00:00:00", "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.
INFO:root:Connector last run: 2020-05-12 01:37:28
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "timestamp": "2020-05-12 01:37:28", "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.
INFO:root:Connector last run: 2020-05-12 01:38:28
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "timestamp": "2020-05-12 01:38:28", "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.

here is the below output of  **python3 worker.py &**

[root@localhost src]# INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Listing Threat-Actors with filters null.
INFO:pika.adapters.utils.connection_workflow:Pika version 1.1.0 connecting to ('::1', 5672, 0, 0)
INFO:pika.adapters.utils.io_services_utils:Socket connected: <socket.socket fd=11, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 35422, 0, 0), raddr=('::1', 5672, 0, 0)>
INFO:pika.adapters.utils.connection_workflow:Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7feb342a3250>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7feb342a3250> params=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
INFO:pika.adapters.utils.connection_workflow:AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7feb342a3250> params=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7feb342a3250> params=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.blocking_connection:Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7feb342a3250> params=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.blocking_connection:Created channel=1
INFO:root:Thread for queue push_14d3e60e-4c3e-4ccd-a208-55735306f214 started
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...
INFO:root:Getting connectors ...

**Comment by cvdsouza** [comment]
what does the OpenCTI index.js logs say when you get this error ?

**Comment by razzeshsingh** [comment]
after update the rabbitmq version issue has been resolved.
