### ISSUE TITLE
Crowdstrike connector failing to connect to OpenCTI

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/connectors#137]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ Crowdstrike connector is failing to connect to OpenCTI, even though OpenCTI is up and running.   }

## Environment

1. OS (where OpenCTI server runs): { AWS Ubuntu / docker }
2. OpenCTI version: { OpenCTI 3.2.2 }
3. OpenCTI client: { python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Start crowdstrike connector }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ opencti_connector-crowdstrike.1| INFO:root:Listing Threat-Actors with filters null.
opencti_connector-crowdstrike.1|   File "/opt/opencti-connector-crowdstrike/crowdstrike/core.py", line 73, in __init__
opencti_connector-crowdstrike.1| Traceback (most recent call last):
opencti_connector-crowdstrike.1|     self.helper = OpenCTIConnectorHelper(config)
opencti_connector-crowdstrike.1|   File "main.py", line 7, in <module>
opencti_connector-crowdstrike.1|   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 180, in __init__
opencti_connector-crowdstrike.1|     connector = CrowdStrike()
opencti_connector-crowdstrike.1|     self.api = OpenCTIApiClient(
opencti_connector-crowdstrike.1|   File "/opt/opencti-connector-crowdstrike/crowdstrike/core.py", line 73, in __init__
opencti_connector-crowdstrike.1|   File "/usr/local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
opencti_connector-crowdstrike.1|     self.helper = OpenCTIConnectorHelper(config)
opencti_connector-crowdstrike.1|   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 180, in __init__
opencti_connector-crowdstrike.1|     self.api = OpenCTIApiClient(
opencti_connector-crowdstrike.1|     raise ValueError(
opencti_connector-crowdstrike.1|   File "/usr/local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
opencti_connector-crowdstrike.1| ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
opencti_connector-crowdstrike.1| INFO:root:Listing Threat-Actors with filters null.
opencti_connector-crowdstrike.1|     raise ValueError(
opencti_connector-crowdstrike.1| Traceback (most recent call last):
opencti_connector-crowdstrike.1| ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
opencti_connector-crowdstrike.1|   File "main.py", line 7, in <module>
opencti_connector-crowdstrike.1|     connector = CrowdStrike()
opencti_connector-crowdstrike.1|   File "/opt/opencti-connector-crowdstrike/crowdstrike/core.py", line 73, in __init__
opencti_connector-crowdstrike.1|     self.helper = OpenCTIConnectorHelper(config)
opencti_connector-crowdstrike.1|   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 180, in __init__
opencti_connector-crowdstrike.1|     self.api = OpenCTIApiClient(
opencti_connector-crowdstrike.1|   File "/usr/local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
opencti_connector-crowdstrike.1|     raise ValueError(
opencti_connector-crowdstrike.1| ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
 }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by rhaist** [comment]
Hey. This error usually occurs when either the api is not up yet or the opencti url is wrong. Please look at the logs of the opencti platform, grakn and elasticsearch containers by using:

`docker ps` to list all containers
`docker logs <container name>`

To see if there are any errors preventing opencti to start. If the Web UI is running it is probably the connector config.
Could you share it without the Crowdstrike credentials?

**Comment by TechBurn0ut** [comment]
This is all that I get from the connector itself:

`INFO:root:Scope 'actor' is not enabled
INFO:root:Scope 'report' is not enabled
INFO:root:Scope 'indicator' is not enabled
INFO:root:Scope 'yara_master' is not enabled
INFO:root:Storing new state: {'last_run': 1589382280}
INFO:root:State stored, next run in: 1800 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1740 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1680 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1620 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1560 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1500 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1440 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1380 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1320 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1260 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1200 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1140 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1080 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 1020 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 960 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 899 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 839 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 779 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 719 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 659 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 599 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 539 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 479 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 419 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 359 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 299 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 239 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 179 seconds
INFO:root:Loaded state: {'last_run': 1589382280}
INFO:root:Connector will not run, next run in: 119 seconds`

OpenCTI is up and running just fine, all other connectors are working correctly.

Here is my config:
  connector-crowdstrike:
    image: opencti/connector-crowdstrike:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CROWDSTRIKE}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=CrowdStrike
      - CONNECTOR_SCOPE=crowdstrike
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CROWDSTRIKE_BASE_URL=https://api.crowdstrike.com
      - CROWDSTRIKE_CLIENT_ID=<removed>
      - CROWDSTRIKE_CLIENT_SECRET=<removed>
      - CROWDSTRIKE_TLP=amber
      - CROWDSTRIKE_ACTOR_START_TIMESTAMP=0
      - CROWDSTRIKE_REPORT_START_TIMESTAMP=0    # BEWARE! A lot of reports!
      - CROWDSTRIKE_REPORT_STATUS=New
      - CROWDSTRIKE_REPORT_INCLUDE_TYPES=notice,tipper,intelligence report
      - CROWDSTRIKE_REPORT_TYPE=Threat Report
      - CROWDSTRIKE_REPORT_GUESS_MALWARE=true  # Use report tags to guess malware
      - CROWDSTRIKE_INDICATOR_START_TIMESTAMP=0 # BEWARE! A lot of indicators!
      - CROWDSTRIKE_INDICATOR_EXCLUDE_TYPES=hash_ion,hash_md5,hash_sha1
      - CROWDSTRIKE_INTERVAL_SEC=1800
    restart: always

**Comment by rhaist** [comment]
you are missing:
`      - CROWDSTRIKE_SCOPES=actor,report,indicator,yara_master`

please have a look at:

https://github.com/OpenCTI-Platform/connectors/blob/master/crowdstrike/docker-compose.yml

**Comment by SamuelHassine** [comment]
@TechBurn0ut Is your problem now solved?

**Comment by TechBurn0ut** [comment]
Yes it did.  Thanks for the follow up!
