### ISSUE TITLE
TAXII2 Connector KeyError more

### ISSUE THREAD

**Issue by The-Stuke** [OpenCTI-Platform/connectors#1371]
## Description

Updating to the TAXII 5.10.0 connector the below error occurs on launch after querying a TAXII 2.1 server.

```
 File "/opt/opencti-taxii2/taxii2.py", line 329, in poll
    if (more := response["more"]) == True:
                ~~~~~~~~^^^^^^^^
KeyError: 'more'
```

## Environment

1. OS (where OpenCTI server runs): Docker 
2. OpenCTI version: 5.10.0
3. OpenCTI client: TAXII2 Connector
4. Other environment details: NA

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run TAXII2 5.10.0 and have it poll from a TAXII server
2. Review error logs

## Expected Output

TAXII connector to run and ingest IOCs.

## Actual Output

Full error output
```
INFO Connector has never run | timestamp=2023-08-28T19:12:37.752362Z name=pycti.connector
INFO Polling entire API root Public API Root | timestamp=2023-08-28T19:12:39.458393Z name=pycti.connector
INFO Polling Collection Public Collection | timestamp=2023-08-28T19:12:40.625463Z name=pycti.connector
DEBUG https://xxxx.xxxxx.xxxxxx:443 "GET /xxxxx/xxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/objects/?added_after=2023-08-26T17%3A12%3A40.625409Z&next=2 HTTP/1.1" 200 None | timestamp=2023-08-28T19:12:52.969515Z name=urllib3.connectionpool
Traceback (most recent call last):
  File "/opt/opencti-taxii2/taxii2.py", line 428, in <module>
    raise e
  File "/opt/opencti-taxii2/taxii2.py", line 426, in <module>
    taxii2Connector.run()
  File "/opt/opencti-taxii2/taxii2.py", line 174, in run
    self.poll_entire_root(root)
  File "/opt/opencti-taxii2/taxii2.py", line 232, in poll_entire_root
    self.poll(coll)
  File "/opt/opencti-taxii2/taxii2.py", line 329, in poll
    if (more := response["more"]) == True:
                ~~~~~~~~^^^^^^^^
KeyError: 'more'
Terminated
```

**Comment by MaxwellDPS** [comment]
Seeing this one as well, whats the eta to a fix here @SamuelHassine, kinda a big one to leave for 2 weeks

**Comment by The-Stuke** [comment]
I took a look over the code a bit today. It looks like the issue is when the more value is not present in the returned data. From the [TAXII Documentation](https://docs.oasis-open.org/cti/taxii/v2.1/taxii-v2.1.html) at section 3.7 Envelope Resource it shows that the more field is optional.

![image](https://github.com/OpenCTI-Platform/connectors/assets/48042955/90fe438c-4140-42b2-9ed7-6f8855533a95)

So taking a look over at the current code it looks like more is evaluated and check for True all in the same line to continue. Since more is not present in some cases when the while loop continues the code isn't able to assign a new value to more since it does not exist and breaks the code resulting in this error.

I was able to confirm this with my TAXII server by querying the same request that was failing for me. Below is the output from my query showing more is not present.

First end of object (more present)
![image](https://github.com/OpenCTI-Platform/connectors/assets/48042955/60d4ba75-080c-4d2f-84ca-20b6946ada5d)

Last end of object (more not present)
![image](https://github.com/OpenCTI-Platform/connectors/assets/48042955/f9814b94-c080-428f-87a7-0f5054aec82f)


```
# Assuming newer versions will support next
while more != False:
    objects = process_response(objects, response, version)
    # Get the next set of objects
    if (more := response["more"]) == True:
        filters["next"] = response["next"]
        response = collection.get_objects(**filters)
```

I believe what needs to be updated is in how more is being checked for. There needs to be a check to see if response["more"] exists and if not gather the last objects and then assume more is equal to False to exit the while loop and continue with the objects that are present.

**Comment by annoyingapt** [comment]
Soz all, didn't realise it was optional. I can look in to this tomorrow if I have time.

**Comment by annoyingapt** [comment]
Do you think something like this might work?
```
while True:
    objects = process_response(objects, response, version)
    
    # Check if "more" exists in response and its value is True
    if "more" in response and response["more"] == True:
        filters["next"] = response["next"]
        response = collection.get_objects(**filters)
    else:
        # "more" doesn't exist or is not True, exit the loop
        break
```

**Comment by annoyingapt** [comment]
Give this a go:
https://github.com/annoyingapt/connectors/blob/fix_taxii/external-import/taxii2/src/taxii2.py

**Comment by The-Stuke** [comment]
@annoyingapt Thanks! That seems to work on my test example. That code should be good to update the Taxii connector

**Comment by annoyingapt** [comment]
@The-Stuke @MaxwellDPS I've updated the code I shared before. As well as making the changes you suggested, I separated the enumeration of main observable type from force multiple pattern name. Meaning you can filter on the observable type from the indicator tab if you are not renaming the indicator. I've test the code at my end and it looks to work as expected, can you please give it a test, if it is all good I will raise a PR for the code.

**Comment by The-Stuke** [comment]
@annoyingapt This seems to have worked from my end. Thanks for looking into this!
