### ISSUE TITLE
Adding a state indicator to enable incremental updates

### ISSUE THREAD

**Issue by intelwolf** [OpenCTI-Platform/connectors#14]
## Problem to Solve

Currently the import process does not foresee in duplicate entities being processed during import. Every time when for instance the Mitre connector is started the complete import process is starting for scratch. It would be good to have only incremental updates being processed

## Current Workaround

Add more workers to speed up the import process or extend the interval period. This does only speed up the process

## Proposed Solution

Adding a state indicator to prevent entities being processed that have not been changed since last import.

## Additional Information

None

**Comment by SamuelHassine** [comment]
@mclaassen: Yes it is definitely a need! We need to save the current state based on the "modified" date field of STIX2 JSON entities. This is in top priority.
