### ISSUE TITLE
AlienVault failed to establish a new connection

### ISSUE THREAD

**Issue by Arcelone** [OpenCTI-Platform/connectors#1404]
## Environment

1. OS (where OpenCTI server runs): Windows 11
2. OpenCTI version: OpenCTI 5.10.2 
3. OpenCTI client: frontend (web)
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install OpenCTI like in the documentation
2. add the AlienVault docker file in the docker-compose.yml
3.  add `depends_on: - opencti`

## Expected Output

Working AlienVault connector

## Actual Output

The container keep restarting with this error (see Screenshot 1) 

## Additional information

When doing Docker inspect on the container i notice that for some reson it nerver get any IP, he is in the default docker network like the other container of the stack but never get any IP.

Tryed with version from 5.10.0 to 5.10.2 of the AlienVault image.
Also tryed to manualy connect the container running `docker network connect ID docker_default`, when doing this the container get an IP but the IP disappear 2/3sec after.

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/connectors/assets/62914065/44bfc720-577d-4208-ac55-34f3b772c827)

![Capture d'écran 2023-09-13 205304](https://github.com/OpenCTI-Platform/connectors/assets/62914065/0c78ed0c-74dc-48e5-938f-5d3c732b03e5)

![image](https://github.com/OpenCTI-Platform/connectors/assets/62914065/c06da39d-e4f9-4cc2-b96e-226567750f97)

**Comment by sourcecodehive** [comment]
Hi 
I had the same issue, and then I found a small fix. In yml file-> alientvault connector defition -> url should be changed from http://localhost:8080 to http://opencti:8080 and it started working.

**Comment by sourcecodehive** [comment]
Please change these to:
- OPENCTI_URL=http://opencti,
- OPENCTI_URL=http://opencti:8080,
and - OPENCTI_URL=http://opencti:8080.

**Comment by Arcelone** [comment]
I just said that I already tried with those 3 alternatives. And I didn't work.

**Comment by sourcecodehive** [comment]
These fields need values... 
   - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${ALLIEN-CONNECTOR}
      /// Token can be generated by creating a new user for connector and then adding it to connector group... there you see the token id. And second connector ID... you can generate it any ID generator website like https://www.uuidgenerator.net/

**Comment by sourcecodehive** [comment]
Follow this url for step by step tut... https://benheater.com/proxmox-running-opencti/

**Comment by Arcelone** [comment]
Those variables are in the .env in the same directory. All the rest (opencti dashboard, other connectors are working fine too). I just have a problem with the AlienVault one.

**Comment by sourcecodehive** [comment]
Can you please share your .env file... I am just a researcher and can do a limited help but will try. Or we can get onto a google meet or something to check...

**Comment by KevinOBytes** [comment]
@Arcelone is the variable also mispelled ALLIEN-CONNECTOR in the .env file? Are you sure the .env is being sourced correctly by compose? 

Based on the error the container is failing to reach the OpenCTI instance and authenticate. Your compose doesn't show any other connectors beside Alienvault and the defaults, please correct me if you've succesfully enabled other connectors. 

Typically this would indicate that the Connector container isn't successfully connecting to the OpenCTI API. I suggest running commands from the live Alienvault container to see what's the issue. 

`docker-compose exec -it <container_name> /bin/sh`
`wget https://localhost:8080`
`wget https://opencti:8080` 

and see what returns and if it's routable. Believe the alienvault connector container might also have nslookup and ping if it helps further troubleshoot.

**Comment by Arcelone** [comment]
Working with version 5.11.13 here is the setup :

[message.txt](https://github.com/OpenCTI-Platform/connectors/files/13328609/message.txt)

```
OPENCTI_ADMIN_EMAIL=admin@opencti.io
OPENCTI_ADMIN_PASSWORD=changeme
OPENCTI_ADMIN_TOKEN=a96d5423-8c97-461b-9301-1f0f9aa10348
OPENCTI_BASE_URL=http://localhost:8080
MINIO_ROOT_USER=opencti
MINIO_ROOT_PASSWORD=changeme
RABBITMQ_DEFAULT_USER=opencti
RABBITMQ_DEFAULT_PASS=changeme
CONNECTOR_EXPORT_FILE_STIX_ID=dd817c8b-abae-460a-9ebc-97b1551e70e6
CONNECTOR_EXPORT_FILE_CSV_ID=7ba187fb-fde8-4063-92b5-c3da34060dd7
CONNECTOR_EXPORT_FILE_TXT_ID=ca715d9c-bd64-4351-91db-33a8d728a58b
CONNECTOR_IMPORT_FILE_STIX_ID=72327164-0b35-482b-b5d6-a5a3f76b845f
CONNECTOR_IMPORT_DOCUMENT_ID=c3970f8a-ce4b-4497-a381-20b7256f56f0
SMTP_HOSTNAME=localhost
ELASTIC_MEMORY_SIZE=4G
```
