### ISSUE TITLE
[ MISP ] Bug Import Sigma rules

### ISSUE THREAD

**Issue by V1D1AN** [OpenCTI-Platform/connectors#142]
# Bug Import Sigma rules

Hi eveybody, i have a problem with the import of sigma rules in OpenCTI

## Environment

1. OS (where OpenCTI server runs): CentOS 7
2. OpenCTI version: 3.2.2
3. OpenCTI client: frontend
4. Other environment details: Docker-ce

## Reproducible Steps

I use the script sigma2misp for import my Sigma rules into MISP
I have an event in MISP with my sigma rules.
I tag my event with "OPENCTI" for synchronization with OpenCTI

When i go to "Signatures" -> "Indicateurs" -> "Sigma" 
I have nothing ..

will this feature appear in a future version?

**Comment by rhaist** [comment]
This really is a corner case @V1D1AN - misp2sigma is even "unofficial" in the MISP universe and now you have a double conversion to OpenCTI. There is no STIX2 pattern type for Sigma and thus OpenCTI has no current way of supporting this, sorry.

Maybe, with enough demand for Sigma support this might be added to the roadmap by @SamuelHassine.

**Comment by V1D1AN** [comment]
Thanks for your response,

How do you import Sigma rules in OpenCTI  ????

**Comment by SamuelHassine** [comment]
We will try to implement this feature in the next milesotne.

**Comment by SamuelHassine** [comment]
Hello @V1D1AN,

Sigma rules are now supported by OpenCTI (and validated at the platform level). But MISP integration will not take SIGMA rules into account, please use the OpenCTI API (or Python client) to import your SIGMA rules.

Kind regards,
Samuel
