### ISSUE TITLE
Removing default labelling of connectors

### ISSUE THREAD

**Issue by rach24smith** [OpenCTI-Platform/connectors#1531]
## Use case

Some of the available connectors, such as the VirusTotal, Shodan and Hygiene connectors are very useful, however, they automatically add specific labels to the data. These labels in some cases cause interference and noise to our platform, causing issues for us. 

## Current Workaround

N/A - In theory, we could remove the lines of code on the connector on our end, but we would have to re-remove it every time an upgrade is released, or never be able to upgrade again. 

## Proposed Solution

Either remove the default labeling completely from the code, or have somehow to allow users who deploy OpenCTI to enable or disable the labelling on their end.

## Additional Information

NA

## Would you be willing to submit a PR?

Yes, for removing labelling all together.

**Comment by SamuelHassine** [comment]
Hello,

This is now possible by removing the "create labels" capability to the user of the connector.

Steps:

1. Remove the label you don't want from your OpenCTI platform
2. Remove the capability to create label to the user of the connector
3. Relaunch the connector

The connector will never re-recreate the label again.
