### ISSUE TITLE
Shodan connector error

### ISSUE THREAD

**Issue by rattat0r** [OpenCTI-Platform/connectors#1567]
## Description

An error occurred in the _generate_x509 function when I started to enrich the observed IP address 187.224.61.233.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an observable: 187.224.61.233
2. Start enriching with the Shodan connector

## Additional information
```
{"timestamp": "2023-11-24T09:29:09.346904Z", "level": "ERROR", "name": "pycti.connector", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 279, in _data_handler
    message = self.callback(json_data["event"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-shodan/shodanImport.py", line 344, in _process_message
    self._convert_shodan_to_stix(response, observable)
  File "/opt/opencti-connector-shodan/shodanImport.py", line 189, in _convert_shodan_to_stix
    x509s = self._generate_x509(shodanHostResponse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-shodan/shodanImport.py", line 90, in _generate_x509
    x509 = self.helper.api.stix_cyber_observable.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1478, in create
    result = self.opencti.query(query, input_variables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 369, in query
    raise ValueError(
ValueError: {'name': 'ValidationError', 'message': 'Invalid field validity_not_before'}"}
```
## Screenshots (optional)
![image_2023-11-24_12-40-51](https://github.com/OpenCTI-Platform/connectors/assets/122795003/92dfc17b-35fc-4684-9542-a75003ae8dd9)

**Comment by SamuelHassine** [comment]
Hello,

I've just tested and it's working well.

![image](https://github.com/OpenCTI-Platform/connectors/assets/1334279/cd255f25-0d5c-4c3c-a2c2-7f6d3bdb9602)

![image](https://github.com/OpenCTI-Platform/connectors/assets/1334279/f13aee92-e702-41bc-912a-6e68d2eb4319)

Are you using the latest version of the platform with connector and platform versions aligned?

Kind regards,
Samuel

**Comment by rattat0r** [comment]
Thanks for the answer. I'm using version 5.11.12. Perhaps this is the problem

**Comment by FIying-Scotsman** [comment]
Getting that same error on 5.11.4 and 5.11.14 for some reason. It's thrown for all IPs passed to the connector.

**Comment by rattat0r** [comment]
@FIying-Scotsman, For some IP it works well for me, but for others it doesn’t work.
