### ISSUE TITLE
[AlienVault] Guess CVE from tags

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#157]
## Problem to Solve

Currently, if a CVE name is in a tag, it will be imported as a tag.

## Current Workaround

None.

## Proposed Solution

Creation a relationship between Intrusion-Set/Malware to a Vulnerability with a "targets" relation.

## Additional Information

None.

**Comment by maertv** [comment]
@SamuelHassine, by "Guess CVE from tags" do you mean something as simple as checking if the tag starts with _CVE-_ or do you have something more elaborate in mind?

Do you think that it is should be a configurable feature, i.e, _guess_cve: true_ in the _config.yml_?

Could you please provide an example pulse that has a CVE as a tag?
