### ISSUE TITLE
Bug in export of a general research request

### ISSUE THREAD

**Issue by gkallenborn** [OpenCTI-Platform/connectors#1572]
## Description

Using the general research form in the upper right part of the OpenCTI interface, I got a list of results. When I selected all the items using the first check box, the export always failed, whatever the exported format I choosed. When I selected all the items one by one, the export always succeeded. 

## Environment

1. OS: SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux
2. OpenCTI version: 5.11.14
3. Client: Chrome Version 119.0.6045.160 (Build officiel) (64 bits)
4. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enter a keyword in the research form (upper right part of the screen)
2. Select all the result items using the first check box
3. Select any kind of format and TLP
4. The export fails

## Expected Output

An export document

## Actual Output

An error message: 
**Connector ready to process the operation, {'name':'Variable "$elementId" of type "String" used in position expecting type "[String]".', 'message':'Variable "$elementId" of type "String" used in position expecting type "[String]".'}**

## Additional information

![research-export-error1-f](https://github.com/OpenCTI-Platform/connectors/assets/28608796/88969199-9467-4d67-8408-da3e76e07261)
![research-export-error2-f](https://github.com/OpenCTI-Platform/connectors/assets/28608796/6d7dba84-259e-4427-a866-5c00ce0dfb04)

**Comment by SamuelHassine** [comment]
Will be solved in 5.12.16.
