### ISSUE TITLE
Modifying enrichment connectors to be "Playbook compatible"

### ISSUE THREAD

**Issue by Jipegien** [OpenCTI-Platform/connectors#1585]
## Use case

Based on what have been already done for connectors that are now compatible with Playbook Automation, continue the work on others.

Priorities: 
- _RF Enrichment_
- Greynoise
- Shodan
- _VMRay Analyzer_
- Malbeacon

Those connectors need to send back complete STIX bundle that will be processed by Playbook automation.

**Comment by nino-filigran** [comment]
To be precise, RF is not done in this task.
