### ISSUE TITLE
"Reject status" connectors: rst report hub, rst threat feed

### ISSUE THREAD

**Issue by Yeelshat** [OpenCTI-Platform/connectors#1587]
## Environment

1. OS (Ubuntu 20)
2. OpenCTI version: 5.11.14
3. OpenCTI client: Portainer
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

connector-rst-threat-feed:
    image: opencti/connector-rst-threat-feed:5.11.14
    environment:
      - OPENCTI_URL=http://oepncti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=83452f29-c4b8-44ba-825f-xxxxxxxxxxxxxx
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=RST Threat Feed
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - RST_THREAT_FEED_BASEURL=https://api.rstcloud.net/v1
      - RST_THREAT_FEED_APIKEY=[MY RST Threat Feed Trial Key]
      - RST_THREAT_FEED_CONTIMEOUT=30
      - RST_THREAT_FEED_READTIMEOUT=60
      - RST_THREAT_FEED_RETRY=5
      - RST_THREAT_FEED_INTERVAL=86400
      - RST_THREAT_FEED_MIN_SCORE_IMPORT=20
      - RST_THREAT_FEED_MIN_SCORE_DETECTION_IP=50
      - RST_THREAT_FEED_MIN_SCORE_DETECTION_DOMAIN=45
      - RST_THREAT_FEED_MIN_SCORE_DETECTION_URL=30
      - RST_THREAT_FEED_MIN_SCORE_DETECTION_HASH=25
      - RST_THREAT_FEED_ONLY_NEW=true
      - RST_THREAT_FEED_DIRS_TMP=/tmp
      - RST_THREAT_FEED_DIRS_STATE=/tmp
    restart: always
    depends_on:
      - opencti

 connector-rst-report-hub:
    image: opencti/connector-rst-report-hub:5.11.14
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=bf8d1b86-b306-4957-8324-xxxxxxxxxxx
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=RST Report Hub
      - CONNECTOR_SCOPE=application/json,application/pdf
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - RST_REPORT_HUB_BASE_URL=https://api.rstcloud.net/v1
      - RST_REPORT_HUB_API_KEY=[MY RST Threat Feed Trial Key]
      - RST_REPORT_HUB_CONNECTION_TIMEOUT=30
      - RST_REPORT_HUB_READ_TIMEOUT=30
      - RST_REPORT_HUB_RETRY_DELAY=30
      - RST_REPORT_HUB_RETRY_ATTEMPTS=5
      - RST_REPORT_HUB_IMPORT_START_DAY=${RST_REPORT_HUB_STARTDATE}
      - RST_REPORT_HUB_FETCH_INTERVAL=300
      - RST_REPORT_HUB_LANGUAGE=eng
    restart: always
    depends_on:
      - opencti

## Actual Output

State | rejected
Error message | No such image: opencti/connector-rst-report-hub:5.11.14

## Additional information

other connectors work without problems
please help with solving this problem,

## Screenshots (optional)
screenshots uploaded
![error](https://github.com/OpenCTI-Platform/connectors/assets/84506281/48bfafcb-ed3b-4268-acf8-37e6297551ca)
![connectors](https://github.com/OpenCTI-Platform/connectors/assets/84506281/e5ecfeee-d7ec-4a57-b5d4-4e0df17d7f2f)

**Comment by k1r10n** [comment]
When it was just published, there was no docker image with such tag. The only tag that was available at the moment was "rolling".
Now, opencti team have integrated the image generation into the pipeline.

https://hub.docker.com/r/opencti/connector-rst-threat-feed/tags

use any of the tags available that will suit your situation
