### ISSUE TITLE
[CVE] Configuration file location seems to have changed during code rework

### ISSUE THREAD

**Issue by guillaumededrie** [OpenCTI-Platform/connectors#1637]
## Description

When using the docker image `opencti/connector-cve:5.12.9`, if you try to mount a configuration file into `/opt/opencti-connector-cve/config.yml`, this file is not loaded and trigger a `TypeError …` (see below).

After digging a little bit, I think it may be related to the declared path of the config file [here](https://github.com/OpenCTI-Platform/connectors/blob/cadfd29656f4261a3b58ae883989e504cdb9a456/external-import/cve/src/services/utils/constants.py#L3), when the application is run in by the container [entrypoint](https://github.com/OpenCTI-Platform/connectors/blob/cadfd29656f4261a3b58ae883989e504cdb9a456/external-import/cve/entrypoint.sh#L7), resolve to `/opt/src/config.yml`.

What do you think of the following patch?

```diff
-import os
+from pathlib import Path

-CONFIG_FILE_PATH = f"{os.path.dirname(os.getcwd())}/src/config.yml"
+CONFIG_FILE_PATH = Path(__file__).parents[2].joinpath('config.yml')
MAX_AUTHORIZED = 120
```

This should have any impact [on those `open` and `os.path.isfile` functions](https://github.com/OpenCTI-Platform/connectors/blob/cadfd29656f4261a3b58ae883989e504cdb9a456/external-import/cve/src/services/utils/config_variables.py#L26) as both support [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) objects as parameters.
 

## Environment

1. Docker
1. OpenCTI version: 5.12.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. `sudo docker run -v ./config.yml:/opt/opencti-connector-cve/config.yml opencti/connector-cve:5.12.9`

Error not present anymore:
1. `sudo docker run -it -v ./config.yml:/opt/src/config.yml opencti/connector-cve:5.12.9`

## Expected Output

```
{"timestamp": "2023-12-20T14:40:07.143837Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null."}
…
```

## Actual Output

```
Traceback (most recent call last):
  File "/opt/opencti-connector-cve/main.py", line 4, in <module>
    from connector import CVEConnector
  File "/opt/opencti-connector-cve/connector/__init__.py", line 2, in <module>
    from .cve_connector import CVEConnector  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-cve/connector/cve_connector.py", line 6, in <module>
    from services import CVEConverter  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-cve/services/__init__.py", line 1, in <module>
    from .client import CVEClient  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-cve/services/client/__init__.py", line 1, in <module>
    from .api import CVEClient  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-cve/services/client/api.py", line 5, in <module>
    from .endpoints import BASE_URL
  File "/opt/opencti-connector-cve/services/client/endpoints.py", line 7, in <module>
    config = ConfigCVE()
             ^^^^^^^^^^^
  File "/opt/opencti-connector-cve/services/utils/config_variables.py", line 18, in __init__
    self._initialize_configurations()
  File "/opt/opencti-connector-cve/services/utils/config_variables.py", line 65, in _initialize_configurations
    self.interval = convert_hours_to_seconds(self.config_interval)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-cve/services/utils/common.py", line 16, in convert_hours_to_seconds
    return int(hours) * 60 * 60
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by helene-nguyen** [comment]
Hello @guillaumededrie,

Thanks for your feedback and suggestions!
It will be changed for the next minor release and you can follow the progress here:

- [PR opened in review](https://github.com/OpenCTI-Platform/connectors/pull/1638)
