### ISSUE TITLE
CVE connector makes unnecessary paginated request and failing to limit API Rate limit when exception thrown

### ISSUE THREAD

**Issue by animedbz16** [OpenCTI-Platform/connectors#1661]
## Description
Looking at the logs, the CVE connector appears to make an unnecessary paginated request for data it has already obtained.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 5.12.14
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure CVE connector with `CVE_HISTORY_START_YEAR = 2005` and ensure pulling history is enabled
2. Configure `debug` logging
3. Start connector

## Expected Output
When looking at the logs you can see that a non-paginated request is made which returns a response with 4451 bytes, then the connector receives this response and then makes a subsequent paginated request, which also receives the same 4451 bytes.

When you look at the underlying data that is returned you, can see that the initial request contains a `totalResults: 3` and within `vulnerabilities` the array of objects contains 3 items, so this request received all of the data and the connector should not engage in submitting a paginated request.

## Actual Output
Connector receives initial non-paginated response, is not checking to see if this response contains all of the data and then initiates a paginated request

## Additional information
As a follow up, it also appears that the API Rate limiting is not functioning propertly, you can see that the last request yields a 403 Forbidden response, when looking at this response it appears to be the following:

```
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

![NVD Nist Forbidden response](https://github.com/OpenCTI-Platform/connectors/assets/2822632/9822945b-e793-45b3-abf1-2a34886de194)

## Screenshots (optional)
![OpenCTI CVE connector logs](https://github.com/OpenCTI-Platform/connectors/assets/2822632/bd7a0628-822d-4752-886d-179e68c4ecf1)

![NVD Nist API response](https://github.com/OpenCTI-Platform/connectors/assets/2822632/f4bcd92a-a9dc-48f7-99c3-c57b9884216c)

**Comment by animedbz16** [comment]
As a follow up, reviewing the code there is a bit of confusion relating to what is described in the configuration file vs the code base.

The docker-compose file seems to indicate this value is in days, while the config.yml file indicates it is in hours.

https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/cve/docker-compose.yml#L17
https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/cve/src/config.yml.sample#L18

Looking at the codebase, it seems this is in hours:
https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/cve/src/connector/cveConnector.py#L269C73-L269C73

But it seems that since the program is throwing an exception, the connector is being retried over and over and OpenCTI is reporting that each of these "runs" is still in progress"

![OpenCTI Connector Status In Progress](https://github.com/OpenCTI-Platform/connectors/assets/2822632/4a06dcf6-7144-4532-8ca5-3c08212888ad)

**Comment by animedbz16** [comment]
The issue with the Rate Limiting is where it is placed.

https://github.com/OpenCTI-Platform/connectors/blob/b3f12ff253d341f98619eae284fe5c165a4c5fc4/external-import/cve/src/services/client/vulnerability.py#L72

This would only limit the requests for paginated API requests and does not take into account all other requests.

In some basic testing, I added a sleep statement when here so that on successful API requests to force a sleep of 10 seconds for examplewhich seems to alleviate the issue.

https://github.com/OpenCTI-Platform/connectors/blob/b3f12ff253d341f98619eae284fe5c165a4c5fc4/external-import/cve/src/services/client/api.py#L62C28-L62C28

This does not account account for the Retry strategy since additional requests could be made or maybe add an additional sleep on failure for extra time to ensure ample time has passed before trying to make additional requests.

**Comment by helene-nguyen** [comment]
Hello @animedbz16,

Thank you for your feedback! We will make some improvement on it.

- **About interval**:

> As a follow up, reviewing the code there is a bit of confusion relating to what is described in the configuration file vs the code base.
> 
> The docker-compose file seems to indicate this value is in days, while the config.yml file indicates it is in hours.
> 

Yes, it was a mistake and it will be changed.

- **About pulling history**:

This connector will import all CVE with CVSS V3.1 base score.
CVSS V3.1 was released in June 2019, thus most CVE published before 2019 do not include the cvssMetricV31 object. The exception are CVE published before 2019 that were later reanalyzed or modified.

We will add some more details on config.sample.yml and docker-compose.yml files to be more precise :)

**Comment by animedbz16** [comment]
@helene-nguyen 

Thank you for your follow up and PR to support the changes for ensuring the API Rate limit will function properly.

With my continued testing, I had noticed another issue with how the pagination is functioning which appears to be a different error, which you can review from the attached screenshot.

The top of the screenshot, you can see a request is made for a specific time range which it had been processing through which provides a `startIndex=38019` and a `resultsPerPage=2000`, then the next request is for `startIndex=40020` and a `resultsPerPage=2000`. It seems that the start index is increased by `2001` which is likely skipping some results.

Looking at the middle you can see that the final request this pagination is `startIndex=48013` and a `resultsPerPage=1989`, which the API logs report as being `Retrieve CVE based on CVSS 3.1 from page 25 out of 25`, but then then there is a subsequent request for `startIndex=48014` and a `resultsPerPage=0` indicating `page 26 out of 25`, then another request for `startIndex=48015` and a `resultsPerPage=0`.

There is definitely something wrong with how this is being tracked.

I'm not sure I follow why the overall history is being chunked by year then trying to determine how many days are in the year, when it seems easier to have a starting date and just increase the timedelta by `120 days`  until you reach `now`, but thinking there could be some improvements to how this function works.

![Uploading OpenCTI CVE connector pagination error.png…]()

**Comment by animedbz16** [comment]
@helene-nguyen I have pushed up a PR to address the pagination issues. Please review at your convenience. This PR would still require the API Rate Limiting changes that you have addressed in your own PR.
