### ISSUE TITLE
Virustotal Connector is reporting no yara ruleset id provided

### ISSUE THREAD

**Issue by animedbz16** [OpenCTI-Platform/connectors#1673]
## Description
There seems to be a bug in how the Virustotal connector is functioning when it enriches an object that contains `crowdsourced_yara_results` and is improperly passing the ruleset / ruleset id between functions.

Once VT has received a JSON response for an object (see screenshot for data), this following code executes for each `crowdsourced_yara_result`
https://github.com/OpenCTI-Platform/connectors/blob/a66595ea3e1178c8df355534583346bdf13dc081/internal-enrichment/virustotal/src/virustotal/virustotal.py#L215-L225

You can see that the `ruleset_id`  is being assigned to `ruleset` and then the yara object and the ruleset (id) is being passed into the `builder.create_yara`, which is a bit confusing since `ruleset` is really the `ruleset_id`.

Looking at the `builder.create_yara` function below:
https://github.com/OpenCTI-Platform/connectors/blob/a66595ea3e1178c8df355534583346bdf13dc081/internal-enrichment/virustotal/src/virustotal/builder.py#L335-L407

Specifically the following line:
https://github.com/OpenCTI-Platform/connectors/blob/a66595ea3e1178c8df355534583346bdf13dc081/internal-enrichment/virustotal/src/virustotal/builder.py#L356

It attempts to get the `id` value out of the `yara`, but the `yara` object does not have an `id`, it has a `ruleset_id` value and thus this fails so when you look at the logs, it reports that `Retrieving ruleset No ruleset id provided`. But it is confusing that the `ruleset` variable passed into this function is actually the `ruleset_id` value that is being accessed here, so its not clear why this is being passed in separately.

See relevant screenshots below.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: OpenCTI 5.12.14
3. OpenCTI client: N/A
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure Virustotal Connector with info logging enabled
2. Internally Enrich an object where the Virustotal Connector report contains crowdsourced_yara_rulesets
3. View logs

## Expected Output

Virustotal connector is able to execute without producing errors.

## Actual Output

Virustotal connector is producing errors.

## Screenshots (optional)

![VirusTotal Connector UI with Logs](https://github.com/OpenCTI-Platform/connectors/assets/2822632/e54a115a-ebbb-417e-a68d-be6d942f8c79)

<img width="839" alt="VirusTotal Connector Error" src="https://github.com/OpenCTI-Platform/connectors/assets/2822632/b64b51e2-03d9-41b2-b6ac-ea185dc3c7a9">

<img width="1680" alt="VirusTotal Connector Error Details" src="https://github.com/OpenCTI-Platform/connectors/assets/2822632/b0844175-a72c-4f7b-b6af-cc901caa5d8a">

**Comment by SamuelHassine** [comment]
Will be solved in 5.12.16.
