### ISSUE TITLE
Mandiant Connector bug: Reports import stops after initial import is finished

### ISSUE THREAD

**Issue by n-kta** [OpenCTI-Platform/connectors#1685]
## Description

Reports import works only initial time you deploy connector. After that all the jobs have 0 operations and do not import anything until I delete the connector and redeploy it. Then again the initial job will collect the missing report and no more reports will be pulled afterwards. Clearing connector state and restarting it gives the same effect.
This issue started after the last update to the connector. There were other issues which were fixed with that update but it broke reports import for me.  

There are no errors in the Mandiant connector logs. The worker logs only have errors presumably related to the individual data being imported. The jobs that are empty do not have any errors.

I tried importing indicators, vulnerabilities, reports, campaigns, malware. I can confirm that the indicators and vulnerabilities get imported fine with the current connector version. Also reports are being created if they are connected to the indicators being pulled by the indicators endpoint but these are usually older reports. (When you set the connector in the debug mode you can see that the API endpoint used to pull the Indicator is configured to pulls reports too).  I cannot say if the malware, actor and campaign endpoints have the same issue as the report endpoint as the former 3 categories have new content being generated less frequently and I have not focused on them.

I also tried importing only reports and all the other options set to false, but it did not change the behaviour.

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: 5.12.15
3. OpenCTI client: Mandiant Connector
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. It happens every time when I deploy connector with reports pull enabled.

## Expected Output

It should continue pulling reports after the initial pull and not only once it pulled all the missing reports.

## Actual Output

All the currently present on the portal reports get pulled. But when after some hours new reports being generated on the portal. The connector jobs continue to be empty and do not pull the reports. Once I clear state and restart the connector it pulls the missing reports and get to the same state of the empty jobs forever until you repeat the process with clearing the state and restarting it.

**Comment by aHenryJard** [comment]
FYI from Slack thread https://filigran-community.slack.com/archives/C06CF1N302W/p1704870492039649

**Comment by SamuelHassine** [comment]
@aHenryJard @Megafredo @helene-nguyen @Kedae @Jipegien : this connector is high priority. Please investigate and solve this problem if any after the latest release.

**Comment by n-kta** [comment]
Hi, I have some more observations for you guys from my side. For 1.5 weeks or so  I cleaned state and restarted the connector on daily basis in the morning to get all the missing reports. The behaviour was as explained. Initial run collects the reports, then empty jobs despite there are reports on the portal. 
Two days ago I did just the same procedure, but through the day the reports continued coming and up until now they are coming too. 

So I suspect some nasty bug there, that is difficult to reproduce. From my side as I said I always did the same action and did not do anything to the platform in the mean time. 

I do not dare to try restarting connector again before I hear from you about the fix or progress as reports are important for us.

**Comment by richard-julien** [comment]
Do you have any logs on connector side during the "blocking" phase? Could be due to some data we fail to parse for some reason coming from mandiant.

**Comment by n-kta** [comment]
I do not have any errors in the connectors logs at all, besides the errors on malware endpoint processing. It is unrelated to this case, but the error is "NoneType object is not iterable". I suspect that it happens when malware endpoint returns no result due to nothing new,  connector tries to iterate through it anyways and gives this error. 

No errors related to reports.
In the worker there are some errors that are probably related to the quality of the data in Mandiant like MISSING_REFERENCE_ERROR one UNSUPPORTED_ERROR from time to time. But it does not create any issues as now that the reports are being pulled still the same errors pop up. 
The errors though are only when the data is actually being pulled. The empty jobs does not create any errors.

Hope it answers the question.

**Comment by Megafredo** [comment]
Hi @n-kta, quick question, have you modified any variables in the config (example: import_periode) that could affect the intervals, dates? and can you also give us an overview of your state when importing your "reports"?
![image](https://github.com/OpenCTI-Platform/connectors/assets/14902945/324b9baf-58e2-42fb-bfde-739615f81c58)

**Comment by n-kta** [comment]
Hi, I did not set import_period and import_internal variables, so they must be default. I only modify import_start_date, so that when I restart the connector I do not fetch data that was already fetched.

In regards to the connector state:

Currently, the reports are being fetched properly as I mentioned in the post above and I do not want to restart it to avoid getting it broken again. The state is as follows:

`{"vulnerabilities": {"start_epoch": "2024-01-19T09:02:49+00:00", "end_epoch": null, "last_run": "2024-01-19T09:02:49+00:00", "offset": 0}, "indicators": {"start_epoch": "2024-01-19T09:02:45+00:00", "end_epoch": null, "last_run": "2024-01-19T09:02:45+00:00", "offset": 0}, "campaigns": {"start_epoch": "2024-01-15T00:00:00+00:00", "end_epoch": null, "last_run": "2024-01-19T09:02:45+00:00", "offset": 107}, "malwares": {"start_epoch": "2024-01-15T00:00:00+00:00", "end_epoch": null, "last_run": "2024-01-18T21:21:37+00:00", "offset": 5347}, "reports": {"start_epoch": "2024-01-19T09:07:50+00:00", "end_epoch": null, "last_run": "2024-01-19T09:07:50+00:00", "offset": 0}, "actors": {"start_epoch": "2024-01-15T00:00:00+00:00", "end_epoch": null, "last_run": "2024-01-19T09:07:50+00:00", "offset": 367}}`

I dug out from the discussions I had on the Slack the state I posted 2024-01-08T14:05:46, that time the reports ingestion had the problem that it worked only the initial time after clearing state and restarting. This is the state of the connector when it was not cleared and reset for 2-3 days:

`{"vulnerabilities": {"start_epoch": "2024-01-08T13:00:17+00:00", "end_epoch": null, "last_run": "2024-01-08T13:00:17+00:00", "offset": 0}, "indicators": {"start_epoch": "2024-01-08T13:00:15+00:00", "end_epoch": null, "last_run": "2024-01-08T13:00:15+00:00", "offset": 0}, "campaigns": {"start_epoch": "2024-01-04T00:00:00+00:00", "end_epoch": null, "last_run": "2024-01-08T13:00:14+00:00", "offset": 103}, "malwares": {"start_epoch": "2024-01-04T00:00:00+00:00", "end_epoch": null, "last_run": "2024-01-04T20:10:50+00:00", "offset": 5321}, "reports": {"start_epoch": "2024-01-08T12:54:12+00:00", "end_epoch": null, "last_run": "2024-01-08T12:54:12+00:00", "offset": 0}, "actors": {"start_epoch": "2024-01-04T00:00:00+00:00", "end_epoch": null, "last_run": "2024-01-08T12:54:12+00:00", "offset": 363}}`

(Source: https://filigran-community.slack.com/archives/CHZC2D38C/p1704711625914469?thread_ts=1702903237.242349&cid=CHZC2D38C)
