### ISSUE TITLE
Import External Reference connector getting stuck in ping work_id

### ISSUE THREAD

**Issue by rach24smith** [OpenCTI-Platform/connectors#1691]
## Description

Hello! We are having issues with the out of the box import-external-reference connector. It will process references, complete successfully, and then at random times after logging "Processing external reference", it will log "Ping work" and then just continuously log "Ping work" and will not process any more records until I restart it. Then it will process work again for a couple minutes, then repeat the same pattern of the ping work logs.

This problem was first seen in OpenCTI 5.11.7, so I thought the upgrade of the platform and connectors to 5.12.15 would solve it, but it did not.

## Environment

1. OS (where OpenCTI server runs): Windows
2. OpenCTI version: OpenCTI 5.11.7 and 5.12.15
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Have data queued to be processed by import external reference connector (one instance I have 3k, the other 719k)
2. Restart connector deployment image for Import External Reference
3. Watch the logs

## Expected Output

Continuously process all pieces of data until the connector message queue is 0. 

## Actual Output

Continuously logs "Ping work" and no data processed.

## Screenshots (optional)
Please see logs here:
![image](https://github.com/OpenCTI-Platform/connectors/assets/36097449/9358f008-f984-4f2f-8e5e-76a840232cc2)

![image](https://github.com/OpenCTI-Platform/connectors/assets/36097449/0d350ded-0c9f-409b-b9d7-12304f062212)

**Comment by SamuelHassine** [comment]
This should be solved in 5.12.17.
