### ISSUE TITLE
MISP MITRE ATT&CK Galaxy not linking to attribute

### ISSUE THREAD

**Issue by biers04** [OpenCTI-Platform/connectors#170]
## Description

Tagging attributes within MISP to a galaxy (in this case specific to MITRE) to that specific attribute is not carrying the relationship over to OpenCTI. Events are properly tagged, and can manually do complete the relationship. MITRE will pull over to OpenCTI, just does not tag properly. Screenshots of example below:

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 3.3.2
3. OpenCTI client: Frontend
4. Other environment details: MISP 2.4.128

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create event in MISP
2. Tag attribute directly
https://imgur.com/wdIC6TS
3. Pivot to OpenCTI and check relationships (no relationships)
https://imgur.com/3VHXASo
## Expected Output

Expect relationship to be maintained on import as the galaxies are subordinate to the attributes.

## Actual Output

Relationship not linked, but attribute/galaxy is still ingested. 

## Additional Information

We are manually doing this workaround
https://imgur.com/Thzi7WN

**Comment by SamuelHassine** [comment]
Solved in the upcoming V4.
