### ISSUE TITLE
[external-import][crtsh] duplicates imports

### ISSUE THREAD

**Issue by pierremahot** [OpenCTI-Platform/connectors#1707]
## Description

crtsh is looping and reimport all the relation, certificate and domain creating unnecessary duplicates

## Environment

1. kubernetes
2. OpenCTI version:  5.12.18
3. OpenCTI client:  python
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. configure and connect the connector with a domain

## Expected Output

only import one all the certificate and subdomain

## Actual Output

create duplicate at each schedulement

**Comment by Jipegien** [comment]
should be fixed with .20. can you check?

**Comment by nino-filigran** [comment]
@pierremahot did it work?

**Comment by SamuelHassine** [comment]
It is fixed in .23, confirmed.
