### ISSUE TITLE
How to change a report modified date 

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/connectors#171]
Hi, 

I used a connector to create an internal report. Everyday I will add new or delete the Observables linked to this report. Now I what I want to do is after I add/delete Observables to this report, I will to change the modified date property of this report. Please let me know how to do this. 
All entities are created by `pycti` library.

**Comment by SamuelHassine** [comment]
Hello @phucsnguyenv,

Sorry for the delayed answer, this behavior should be definitely solved in OpenCTI >= 4.X.X. Please let us know if you are facing any more difficulties.

Kind regards,
Samuel
