### ISSUE TITLE
Virustotal Connector Error

### ISSUE THREAD

**Issue by AlinaSeilbekova** [OpenCTI-Platform/connectors#1717]
Hello, we got some troubles with VirusTotal Connectors. 
When we try to scan malicious ipv4 we got this error 
![image](https://github.com/OpenCTI-Platform/connectors/assets/113204792/e3357827-dbd6-445d-a462-7780617b9d3c)

Error: "{'name': 'unknown argument "fromortoid" on field "query.stixnestedrefrelationships". did you mean "fromid"?', 'message': 'unknown argument "fromortoid" on field "query.stixnestedrefrelationships". did you mean "fromid"?'}"

Environment:

1. Proxmox Ubuntu Server 22.04.3 LTS
2. OpenCTI version - 5.12.15
3. OpenCTI client: frontend
4. Virustotal image version - opencti/connector-virustotal:5.12.17

**Comment by nino-filigran** [comment]
@AlinaSeilbekova would you adding some reproducble steps please? (does it occur with every IPV4)

This is a connecotr that is supported by the community. I see that we have the follwoing contributors: @YungBinary, @dinateper, @rlynch-ironnet, @axelfahy, @fdevillard. Would any of you mind having a look?

**Comment by AlinaSeilbekova** [comment]
> @AlinaSeilbekova would you adding some reproducble steps please? (does it occur with every IPV4)
Are you asking me to describe the installation step by step or how we scan?

**Comment by helene-nguyen** [comment]
Yes, sure, I will give you an update as soon as possible :)

**Comment by AlinaSeilbekova** [comment]
![image](https://github.com/OpenCTI-Platform/connectors/assets/113204792/d2879da6-884e-4f42-9298-59dca353c1a8)

I am sending you docker-compose.yml

We get this error not only with IPv4, but also with domains.
When I try to enrich again I get the same error

**Comment by Megafredo** [comment]
I did a first test to reproduce the bug on version 5.12.20 of OpenCTI
And the enrichment is carried out correctly without errors (see screenshot)
![VirusTotal](https://github.com/OpenCTI-Platform/connectors/assets/14902945/48ae8181-9e3d-4751-a03f-e58441547537)

I will investigate the OpenCTI version - 5.12.15, I will come back to you when I have more information

**Comment by AlinaSeilbekova** [comment]
thanks to all :)
the problem really was in the opencti version
