### ISSUE TITLE
MISP connector not inporting anything

### ISSUE THREAD

**Issue by asucrews** [OpenCTI-Platform/connectors#173]
## Description

MISP connection is returning the below logs and not importing.

INFO:root:Listing Threat-Actors with filters null.,
ROR:root:Duplicate entry,
'NoneType' object is not subscriptable,

## Environment

1. ubuntu 20.04
2. OpenCTI version: 3.3.2
3. OpenCTI client: frontend
4. Other environment details:
Docker, MISP  v2.4.128 (4693ae347365e51fc1f1b17d7a91d08c09ba03b8)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. added docker config to docker compose file
2. docker-compose up -d

## Expected Output

Event imported

## Actual Output

Not Importing, red icon on the connections and worker tab.

**Comment by GlennHD** [comment]
I would ask this in the Slack channel https://slack.luatix.org/. 

Many are running the same configuration you are and are not having any issues.

**Comment by asucrews** [comment]
Got hel from https://slack.luatix.org/ people.
