### ISSUE TITLE
Some readme are missing for some connectors

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/connectors#176]
## Description

It would be useful to have a short readme for some connectors, explaining what they are for and how they work.

**Comment by alnash28** [comment]
@manonviallet This request seems a little outdated. Are there specific connectors not mentioned [herein ](https://www.notion.so/Connectors-4586c588462d4a1fb5e661f2d9837db8)

**Comment by SamuelHassine** [comment]
@manonviallet Please re-open an issue for each connector where you actually need documentation in order to properly implement/deploy them.
