### ISSUE TITLE
Crowdstrike connector replaces first byte of IP with '0'

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/connectors#177]
## Description

Crowdsrike connector replaces first byte of IP address with '0'.

## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: OpenCTI 3.3.2
3. OpenCTI client: Frontend
4. Other environment details: pycti: 3.3.3 crowdstrike-client 0.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run crowdstrike connector
2. Search Intrusion sets for known URLs/Indicators with IPs
3. Returns "http://0.xxx.yyy.zzz"

## Expected Output

Should be correct IP

## Actual Output

First byte of the quartet is '0'
 
## Additional information

![image](https://user-images.githubusercontent.com/8810661/89548065-8ef9de00-d7d4-11ea-9684-2a40f950fb08.png)

**Comment by smclinden** [comment]
![image](https://user-images.githubusercontent.com/8810661/89548300-d5e7d380-d7d4-11ea-87e4-c33eee20c05f.png)

**Comment by maertv** [comment]
I searched for _http://0.146.188.228:47843_ on the CrowdStrike Portal and found that indicator with this value (_URL: http://0.146.188.228:47843_, Geodo, Emotet and MUMMYSPIDER, published 2020-08-04) exists there.

It seems to me that this is how the connector received it from the CrowdStrike.

**Comment by smclinden** [comment]
It is MUMMYSPIDER but I am wondering why Crowdstrike is getting it wrong, unless their API is broken.

**Comment by maertv** [comment]
The CrowdStrike Falcon platform UI (web) shows these URLs exactly the same way. It seems that this is how these URLs are in their system.

Unfortunately, I do not know why these URLs are the way they are. Please contact CrowdStrike.
