### ISSUE TITLE
OpenCTI's documentation on notion not accessible

### ISSUE THREAD

**Issue by mohanex** [OpenCTI-Platform/connectors#1770]
Hello,

This is not a technical issue but rather an informative one.

While attempting to install the Tweetfeed connector, I encountered an issue with accessing the three Notion OpenCTI documentation pages that were tagged in the Installation section. Unfortunately, it seems that the provided links are not functional. Have these three documentation resources been relocated to a different website, or are they no longer accessible?

Thank you.

**Comment by Jipegien** [comment]
I have changed the links to the new documentation's pages. Documentation has been migrated to https://docs.opencti.io.
