### ISSUE TITLE
URLSCAN url enrichment

### ISSUE THREAD

**Issue by sudesh0sudesh** [OpenCTI-Platform/connectors#1785]
## Use case

URL enrichment

## Proposed Solution

There are very few sources for URL enrichment; What if we build a connector that submits the URL to urlscan via API, captures the UUID from response.

We can use the UUID received to in creation of the URL that can be viewed to see the image and add the URL link generated to the external reference?

## Would you be willing to submit a PR?

Yes

We strongly encourage you to submit a PR if you want and whenever you want. If your issue concern a "Community-support" connector, your PR will probably be accepted after some review. If the connector is "Partner-support" or "Filigran-support", a dev team make take over but will base its work on your PR, speeding the process. It will be much appreciated.

**Comment by nino-filigran** [comment]
@sudesh0sudesh This is something already planned for next release https://github.com/OpenCTI-Platform/connectors/issues/1103
