### ISSUE TITLE
Connector import-external-ref doesn't work in some cases

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#1812]
## Description

In some cases, the pdf import does not work. I don't get any errors on the GUI side, but I can see one in the logs.

## Environment

OCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add an external reference with a Security Affairs article (e.g. https://securityaffairs.com/159074/reports/ransomfeed-q3-report-2023-ransomware.html)
2. Try to import the pdf with the import-external-reference connector
-> No error (in the GUI) but no pdf

#### Error in log

![Screenshot 2024-02-13 183035](https://github.com/OpenCTI-Platform/connectors/assets/70956706/acd2ef11-8de1-41fe-bed0-fe0267f6caad)

**Comment by nino-filigran** [comment]
@Lhorus6 what's the output you get?
On my side, the external reference modal remains opened, like if I would not have clicked on Create.

![image](https://github.com/OpenCTI-Platform/connectors/assets/148041607/13ab120f-a464-4b5c-80f0-acb883acc816)

**Comment by Lhorus6** [comment]
You have to test that:

![Screenshot 2024-02-14 105953](https://github.com/OpenCTI-Platform/connectors/assets/70956706/7e56850e-4775-46c3-b214-062a49d7df1a)

So just create an ext ref with 
- the title, and 
- the link to the security affairs article.

**Comment by Lhorus6** [comment]
Another example of a source that doesn't work : TrendMicro (e.g. https://www.trendmicro.com/en_us/research/24/b/cve202421412-water-hydra-targets-traders-with-windows-defender-s.html)

**Comment by nino-filigran** [comment]
Thanks for the pointer, indeed now I can reproduce!
