### ISSUE TITLE
[MISP] Add "misp-galaxy:mitre-attack-pattern" as a supported tag

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#1827]
## Use case

We need to import in OpenCTI the MITRE TPPs set in the tags. To do so, the connector needs to support the tag "misp-galaxy:mitre-attack-pattern" (in addition of the tag "mitre-attack:attack-pattern", cf https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/src/misp.py#L2017).

## Current Workaround

Nothing excepted doing all

## Proposed Solution

None except to do it manually, which is unthinkable for a large number of events to be imported.

## Additional Information

@helene-nguyen is already familiar with the subject and should be dealing with it next week. I create this ticket to trace it for the customer.

**Comment by Lhorus6** [comment]
Indeed, it seems to be the same thing. Here are the line where we should add "misp-galaxy:mitre-attack-pattern":

- https://github.com/OpenCTI-Platform/connectors/blob/a2e6fe2d35a5d85f7246a7884a25e2e5935489ea/external-import/misp-feed/src/misp-feed.py#L653

**Comment by helene-nguyen** [comment]
Hello @ckane,
Yes, I'm on it and will open the PR for review today :)

**Comment by ckane** [comment]
> Hello @ckane,
> Yes, I'm on it and will open the PR for review today :)

Thanks, you rock!

**Comment by vladimirvarga** [comment]
@helene-nguyen I am sorry to bother you with this, but your commit
https://github.com/OpenCTI-Platform/connectors/commit/22b5559f3c7d3da90249504578a9bf11882007bc
incorrectly changes the tag name.

You have addedd `"misp-galaxy:attack-pattern"` but it should have been `"misp-galaxy:mitre-attack-pattern"`. It's missing the prefix `mitre-`

**Comment by helene-nguyen** [comment]
Hi @vladimirvarga,
I add here the summary of our discussion about the expected tags.

On Misp, we can find both ways of writing tags

![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/9bc494f2-2cd7-474b-a47b-516cc94d935a)

![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/b25f112e-ab06-4c89-b323-afe97009f0c8)

My recent bugfix concerns this specific tag from `misp-galaxy:attack-pattern` and as you mentionned, `misp-galaxy:mitre-attack-pattern` also exists. I will add this change to complete the last one.

Thanks for you feedback :)
