### ISSUE TITLE
[MISP] The connector uses a deprecated class

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#1900]
## Description

The connector uses a deprecated class of the MISP library (PyMISP)

## Environment

OCTI 6.0.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the connector with log level "info"

## Screenshots

![capture](https://github.com/OpenCTI-Platform/connectors/assets/70956706/3f2039d4-d619-484b-802e-2496eaf7df8b)

**Comment by Lhorus6** [comment]
Maybe this PR solve the issue : https://github.com/OpenCTI-Platform/connectors/pull/1896

**Comment by Jipegien** [comment]
@Kedae As I understand it, it is not a bug, but a dependencies to update. Can you confirm?
@Lhorus6 is the connector still working?

**Comment by Lhorus6** [comment]
Yes, the connector still works. It just uses a deprecated component (indeed, I may have misused "bug")

**Comment by Kedae** [comment]
@Lhorus6 The PR has been merged, can you check if you still have the warning ?

**Comment by Lhorus6** [comment]
Not really, it was a customer who told me about it
