### ISSUE TITLE
[MITRE] Several errors appear during import

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#1909]
## Description

When launching the MITRE connector, several errors appear (see screenshot)

## Environment

OCTI 6.0.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the connector MITRE
2. Check the error raised

## Screenshots

![Screenshot 2024-03-10 041725](https://github.com/OpenCTI-Platform/connectors/assets/70956706/aaa1f61d-5561-4ee8-9a14-9058256d9a3e)

**Comment by SamuelHassine** [comment]
Expected behavior.
