### ISSUE TITLE
Launch import not working

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/connectors#196]
## Description

I enabled ImportFileStix2 and uploaded a Stix2 file but the button for Launch import remains greyed out.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 3.3.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to Data Import
2. Upload a STIX2 file
3. The option to import is not activated (download and delete are)

## Expected Output

The ability to import the file using the Connector

## Actual Output

The option to import is not active
 
## Additional Information

```
yarn check v1.22.4
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error "graphql-constraint-directive#graphql@^0.13.0" doesn't satisfy found match of "graphql@14.6.0"
warning "jest#jest-cli#yargs@^15.3.1" could be deduped from "15.4.1" to "yargs@15.4.1"
error "graphql-constraint-directive#graphql-tools#graphql@^0.13.0" doesn't satisfy found match of "graphql@14.6.0"
warning "@jest/core#jest-runtime#yargs@^15.3.1" could be deduped from "15.4.1" to "yargs@15.4.1"
warning "jest-environment-jsdom#jsdom#escodegen@^1.11.1" could be deduped from "1.14.3" to "escodegen@1.14.3"
warning "jest-environment-jsdom#jsdom#request-promise-native@^1.0.7" could be deduped from "1.0.9" to "request-promise-native@1.0.9"
warning "jest-environment-jsdom#jsdom#ws@^7.0.0" could be deduped from "7.3.1" to "ws@7.3.1"
info Found 5 warnings.
error Found 2 errors.
```

**Comment by smclinden** [comment]
![image](https://user-images.githubusercontent.com/8810661/97804694-8d975080-1c1f-11eb-98ce-9525e2404fa2.png)

**Comment by richard-julien** [comment]
Hi @smclinden ,

The connector is configured by default to handle json files. In your screenshot you upload .stix files. Try to change the extension and re upload.

**Comment by smclinden** [comment]
Yeah, I discovered that, yesterday, while searching the Web. It would be nice if that were documented, somewhere.

On a related note, I've been looking at importing STIX1 files using stix2_elevator but I am wondering if this actually makes sense?

**Comment by richard-julien** [comment]
Yep. Just added a description in the doc. See https://www.notion.so/ImportFileStix-868abc3d8daa420db6085f1c8ac36432

I think it makes sense. Could be interesting to improve the connector to detect the stix version and use the elevator to be able to import it in the platform. Supporting older version out of box should be interesting for the community.

You can create a feature request for that and if you want to push a PR for that it could be very helpful :)
