### ISSUE TITLE
When using the new connectors, it will not connect to OpenCTI.

### ISSUE THREAD

**Issue by Sh311c0d324** [OpenCTI-Platform/connectors#203]
#203  Description

When upgrading to the latest connectors, I am presented with the following error message. Any help with this would be much appreciated. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.0.5
2. OpenCTI version: Latest
3. OpenCTI client: 4.0.0
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Upgrade to the latest connectors
2. Try to use a connector
3. Error message

## Expected Output

It connects to OpenCTI

## Actual Output

From connector side

![image](https://user-images.githubusercontent.com/64936020/99439048-4b863400-28da-11eb-8d85-d85eda15621a.png)

 From OpenCTI side

![image](https://user-images.githubusercontent.com/64936020/99439500-df580000-28da-11eb-8531-960794a7bf7a.png)

**Comment by richard-julien** [comment]
Hi @Sh311c0d324 ,

Its a bit difficult to answer your problem.
Today the v4 and the connectors are not yet published so you can't use safely the rolling docker images or the code source.

OpenCTI version: Latest -> v3 or rolling?
OpenCTI client: 4.0.0 -> This version is not release yet. You talk about the rolling?
Upgrade to the latest connectors -> Version?

Thanks

**Comment by Sh311c0d324** [comment]
Yeah I am talking about the rolling. I went ahead and dropped to the pycti 3.3.3 version and it's working fine sorry for the confusion.

**Comment by richard-julien** [comment]
No problem :)
