### ISSUE TITLE
Qradar connector error in script

### ISSUE THREAD

**Issue by vanitasKE** [OpenCTI-Platform/connectors#2033]
## Environment

1. Linux Debian 11 bullseye
2. OpenCTI version: 6.0.9
3. OpenCTI client: 6.0.9
4. Other environment details:
image: opencti/connector-qradar:6.0.9
image: opencti/platform:6.0.9
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. install : git clone https://github.com/OpenCTI-Platform/docker.git
2. configure : vim docker-compose.yml
3. export env 
4. docker-compose up -d

## Expected Output

Create refference set in Qradar

{"timestamp": "2024-04-16T10:08:55.793727Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "an error occurred while consuming messages", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 62, in create\n    f\"{self.collection_url}_{self.get_type(payload)}\",\n                             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 49, in get_type\n    ).group(1)\n      ^^^^^\nAttributeError: 'NoneType' object has no attribute 'group'"}

28d960c5293d   opencti/connector-qradar:6.0.9                         "/entrypoint.sh"         10 minutes ago   Restarting (1) 33 seconds ago         

Started docker-compose ip -d .... and qradar connector keeep restarting with error above

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/154703269/6fda9b6e-ed32-477b-b366-acf3576994f1)

**Comment by Megafredo** [comment]
Hi @vanitasKE, there seems to be a typo in the "reference_name" variable in docker-compose :

Actual: QRADAR_RFERENCE_NAME: opencti 
New: QRADAR_REFERENCE_NAME: opencti

**Comment by vanitasKE** [comment]
Hi @Megafredo, ty i rewrited this typo but issue is still occuring :
`{"timestamp": "2024-04-16T15:14:08.233188Z", "level": "INFO", "name": "api", "message": "Health check (platform version)..."}
{"timestamp": "2024-04-16T15:14:08.372886Z", "level": "INFO", "name": "api", "message": "Health check (platform version)..."}
{"timestamp": "2024-04-16T15:14:08.824192Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "Connector registered with ID", "attributes": {"id": "9380b5b7-dd6c-4738-8076-6a786eb1f758"}}
{"timestamp": "2024-04-16T15:14:08.824807Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "Starting PingAlive thread"}
{"timestamp": "2024-04-16T15:14:08.825376Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "connector helper initialized"}
{"timestamp": "2024-04-16T15:14:08.825664Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "reference_set created"}
{"timestamp": "2024-04-16T15:14:08.827524Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "Starting ListenStream thread"}
{"timestamp": "2024-04-16T15:14:08.828265Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "starting 10 consumer threads"}
{"timestamp": "2024-04-16T15:14:08.828892Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "Starting StreamAlive thread"}
{"timestamp": "2024-04-16T15:14:08.832388Z", "level": "INFO", "name": "OpenCTI QRADAR Connector", "message": "Starting to listen stream events", "attributes": {"live_stream_url": "http://opencti:8080/stream/b20f4027-08f8-4f49-a7b2-e2b5ccb149c7?recover=2024-04-16T15:14:08Z", "listen_delete": "true", "no_dependencies": "false", "with_inferences": "false"}}
{"timestamp": "2024-04-16T15:14:09.199876Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "an error occurred while consuming messages", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 62, in create\n    f\"{self.collection_url}_{self.get_type(payload)}\",\n                             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 49, in get_type\n    ).group(1)\n      ^^^^^\nAttributeError: 'NoneType' object has no attribute 'group'"}
{"timestamp": "2024-04-16T15:14:09.200851Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "an error occurred while consuming messages", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 62, in create\n    f\"{self.collection_url}_{self.get_type(payload)}\",\n                             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 49, in get_type\n    ).group(1)\n      ^^^^^\nAttributeError: 'NoneType' object has no attribute 'group'"}
{"timestamp": "2024-04-16T15:14:09.201453Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "'NoneType' object has no attribute 'group'", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 62, in create\n    f\"{self.collection_url}_{self.get_type(payload)}\",\n                             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 49, in get_type\n    ).group(1)\n      ^^^^^\nAttributeError: 'NoneType' object has no attribute 'group'"}`

**Comment by vanitasKE** [comment]
Here is my yml file
`  connector-qradar:
    image: opencti/connector-qradar:6.0.9
    environment:
      OPENCTI_URL: http://opencti:8080
      OPENCTI_TOKEN: ${OPENCTI_ADMIN_TOKEN}
      CONNECTOR_ID: ${CONNECTOR_QRADAR_ID}
      CONNECTOR_LIVE_STREAM_ID: b20f4027-08f8-4f49-a7b2-e2b5ccb149c7 # ID of the live stream created in the OpenCTI UI
      CONNECTOR_LIVE_STREAM_LISTEN_DELETE: null
      CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES: null
      CONNECTOR_NAME: OpenCTI QRADAR Connector
      CONNECTOR_SCOPE: qradar
      CONNECTOR_CONFIDENCE_LEVEL: 80 # From 0 (Unknown) to 100 (Fully trusted)
      CONNECTOR_LOG_LEVEL: info
      QRADAR_URL: https://url
      QRADAR_TOKEN: 6bc8954b-ee1c-4410-b522-b2f7a747e3db
      QRADAR_SSL_VERIFY: null
      QRADAR_REFERENCE_NAME: opencti
      QRADAR_IGNORE_TYPES: label,marking-definition,identity
`

**Comment by Megafredo** [comment]
Hi @vanitasKE, in fact, there is still a problem with the structure of docker-compose.yml.
It should look like this:

```
version: "3"
services:
  connector-qradar:
    image: opencti/connector-qradar:6.0.9
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_LIVE_STREAM_ID=live # ID of the live stream created in the OpenCTI UI
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
      - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true
      - CONNECTOR_NAME=OpenCTI QRADAR Connector
      - CONNECTOR_SCOPE=qradar
      - CONNECTOR_LOG_LEVEL=info
      - QRADAR_URL=https://QRADAR1.changeme.com
      - QRADAR_TOKEN=Token1
      - QRADAR_SSL_VERIFY=true
      - QRADAR_REFERENCE_NAME=opencti
      - QRADAR_IGNORE_TYPES=label,marking-definition,identity
    restart: always
   ```
   
   Thanks, it will be fixed !

**Comment by vanitasKE** [comment]
Hi @Megafredo, 
I changed connector according to you:
    depends_on:
      - opencti
  connector-qradar:
    image: opencti/connector-qradar:6.0.9
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_QRADAR_ID}
      - CONNECTOR_LIVE_STREAM_ID=b20f4027-08f8-4f49-a7b2-e2b5ccb149c7 # ID of the live stream created in the OpenCTI UI
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=null
      - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=null
      - CONNECTOR_NAME=OpenCTI QRADAR Connector
      - CONNECTOR_SCOPE=qradar
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
      - QRADAR_URL=https://url
      - QRADAR_TOKEN=token id
      - QRADAR_SSL_VERIFY=false
      - QRADAR_REFERENCE_NAME=opencti
      - QRADAR_IGNORE_TYPES=label,marking-definition,identity
    restart: always

volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:
  


Live stream is running:
![image](https://github.com/OpenCTI-Platform/connectors/assets/154703269/2d310c9d-c991-4a54-a7db-0170ed19d91b)

But connector still restarting:
![image](https://github.com/OpenCTI-Platform/connectors/assets/154703269/00a1e81f-1802-4f83-bea2-998ef83d1b1a)

root@debian:~/opencti/docker# docker service logs nirui3vqn93b
opencti_connector-qradar.1.q6keyp2qnrvz@debian    | {"timestamp": "2024-04-17T06:27:00.022421Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "an error occurred while consuming messages", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 62, in create\n    f\"{self.collection_url}_{self.get_type(payload)}\",\n

**Comment by vanitasKE** [comment]
Also this error while ssl-verify set to true:
`root@debian:~/opencti/docker# docker service logs nirui3vqn93b
opencti_connector-qradar.1.yoh28hbpwnxs@debian    | {"timestamp": "2024-04-17T06:37:41.749943Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "an error occurred while consuming messages", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 61, in create\n    r = requests.post(\n        ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/requests/adapters.py\", line 458, in send\n    self.cert_verify(conn, request.url, verify, cert)\n  File \"/usr/local/lib/python3.11/site-packages/requests/adapters.py\", line 261, in cert_verify\n    raise OSError(\nOSError: Could not find a suitable TLS CA certificate bundle, invalid path: null"}
`

**Comment by vanitasKE** [comment]
Hi Again ,

I change ssl_verify to false instead to null and connection is working and RS is created thank you.
Just this eeror is in logs.
''. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
opencti_connector-qradar.1.d1kh167gej5h@debian    |   warnings.warn(

**Comment by Megafredo** [comment]
Ok, that's good news, even though the certificate issue baffles me ! Anyway, thanks for your feedback !

**Comment by Megafredo** [comment]
Hello @Alib333, your error has also been identified on this issue : #1437
I invite you to see it move forward!
