### ISSUE TITLE
Flashpoint - tackle issues 

### ISSUE THREAD

**Issue by nino-filigran** [OpenCTI-Platform/connectors#2042]
## Description

In this ticket https://github.com/OpenCTI-Platform/connectors/issues/1988 , some issues regarding the connector have been defined. The goal of this ticket is simply to ensure [that we tackle the following problem: MVP] The connector seems to loop (see screenshot) ✅

**Comment by Lhorus6** [comment]
The real bug is the first line "The connector seems to loop (see screenshot)". Without correcting this, we won't be able to deploy it.

**Comment by nino-filigran** [comment]
thx, I've modified this.

**Comment by Lhorus6** [comment]
If we can also manage the second point (remove "Flashpoint" org of the object_ref of the report) , that would be perfect, it's two lines of code to remove. 
Identify the location in the code + delete it -> This will take no more than 5 minutes, for sure

**Comment by richard-julien** [comment]
Will be handled by https://github.com/OpenCTI-Platform/connectors/issues/1988
