### ISSUE TITLE
[VirusTotal] OpenCTI API is not reachable and AUTH_REQUIRED errors

### ISSUE THREAD

**Issue by Zhindonm** [OpenCTI-Platform/connectors#2043]
## Description

I added the VirusTotal connector to my docker-compose, however I keep getting the following errors

```
OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO Health check (me)... | timestamp=2024-04-17T14:49:11.898050Z name=api
ERROR {'name': 'AUTH_REQUIRED', 'message': 'You must be logged in to do this.'} | timestamp=2024-04-17T14:49:11.920434Z name=api exc_info=Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 380, in health_check
    test = self.query(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 344, in query
    raise ValueError(
ValueError: {'name': 'AUTH_REQUIRED', 'message': 'You must be logged in to do this.'}
```

The connector is in the right network, I have validated my API key and it works. 

## Environment

`CONNECTOR_VIRUSTOTAL_TOKEN` is the UUID from a dedicated OpenCTI user I created with a role that can bypass all capabilities.  
 `CONNECTOR_VIRUSTOTAL_ID` is a randomly generated UUID.  
`CONNECTOR_VIRUSTOTAL_APIKEY` is my VT Enterprise API key

```
  connector-virustotal:
    image: opencti/connector-virustotal:6.0.9
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN={CONNECTOR_VIRUSTOTAL_TOKEN}
      - CONNECTOR_ID={CONNECTOR_VIRUSTOTAL_ID}
      - CONNECTOR_NAME=VirusTotal
      - CONNECTOR_SCOPE=StixFile,Artifact,IPv4-Addr,Domain-Name,Url
      - CONNECTOR_AUTO=false # Enable/disable auto-enrichment of observables
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_EXPOSE_METRICS=false
      - VIRUSTOTAL_TOKEN={CONNECTOR_VIRUSTOTAL_APIKEY}
```

## Expected Output

Internal Enrichment option enabled for observables

## Actual Output

An error indicating that the OpenCTI API is not accessible and that I need to authenticate.

## Additional information

I have multiple connectors setup, there is no conflict in connector IDs as they are all unique. This is the only connector with these errors

Screenshot shows containers are in the same network  
![image](https://github.com/OpenCTI-Platform/connectors/assets/32451415/f07c77db-42c8-44fa-b6de-f1a8c3d65e51)

**Comment by annoyingapt** [comment]
I think you need a "$" in front of your brackets in your compose file
https://docs.docker.com/compose/environment-variables/set-environment-variables/
