### ISSUE TITLE
[MISP] OpenCTI API is not reachable

### ISSUE THREAD

**Issue by B1u3f331** [OpenCTI-Platform/connectors#205]
## Description

After lunached MISP module, the logs said the OpenCTI API is not reachable and Threat-Actors problems.

## Environment

1. OS (where OpenCTI server runs): Linux opencti-rolling 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

2. OpenCTI version: “From Virtual machine template” https://drive.google.com/drive/folders/1bvB6RmdQNHMW_3h-88KbAit9GRZlL5Bj

3. OpenCTI client: “From Virtual machine template” https://drive.google.com/drive/folders/1bvB6RmdQNHMW_3h-88KbAit9GRZlL5Bj

4. Other environment details: Running in the VMware ESXi

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Running OpenCTI and MISP
2. Download Connectors(MISP) & Configure docker-compose.yml
3. Running command, "sudo docker-compose up"

## Expected Output

MISP module shows in the dashboard(Data -> Connectors)

## Actual Output

NO MISP module in the dashboard(Data -> Connectors)

 
## Additional information

1. docker-compose.yml

version: '3'
services:
  connector-misp:
    image: opencti/connector-misp:3.3.1
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=7c3928d5-b2db-42ec-9863-75858ad7e06e
      - CONNECTOR_ID=767985a8-ec16-4962-8f3d-8ed7cf57d9f4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://172.18.4.156 # Required
      - MISP_KEY=2D8J44hZOf23gWSABz83J3h16eH0NyLZwzKZ7DAk # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always

2. Logs from "sudo docker-compose up"

connector-misp_1  | INFO:root:Listing Threat-Actors with filters null.

connector-misp_1  | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

INFO:root:{"errors":[{"message":"Cannot query field \"stix_id_key\" on type \"ThreatActor\".","locations":[{"line":8,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"stix_label\" on type \"ThreatActor\".","locations":[{"line":9,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"alias\" on type \"ThreatActor\". Did you mean \"aliases\"?","locations":[{"line":13,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"graph_data\" on type \"ThreatActor\".","locations":[{"line":15,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"goal\" on type \"ThreatActor\". Did you mean \"goals\"?","locations":[{"line":16,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"secondary_motivation\" on type \"ThreatActor\". Did you mean \"secondary_motivations\", \"primary_motivation\", or \"personal_motivations\"?","locations":[{"line":20,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"personal_motivation\" on type \"ThreatActor\". Did you mean \"personal_motivations\", \"primary_motivation\", or \"secondary_motivations\"?","locations":[{"line":21,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"createdByRef\" on type \"ThreatActor\". Did you mean \"createdBy\", \"created\", or \"created_at\"?","locations":[{"line":28,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"organization_class\" on type \"Organization\".","locations":[{"line":40,"column":25}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"markingDefinitions\" on type \"ThreatActor\".","locations":[{"line":47,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"tags\" on type \"ThreatActor\".","locations":[{"line":65,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"stix_id_key\" on type \"ExternalReference\".","locations":[{"line":83,"column":25}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"relation\" on type \"ExternalReferenceEdge\".","locations":[{"line":92,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}

**Comment by richard-julien** [comment]
Hi @B1u3f331 , looks like your deployment have some versions mismatch.
Please check that you use also the version 3.3.1 of the OpenCTI Api.

**Comment by khalidrehan** [comment]
I belive I have the same issue [issue #981].
I used: `image: opencti/connector-misp:3.3.1`

**Comment by khalidrehan** [comment]
> Hi @B1u3f331 , looks like your deployment have some versions mismatch.
> Please check that you use also the version 3.3.1 of the OpenCTI Api.

That is right, it worked when I matched the version.
Thanks!
