### ISSUE TITLE
Hygiene is breaking

### ISSUE THREAD

**Issue by daemitus** [OpenCTI-Platform/connectors#2058]
## Description

Hygiene is throwing an error for the field `indicatorsIds` missing. In my current instance, I don't have a single hygiene tag applied to a single observable or indicator at all.

```
opencti_entity={"timestamp": "2024-04-18T17:18:31.799117Z", "level": "INFO", "name": "Hygiene", "message": "opencti_entity={'id': '570b40f6-2760-4229-8d59-0d0a2cd807a3', 'standard_id': 'domain-name--250dd19d-bc65-5eb7-a1e5-5218ba1d4d0d', 'entity_type': 'Domain-Name', 'parent_types': ['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Cyber-Observable'], 'spec_version': '2.1', 'created_at': '2024-04-18T16:53:18.587Z', 'updated_at': '2024-04-18T16:53:18.587Z', 'objectOrganization': [], 'createdBy': None, 'objectMarking': [], 'objectLabel': [], 'externalReferences': [], 'importFiles': [], 'observable_value': 'www.amazon.com', 'value': 'www.amazon.com', 'createdById': None, 'objectMarkingIds': [], 'objectLabelIds': [], 'externalReferencesIds': [], 'importFilesIds': []}"}

connector-1  | {"timestamp": "2024-04-18T17:18:31.804616Z", "level": "ERROR", "name": "Hygiene", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 352, in _data_handler\n    message = self.callback(event_data)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-hygiene/hygiene.py\", line 272, in _process_message\n    return self._process_observable(stix_objects, stix_entity, opencti_entity)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-hygiene/hygiene.py\", line 234, in _process_observable\n    for indicator_id in opencti_entity[\"indicatorsIds\"]:\n                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nKeyError: 'indicatorsIds'"}
```

## Environment

1. OS (where OpenCTI server runs): docker-compose on mac
2. OpenCTI version: 6.0.5 (earliest checked) -> 6.0.10
3. OpenCTI client: python
4. Other environment details: n/a

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Spin up the system and hygiene
2. via the gui, create an indicator and automatic observable for www.amazon.com
3. apply hygiene enrichment if not automatic

## Expected Output

hygiene tag applied

## Actual Output

error reported, as seen in the log above

## Additional information

https://github.com/OpenCTI-Platform/connectors/blob/master/internal-enrichment/hygiene/src/hygiene.py#L232

**Comment by daemitus** [comment]
For what its worth, its busted on the demo stack too.

**Comment by SamuelHassine** [comment]
Fixed by https://github.com/OpenCTI-Platform/client-python/commit/63e507865804ad7c7c2b0b66a365ddad08117376.
