### ISSUE TITLE
connector-abuseipdb bug

### ISSUE THREAD

**Issue by bambooqj** [OpenCTI-Platform/connectors#2079]
## Description

When I am processing IP data using ipdb, I triggered a strange error.

## Environment

1. OS Ubuntu 22.04
2. OpenCTI version: 6.0.10
3. OpenCTI client: python
4. Other environment details: opencti/connector-abuseipdb:6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:

## Expected Output

{"timestamp": "2024-04-25T15:02:42.450377Z", "level": "ERROR", "name": "AbuseIPDB", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 352, in _data_handler\n    message = self.callback(event_data)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-abuseipdb/abuseipdb.py\", line 158, in _process_message\n    id=Location.generate_id(ckey, \"Country\"),\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_location.py\", line 203, in generate_id\n    name = name.lower().strip()\n           ^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'lower'"}

**Comment by Megafredo** [comment]
Hi @allexBR,
This error seems to occur because the `interval` environment variable is not set or is set incorrectly.
Do you have your interval environment variable defined in your `config.yml` ?

**Comment by allexBR** [comment]
Hi @Megafredo,

My AbuseIPDB IP Blacklist connector config.yml file is set as follows:

opencti:
  url: 'http://my-opencti-server:8080'
  token: 'My-UUIDv4-Token'

connector:
  id: 'My-custom-UUIDv4-generated'
  type: 'EXTERNAL_IMPORT'
  name: 'AbuseIPDB IP Blacklist'
  scope: 'abuseipdb' # MIME type or SCO
  log_level: 'info'

abuseipdb:
  api_url: 'https://api.abuseipdb.com/api/v2/blacklist'
  api_key: 'My-AbuseIPDB-API-Key'
  score: 100
  limit: 1000
  interval: 2 # In days, must be strictly greater than 1



I'm using the same sample that integrates OpenCTI. However, I used AI to check the Python script and there were improvements in the code making it work correctly.


Still, I appreciate your response. Thanks!
