### ISSUE TITLE
cve connector doesn't pull anything without error

### ISSUE THREAD

**Issue by 50YUD4N60** [OpenCTI-Platform/connectors#2087]
## Description

Can't pull cve info with cve connector,

suppose starting to pull data after "message": "[CONNECTOR] Connector retrieve CVE history for year 2019, 365 days left"}, but it stuck at here.

## Environment

1. OS  Ubuntu 16.4
2. OpenCTI version:OpenCTI 6.0.10
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: Python 3.10.12

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. sudo docker-compose up -d

## Expected Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/125332597/79109fd3-33a6-496e-a589-1bc0d0e25438)

## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/125332597/9a9bf462-4845-4b33-8a46-fa5d0fbbaa4c)

## Additional information
my config in docker-compose.yml

connector-cve:
    image: opencti/connector-cve:6.0.10
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CVE}
      - CONNECTOR_NAME=Common Vulnerabilities and Exposures
      - CONNECTOR_SCOPE=identity,vulnerability
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_RUN_AND_TERMINATE=true
      - CONNECTOR_LOG_LEVEL=debug
      - CVE_BASE_URL=https://services.nvd.nist.gov/rest/json/cves
      - CVE_API_KEY=${NVD_API_KEY}
      - CVE_INTERVAL=2 # Required, in hours advice min 2
      - CVE_MAX_DATE_RANGE=100 # In days, max 120
      - CVE_MAINTAIN_DATA=true # Required, retrieve only updated data
      - CVE_PULL_HISTORY=true # If true, CVE_HISTORY_START_YEAR is required
      - CVE_HISTORY_START_YEAR=2019 # Required if pull_history is True, min 2019 (see documentation CVE and CVSS base score V3.1)
    restart: always
    depends_on:
      - opencti

**Comment by Misschihiro** [comment]
I have the same problem. How to solve this?  And in my platform(data-->ingestion-->connectors), I can not find the cve connetor. opencti version:6.0.10

**Comment by helene-nguyen** [comment]
@Misschihiro @50YUD4N60 I'm on it, I'll give you an update 

@Misschihiro If you cannot find CVE connector, it's probably a misconfiguration when it is deployed and an another issue can be open or you can write to me on Slack to check it, @50YUD4N60 do you see the CVE connector in Data Ingestion tab ?

**Comment by helene-nguyen** [comment]
@50YUD4N60 I've deployed the connector to test it and it may take some time to get the first data from 2019, but everything seems to work.

![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/6bb51410-5f01-4a31-a5df-7c886a972d0c)

Could you update your platform and try again? Sometimes, from one network to another, you can have some latency

**Comment by helene-nguyen** [comment]
@50YUD4N60 Do you have any update? 
I close the issue for now but it can be re-opened if needed :)

**Comment by anavitgo** [comment]
Hello! I am having the same problem. My config for the cve connector is the same as @50YUD4N60

**Comment by anavitgo** [comment]
btw, what is the problem that the connectors exceed the max tries to connect to opencti on /graphql endpoint? Is this expected?

**Comment by helene-nguyen** [comment]
@anavitgo If you pull the history, could you try 2024 in the configuration file?
If the connectors exceed the max tries, it means that it cannot connect to your OpenCTI, could you check the logs ?

**Comment by nhungnghh** [comment]
I have the same problem as you, I still can't fix it. Please help me. I crawl CVE from NVD to send bundle on OpenCTI, but it always notify ERROR 404. I actually don't know reason, I try everything

**Comment by helene-nguyen** [comment]
@randomerror48 @nhungnghh sorry for the delay of answer, we have fix the issue. It was the the attributes key for the header that change.
Could you please retry?

**Comment by nhungnghh** [comment]
I have a new issue. I want to import more observables include: hash, ip,
hostname. It's about 6 millions records. So, I don't how to import them. I
try many solution but it doesn't work. I hope you can help me.
Thank you!

Vào Th 7, 4 thg 10, 2025 vào lúc 03:47 Helene Nguyen <
***@***.***> đã viết:
