### ISSUE TITLE
VirusTotal Connector updating score incorrectly

### ISSUE THREAD

**Issue by demonoidvk** [OpenCTI-Platform/connectors#2091]
## Description
When a new observable is added to the platform and at that time, lets say it got a score of 50.
When an enrichment is done using virustotal, and the score "vt_score" is less then "opencti_score", and the flag : "replace_with_lower_score" is false. it still updates the score with the vt_score.

I tried it with both options for flag: true and false, it always updates the score.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 6.0.9
3. OpenCTI client: Connector
4. Other environment details: the whole setup is in Docker Containers, using docker-compose file.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. take a note of opencti platform score
2. Run the virustotal enrichment on any IOC.
3. Check the score, if it changes.

## Expected Output

when the vt_score is less then opencti_score, and Flag, is also "False", the score should be left as is.

## Actual Output

when the vt_score is less then opencti_score, and Flag, is also "False", the score changes to vt_score.

## Additional information

The code for this change: https://github.com/OpenCTI-Platform/connectors/blob/master/internal-enrichment/virustotal/src/virustotal/builder.py - > after line 94 to 101.

On line 101, the return value should be opencti_score.

**Comment by nino-filigran** [comment]
@Megafredo or @helene-nguyen  can you have a look at this please?

**Comment by demonoidvk** [comment]
Probable issue with following code: opencti_score = (
            self.stix_entity["x_opencti_score"]
            if "x_opencti_score" in self.stix_entity
            else self.helper.api.get_attribute_in_extension("score", self.stix_entity)
        )

This is line 89, onwards. opencti_score is always None, so everytime update happens.
