### ISSUE TITLE
GreyNoise Feed connector environment variables not properly ingested

### ISSUE THREAD

**Issue by unguest** [OpenCTI-Platform/connectors#2106]
## Description

GreyNoise connector does not create the `config.yml` file.

## Environment

1. OS (where OpenCTI server runs): Debian 12 Bookworm
2. OpenCTI version: 6.0.10
3. OpenCTI client: frontend
4. Other environment details: Docker management _via_ Portainer

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Copy/Paste the yml config into the docker-compose file.

## Expected Output

Connector working, `docker attach` showing working operations.

## Actual Output

1. Docker attach shows the following message : `{"timestamp": "2024-05-05T17:11:22.728620Z", "level": "ERROR", "name": "GreyNoiseFeed", "message": "Value for source is not one of: feed, tags", "exc_info": "NoneType: None"}`
2. When executing `env` command in the greynoise-feed container, `GREYNOISE_SOURCE` variable is well set to `feed` and `GREYNOISE_FEED_TYPE` to `benign+malicious`.

## Additional information

None.

**Comment by helene-nguyen** [comment]
@unguest Maybe I can give you some explanations on this bug.

If you need to add an environment variable, you don't need to copy/paste the config.yml when deploying via docker containers.
In the Greynoise connector folder you'll find a docker-compose.yml file with all the necessary configuration and you just need to replace some values to make it work.

You just have to replace "ChangeMe"
![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/190af9ec-d908-4e70-ad07-205284a23cbb)
By running your docker-compose.yml file, it will take the `environment` into account.

If you deploy it via Portainer using stacks:
![image](https://github.com/OpenCTI-Platform/connectors/assets/75518128/ebecc813-578e-4d76-acaf-2d4e05aacbc8)
If the connector is deployed aside, don't forget to add the network of your OpenCTI.

The config.yml file is here for local development, you can run the python script manually (make sure you have OpenCTI running on your local machine).

And if you have copied content from confi.yml to docker-compose.yml, the format is not the good one and you will get errors.

If you need more informations, you can contact us on Slack :)

Hope that helps,

I will close the issue and it can be re-opened if needed :)

**Comment by unguest** [comment]
Sorry for the confusion with the original title which mentions config.yml file, I merged title with another PR...

I'm talking about the greynoise-feed container, directly deployed on the opencti stack via Portainer, nothing to see with config.yml file 😅.
