### ISSUE TITLE
AlienVault Connector observables ineffiecent in new data model.

### ISSUE THREAD

**Issue by DR913** [OpenCTI-Platform/connectors#211]
## Problem to Solve

The AlienVault Connector is currently creating one file observable per hash indicator, but must pulses contain multiple hash indicators for the same file.

## Current Workaround

It appears that having a VirusTotal license will reduce this problem, but it would be expensive for the volume of data. You can also continue to exclude MD5 and SHA1 files, but some systems are still really reliant on these indicators (and SHA1 is very valuable for amcache analysis).  Otherwise, it appears that it would be a manual process to clean/curate the data after it has been ingested.

## Proposed Solution

Checking the description of the indicator could allow us to perform a search to see if the file observable already exists.
- `^SHA256 of `
- `^SHA1 of `
- `^MD5 of `
If any of the above patterns exist in the description of the observable, we can can check to see if either the indicator value and the hash in the description exists in the database.  If the file exists based on searching either hash, we can add the missing value.  If neither of them exists, we can create a new file observable with both hashes.

## Additional Information

N/A

**Comment by maertv** [comment]
It is possible that the current AlienVault connector uses the wrong API.

For example, the subset of indicators from the current response of the API call:
```
...
        {
          "id": 2748189961,
          "indicator": "56ceb6d0011d87b6e4d7023d7ef85676",
          "type": "FileHash-MD5",
          "created": "2020-12-14T03:44:21",
          "content": "",
          "title": "",
          "description": "",
          "expiration": null,
          "is_active": 1,
          "role": null
        },
        {
          "id": 2748189962,
          "indicator": "019085a76ba7126fff22770d71bd901c325fc68ac55aa743327984e89f4b0134",
          "type": "FileHash-SHA256",
          "created": "2020-12-14T03:44:21",
          "content": "",
          "title": "",
          "description": "",
          "expiration": null,
          "is_active": 1,
          "role": null
        },
...
```
Do these hashes belong to the same file?

In some cases there is a description with for example `MD5 of` but not always. It seems to depend on the pulse creator and even then not all of them have it.

You can use `curl` to query the API:
```
curl -H "X-OTX-API-KEY: <X-OTX-API-KEY>" "https://otx.alienvault.com/api/v1/pulses/subscribed?modified_since=2020-12-16T00%3A00%3A00&limit=500"
```

The current AlienVault connector creates STIX2 bundles that will be processed by the worker(s). The connector does not directly create any entities.

**Comment by DR913** [comment]
Thanks for the quick response @maertv

My experience has been that pluses where the author is "AlienVault" have the `MD5 of` in the description field. A lot of the pluses from "AlienVault" itself cover the OSINT from the larger security vendors, so I feel like it would still be a valuable improvement to the connector if we can consolidate these into a single file observable instead of three separate entries.

I've placed a example from my subscription below. You can search "9522f369ac109b03e6c16511d49d1c5b42e12a44" or "989334094ec5ba8e0e8f2238cdf34d5c57c283f2" to see the case.

`{
    "id": "5fdb7a78511b3c28ff7bd93b",
    "name": "Operation SignSight: Supply chain attack against a certification authority in Southeast Asia",
    "description": "ESET researchers uncovered this new supply-chain attack in early December 2020 and notified the compromised organization and the VNCERT. We believe that the website has not been delivering compromised software installers as of the end of August 2020 and ESET telemetry data does not indicate the compromised installers being distributed anywhere else. The Vietnam Government Certification Authority confirmed that they were aware of the attack before our notification and that they notified the users who downloaded the trojanized software.",
    "author_name": "AlienVault",
    "modified": "2020-12-17T15:34:16.853000",
    "created": "2020-12-17T15:34:16.853000",
    "revision": 1,
    "tlp": "white",
    "public": 1,
    "adversary": "",
    "indicators": [{
        "id": 2580512549,
        "indicator": "830dd354a31ef40856978616f35bd6b7",
        "type": "FileHash-MD5",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "Cabinet_Archive",
        "description": "MD5 of 9522f369ac109b03e6c16511d49d1c5b42e12a44",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2582698716,
        "indicator": "9522f369ac109b03e6c16511d49d1c5b42e12a44",
        "type": "FileHash-SHA1",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "Cabinet_Archive",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2586509904,
        "indicator": "office365.blogdns.com",
        "type": "hostname",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2589542258,
        "indicator": "6c1db6c3d32c921858a4272e8cc7d78280b46bad20a1de23833cbe2956eebf75",
        "type": "FileHash-SHA256",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2589707342,
        "indicator": "97a5fe1d2174e9d34cee8c1d6751bf01f99d8f40b1ae0bce205b8f2f0483225c",
        "type": "FileHash-SHA256",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "Cabinet_Archive",
        "description": "SHA256 of 9522f369ac109b03e6c16511d49d1c5b42e12a44",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2743822389,
        "indicator": "1d9bc6939e2eceb3e912f158e05e04cadc1965849c4eb2c96e37e51a7d4f7aa5",
        "type": "FileHash-SHA256",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2743822395,
        "indicator": "f659b269fbe4128588f7a2fa4d6022cc74e508d28eee05c5aff26cc23b7bd1a5",
        "type": "FileHash-SHA256",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "SHA256 of 989334094ec5ba8e0e8f2238cdf34d5c57c283f2",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2743822405,
        "indicator": "vgca.homeunix.org",
        "type": "hostname",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2754639960,
        "indicator": "fc6da5e90277cde60d19e258949767202465893886d6a6c63febfb8b5770d026",
        "type": "FileHash-SHA256",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2754639961,
        "indicator": "c11e25278417f985cc968c1e361a0fb0",
        "type": "FileHash-MD5",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "MD5 of 989334094ec5ba8e0e8f2238cdf34d5c57c283f2",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2754639962,
        "indicator": "5c77a18880cf58df9fba102dd8267c3f369df449",
        "type": "FileHash-SHA1",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2754639963,
        "indicator": "5dfc07bb6034b4fda217d96441fb86f5d43b6c62",
        "type": "FileHash-SHA1",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2754639964,
        "indicator": "989334094ec5ba8e0e8f2238cdf34d5c57c283f2",
        "type": "FileHash-SHA1",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }, {
        "id": 2754639965,
        "indicator": "b0e4e9bb6ef8aa7a9fcb9c9e571d8162b1b2443a",
        "type": "FileHash-SHA1",
        "created": "2020-12-17T15:34:17",
        "content": "",
        "title": "",
        "description": "",
        "expiration": null,
        "is_active": 1,
        "role": null
    }],
    "tags": ["phantomnet", "vietnam", "able desktop"],
    "targeted_countries": ["Philippines", "Viet Nam"],
    "malware_families": ["PhantomNet", "SManager"],
    "attack_ids": ["T1105", "T1027", "T1113", "T1553", "T1033", "T1053", "T1071", "T1082", "T1090", "T1195", "T1204", "T1543", "T1573"],
    "references": ["https:\/\/www.welivesecurity.com\/2020\/12\/17\/operation-signsight-supply-chain-attack-southeast-asia\/"],
    "industries": [],
    "extract_source": [],
    "more_indicators": false
}`

**Comment by SamuelHassine** [comment]
Hello,

Since a lot of things have been modified since the issue has been raised (V4, improvments on merging and on the AlienVault connector, etc.). I close this issue for now. Please feel free to open a new one and give some details about the behaviour you would like to have in this connector.

Kind regards,
Samuel
