### ISSUE TITLE
FireEye Connector Error 'object_marking_refs'

### ISSUE THREAD

**Issue by GlennHD** [OpenCTI-Platform/connectors#212]
## Description

FireEye Connector Error 'object_marking_refs'

## Environment

1. OS: Ubuntu Server 20.04.1 LTS
2. OpenCTI v4.0.3
4. Docker version

## Reproducible Steps
- Setup FireEye Connector with valid credentials using the docker-compose.yml  example.

## Actual Output

- OpenCTI infinitely spawns "Works" every minute. Screencap [here](https://i.imgur.com/ElCLlig.png).
- Errors generated for "object_marking_refs'. Screencap [here](https://i.imgur.com/AHMPwKN.png).

## Expected Output

- FireEye data should be ingested but this error appears to be getting in the way. All other connectors appear to be working.

**Comment by SamuelHassine** [comment]
Will be fixed in 4.0.4.
