### ISSUE TITLE
[Export CSV] Relationships export with filter exports more than required

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#2120]
## Description

Take the below query on Relationships:

![image](https://github.com/OpenCTI-Platform/connectors/assets/124377454/e1fe2620-e3a9-4084-8791-09ece01f43fc)

When exporting to CSV, relationship types other than the one filtered for 'Related To' are also exported.

## Environment

6.0.10

## Reproducible Steps

Filter on Relationships with specific creator (that produces different types of relationships) and relationship type
Export as CSV
Observe other relationship types also exported

## Expected Output

Exports only filtered results

## Actual Output

Exports other relationship types

**Comment by Jipegien** [comment]
Can't reproduce it on 6.1.1 Can you upgrade your platform and retry? Reopen the issue of it persists.

**Comment by dominictory** [comment]
> Can't reproduce it on 6.1.1 Can you upgrade your platform and retry? Reopen the issue of it persists.

Not seeing this on 6.1.2. Thanks :)
