### ISSUE TITLE
MISP AUTH Key variable appears to be missing for the misp-feed connector

### ISSUE THREAD

**Issue by mgefx** [OpenCTI-Platform/connectors#2145]
How do I pass the MISP AUTH Key with the misp-feed connector? I don't see a variable in the docker compose file or in the .env. And misp-feed.py doesn't appear to reference a key either. Hopefully I'm just overlooking something but I keep getting 'HTTP 403 Forbidden' error when trying to run the misp-feed connector. My MISP connector works fine but it also has the "MISP_KEY" variable that I set whereas misp-feed doesn't appear to have that option. Thanks in advance for any help or direction!

**Comment by annoyingapt** [comment]
Are you connecting to a msip, you will then need to use the MISP connector, not MISP feed.
