### ISSUE TITLE
Virus Total connector fails to enrich observables with an empty score

### ISSUE THREAD

**Issue by Jipegien** [OpenCTI-Platform/connectors#2146]
## Description

When trying to enrich an IPv4 observable, VirusTotal sometimes fails with the following error:

![image](https://github.com/OpenCTI-Platform/connectors/assets/104078945/4cec17fb-6ba0-4f0c-951c-4efe7d0ec478)

## Environment

testing, 6.1.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Got to an Ipv4 observable, for example 94.156.69.166
2. launch Virus Total enrichement

## Expected Output

bundle stix generated and no error

## Actual Output

see screenshot above

## Additional information

support-package-May 20, 2024, 9:12:51 AM

**Comment by richard-julien** [comment]
https://github.com/OpenCTI-Platform/client-python/issues/646 must be done before.
Then code of previous fix must be rollback in favor on this new way to resolve information
