### ISSUE TITLE
[Intel471] List of bug and improvement  

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#2156]
## Description

The Intel471 connector is not operational as is. It has many blocking problems that prevent it from being put into production and many other points on which it could be improved.

### Blocking problems

- The "state" of the connector does not seem to be updated.
- Considering the number of operations in the works created by the connector, the connector seems to loop (i.e. always import the same data). This may be due to the fact that the connector does not update its state (previous point), and therefore always retrieves the data from the same date/timestamp.
- The x_opencti_main_observable field of the Indicator isn't filled. This is a mandatory field to fill in to be able to sort on types (e.g. IPv4, Domain name, etc.). See the example in the Threatfox connector code for example: https://github.com/OpenCTI-Platform/connectors/blob/48b88e88293666bd66293e040b98a0d6a50a11c2/external-import/threatfox/src/main.py#L419

### Desirable

- The author is not referenced in the Observables (STIX Cyber Observables) unlike all entities where it is well referenced (e.g. Report, Indicators, etc.)

![Screenshot 2024-05-22 195649](https://github.com/OpenCTI-Platform/connectors/assets/70956706/3ca1f736-d820-4eed-8642-b7cdc90c3b85)

- There is no relationship between Observables and Indicators. A relationship `Indicator -> "Based on" -> Observables` should be created.

![image](https://github.com/OpenCTI-Platform/connectors/assets/70956706/6b1af785-bf61-43a8-be3a-69e24b683280)

### Useful

- The connector does not model victims and threats. In the reports we can see the Indicators and Observables, but the rest would be interesting to capitalize on. For example, for a report on an APT29 campaign targeting France, it would be good to add the Intrusion set APT29 + the Country France + the "targets" relationship between the two.
- Adding the report as a text file attachment is great. A small improvement would be to name the file correctly (e.g. give it the name of the report). Currently, all files have the same name, i.e. "Raw Text"

![image](https://github.com/OpenCTI-Platform/connectors/assets/70956706/e7d9b16a-e4d3-4ebd-b1b9-a655df4b769d)

## Environment

6.1.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start the connector and wait

**Comment by Lhorus6** [comment]
In addition, the import of CVE (i.e. the work "Intel471CVEsStream") raises an error:
`Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/opencti-intel471/intel471/streams/common.py", line 74, in run for bundle in self.get_bundle(): File "/opt/opencti-intel471/intel471/streams/common.py", line 91, in get_bundle api_response = getattr(api_instance, self.api_method_name)(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api/vulnerabilities_api.py", line 99, in cve_reports_get return self.cve_reports_get_with_http_info(**kwargs) # noqa: E501 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api/vulnerabilities_api.py", line 277, in cve_reports_get_with_http_info return self.api_client.call_api( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 374, in call_api return self.__call_api(resource_path, method, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 213, in __call_api return_data = self.deserialize(response_data, response_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 285, in deserialize return self.__deserialize(data, response_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 324, in __deserialize return self.__deserialize_model(data, klass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 692, in __deserialize_model kwargs[attr] = self.__deserialize(value, attr_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 301, in __deserialize return [self.__deserialize(sub_data, sub_kls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 301, in <listcomp> return [self.__deserialize(sub_data, sub_kls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 324, in __deserialize return self.__deserialize_model(data, klass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 692, in __deserialize_model kwargs[attr] = self.__deserialize(value, attr_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 324, in __deserialize return self.__deserialize_model(data, klass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 692, in __deserialize_model kwargs[attr] = self.__deserialize(value, attr_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 324, in __deserialize return self.__deserialize_model(data, klass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 692, in __deserialize_model kwargs[attr] = self.__deserialize(value, attr_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 301, in __deserialize return [self.__deserialize(sub_data, sub_kls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 301, in <listcomp> return [self.__deserialize(sub_data, sub_kls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 324, in __deserialize return self.__deserialize_model(data, klass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/api_client.py", line 695, in __deserialize_model instance = klass(**kwargs) ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/models/simple_cve_schema_data_cve_report_poc_links_inner.py", line 60, in __init__ self.title = title ^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/titan_client/models/simple_cve_schema_data_cve_report_poc_links_inner.py", line 84, in title raise ValueError("Invalid value for `title`, must not be `None`") # noqa: E501 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: Invalid value for `title`, must not be `None``

"ValueError: Invalid value for `title`, must not be `None`" -> Seems like a value/field is not filled

**Comment by mmolenda** [comment]
We will definitely have a look, thanks for the heads up.

**Comment by nino-filigran** [comment]
Thanks for your quick response already!

**Comment by mmolenda** [comment]
@Lhorus6, thanks again for your feedback. I'll address your comments below.

> 1. The "state" of the connector does not seem to be updated.
> 2. (...) the connector seems to loop

Are you referring to a situation when you restart the connector, or to consecutive scheduled runs? The former one appears to be OpenCTI's limitation, which does not persist the state between restarts. Regarding the latter case - I spun up fresh (and newest) instance of both OpenCTI and the connector and I see no issues with updating of the status (see screenshot below). Is there anything troubling in the logs?

![Screenshot 2024-06-04 at 13 27 07](https://github.com/OpenCTI-Platform/connectors/assets/5938800/70032be8-1a76-4bda-8b97-5c01b48a5057)

> 3. The x_opencti_main_observable field of the Indicator isn't filled.

We will address it in the next bugfix release.

> 4. The author is not referenced in the Observables

We will address it in the next bugfix release.

> 5. There is no relationship between Observables and Indicators. A relationship `Indicator -> "Based on" -> Observables` should be created.

We create mentioned relationships for all Indicator/Observable pairs. See screenshot below and the [code that is responsible for it in our client](https://github.com/intel471/titan-client-python/blob/main/titan_client/titan_stix/mappers/iocs.py#L83)

![Screenshot 2024-06-04 at 15 46 00](https://github.com/OpenCTI-Platform/connectors/assets/5938800/f35333bd-dda6-4a78-bc45-94e9d76f1495)

I don't know why don't the relationships show up on the graph. @nino-filigran any idea how to fix it or who might help with that?

> 6. The connector does not model victims and threats.

We will add it to our list and consider for future release.

> 7. Adding the report as a text file attachment is great. A small improvement would be to name the file correctly

We will address it in the next bugfix release.

> 8. In addition, the import of CVE (i.e. the work "Intel471CVEsStream") raises an error

This is a problem on our API level. We are on it.

**Comment by Lhorus6** [comment]
Hi @mmolenda, thank you for your feedback! :) 

1 and 2 -> I don't seem to have observed that when we were testing. We'll have to test again to see.
5 -> I see. So the problem is not the creation of the relationship but the addition of the relation to the report. You need to include the relationships in the report (just as you include the indicators and observables [here I think](https://github.com/intel471/titan-client-python/blob/b62f171bed92d184f0419fe04fad5272e8ac04f2/titan_client/titan_stix/mappers/iocs.py#L110)).
As for the rest -> noted, thanks for the improvements.
