### ISSUE TITLE
New Connectors not showing up - Please help :) 

### ISSUE THREAD

**Issue by davealyn** [OpenCTI-Platform/connectors#2172]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview/) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting/) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I am adding new connectors to the Docker-Compose.yml file, they seem to be booting up perfectly fine when I 'docker up -d' and  they seem to be there when I search for working docker containers  however when I go onto the OpenCti connector dashboard the new ones are not there. I have submitted screenshots of my files. 

## Environment

1. OS Ubuntu
2. OpenCTI version 6.1.3
3. OpenCTI client: unsure 
4. Other environment details:

## Reproducible Steps

<img width="666" alt="compose yml file " src="https://github.com/OpenCTI-Platform/connectors/assets/52677160/78d8edaf-765d-4caf-8cc5-6ec1ba351a49">
<img width="758" alt="cti connectors" src="https://github.com/OpenCTI-Platform/connectors/assets/52677160/0459b95f-8319-43ef-bd40-fd376d28e03b">
<img width="758" alt="Screenshot 2024-05-24 CTI " src="https://github.com/OpenCTI-Platform/connectors/assets/52677160/fbc28c77-6310-4bd6-b99b-3ea645375125">

**Comment by carlosaraujojr** [comment]
Hey @davealyn - how did you solve this issue? I'm going through the same thing.
Thanks!

**Comment by MrKenie** [comment]
how did you solve this issues ? i have the same problem

**Comment by Machos65** [comment]
Hello guys 
Was there anybody able to solve that. Issue i was goin the same problem
