### ISSUE TITLE
Taxii2 none authentication

### ISSUE THREAD

**Issue by mt2651** [OpenCTI-Platform/connectors#2181]
I connected to taxii2 server, which didn't require authen but connector require TokenAuth, ApiKeyAuth, User/Pass

**Comment by annoyingapt** [comment]
I would have thought most MISP would be using authentication even if it was guest/guest. Is this a public feed?

**Comment by annoyingapt** [comment]
Sorry, just thought about this, can you use the MISP-feed connector?

**Comment by mt2651** [comment]
i tried with eclecticiq

**Comment by SamuelHassine** [comment]
@mt2651 I suggest using the native TAXII 2 ingest from the platform and not the connector.
