### ISSUE TITLE
[4.0.4] Worker: "Error:root:Unknown object type "x-mitre-tactic", doing nothing...' from data from Mitre connector

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#220]
Platform: v4.0.4
Workers (20): v4.0.4
Mitre Connector: v4.0.4

Elasticsearch cluster: 3 nodes of 16 vCPUs, 64 GB each. JVM Heap: 96.0 GB

OpenCTI worker log: 
![image](https://user-images.githubusercontent.com/51339113/103423171-2c362400-4b73-11eb-9c4d-243fb9c37e72.png)

**Comment by SamuelHassine** [comment]
Hello @kudrew,

That's the expected behaviour. MITRE Tactics are just imported as STIX 2.1 Kill Chain Phases. We don't want to implement a custom/special object for that which is not STIX 2.1 compliant. 

Thanks!

Kind regards,
Samuel
