### ISSUE TITLE
CrowdStrike connector work jobs increasing at a steady rate due to "Cant upsert entity. Too many entities resolved"

### ISSUE THREAD

**Issue by brett-fitz** [OpenCTI-Platform/connectors#2201]
## Description

CrowdStrike's connector jobs are increasing at a steady rate after an issue came up with one of the STIX bundles:

**Message**
```json
{'name': 'UNSUPPORTED_ERROR', 'error_message': 'Cant upsert entity. Too many entities resolved', 'http_status': 500, 'genre': 'BUSINESS', 'entityIds': ['intrusion-set--9a4f2db4-ef15-590b-9006-3caf2631269b', 'intrusion-set--e39e6fa1-6a32-5397-b010-a6f1e73e9929']}
```

**Source**
```json
{"type": "intrusion-set", "spec_version": "2.1", "id": "intrusion-set--03ca672d-1052-5899-bccd-6ba1c75ceaaf", "created_by_ref": "identity--f29f12ba-3980-5642-9b3e-d11e9b296aed", "created": "2024-06-06T21:09:57.215776Z", "modified": "2024-06-06T21:09:57.215776Z", "name": "BERSERK BEAR", "aliases": ["BERSERKBEAR"], "external_references": [{"source_name": "CrowdStrike", "url": "https://falcon.crowdstrike.com/intelligence/actors/berserk-bear/", "external_id": "1809"}], "object_marking_refs": ["marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"], "nb_deps": 3, "x_opencti_stix_ids": null, "x_opencti_granted_refs": null, "x_opencti_workflow_id": null}
```

## Environment

1. OS (where OpenCTI server runs): AWS ECS
2. OpenCTI version: 6.1.10
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the CrowdStrike connector
2. Wait 

## Expected Output

Connector should just import the new entities and perhaps skip the bundle that is error'ing out.

![image](https://github.com/OpenCTI-Platform/connectors/assets/37186808/71ee8c58-7132-4f8b-8a72-fcdbea3689d8)

## Actual Output

As we can see once the error pops up the work starts increasing likely due to this failure. 

![image](https://github.com/OpenCTI-Platform/connectors/assets/37186808/c85a2da6-6f68-4c59-b7ce-4272c991103b)

## Screenshots (optional)

* Screenshots above

**Comment by Megafredo** [comment]
Hi @brett-fitz, if you get this error: 'UNSUPPORTED_ERROR' => 'Cant upsert entity. Too many entities resolved' then this is expected behavior and the problem lies in the names and aliases of your intrusion sets.

In fact, if you have two different intrusion sets corresponding to this set of names and/or aliases, then OpenCTI is not able to determine which set of intrusion to select and then attach the knowledge.

To resolve this issue, simply merge your intrusion sets or edit the alias distribution in your OpenCTI platform to match the CrowdStrike data source.

When manually creating an intrusion set, you can see the number of duplicates for example:

![image](https://github.com/OpenCTI-Platform/connectors/assets/14902945/7c33fbd0-c839-403e-a4d2-35fb578128e6)

**Comment by brett-fitz** [comment]
@Megafredo  Would we expect this to occur with two different entity types?
<img width="1362" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/37186808/648c8db6-2d71-4fb5-b3ea-cb291893549d">

**Comment by Megafredo** [comment]
@brett-fitz If the entities are unrelated by name or alias, then yes, there is indeed a problem. We will investigate. Thanks

**Comment by brett-fitz** [comment]
FYSA: There is no alias on the malware 
<img width="803" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/37186808/b3265954-4fb8-4522-9350-77ff110e7dd0">

The only connection I could find (outside of relationship with Dragonfly which has an alias with BERSERK BEAR) is this external reference on Havex:
<img width="786" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/37186808/619ea7ec-2ad9-4e29-843e-a7603c1b1fa4">

**Comment by brett-fitz** [comment]
More screenshots:
<img width="804" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/37186808/5ff303d7-0c53-4fd8-a76a-749118e70dc4">
Note: I did merge BERSERK BEAR with Dragonfly and made Dragonfly the primary entity.

**Comment by brett-fitz** [comment]
Hey @Megafredo any update on the above? Number of operations for us has gotten do 60k and steadily increasing (its ingesting all data since the last reported time in the state). Is there a stop gap fix for this?

**Comment by romain-filigran** [comment]
I close the issue as discussed
