### ISSUE TITLE
Alien Vault connector fails to retrieve info (2024-06-02T07:31:42.004714900Z Terminated)

### ISSUE THREAD

**Issue by tiancu1980** [OpenCTI-Platform/connectors#2206]
While trying to install AlienVault connector i get a strange behavior.
The connector says is active but the jobs always stay in pending:
![image](https://github.com/OpenCTI-Platform/docker/assets/41986941/65282ff2-b3ce-4c9a-a9f1-290c9d119326)
I have only one entry in the connector logs
![image](https://github.com/OpenCTI-Platform/docker/assets/41986941/c147c1f3-eb38-4149-8418-27d3b39c79c0)
I had it running but at some point stopped retrieving events
I tried rebuilding the hole environment  it did not help 
   - i reset the api token
   - i reset the UUID
   - deleted all db and reinstall fresh environment
   - i do not see any errors related to the connector in opencti logs
ENV 
- 4 elastic nodes 
- 4 opencti nodes (3 internal for connectors 1 for UI)
- 2 redis nodes (1 master one slave)
- 1 RabbitMQ
- 6 Workers
   All other connectors seems to be working Oki.
![image](https://github.com/OpenCTI-Platform/docker/assets/41986941/0117c61d-1652-4e44-a176-ce9c54668218)

I have no idea how to proceed with further debugging.
Can someone help with this issue?

**Comment by ktneely** [comment]
> Reinitialized my account on AlienVault pulse subscription

Did that fix the issue?  I have a new OpenCTI instance and an old-ish OTX account and am seeing this exact issue.  What does it mean to "reinitialize the account"?

**Comment by tiancu1980** [comment]
Hi i had to recreate the api token. (only new api token did not resolve my issue)
And unsubscribe on all of my pulses and resubscribe to all of my pulses again.

Afterword's the connector started to retrieve the information again.

Hope that will solve the issue for you too.
