### ISSUE TITLE
Error 'standard_id' when using the export-file-stix connector v6.1.10 on a report that contains nested relationships

### ISSUE THREAD

**Issue by fboissel** [OpenCTI-Platform/connectors#2214]
## Description

The export-file-stix connector v6.1.10 generate an error 'standard_id' when trying to export a report which contains nested relationships (e.g. Sample relationship between a Malware SDO and a File SCO). The connector doesn't seem to be able to retrieve a standard_id for these entities. I am not sure that STIX2.1 is attributing an id to these nested relationships: 
"_The sample_refs property specifies a list of identifiers of the SCO file or artifact objects associated with this malware instance(s) or family._"(https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070645)

## Environment

1. OS (where OpenCTI server runs):  **docker** 
2. OpenCTI version: **6.1.10** 
3. OpenCTI client: **python**

## Reproducible Steps

Steps to create the smallest reproductible scenario:
1. Create a report
2. Add a Maware SDO
3. Add a File SCO
4. Create a Nested relationship between Malware and File, with a relationship type: Sample
5. In the Data tab of the Report, generate an application/json export using the export-file-stix connector for v6.1.10

## Expected Output

We are expecting to generate a json file in STIX of the report that we can download.

## Actual Output

Connector error: "KeyError: 'standard_id"

**Comment by nino-filigran** [comment]
@fboissel can you try to upgrade your openCTI version to the latest?
I can't seem to reproduce your issue in our environment.

**Comment by fboissel** [comment]
Hi @nino-filigran
Sorry for the late answer, the process to get our platform upgraded took a while.
I confirm that an upgrade of OpenCTI to the v6.2.5 with the compatible export connectors solved the problem.
I think this issue can be close as resolved. 
Thanks a lot!
Fred
