### ISSUE TITLE
[ZeroFox] Connector doesn't start

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/connectors#2221]
## Description

The connector works well but it doesn't import the data @DNRRomero. Seems to be related to this:
https://github.com/OpenCTI-Platform/connectors/blob/38f0ace73fb2542b4fd5412186e9e78a6c6696b4/external-import/zerofox/src/main.py#L125 regarding the interval.  

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/connectors/assets/155080335/863fdce6-17b6-4d89-8fe7-153ee59e20f4)

**Comment by romain-filigran** [comment]
@DNRRomero : I see that you are the source of this connector. Do you have any idea of the problem reported by @NiQuintin ?

**Comment by DNRRomero** [comment]
Hi, @romain-filigran we have identified the issue and are working on a solution for it

**Comment by romain-filigran** [comment]
@DNRRomero : Very good news

**Comment by NiQuintin** [comment]
Hi @DNRRomero after reviewing the connector I see on indicators the field  "x_opencti_main_observable_type": "Unknown". It can a problem especially because to filter on indicator's types the user needs this field. Otherwise it won't be possible to filter the data.

**Comment by alexmfarrell** [comment]
@NiQuintin Hi NiQuintin, do you have any more context about this error? Is this a field we need to provide the user from our end? Any further info on this will help, thank you in advance!
