### ISSUE TITLE
AlienVault connector error AMQPConnection - Name does not resolve

### ISSUE THREAD

**Issue by a108a108** [OpenCTI-Platform/connectors#223]
## Description

Error while running AlienVault connector:  AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve');

## Environment

1. OS: CentOS 8, Docker
2. OpenCTI version: 4.0.7
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

**Compose file:**

version: '3'
services:
  connector-alienvault:
    image: opencti/connector-alienvault:4.0.7
    environment:
      - OPENCTI_URL=http://ip_of_the_server:8080
      - OPENCTI_TOKEN=my_token
      - CONNECTOR_ID=cbec6a0e-639f-491a-be64-061fc6ce942e
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=AlienVault
      - CONNECTOR_SCOPE=alienvault
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - ALIENVAULT_BASE_URL=https://otx.alienvault.com
      - ALIENVAULT_API_KEY=my_otx_key
      - ALIENVAULT_TLP=White
      - ALIENVAULT_CREATE_OBSERVABLES=true
      - ALIENVAULT_CREATE_INDICATORS=true
      - ALIENVAULT_PULSE_START_TIMESTAMP=2021-01-10T00:00:00                  # BEWARE! Could be a lot of pulses!
      - ALIENVAULT_REPORT_TYPE=threat-report
      - ALIENVAULT_REPORT_STATUS=New
      - ALIENVAULT_GUESS_MALWARE=false                                        # Use tags to guess malware.
      - ALIENVAULT_GUESS_CVE=false                                            # Use tags to guess CVE.
      - ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES=FileHash-MD5,FileHash-SHA1  # Excluded Pulse indicator types.
      - ALIENVAULT_INTERVAL_SEC=1800
    restart: always

**Output when I execute "docker-compose up" command:**

connector-alienvault_1  | INFO:root:Listing Threat-Actors with filters null.
connector-alienvault_1  | INFO:root:Connector registered with ID:cbec6a0e-639f-491a-be64-061fc6ce942e
connector-alienvault_1  | INFO:root:Starting ping alive thread
connector-alienvault_1  | INFO:root:Starting AlienVault connector...
connector-alienvault_1  | INFO:root:Running AlienVault connector...
connector-alienvault_1  | INFO:root:Loaded state: {}
connector-alienvault_1  | INFO:root:Connector first run
connector-alienvault_1  | INFO:root:Initiate work for cbec6a0e-639f-491a-be64-061fc6ce942e
connector-alienvault_1  | INFO:root:Running pulse importer (update data: False, guess malware: False, guess cve: False)...
connector-alienvault_1  | INFO:root:62 pulse(s) since 2021-01-10 00:00:00...
connector-alienvault_1  | INFO:root:Processing pulse Phishing URLs (5e98271289d56c79998870d9)...

connector-alienvault_1  | INFO:root:Update action expectations opencti-work--563cff31-bfce-4580-b470-10708ab0c9a2 - 22210
connector-alienvault_1  | ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(-2, 'Name does not resolve')
connector-alienvault_1  | ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(-2, 'Name does not resolve').
connector-alienvault_1  | ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None.
connector-alienvault_1  | ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None
connector-alienvault_1  | ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None
connector-alienvault_1  | ERROR:pika.adapters.blocking_connection:Error in _create_connection().
connector-alienvault_1  | Traceback (most recent call last):
connector-alienvault_1  |   File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
connector-alienvault_1  |     raise self._reap_last_connection_workflow_error(error)
connector-alienvault_1  |   File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 562, in _resolve
connector-alienvault_1  |     result = socket.getaddrinfo(self._host, self._port, self._family,
connector-alienvault_1  |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
connector-alienvault_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
connector-alienvault_1  | socket.gaierror: [Errno -2] Name does not resolve
connector-alienvault_1  | ERROR:root:Internal error: [Errno -2] Name does not resolve

I can see the connector in "Data", but it never completes the progress.

Do I have to add a DNS record for the rabbitmq or change a hostname somewhere else?

**Comment by richard-julien** [comment]
Hi @a108a108 ,

This is not an OpenCTI error, just the way docker works.
A docker compose come with its internal network.
So starting a docker compose with OpenCTI and some connectors will run on NETWORK_DEFAULT
Then if you start a new docker compose with only AlienVault, it will run on ANOTHER_NETWORK
NETWORK_DEFAULT and ANOTHER_NETWORK can't communicate and so dont have any DNS resolution between them.

You have 2 solutions.
1. Modify the openCTI docker compose to add your connector and then docker-compose up again. It will add the container inside the same network.
2. Configure docker to link the networks. Example https://tjtelan.com/blog/how-to-link-multiple-docker-compose-via-network/

Julien,

**Comment by a108a108** [comment]
Hi @richard-julien 
I will do that, thank you!
