### ISSUE TITLE
[Crowdstrike] State of the connector can't be set

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/connectors#226]
## Description

The connector state can't be set during a run leading to a rerun every few minutes.
The only log found is not very helpful:
`ERROR:root:CrowdStrike connector internal error: {'name': 'UnknownError', 'message': 'No reason specify'}`

## Environment

1. OS (where OpenCTI server runs): full-docker instance
2. OpenCTI version: 4.0.7
3. OpenCTI client: worker and all connectors in 4.0.7
4. Other: data in the platform has been imported from an OpenCTI v3 with the Crowdstrike connector activated

## Reproducible Steps

I have no idea if this bug depends on the data already in the platform...
1. Lauch Crowdstrike connector
2. Wait for a full run (several runs are launched during that time)
3. The state is "null", even after several runs and state resets

## Expected Output

State updated at the beginning of the connector run.

## Actual Output
State equals "null"

**Comment by maertv** [comment]
Please check the OpenCTI Platform logs. I could be mistaken but the error:
```
ERROR:root:CrowdStrike connector internal error: {'name': 'UnknownError', 'message': 'No reason specify'}
```

The part `{'name': 'UnknownError', 'message': 'No reason specify'}` seems to be coming from the OpenCTI.

**Comment by amr-cossi** [comment]
The status is ok now. I'll do some test with full history later.
