### ISSUE TITLE
[MITRE] unresolvedIDs errors with other-stix-ids

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/connectors#2265]
## Description

Sometimes, the MITRE connector displays Missing reference errors with unresolvedIds on data component entities. After verification, it seems that the connector is unable to retrieve the other_stix_ids from the data components and is displaying these errors.

## Environment

OpenCTI version: 6.1.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Checking erros in Mitre connector works

## Expected Output

The connector handles other stix ids of entities

## Actual Output

The connector fails to handle the other stix ids and displays errors

## Screenshots (optional)
![Untitled (3)](https://github.com/OpenCTI-Platform/connectors/assets/155080335/72dc702d-6e32-42ac-ad2e-cd125db879c2)

**Comment by Jipegien** [comment]
@NiQuintin what is the actual impact on the data? Do we miss some?

**Comment by Jipegien** [comment]
@helene-nguyen

**Comment by helene-nguyen** [comment]
@Jipegien I think that when the Other STIX Ids were created, as the error shows `MISSING_REFERENCE_ERROR`, the data is not created.

@richard-julien do you have an idea about this one about resolving entity with other stix ids ?

**Comment by NiQuintin** [comment]
### I close the issue
The problem stems from Mitre's bundle structure, so it's not related to the connector or the platform.
