### ISSUE TITLE
Malpedia

### ISSUE THREAD

**Issue by sudesh0sudesh** [OpenCTI-Platform/connectors#2276]
## Use case

Can we add descriptions from Malpedia when intrusion sets are being created using malpedia library, Please?
@Megafredo

**Comment by Megafredo** [comment]
Hi @sudesh0sudesh, currently, each intrusion set has a description, but if it is missing, it is because the description is missing from Malpedia.

**Comment by sudesh0sudesh** [comment]
Even if it is present it is not adding the descriptions, it is adding something like 
"Malpedia library entry for IS name"

**Comment by Megafredo** [comment]
Hi @sudesh0sudesh, can you give me the exact name or malpedia link of the specific family ? Or does this happen for all families ?  

Condition in the code :
```Python
if data_family.description == "" or data_family.description is None:
    data_family.description = (
        "Malpedia entry for " + data_family.malpedia_name
    )
```
## Example 1 with description :
![Malpedia-AbstractEmu](https://github.com/user-attachments/assets/984a3a27-b875-4b5c-8dc0-474e635b11e5)
![OpenCTI-AbstractEmu](https://github.com/user-attachments/assets/fb9ab66d-a168-4318-8845-c53c5d51fa58)

## Example 2 without description :
![Malpedia-PjobRAT](https://github.com/user-attachments/assets/a71b416c-0805-470f-8e4e-81c1474e664d)
![OpenCTI-PjobRAT](https://github.com/user-attachments/assets/b5e99dc9-d794-4946-b0d6-0860b32f3b3f)

**Comment by sudesh0sudesh** [comment]
Hello @Megafredo , Sorry but i was asking about Intrusion set

**Comment by Megafredo** [comment]
My apologies, I don't know why I went for the malware families... you're right, there's a little problem with the condition for the description of instusion sets. This will be fixed ;)
