### ISSUE TITLE
MISP connector parsing error with File objects

### ISSUE THREAD

**Issue by pinowudi** [OpenCTI-Platform/connectors#229]
## Description

When connecting to MISP, the connector enumerates events and starts walking them, only to crash on 'file' objects that do not have a 'x_opencti_main_observable_type' indicator defined. Since my MISP has no knowledge of OpenCTI, it does not have this defined. 

## Environment

1. OS Ubuntu provided with OpenCTI OVA virtual machine
2. OpenCTI version: 4.0.3
3. OpenCTI client: python
4. Other environment details: all connectors set to version 4.0.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. set up MISP variables and docker-compose stanzas
2. redeploy opencti stack
3. Modules register in OpenCTI on the Data page. Looking good...
4. click containers in Portainer and show logs
5. There is a python error describing the crash at x_opencti_main_observable_type, line 384

I've tried this on two different MISP instances and the behavior is consistent across both.

## Expected Output

info message staging processing of the event.

## Actual Output

```
INFO:root:Bundle has been sent
INFO:root:Bundle has been sent
INFO:pika.channel:Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f777e653f40> params=<URLParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
INFO:pika.channel:Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f777e653f40> params=<URLParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
INFO:root:Processing event 5ad09f32-ce58-47f3-b137-4411950d210f
Traceback (most recent call last):
  File "misp.py", line 1273, in <module>
    mispConnector.run()
  File "misp.py", line 222, in run
    self.process_events(work_id, events)
  File "misp.py", line 384, in process_events
    and indicator["indicator"].x_opencti_main_observable_type
AttributeError: 'NoneType' object has no attribute 'x_opencti_main_observable_type'
```
 
## Additional information

This is the section of code that is failing. Not sure what it is looking for about `x_opencti_main_observable_type`

```
                    if indicator is not None:
                        indicators.append(indicator)
                        if (
                            object["meta-category"] == "file"
                            and indicator["indicator"].x_opencti_main_observable_type
                            in FILETYPES
                        ):
                            object_attributes.append(indicator)
```

The MISP object it is failing on

![Screen Shot 2021-01-27 at 18 58 50](https://user-images.githubusercontent.com/1254663/106033295-e74dd080-60d1-11eb-8033-7ad3d4a0c040.png)

**Comment by SamuelHassine** [comment]
Hello,

Thanks for the issue, it will be solved in the next release.

Kind regards,
Samuel
