### ISSUE TITLE
Split logics for Microsoft Sentinel / Tanium Threat Response / HarfangLabs between Stream & Import

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#2298]
## Use case

Split logics for Microsoft Sentinel / Tanium Threat Response / HarfangLabs between Stream & Import

@nino-filigran @Jipegien please ping me on this, this is quiet important.

**Comment by TechBurn0ut** [comment]
You will also want to do the same for Crowdstrike and SentinelOne….
