### ISSUE TITLE
Connector get ERROR

### ISSUE THREAD

**Issue by antime** [OpenCTI-Platform/connectors#2327]
## Description
connector-alienvault get error like it :
getaddrinfo failed: gaierror(-2, 'Name does not resolve')

## Environment

1. OS (where OpenCTI server runs): Centos7.4
2. OpenCTI version: OpenCTI6.2.2
3. OpenCTI client: docker
4. Other environment details: opencti/connector-alienvault:6.2.3

## Reproducible Steps
OpenCTI platform is run normal,and then run connector.
my alienvault connector docker-compose file like it:

version: '3'
services:
  connector-alienvault:
    image: opencti/connector-alienvault:6.2.3
    environment:
      - OPENCTI_URL=http://10.*.*.*:8080
      - OPENCTI_TOKEN=714c8ed0-a70e-457d-93fe-df******
      - CONNECTOR_ID=1362e9b2-7ceb-3b87-ee84-e***
      - CONNECTOR_NAME=AlienVault
      - CONNECTOR_SCOPE=alienvault
      - CONNECTOR_LOG_LEVEL=info
      - ALIENVAULT_BASE_URL=https://otx.alienvault.com
      - ALIENVAULT_API_KEY=85dc583928ac3cf77f5c7016ac8389********************
      - ALIENVAULT_TLP=White
      - ALIENVAULT_CREATE_OBSERVABLES=true
      - ALIENVAULT_CREATE_INDICATORS=true
      - ALIENVAULT_PULSE_START_TIMESTAMP=2022-05-01T00:00:00                  # BEWARE! Could be a lot of pulses!
      - ALIENVAULT_REPORT_TYPE=threat-report
      - ALIENVAULT_REPORT_STATUS=New
      - ALIENVAULT_GUESS_MALWARE=false                                        # Use tags to guess malware.
      - ALIENVAULT_GUESS_CVE=false                                            # Use tags to guess CVE.
      - ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES=FileHash-MD5,FileHash-SHA1  # Excluded Pulse indicator types.
      - ALIENVAULT_ENABLE_RELATIONSHIPS=true                                  # Enable/Disable relationship creation between SDOs.
      - ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES=false                     # Enable/Disable "indicates" relationships between indicators and attack patterns
      - ALIENVAULT_INTERVAL_SEC=1800
    restart: always

And run it with cmd: docker-compose up -d

Waiting for a while and reporting an error like it：
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.165482Z", "level": "INFO", "name": "alienvault.builder", "message": "Bundling 5 objects"}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.166572Z", "level": "INFO", "name": "api", "message": "Update action expectations", "attributes": {"work_id": "work_1362e9b2-7ceb-3b87-ee84-ee10347e3e00_2024-07-10T13:25:05.004Z", "expectations": 5}}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.224148Z", "level": "ERROR", "name": "pika.adapters.utils.selector_ioloop_adapter", "message": "Address resolution failed: gaierror(-2, 'Name does not resolve')"}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.224492Z", "level": "ERROR", "name": "pika.adapters.utils.connection_workflow", "message": "getaddrinfo failed: gaierror(-2, 'Name does not resolve')."}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.224954Z", "level": "ERROR", "name": "pika.adapters.utils.connection_workflow", "message": "AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None."}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.225072Z", "level": "ERROR", "name": "pika.adapters.utils.connection_workflow", "message": "AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None"}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.225194Z", "level": "ERROR", "name": "pika.adapters.blocking_connection", "message": "Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None"}
connector-alienvault-1  | {"timestamp": "2024-07-10T13:41:20.227015Z", "level": "ERROR", "name": "pika.adapters.blocking_connection", "message": "Error in _create_connection().", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py\", line 451, in _create_connection\n    raise self._reap_last_connection_workflow_error(error)\n  File \"/usr/local/lib/python3.11/site-packages/pika/adapters/utils/selector_ioloop_adapter.py\", line 565, in _resolve\n    result = socket.getaddrinfo(self._host, self._port, self._family,\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 962, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name does not resolve"}
connector-alienvault-1  | Terminated

## Additional information

<img width="1719" alt="image" src="https://github.com/OpenCTI-Platform/connectors/assets/17289600/638870c0-18ae-465a-b576-926a2c656380">

**Comment by romain-filigran** [comment]
Hello @antime. How is your OpenCTI instance deployed (Docker or standalone)? I have the feeling that your Alienvault connector is not able to connect to RabbitMQ and so that your connector is deployed in another docker context than your OpenCTI instance. Is it the case ?

**Comment by antime** [comment]
> Hello @antime. How is your OpenCTI instance deployed (Docker or standalone)? I have the feeling that your Alienvault connector is not able to connect to RabbitMQ and so that your connector is deployed in another docker context than your OpenCTI instance. Is it the case ?

Firstly, thank you for your response.
I deployed OpenCTI use docker-compose file, and deployed connector in another docker-compose file.
Thanks.

**Comment by antime** [comment]
Firstly, thank you for your response.
I deployed OpenCTI use docker-compose file, and deployed connector in another docker-compose file.
Thanks.

**Comment by romain-filigran** [comment]
Is it possible for you to deploy OpenCTI and Alienvault connector in the same docker-compose file ? 
If no, you will have to 

1. update your OpenCTI docker-compose file to expose RabbitMQ port outside of docker context (port 5672). By default, RabbitMQ port is not exposed.

2. add a local DNS resolution to be able to point to "rabbitmq" name
