### ISSUE TITLE
[Cape Sandbox] Cape URL variable not being utilised

### ISSUE THREAD

**Issue by human4357** [OpenCTI-Platform/connectors#2355]
## Description

The enrichment connector does not utilize the API URL from the config file, resulting in the connector not working. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 24.04 LTS
2. OpenCTI version: 6.2.5
3. OpenCTI client: Python (probably)
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enter domain/IP in the docker-compose.yml
2. Attempt to perform analysis via enrichment in the OpenCTI front end

## Expected Output
Artifact is sent to Cape for analysis

## Actual Output
Connector throws multiple errors which shows the URL not being pass, and the handling of that error results in a type error. 

## Additional information
In the file `cape-sandbox,py` in the container, entering the address of cape on line 47 fixes the issue. 

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/1e2a6c5f-c4aa-4c41-a9f0-d6786c1d615e)
![image](https://github.com/user-attachments/assets/4b5bd834-1f25-4fdf-a979-e9b90b636897)

**Comment by romain-filigran** [comment]
Hello @human4357. I think there is a mistake in the docker-compose.yml file. Can you try to rename "CAPE_SANDBOX_API_URL" by "CAPE_SANDBOX_URL"

**Comment by human4357** [comment]
Hi @romain-filigran, thank you for the speedy response, that has solved this issue. 

Now I am faced with a different issue, I will open a different issue for this.
