### ISSUE TITLE
Typo in Sighting connector Dockerfile => build fail

### ISSUE THREAD

**Issue by Madc4t** [OpenCTI-Platform/connectors#237]
## Description

In sighting connector Dockerfile https://github.com/OpenCTI-Platform/connectors/blob/master/sighting/Dockerfile, there is a reference to ipinfo connector instead of sighting.
`RUN apk --no-cache add git build-base libmagic libffi-dev && \
    cd **/opt/opencti-connector-ipinfo** && \
    pip3 install --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@4.1.2 && \
    pip3 install --no-cache-dir -r requirements.txt && \
    apk del git build-base`
## Reproducible Steps

Try to build docker image from dockerfile.
cd sighting
docker build . 

## Expected Output

Build is succesful

## Actual Output

Build fail

**Comment by SamuelHassine** [comment]
Hello @Madc4t,

This connector is not ready yet and has been removed for the moment.

Kind regards,
Samuel
