### ISSUE TITLE
[splunk] Connection errors are not logged

### ISSUE THREAD

**Issue by gileri** [OpenCTI-Platform/connectors#2374]
## Description

Critical errors seem to not be logged in the splunk connector. For example, network connection errors lead to the process termination without any logs except the standard "Terminated" message

```
2024-07-18 15:46:45.174	Terminated
2024-07-18 15:39:33.046	Terminated
2024-07-18 15:32:14.774	Terminated
2024-07-18 15:24:56.502	Terminated
```

## Environment

1. OS (where OpenCTI server runs): [Official docker image](https://hub.docker.com/layers/opencti/connector-splunk/6.2.5/images/sha256-44846a7edf7c21fd2a096b7252ae89c28e7bfe6479ff6d0d174bc89290061949?context=explore).
2. OpenCTI version: 6.2.5
3. OpenCTI client: 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Use an source IP address on your host that is blocked by the remote splunk instance
2. Use connector

## Expected Output

An error or exception in logs.

## Actual Output

No logs, just a `Terminated` message.

## Additional information

I believe other errors may also not be logged, but haven't investigated further.

**Comment by nino-filigran** [comment]
@helene-nguyen & @Megafredo Could you have a look at this please 🙏 ?

**Comment by helene-nguyen** [comment]
@nino-filigran Yes, sure!
