### ISSUE TITLE
[Misp] Error outside the main connector process is not logged

### ISSUE THREAD

**Issue by helene-nguyen** [OpenCTI-Platform/connectors#2389]
## Description

- Error outside the main connector process is not logged
- Issue on indentation

## Expected output

- Have traceback of the error

**Comment by piolug93** [comment]
I changed indent because it solves the problem with complex types, such as filename|md5. When indenting is in a loop, it only creates an indicator for filename and bypasses md5.

**Comment by helene-nguyen** [comment]
@piolug93 Ok, let me check this out and dig into it. There are some issues with the variables when changing the indentation that are not taken into account
