### ISSUE TITLE
[VirusTotal Hunting] Create the connector

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#24]
To obtain IOCs (hashes values, ...) and associated context (submit date, country, etc) for surveilled malware families.

Yara rules are provided as an entry by the susbriber

https://www.virustotal.com/gui/hunting-overview

**Comment by YungBinary** [comment]
@Fred-certeu Does this Connector suffice? https://github.com/OpenCTI-Platform/connectors/pull/543
