### ISSUE TITLE
looking for connector to consume STIX1.1.1 or STIX2.1

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/connectors#240]
Hi,
Any connectors to ingest STIX 1.1.1 & STIX2.1?
We have a paid commercial thread feeds that we would like to ingest to OpenCTI. 
Their api can be access either STIX 1.1.1 or  STIX2.1

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

STIX 2.1 can be ingested automatically using the Python library (import_bundle), and through the TAXII 2.1 connector. No plan to be able to ingest STIX 1.1.1 for now.

Kind regards,
Samuel
