### ISSUE TITLE
[CrowdStrike/AlienVault] Connector does not seem to update state unless initial processing is fully done

### ISSUE THREAD

**Issue by trocade** [OpenCTI-Platform/connectors#242]
## Description

When doing the initial import of data from crowdstrike and the connector will not store last-state until done.
If the connector is restarted or interrupted it have to start over from the beginning.

## Environment

1. Ubuntu 18.04 LTS (Docker)
2. OpenCTI version: 4.12
3. OpenCTI client: fronted/python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Setup a new opencti instance with crowdstrike connector
2. Set the REPORT and INDICATORS START time to start on 2019-01-01
3. Let it process data for a while and restart the connector

## Expected Output

After restart it processing should continue from where it left off
## Actual Output

the connector seem to start over since there is not last state stored

**Comment by samjackson200** [comment]
Additionally, if the connector encounters a error response from the Crowdstirke API it is unable to handle the error, causing the connector to stop, and when the connector is restarted it commences processing from the start again due to this issue.

**Comment by SamuelHassine** [comment]
Hello @maertv,

Do you think it's possible to address this issue in both AlienVault and CrowdStrike connectors?

Thanks!

Kind regards,
Samuel

**Comment by maertv** [comment]
Hopefully, it is somewhat better now. The connector tries to set the state after every importer run. The importers for actors and reports also try to set the state after processing a batch of entities. For indicators and YARA master there is no intermediate state capture.

In general the connector will stop after a CrowdStrike API error and starts with a state that was last stored before the error. It depends when the error occurs but with the intermediate state capture the connector should not start from the
beginning.

**Comment by maertv** [comment]
Some "improvements" were done regarding issue. Not sure if they actually improved anything but I am closing the issue.

Please open a new issue with detailed description if future development is required.
