### ISSUE TITLE
[Hygiene] Hygiene enrichment connector error

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#2435]
## Description

When enriching some Observable, an error is thrown. However, I have the impression that the connector still worked.

## Environment

OCTI 6.2.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create the Domain name "api.ipify.org"
2. Run the Hygiene connector

![Screenshot 2024-07-31 182936](https://github.com/user-attachments/assets/24117198-6a36-4418-91af-e1b285123ec1)

**Comment by romain-filigran** [comment]
Locally reproduced. This prevents the connector from working properly. A quick fix is possible, but the problem is likely to recur with other warninglists.
