### ISSUE TITLE
Sighting connector - Pull access denied

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/connectors#247]
OS: Ubuntu 20
OpenCTI latest version (docker)

Attempted to add "Sighting" connector to docker-compose and got this error.
"ERROR: for connector-sighting  pull access denied for opencti/connector-sighting, repository does not exist"

![image](https://user-images.githubusercontent.com/20463433/107790296-a0dab180-6d20-11eb-96c8-8191547ae180.png)

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

This connector is not ready for production yet. Please refer to the official list here: https://www.notion.so/luatix/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76.

Kind regards,
Samuel
