### ISSUE TITLE
[Sekoia] Reports ingested with attachments without extension (pdf_report)

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/connectors#2479]
## Description

The Sekoia connector ingests report entities with attachments in content that have no .pdf extension and are automatically named pdf_report.

## Environment

1. OpenCTI 6.2.13
2. connector-sekoia:6.2.13

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on a report ingested by Sekoia connector,
2. Check for content tab, must see a pdf_report doc

## Expected Output

The PDF attachment is ingested with the right extension .pdf

## Actual Output

No extension on the pdf_report file

**Comment by nino-filigran** [comment]
@helene-nguyen could you have a look?

**Comment by helene-nguyen** [comment]
@nino-filigran Yes, sure :)
