### ISSUE TITLE
OpenCTI Stream Connector with IBM QRadar issues and missing reference sets

### ISSUE THREAD

**Issue by nikitah4x** [OpenCTI-Platform/connectors#2495]
## Prerequisites

- [X] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview/) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting/) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant
- [X] I googled the issue and didn't find anything relevant

## Description

I'm getting the error that is mentioned below, and for some reason I'm not getting the IPv4 Addresses into the reference sets.
I don't know if the error is associated with the issue mentioned in the log but I need to get the IPv4 addresses to the reference sets as well.

The ignore set to:
QRADAR_IGNORE_TYPES=label,marking-definition,identity

Another thing is that the malware hashes that are being streamed are SHA512, is it possible to change it to SHA256?

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: OpenCTI 6.2.13
3. OpenCTI client: Docker
4. Other environment details: IBM QRadar 7.5.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Creating a token within QRadar
2. Deploy the IBM QRadar Connector with editing the OpenCTI Stack with Portainer
3. Check the service logs for the QRadar Container.
4. `{"timestamp": "2024-08-18T07:18:09.225923Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "Unterminated string starting at: line 1 column 1029 (char 1028)", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 228, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 238, in _consume\n    payload = json.loads(msg.data)[\"data\"]\n              ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\n               ^^^^^^^^^^^^^^^^^^^^^^\njson.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1029 (char 1028)"}`

**Comment by Megafredo** [comment]
Hi @nikitah4x,

Unfortunately, we cannot reproduce the connection with QRADAR, it is a community support connector, so our access is limited.

However, after investigation it appears that this error may be caused by the presence of unsupported special characters in the data (e.g. in the description of an indicator), which change the structure of the JSON string. These special characters, if not properly encoded or escaped, can interfere with the JSON syntax, rendering part of the file unreadable and causing a parsing error.

For example in description :
![unsupported_characters](https://github.com/user-attachments/assets/0ff5b8b8-4185-41e9-8e55-d0a9808ef422)

Can you tell us if you are using a specific connector to enrich your indicators ? Do you have an IPv4 example to share ?

**Comment by BugSoc** [comment]
Hey,
I'm getting the IPV4 from AbuseIPDB and AlienVault.
For some reason in QRadar I'm not getting them.
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/1bc86047-6d21-4935-9d74-7c4641085862">

<img width="213" alt="image" src="https://github.com/user-attachments/assets/074aac97-f189-4172-9dd2-1cf66f071329">

**Comment by nikitah4x** [comment]
Hey,
I'm getting the IPV4 from AbuseIPDB and AlienVault.
For some reason in QRadar I'm not getting them.
<img width="768" alt="image" src="https://github.com/user-attachments/assets/53a9dab1-90d0-4766-95d9-f548d020f720">
QRadar Reference set:
<img width="194" alt="image" src="https://github.com/user-attachments/assets/ad8fed6e-1ad8-47d0-ac45-c322b2f85261">

**Comment by Megafredo** [comment]
Hi @nikitah4x,
it's surprising that you don't have an ipv4 observable in qradar, can you tell me what you have set for the "ignore_types" environment variable?
Out of curiosity, did you set up a specific stream id? If so, did you use any specific filters can you tell me there values?
