### ISSUE TITLE
[CrowdStrike] "KeyError" when importing a report

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#2517]
## Description

A customer encountered an error on the CrowdStrike connector related to the use of a non-existent "description" key on a report.

Is it possible that a report is not this key?

Or maybe we do not verify that it is indeed a report before sending it in the "create_stix2_report_from_report" function?

## Environment

OCTI 6.2.7

![image-20240821-180021](https://github.com/user-attachments/assets/bdbd9685-0257-490c-8c8e-5d5b42710013)

**Comment by Lhorus6** [comment]
The customer also says that there is a log to fix, I'll let you judge:

Logging messages that utilize the %s formatting do not work. Python needs to use the {0}, {1}, etc… formatting for code lines like this… (see attached image) in external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py

![image-20240821-180414](https://github.com/user-attachments/assets/b9acbb7d-1249-444d-84ff-8c73cf69918b)

**Comment by romain-filigran** [comment]
@Megafredo @helene-nguyen : Can you have a look on this issue ?

**Comment by helene-nguyen** [comment]
@romain-filigran yes, sure :)
