### ISSUE TITLE
Shodan Unsupported pattern type: stix

### ISSUE THREAD

**Issue by ryangar888** [OpenCTI-Platform/connectors#2523]
## Description

I using Shodan connector and get the error: Unsupported pattern type: stix

## Environment

1. OS (where OpenCTI server runs): ubuntu 22.04
2. OpenCTI version: 6.2.14
3. OpenCTI client: docker
4. Other environment details:
5. Connector Shodan version: 6.2.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run "docker container logs <container name>
2. Get error: {"timestamp": "2024-08-24T04:32:30.612986Z", "level": "ERROR", "name": "Shodan", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 352, in _data_handler\n    message = self.callback(event_data)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-shodan/shodanImport.py\", line 525, in _process_message\n    raise ValueError(\nValueError: Unsupported pattern type: stix"}

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/d1570e5f-3311-4c3c-9772-92af355ea71f)

**Comment by ryangar888** [comment]
Update: It's occur with incidcator object, it's working with IPv4-Addr

**Comment by Jipegien** [comment]
The shodan enrichement connector does not aim to process stix pattern, only shodan pattern, for threat hunting purposes.

**Comment by ryangar888** [comment]
ah I got it, thanks you
