### ISSUE TITLE
[jira] Incorrect connector Dockerfile path

### ISSUE THREAD

**Issue by gileri** [OpenCTI-Platform/connectors#2535]
## Description

Error during startup of Jira connector

## Environment

1. OS (where OpenCTI server runs):
2. OpenCTI version: 6.2.15
3. OpenCTI client: 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run connector connector container

## Expected Output

No error/crash

## Actual Output

Connector crashes with a path not existing

## Additional information

Looks like a [typo here](https://github.com/OpenCTI-Platform/connectors/blob/5c0c6aa5f5d67f140fae15f7ad503274583b8255/stream/jira/Dockerfile#L5).

## Screenshots (optional)

**Comment by damians-filigran** [comment]
Also [here](https://github.com/OpenCTI-Platform/connectors/blob/5c0c6aa5f5d67f140fae15f7ad503274583b8255/stream/jira/Dockerfile#L10), presumably

**Comment by damians-filigran** [comment]
Have edited lines 5 and 8 in a local build and tested, runs OK.
