### ISSUE TITLE
Cyber Crime Tracker Connector Not Working

### ISSUE THREAD

**Issue by malwaredevil** [OpenCTI-Platform/connectors#255]
## Description

When enabling the Cyber Crime Tracker, it doesn't pull any feeds.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 4.2.3
3. OpenCTI client: frontend
4. Other environment details: 

- Docker version 20.10.3, build 48d30b5
- docker-compose version 1.21.2, build a133471

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. set environment variables
2. run docker-compose up -d
3. cyber crime connector doesn't pull feed or iocs. See above for log output.

## Expected Output

Pulls in the cyber crime feed

## Actual Output

Hangs before it pulls in feed. 
 
## Additional information

Log:
`INFO:root:Connector has never run

INFO:root:Connector will run!

INFO:root:Initiate work for [REDACTED]

ERROR:root:'NoneType' object has no attribute 'encode'`

**Comment by malwaredevil** [comment]
Figured out the issue:
The "CYBERCRIME_TRACKER_FEED_URL" variable is misspelled in the code as "CYBERCRIMET_RACKER_FEED_URL". See below for location in code that needs to be updated.
https://github.com/OpenCTI-Platform/connectors/blob/a7d6a3a642685d8b50b937336e99d1a2faadd49a/cybercrime-tracker/src/cybercrime-tracker.py#L41

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine Hello! I add this service in my docker-compose.yml file. And the connector doesn't work. The log file is shown as below:
![image](https://user-images.githubusercontent.com/68931768/114488907-aa688480-9bbe-11eb-8dde-ae5d56fbd5d5.png)
I check what @malwaredevil says, and the misspelling is still there.

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine Hello! Can the misspelling pointed out by @malwaredevil be corrected?
