### ISSUE TITLE
[Intel471] incorrect indicator names

### ISSUE THREAD

**Issue by marckto-filigran** [OpenCTI-Platform/connectors#2595]
## Description

For the connector intel471 the indicator names have the same value as the pattern.
Example: https://[REDACTED]/dashboard/observations/indicators/7a65ebfc-2d81-42a2-ba57-d4cf5a7f7b0b
This applies to all the types of indicators from intel471.

## Expected Output

result should be for an ipv4 for example:
name: <IP>
pattern: [ipv4-addr:value = 'IP']

**Comment by mmolenda** [comment]
According to STIX specification name is optional. We don's supply it and OpenCTI automatically fills it with the value of pattern field.
Can you point me to OpenCTI requirements on this field please? 
Can you check the example in the original comment, as the name field there is empty.

**Comment by Megafredo** [comment]
Hi @mmolenda,
In fact, the name field is automatically filled with the pattern value if the name is missing. However, for better readability and a more user-friendly search, we recommend that you extract the value without the name pattern:
 
For example
- name for domain name: [domain name:value = 'ExampleDomainName']
- name for ipv4: [ipv4-addr:value = '100.100.100.100']
- name for file name: [file:hashes.md5 = '79054025255fb1a26e4bc422aef54eb4']
- name for network-traffic: [network-traffic:dst_ref.value = '23.12.12.23' AND network-traffic:dst_port = 443]
 
Example after parsing:
- domain name: 'ExampleDomainName' (domain name)
- ipv4 name: '100.100.100.100' (domain name)
- filename: '79054025255fb1a26e4bc422aef54eb4' (file name)
- network-traffic name: '100.100.100.100:4000'

More complex case not handled by AND and OR:
- [network-traffic:dst_ref.value = '23.12.12.23' AND network-traffic:dst_port = 443 AND .... OR ...]
- [file:hashes.md5 = '79054025255fb1a26e4bc422aef54eb4' AND ... OR ...]

For all these cases, leave the pattern as its name, I hope I've been able to clarify things for you.

**Comment by mmolenda** [comment]
Thank you for the guidance. We'll change it the next release.

**Comment by marckto-filigran** [comment]
thanks @mmolenda !
By any chance, do you have an ETA for the next release?

**Comment by mmolenda** [comment]
We will try to release this month.
