### ISSUE TITLE
Alienvault OTX connector

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#26]
Collect IOCs from AlienvaultOTX

Create automatically associated reports
Create automatically associated links

Use Alienvault tags to create automatically

- associated threats (threat actors, intrusion sets, malware)
- assocated countries

https://www.alienvault.com/documentation/otx.htm?tocpath=Documentation%7CAlienVault%C2%AE%20Open%C2%A0Threat%20Exchange%C2%AE%7C_____0

**Comment by Fred-certeu** [comment]
Hello b4dpxl, I see that this issue is assigned to you... good luck !
Just to check, do you plan to include OTX observables collection ?
Thanks

**Comment by HarishHary** [comment]
@b4dpxl Are you still working on this ? I am willing to pick up the work on where you left of. And try to make it merge.

**Comment by CGarat** [comment]
Hello @b4dpxl, thanks a lot for this! I've forked your project to fetch observables as well (and added a support for Docker + changed the config a little). This is only a v1, we're probably missing some types.  https://github.com/CGarat/otx_to_opencti

**Comment by b4dpxl** [comment]
Hi. Sorry for not responding in ages. Thanks @CGarat. @HarishHary unfortunately, due to a (hopefully temporary) change in work focus, I'm not going to be looking at this for the foreseeable future :(

**Comment by SamuelHassine** [comment]
Hello guys,

CERT-EU is working on this connector. @maertv @Fred-certeu could you please tell us about the current status of your work?

**Comment by maertv** [comment]
Yes, we are actively working on it. No defined deadlines yet.

**Comment by maertv** [comment]
@SamuelHassine , is it OK to close this issue?
