### ISSUE TITLE
[TAXII 1] Create the connector

### ISSUE THREAD

**Issue by Tyrell20** [OpenCTI-Platform/connectors#260]
**Problem to Solve**
Could you please considering to implement a connector that using TAXII v1?

**Current Workaround**
Manual JSON Import

**Proposed Solution**
Connector that implemented TAXII 1 protocol

Many Thanks

**Comment by SamuelHassine** [comment]
Hello @Tyrell20,

We have implemented TAXII 2 protocol directly in the core platform. You can now create TAXII 2 collections directly in the UI:  https://demo.opencti.io/dashboard/data/taxii.

TAXII 1 is unfortunately not part of our roadmap and will not be prioritized for the moment. If your organization really need TAXII 1 endpoint, let's discuss that on Slack (you can DM me).

Kind regards,
Samuel
