### ISSUE TITLE
#Kaspersky Connector# How to get a certificate?

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#261]
Hello! Many thanks for your useful platform! I intend to install the connector to Kaspersky. In the docker-compose.yml, it shows I need to give the certificate path. I register the Kaspersky Threat Intelligence Portal, and then I get an API token, but I don't know how to get a certificate. Can you please tell me? Thank you!

**Comment by 2xyo** [comment]
The OpenCTI Kaspersky connector can be used to import knowledge from the [Kaspersky Threat Intelligence premium services](https://www.kaspersky.com/enterprise-security/apt-intelligence-reporting), not opentip.kaspersky.com.

If you have a premium account,  contact your dedicated Technical Account Manager at Kaspersky to obtain a certificate. A certificate and your credentials will be provided in a secure way.

**Comment by Ken-Abruzzi** [comment]
Thank you! I get it.
