### ISSUE TITLE
[QRadar] Full refactor of the connector and bring Filigran support

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#2616]
## Use case

[QRadar] Full refactor of the connector and bring Filigran support

**Comment by vishesh-verma-coder** [comment]
Hello Sam ,

It seems the connector code needs to be fixed for function "**process_indicator**" where it returns data.
**Issue**:  In case of indicator where Main observable type is File, it will return only 1 hash and will ignore others.

Generator could have been used in this case to capture all values in the STIX pattern
