### ISSUE TITLE
[urlscan] Failed: `pydantic:parse_raw_as` has been removed in V2.

### ISSUE THREAD

**Issue by brett-fitz** [OpenCTI-Platform/connectors#2642]
## Description

During testing, a bug was identified:

Failed: `pydantic:parse_raw_as` has been removed in V2. For further information visit https://errors.pydantic.dev/2.8/u/import-error
Introduced: https://github.com/OpenCTI-Platform/connectors/pull/2444/files#diff-e368303cb1c9de71c63e62c1f51aaefbf5f77e34b54cbcf179ca9f6a6ddd5a56

Solution:

* remove import pydantic
* import parse_raw_as from pydantic v1

**Comment by Megafredo** [comment]
Hi @brett-fitz, thanks for your feedback and PR, this solution will indeed solve the bug !
