### ISSUE TITLE
[Intel471] Files attached with no extension

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/connectors#2675]
## Description

The Intel471 connector ingests report containers with attachments without file extension (.pdf). As a result, when you download the file, you have to choose an extension to open it (time consuming) and the attachment is not displayed in the container's content tab.

## Expected Output

Having a .pdf extension on the attachment for instance to download open it easily and being able to see it in content.

## Actual Output

No extension so need to choose one after donwloading to open it and can't see the attachment in content tab of the container.

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/4299068d-3f42-44cb-af66-d83c449e69c3)

**Comment by nino-filigran** [comment]
@mmolenda Would you mind having a look at this, please?

**Comment by mmolenda** [comment]
Hi, I’ll take a look shortly. It should be an easy fix.

**Comment by nino-filigran** [comment]
Thanks a lot 🙏
