### ISSUE TITLE
Columns in the MITRE ATT&CK kill chain are out of order

### ISSUE THREAD

**Issue by seanthegeek** [OpenCTI-Platform/connectors#2688]
## Description

Columns in the `mitre-attack` kill chain are out of order. This issue can also be seen in `mitre-atlas`, `mitre-ics-attack` and `mitre-mobile-attack`.

## Environment

1. OS (where OpenCTI server runs): Debian 12
2. OpenCTI version: 6.3.1
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Click on an Intrusion Set provided by the MITRE connector
2. Click on the knowledge tab
3. Under the Capabilities box, click VIEW ALL  

## Expected Output

The columns should match the order of the ATT&CK Matrix on the [MITRE website](https://github.com/OpenCTI-Platform/connectors)

From left to right:

1. Reconnaissance
2. Resource Development
3. Initial Access
4. Execution
5. Persistence
6. Privilege Escalation
7. Defense Evasion
8. Credential Access
9. Discovery
10. Lateral Movement 
11. Collection
12. Command and Control
13. Exfiltration
14. Impact
 

## Actual Output

OpenCTI displays the columns in the following order, from left to right:

1. command-and-control
2. resource-development
3. privilege-escalation
4. impact
5. persistence
6. execution
7. initial-access
8. credential-access
9. lateral-movement
10. collection
11. discovery
12. defense-evasion
13. exfiltration
14. reconnaissance

**Comment by romain-filigran** [comment]
Hi @seanthegeek: Orders are not defined by the MITRE connector. You can configure the order by navigating to “settings--> customize --> taxonomies”. 
However, a bug has been identified and will be corrected in the next minor to respect the order defined through this panel: https://github.com/OpenCTI-Platform/opencti/issues/8424

**Comment by romain-filigran** [comment]
I close the issue but feel free to reopen it

**Comment by seanthegeek** [comment]
It would be better of the order was set correctly by the connector without having to configure it manually.
