### ISSUE TITLE
automated export of IoCs or REST api?

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/connectors#269]
Hi,

From the OpenCTI, I would like to automatically push IoCs (IP, hash) to our firewall. Our firewall have a feature to pull to a taxii server or to a REST.
But first, I am looking for OpenCTI capability or feature that can export IoC in automated basis - any existing connector that does this? Or somehow to pull from OpenCTI all those IoCs out? Please advise

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

TAXII Collections are now available directly on the platform. Here in the demo:  https://demo.opencti.io/dashboard/data/taxii.

Kind regards,
Samuel
