### ISSUE TITLE
[Sentinel] Store additional information 

### ISSUE THREAD

**Issue by yassine-ouaamou** [OpenCTI-Platform/connectors#2704]
## Use case

Be able to store the score or any additional information in Sentinel

## Proposed Solution

Following the recommendation of Microsoft, the idea is to store the score in the **AdditionalInformation** field.

## Additional Information

Bonus: It could be interesting to give the user the possibility to use this field to store more information in this field

**Comment by romain-filigran** [comment]
@Megafredo : Can we plan to exchange about this one.
