### ISSUE TITLE
How to deploy a connector in a separate yml file instead of all services in one yml file?

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#271]
**Hello, everyone! I need some help. Initially, I put all connectors service configuration in one yaml file with the opencti platform, redis, etc.. Then I find the CVE connector does not start importing data for many days.** 
![image](https://user-images.githubusercontent.com/68931768/109440062-b4a33a80-79e5-11eb-983f-b68f96521b1d.png)
 **I then remove the CVE connector by clicking the dustbin icon in the upper right of the above picture. Then I want to remove the CVE connector service in the yaml file temporarily. But I find it is inconvenient to deploy all services in one yaml file. Then I want to make a directory for every connector where the yaml and env files for only this connector are kept. I tried to deploy cve connector in such a way. And the yml file and the env file are shown as below**
![image](https://user-images.githubusercontent.com/68931768/109439908-1c0cba80-79e5-11eb-9b3c-d53cc820dcb0.png)
![image](https://user-images.githubusercontent.com/68931768/109439994-73ab2600-79e5-11eb-89bf-cb6541b19df4.png)
**Then I ran "sudo docker-compose up -d", and "sudo docker ps", there are two cve connectors running**
![image](https://user-images.githubusercontent.com/68931768/109440527-773fac80-79e7-11eb-9092-7e967fd1905d.png)
**and the newly built cve connector restarts frequently**
![image](https://user-images.githubusercontent.com/68931768/109440634-cdaceb00-79e7-11eb-89fe-ecfe7a8bd632.png)
![image](https://user-images.githubusercontent.com/68931768/109440925-9d198100-79e8-11eb-8b12-344f82159ffa.png)
**and in the web page, neither of formerly built cve connector nor the newly built one is shown**
![image](https://user-images.githubusercontent.com/68931768/109440560-94747b00-79e7-11eb-879d-c89d58ca2fba.png)
**Can anyone tell me the problem? Thanks a lot!**

**Comment by SamuelHassine** [comment]
Hello,

You can deploy the connectors in separate `docker-compose.yml` files if you have a proper management of network configuration. The connector must be able to access to the RabbitMQ server configured in the main platform (settings are transmitted as they are).

A lot of OpenCTI users deploy them in different files, take a look to the Terraform script to deploy OpenCTI in AWS, GCP and Azure: https://github.com/newcontext-oss/opencti-terraform.

Kind regards,
Samuel

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine Thank you!
