### ISSUE TITLE
[Virustotal] Error when enriching certain entities

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#2713]
## Description

On some entity, this error appears:

`{
    "timestamp": "2024-09-25T07:45:21.751840Z",
    "level": "ERROR",
    "name": "VirusTotal",
    "message": "Error in message processing, reporting error to API",
    "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 352, in _data_handler\n    message = self.callback(event_data)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-virustotal/virustotal/virustotal.py\", line 425, in _process_message\n    return self._process_file(stix_objects, stix_entity, opencti_entity)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-virustotal/virustotal/virustotal.py\", line 269, in _process_file\n    \"| \"\nTypeError: can only concatenate str (not \"NoneType\") to str"
}`

## Environment

OCTI 6.2.18

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enable the Virustotal enrichment connector
2. Try to enrich entities, hoping that an entity will raise this error

## Additional information

[Line 278 of the script](https://github.com/OpenCTI-Platform/connectors/blob/11c8cc3fc2958b1e994d760f193ef687adde6057/internal-enrichment/virustotal/src/virustotal/virustotal.py#L278) we check that the variable is not None, otherwise we use the string "N/A". 

However, for all the other previous ones (e.g. [line 269](https://github.com/OpenCTI-Platform/connectors/blob/11c8cc3fc2958b1e994d760f193ef687adde6057/internal-enrichment/virustotal/src/virustotal/virustotal.py#L270)) we don't do that and that seems to be the problem. Adding verification steps like in line 278 should fix the error.

**Comment by romain-filigran** [comment]
related to : https://github.com/OpenCTI-Platform/connectors/issues/2671
