### ISSUE TITLE
The connector for CVE does not import data and cannot be restart or removed

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#273]
## Description

The CVE connector remains the same state for 3 days, and when I click the buttons to reset the connector or clear the connector or delete the work, it shows "Error updating elastic".
![image](https://user-images.githubusercontent.com/68931768/109448992-31d9aa00-79fc-11eb-976d-7f6e86bc231b.png)

## Environment

1. OS : Ubuntu 20.04.2
2. OpenCTI version: 4.2.4
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Copy the yaml file from the github and modify the underlined fields as below:
![image](https://user-images.githubusercontent.com/68931768/109449325-03100380-79fd-11eb-8bd0-4150aeb37576.png)
2. Generate a uuid for the connector and add it in the .env file as below:
![image](https://user-images.githubusercontent.com/68931768/109449528-8e899480-79fd-11eb-9473-503374b985e9.png)
3. run "sudo docker-compose up -d"

## Expected Output

The data is imported continuously.

## Actual Output

The import progress stays at zero for 3 days. And I cannot delete the work, nor can I reset the connector or remove it. It always shows "Error updating elastic".

## Additional information

The connector for AlienVault is running very slow for 3 days. Perhaps at the same time, only one connector can work while others must wait. Is it true?
![image](https://user-images.githubusercontent.com/68931768/109449909-867e2480-79fe-11eb-9783-a9f90705d3ec.png)
It runs very slowly at a speed of 0.4/s.
![image](https://user-images.githubusercontent.com/68931768/110879491-f22f7f80-8291-11eb-94d1-47fa1c7488c5.png)

**Comment by SamuelHassine** [comment]
Hello @Ken-Abruzzi,

Can you please share the OpenCTI logs when you have the error "Error updating Elastic"?

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine Hello! Thanks for your attention. I have raised another question here [https://github.com/OpenCTI-Platform/opencti/issues/1139](url). I think the two phenomena may have same reason.

**Comment by Ken-Abruzzi** [comment]
I know the reason. The disk is short of space for elasticsearch to run.  I need to expand the disk space.
