### ISSUE TITLE
Fix description when exporting pdf in a IR case

### ISSUE THREAD

**Issue by NLAfiligran** [OpenCTI-Platform/connectors#2735]
Original format
![image](https://github.com/user-attachments/assets/3fd9b03f-260d-48c7-825f-fa10029980c7)

But when exporting to pdf, the format is broken
![image](https://github.com/user-attachments/assets/e0b3dbcb-8936-4a7d-9d33-dc1c1feae6b2)

**Comment by romain-filigran** [comment]
Need to convert markdown to html before exporting
