### ISSUE TITLE
Connector crowdstrike - setting epoch to milliseconds timestamp cause the connector to loop

### ISSUE THREAD

**Issue by trocade** [OpenCTI-Platform/connectors#274]
## Description

Setting the values of to epoch milliseconds
```
CROWDSTRIKE_REPORT_START_TIMESTAMP=
CROWDSTRIKE_INDICATOR_START_TIMESTAMP=

```
causes the connector to get stuck in a loop.

## Environment

1. Ubuntu 18.04 LTS
2. OpenCTI 4.2.4
3. python
4. N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set the REPORT or INDICATOR start time to a epoch time in milliseconds (2018-01-01 00:00:00) 1514764800000
2. Restart the connector
3. ERROR:root:CrowdStrike connector internal error: year 49970 is out of range

## Expected Output

The connector should not try to process any data

## Actual Output

The connector spawned several similar jobs with the same number of items over and over again.
![Capture](https://user-images.githubusercontent.com/9382220/109464998-dd6c1400-7a67-11eb-9bb9-efaa81e046d8.PNG)
 
![Capture](https://user-images.githubusercontent.com/9382220/109465894-2cff0f80-7a69-11eb-8474-899be02627fd.PNG)

## Additional information

When fixing the date the connector are now processing data but it has latest state "null" but I am giving it some time to see if this is fixed when it has manged to process all data.

**Comment by maertv** [comment]
Please use seconds since the Unix epoch.

**Comment by trocade** [comment]
Of course but:

The bug report is that even that the connector does seem to notice that the timestamp is wrong but still tries to process data from this incorrect date. And when it happens it will cause the loop of failed processed reports.

**Comment by maertv** [comment]
I understood.

It only accepts seconds since Unix epoch, but it is not explicitly checked. The documentation wrongly assumes that it is clear for everyone that the timestamp in UNIX Epoch time means it should be in seconds.
