### ISSUE TITLE
[CrowdStrike] Use modified date instead of created date when getting reports

### ISSUE THREAD

**Issue by brett-fitz** [OpenCTI-Platform/connectors#2756]
## Use case

Reports can be updated over time and thus, the corresponding report in OpenCTI should be updated if new entities are added or removed. 

## Current Workaround

* N/A

## Proposed Solution

Use the modified date instead of the created date when fetching reports.
* https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py#L106

_Note: Other changes are likely required to make this change work seamlessly._

## Would you be willing to submit a PR?

Yes I am willing to submit this fix.

**Comment by helene-nguyen** [comment]
@brett-fitz I will handle that :) Thanks
