### ISSUE TITLE
[Cyber Threat Coalition] Problem with the connector

### ISSUE THREAD

**Issue by Tyrell20** [OpenCTI-Platform/connectors#276]
## Description

Unable to pull data from  Cyber Threat Coalition connector (v. 4.2.4) into OpenCTI.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps
Configuration on docker-compose.yml:
      - CYBER_THREAT_COALITION_INTERVAL=604800 # Seconds (1 week)
      - CYBER_THREAT_COALITION_BASE_URL=https://blacklist.cyberthreatcoalition.org/vetted
      - CYBER_THREAT_COALITION_CREATE_INDICATORS=true
      - CYBER_THREAT_COALITION_CREATE_OBSERVABLES=true

## Expected Output

Expected log data indicating successful pull.

## Actual Output
Cyber Threat Coalition does not appear in the registered connectors list on OpenCTI Data dashboard.
 
## Additional information

docker logs:
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID:dda71278-f460-42f6-96d8-66b49f56950e
INFO:root:Starting ping alive thread
INFO:root:Fetching Cyber Threat Coalition vetted blacklists...
INFO:root:Loaded state: {}
INFO:root:Initiate work for dda71278-f460-42f6-96d8-66b49f56950e

**Comment by SamuelHassine** [comment]
Hello @Tyrell20,

The CTC connector is known to create a lot of things in one single report, which is not optimal. But still, it's working, are you sure of the ID and the name of the connector?

Kind regards,
Samuel

**Comment by Tyrell20** [comment]
Hello @SamuelHassine ,

yes, I'm sure of the ID and name of the connector.

With the latest versions, the connector appears in the list but it seems to still not work.
![screenshot 372](https://user-images.githubusercontent.com/64137969/112807289-02a86e00-9078-11eb-8858-82a8b05f6b3a.jpg)

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine Hello! I also confront such phenomenon shown as the above picture. And I check the docker log and it showns some errors:
![image](https://user-images.githubusercontent.com/68931768/119953139-28ec6c00-bf4a-11eb-9fb6-3ca95e7ea054.png)
I can visit the url given in the docker-compose.yml.
![image](https://user-images.githubusercontent.com/68931768/119953330-576a4700-bf4a-11eb-8d97-63cba44adcae.png)

**Comment by sukesh-ak** [comment]
I had to remove this connector since it spikes CPU a lot unlike all other connectors.
This is 2nd to elastic search in CPU usage.

**Comment by Ken-Abruzzi** [comment]
> I had to remove this connector since it spikes CPU a lot unlike all other connectors.
> This is 2nd to elastic search in CPU usage.

Yes. I also find this connector consumes the computer resources greedily.

**Comment by nor3th** [comment]
Hey

Is it the connector which consumes so much CPU or opencti_worker (which handles the STIX object creation part).

Regards,

**Comment by sukesh-ak** [comment]
@nor3th For me since I am using docker, the spike is shown for this specific connector container.

**Comment by SamuelHassine** [comment]
@nor3th, @sukesh-ak, I will rework this connector in the next major release. The CPU pike is linked to the global conversion of more than 100K observables in STIX 2.1 without any concerns about diff or already ingested entities.

**Comment by SamuelHassine** [comment]
Cyber Threat Coalition vetted list is not available anymore.
