### ISSUE TITLE
[ransomwarelive] Create predictive ids to prevent stix ids location explosion

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/connectors#2768]
Improve ransomwarelive connector to create predictive ids to prevent stix ids location explosion

**Comment by annoyingapt** [comment]
Is it the generate id from the pycti library that is being used to a generate predicable id. Would you be recommending that other connectors use the same library?

**Comment by richard-julien** [comment]
Yes. But currently working on a more generic approach. https://github.com/OpenCTI-Platform/opencti/issues/7158

**Comment by sudesh0sudesh** [comment]
@richard-julien , Can i have a link to how predictive ID works please as i was also working some other changes to ransomwarelive.
