### ISSUE TITLE
[ZeroFox] Entity mapping is sometimes inadequately structured

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/connectors#2780]
### Malware: 

- Some malware is named using the hash of the indicator, which makes differentiation very difficult.
- Some labels on malware refer to MITRE tactics. It would be useful to have this information included in the "Kill chain phases". 
- If specific techniques from these tactics are identified, it would also be desirable to link them to the corresponding attack pattern entity.

### CVE: 

Some CVEs are listed as "Tools" entities in addition to being listed as "Vulnerability" entities.

### Indicators: 

The indicators do not have any "Indicator types" specified.

### Infrastructures: 

Infrastructures are ingested in bulk, but they are just IP addresses. These same infrastructures are not linked to corresponding indicators/observables.

**Comment by romain-filigran** [comment]
Hello @DNRRomero @alexmfarrell: Could you take a look at Nicolas' requests for improvements?

**Comment by alexmfarrell** [comment]
Hey there
@NiQuintin @romain-filigran, this is currently been worked and should be pushed no later than tomorrow.
Cheers!
