### ISSUE TITLE
[Flashpoint] Errors while adding the connector

### ISSUE THREAD

**Issue by EinatAR** [OpenCTI-Platform/connectors#2803]
## Description

Working through adding the flashpoint connector: 

Error received 

`{"timestamp": "2024-10-15T15:21:37.937245Z", "level": "ERROR", "name": "Flashpoint", "message": "File data is not a valid bundle", "exc_info": "Traceback (most recent call last):\n File \"/opt/opencti-connector-flashpoint/flashpoint.py\", line 379, in _import_apt\n self.helper.send_stix2_bundle(\n File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 1701, in send_stix2_bundle\n ) = stix2_splitter.split_bundle_with_expectations(\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File \"/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2_splitter.py\", line 77, in split_bundle_with_expectations\n raise Exception(\"File data is not a valid bundle\")\nException: File data is not a valid bundle"}`

`{"timestamp": "2024-10-15T15:23:22.426418Z", "level": "ERROR", "name": "Flashpoint", "message": "'site_source_uri'", "exc_info": "Traceback (most recent call last):\n File \"/opt/opencti-connector-flashpoint/flashpoint.py\", line 834, in _import_alerts\n url=item[\n ^^^^^\nKeyError: 'site_source_uri'"}`

## Environment

OpenCTI version: 6.3.1
and the connector versions are the same

## Additional information

`{"timestamp": "2024-10-07T21:07:23.331934Z", "level": "ERROR", "name": "Flashpoint", "message": "File data is not a valid bundle", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-flashpoint/flashpoint.py\", line 379, in _import_apt\n    self.helper.send_stix2_bundle(\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 1701, in send_stix2_bundle\n    ) = stix2_splitter.split_bundle_with_expectations(\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2_splitter.py\", line 77, in split_bundle_with_expectations\n    raise Exception(\"File data is not a valid bundle\")\nException: File data is not a valid bundle"}{"timestamp": "2024-10-07T21:07:23.926432Z", "level": "ERROR", "name": "Flashpoint", "message": "File data is not a valid bundle", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-flashpoint/flashpoint.py\", line 412, in _import_malware\n    self.helper.send_stix2_bundle(\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 1701, in send_stix2_bundle\n    ) = stix2_splitter.split_bundle_with_expectations(\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2_splitter.py\", line 77, in split_bundle_with_expectations\n    raise Exception(\"File data is not a valid bundle\")\nException: File data is not a valid bundle"}`

**Comment by flavienSindou** [comment]
Investigation Notion Page: 

https://www.notion.so/filigran/Flashpoint-1218fce17f2a80359e8ef0624dfd381f
