### ISSUE TITLE
[Zerofox] Title indicator and country structure to be corrected

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/connectors#2828]
## Description

In the latest version of the connector, two small corrections need to be made:

- Remove "Pattern for malware" from the title, leaving only the hash in the title.
- For the country entities, apply a correction so that they display correctly (see screenshots).

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/bdeff844-4d8c-460f-b0d2-103025171129)
![image](https://github.com/user-attachments/assets/2474f2fe-0e61-45fa-84bb-aea94446b515)

**Comment by NiQuintin** [comment]
@DNRRomero last little fix to make. If you have questions do not hesitate.

cc: @helene-nguyen

**Comment by alexmfarrell** [comment]
Hey there! I understood the original ask from was to not have the hash being the sole title of the entry, as asked here (https://github.com/OpenCTI-Platform/connectors/issues/2780)? You want this reverted back, and just show the hash?
2nd point, you just want the country code, eg "TW" and not "TW-400"?
Given these are just cosmetic issues and not functional errors we will have to prioritise this update into our backlog to join other items to be planned. These update should not be affecting the flow of data to the end customer.

**Comment by NiQuintin** [comment]
Hey @alexmfarrell thanks for your feedback 😊

Yes usually we just add the hash in title like this: 

![image](https://github.com/user-attachments/assets/568e067a-ee38-4b84-801b-6a8cb3377e14)

For the countries, the best would be to add the full name of the country or at least just the country code like "TW". 

**Oh and just seen also for the Indicators, you need to fill in the field x_opencti_main_observable_type** otherwise it's gonna be impossible for users to filter on them:

![image](https://github.com/user-attachments/assets/bc439e1f-4a36-4d89-9a89-4fef8a58e8d1)


![Screenshot 2024-10-21 100701](https://github.com/user-attachments/assets/f21c0685-6100-4f2d-940f-5292ef351eef)

**Comment by alexmfarrell** [comment]
@NiQuintin Cool, this has been prioritised into our backlog. Will let you know when the PR is ready. Thank you!

**Comment by alexmfarrell** [comment]
@NiQuintin Hey there! The PR is available now, we've amended the data to display as requested. Let me know if you have any questions.
Cheers!!!

**Comment by yassine-ouaamou** [comment]
Hey @alexmfarrell,
Thanks for the heads-up. 
We haven't seen any Pull request in the repo. Can you submit it in this repository: https://github.com/OpenCTI-Platform/connectors/pulls?

**Comment by alexmfarrell** [comment]
So sorry, it was sent to the wrong fork. This is the PR here:
https://github.com/OpenCTI-Platform/connectors/pull/2988

**Comment by DNRRomero** [comment]
Hi @yassine-ouaamou  we have the PR ready for review 😄
