### ISSUE TITLE
[Mandiant] Connector can't import data due to key error

### ISSUE THREAD

**Issue by cyc123456789** [OpenCTI-Platform/connectors#2833]
## Description
Maindiant connector can't import data due to key error

## Environment

1. OS (where OpenCTI server runs): Docker on Ubuntu 22.04
2. OpenCTI version:6.3.1
3. OpenCTI client: frontend
4. Maindiant connector yml:
  connector-mandiant:
    image: opencti/connector-mandiant:6.3.6
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ANALYSIS_ID} # Valid UUIDv4
      - CONNECTOR_NAME=Mandiant
      - CONNECTOR_SCOPE=mandiant
      - CONNECTOR_LOG_LEVEL=debug
      - CONNECTOR_DURATION_PERIOD=PT5M # In ISO8601 Format starting with "P" for Period ex: "PT5M" = Period time of 5 minutes
      - MANDIANT_API_V4_KEY_ID=...
      - MANDIANT_API_V4_KEY_SECRET=...

## Actual Output
![image](https://github.com/user-attachments/assets/72b8d5f6-c9c1-4104-b3f5-244fa90e5baa)

**Comment by romain-filigran** [comment]
Reproduced. This error occurs if no state is associated with the connector (i.e. the first execution).
@helene-nguyen : Could you have a look into please.

**Comment by helene-nguyen** [comment]
@romain-filigran yes, I will handle this

**Comment by helene-nguyen** [comment]
@cyc123456789 After some investigations, I cannot reproduce the issue. 

Even if the state is not define on the first run of the connector, you have a method which compute the base structure of the state for each collection:
https://github.com/OpenCTI-Platform/connectors/blob/49674c1f1c371a325f5f270949d5fa71ca2b121b/external-import/mandiant/src/connector/base.py#L499

Here the detail of the code when no state exists:

```python
        if not self.helper.get_state():
            # Create period of 1 day starting from the configuration
            # Mandiant API only paginate in reverse time ordering
            base_structure = self.compute_start_structure(
                self.mandiant_import_start_date
            )
            indicator_structure = self.compute_start_structure(
                self.mandiant_indicator_import_start_date
            )
            self.helper.set_state(
                {
                    "vulnerabilities": base_structure,
                    "indicators": indicator_structure,
                    "campaigns": base_structure,
                    "malwares": base_structure,
                    "reports": base_structure,
                    "actors": base_structure,
                }
            )
```

And here how it computes on the first run the initial state:
https://github.com/OpenCTI-Platform/connectors/blob/49674c1f1c371a325f5f270949d5fa71ca2b121b/external-import/mandiant/src/connector/base.py#L519
```python
    def compute_start_structure(self, start_date):
        now = Timestamp.now()
        start = Timestamp.from_iso(start_date)
        end = start.delta(days=self.mandiant_import_period)
        if end.value > now.value:
            end = None
        return {
            STATE_START: start.iso_format,
            STATE_END: end.iso_format if end is not None else None,
            STATE_LAST_RUN: now.iso_format,
            STATE_OFFSET: 0,
        }
```

Can you try something for me ? Could you realign the versions of both OpenCTI platform and Mandiant connector to the last version and give it a try please ?

**Comment by cyc123456789** [comment]
I discovered that by reconfiguring a new CONNECTOR_ID, I was able to use the connector normally. Thank you for your assistance.
