### ISSUE TITLE
[Tanium] Connector getting terminated without explicit logs

### ISSUE THREAD

**Issue by troll-os** [OpenCTI-Platform/connectors#2850]
## Description

The Tanium connector is recently being unable to run properly and crashes constantly without explicit logs on multiple deployments 

## Environment

Filigan SaaS

## Reproducible Steps

Run the Tanium connector, it should crash right away

## Expected Output

Connector is running without issues or at least provide logs for why it crashes 

## Actual Output

Connector is getting killed, last available log is "Terminated".
No other error logs are associated with the container ending 

## Additional information

DM if needed

**Comment by Powlinett** [comment]
I opened a PR to add some logs but the issue underneath was due to our credentials.
@troll-os, @romain-filigran  I shared with you my investigation's conclusions :)
