### ISSUE TITLE
Option for Data Import Conenctors to use Request on Demand?

### ISSUE THREAD

**Issue by JustCodeIt4Head** [OpenCTI-Platform/connectors#289]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve
As far as I'm aware, Connectors like AlienValut or Malpedia can't be configured to work only on Request, they have to Download the Entire Dataset if connected.
So lets say i have IP 1.1.1.1 and only want Information from AlivenValut about that IP, it would be nice to have the Option to just download that specific Data then via the worker and not every Pulse since Date X

## Current Workaround
Download the whole Pulses, with the Chance of Missing older ones when you don't go back far enough

## Proposed Solution

A Switch Option that you can Run the "Data Import" Connectors in normal or Request Only Mode. So only Data for Imported IOCs gets pulled.

## Additional Information

Not sure if this Option exists and im just not be able to find it or if the Option is not available or not possible, since i don't know how exactly the API from AlienVault etc works.
But I feel that would be a nice Feature, at least I miss it

**Comment by SamuelHassine** [comment]
Hello @JustCodeIt4Head,

This is the purpose of "enrichment" connectors. Please can you open issues to create enrichment connectors for the services you need? 

For instance, if you need an AlienVault Enrichment connector, it will be a different connector which will pull Pulses related to a specific indicator/observable.

Kind regards,
Samuel
