### ISSUE TITLE
[Mandiant] Connector does not show accurate progess, and ingests reports very slowly

### ISSUE THREAD

**Issue by damians-filigran** [OpenCTI-Platform/connectors#2892]
## Description

When ingesting reports, for the first day's ingest, the connector shows 100% progress, but then continues to ingest and increase the total operations despite the job apparently being completed. This continues for 1hr so far, with the count going higher and higher, despite the job showing as complete.

## Environment

1. OS: SaaS
2. OpenCTI version: 6.2.8
3. OpenCTI client: Edge on MacOS
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure Mandiant connector
2. Set start date from 2 months ago
3. Click into connector status view
4. Watch the completed job continue to build total count

## Expected Output

Job should stay as In Progress until complete

## Actual Output

Job apparently complete
![image](https://github.com/user-attachments/assets/08dca819-3690-42f1-ba5e-3f3d72ef22cc)

Job even more complete
![image](https://github.com/user-attachments/assets/b27a52c8-37e9-4708-975e-65f93490bd87)

## Additional information

In effect, this accompanies a very slow ingest of the report from the API, maybe 1 operation per second, for Reports specifically.

**Comment by Megafredo** [comment]
Hi @damians-filigran, 
As far as the “complete” status is concerned, a general issue has been opened here (https://github.com/OpenCTI-Platform/opencti/issues/8224)
As for the slow ingestion of Mandiant's reports, it must be understood that some reports are extremely voluminous, which could explain this feeling.
