### ISSUE TITLE
[Mandiant connector] missing campaign descriptions

### ISSUE THREAD

**Issue by NLAfiligran** [OpenCTI-Platform/connectors#2939]
The campaign descriptions are missing

![image](https://github.com/user-attachments/assets/bd3ca2ca-1fc5-4589-b36c-665f419f25f6)
![image](https://github.com/user-attachments/assets/20af14a9-a4b1-4d75-8ec4-9564ddd5d1c1)

**Comment by nino-filigran** [comment]
Opened by mistake, already fixed.
