### ISSUE TITLE
[MITRE] Can't sync mitre connector.

### ISSUE THREAD

**Issue by romanrusetsky** [OpenCTI-Platform/connectors#306]
## Description

I am trying to sync the miter connector with opencti-release-4.3.1 and I keep failing.

## Environment

1. Vmware On windows -> Ubuntu 16.4 -> opencti-release-4.3.1 OVF image
2. opencti-release-4.3.1
3. python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. cd to connectors dir mitre/src
2. edited the config.yml:
"""
"""
"""
opencti:
  url: 'http://localhost:8080'
  token: '1c4fd02e-e69f-4859-a5ef-2e14b21b7849'

connector:
  id: 'f584072a-ff4f-44e7-a996-0d393dfaa0f0'
  type: 'EXTERNAL_IMPORT'
  name: 'MITRE ATT&CK'
  scope: 'identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report,external-reference-as-report'
  confidence_level: 15 # From 0 (Unknown) to 100 (Fully trusted)
  update_existing_data: True
  log_level: 'info'

mitre:
  enterprise_file_url: 'https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json'
  pre_attack_file_url: 'https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json'
  mobile_attack_file_url: 'https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json'
  interval: 7 # In days, must be strictly greater than 1
"""
3. run python3 mitre.py

## Expected Output

none

## Actual Output

I get this exception. 

INFO:root:Update action expectations opencti-work--18a2aed9-9ffb-4692-bc50-a91cf402b9dc - 10923
ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(11002, 'getaddrinfo failed')
ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(11002, 'getaddrinfo failed').
ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 except
ions in all; last exception - gaierror(11002, 'getaddrinfo failed'); first exception - None.
ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFaile
d: 1 exceptions in all; last exception - gaierror(11002, 'getaddrinfo failed'); first exception - None
ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all
; last exception - gaierror(11002, 'getaddrinfo failed'); first exception - None
ERROR:pika.adapters.blocking_connection:Error in _create_connection().
Traceback (most recent call last):
  File "C:\Users\romanr\AppData\Local\Programs\Python\Python38\lib\site-packages\pika\adapters\blocking_connection.py
", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "C:\Users\romanr\AppData\Local\Programs\Python\Python38\lib\site-packages\pika\adapters\utils\selector_ioloop_
adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
  File "C:\Users\romanr\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed
 
## Additional information

From some googling it looks like something is wrong with my RabitMQ, I have added it explicitly to the hosts file, but this did not solve it.

**Comment by SamuelHassine** [comment]
Hello @romanrusetsky,

It seems your connectors have no access to the RabbitMQ. You have to allow them to reach RabbitMQ using the parameters set in the core platform. Please verify your configuration.

Kind regards,
Samuel
