### ISSUE TITLE
[VirusTotal] What is VIRUSTOTAL_TOKEN?

### ISSUE THREAD

**Issue by nicolas-gagnon** [OpenCTI-Platform/connectors#312]
What info we need to filed in VIRUSTOTAL_TOKEN in docker-compose.yml

version: '3'
services:
  connector-virustotal:
    image: opencti/connector-virustotal:4.3.4
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=VirusTotal
      - CONNECTOR_SCOPE=StixFile,Artifact
      - CONNECTOR_AUTO=true
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - VIRUSTOTAL_TOKEN=**ChangeMe**
      - VIRUSTOTAL_MAX_TLP=TLP:AMBER
    restart: always

**Comment by SamuelHassine** [comment]
Hello @nicolas-gagnon,

This is your VirusTotal API Key.

Kind regards,
Samuel
