### ISSUE TITLE
[Harfanglab-incident] TypeError

### ISSUE THREAD

**Issue by breizh33** [OpenCTI-Platform/connectors#3135]
## Description

The connector does not work, here are the traces:

Traceback (most recent call last):
  File "/opt/opencti-harfanglab-incidents/main.py", line 16, in <module>
    connector = HarfanglabIncidentsConnector()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py", line 56, in __init__
    self.api = HarfanglabClient(self.helper, self.config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/client_api.py", line 22, in __init__
    "Authorization": "Token " + self.config.harfanglab_token,
                     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str


## Environment

1. OS RHEL 9.4
2. OpenCTI version: 6.4.3
4. Other environment details: podman

**Comment by breizh33** [comment]
I looked at the changes and therefore modified the name of the variables, this allowed to move forward in the connection. But now, I have a new error:

{"timestamp": "2024-12-18T08:25:04.266251Z", "level": "INFO", "name": "HarfangLab", "message": "[API] HTTP GET Request to endpoint", "attributes": {"url": "https://xxxxx//api/data/alert/alert/Alert?status=new%2Cinvestigating%2Cclosed&alert_type=yara%2Csigma%2Cioc&maturity=stable&ordering=alert_time&limit=100&from=2024-01-01T00%3A00%3A00%2B00%3A00"}}
{"timestamp": "2024-12-18T08:25:04.667991Z", "level": "INFO", "name": "HarfangLab", "message": "[API] HTTP GET Request to endpoint", "attributes": {"url": "https://XXXXXXXXXX//api/data/threat_intelligence/SigmaRule"}}
{"timestamp": "2024-12-18T08:25:04.671117Z", "level": "ERROR", "name": "HarfangLab", "message": "'NoneType' object has no attribute 'name'", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py\", line 296, in process_message\n    stix_bundle = self.create_stix_bundle()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py\", line 267, in create_stix_bundle\n    stix_objects = self._collect_incident_intelligence()\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py\", line 170, in _collect_incident_intelligence\n    stix_observables = self.converter_to_stix.create_observables(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/converter_to_stix.py\", line 343, in create_observables\n    observable = self._create_file(alert.process)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/converter_to_stix.py\", line 67, in _create_file\n    name=process.name,\n         ^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'name'"}
{"timestamp": "2024-12-18T08:25:04.672808Z", "level": "INFO", "name": "HarfangLab", "message": "[INFO] Schedule next run of connector: ", "attributes": {"next_run_datetime": "2024-12-18T08:26:04Z"}}


My configuration is :
  harfanglab-incidents:
    image: opencti/connector-harfanglab-incidents:rolling
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_CONNECTOR_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_HARFANGLAB_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=HarfangLab
      - CONNECTOR_SCOPE=harfanglab
      - CONNECTOR_LOG_LEVEL=debug
      - CONNECTOR_DURATION_PERIOD=PT1M
      - HARFANGLAB_INCIDENTS_URL=https://xxxxxx/
      - HARFANGLAB_INCIDENTS_SSL_VERIFY=true
      - HARFANGLAB_INCIDENTS_TOKEN=${TOKEN_HARGFANLAB}
      - HARFANGLAB_INCIDENTS_IMPORT_THREATS=false # If true then threats will be imported too (as Case Incidents), otherwise only alerts will be imported (as Incidents)
      - HARFANGLAB_INCIDENTS_ALERT_STATUSES=new,investigating,closed # Filters available : new, investigating, false_positive, closed
      - HARFANGLAB_INCIDENTS_ALERT_TYPES=yara,sigma,ioc # Filters available : yara, sigma, ioc
      - HARFANGLAB_INCIDENTS_DEFAULT_MARKING=TLP:AMBER # Markings available : TLP:CLEAR - TLP:GREEN - TLP:AMBER - TLP:RED (default: TLP:CLEAR)
      - HARFANGLAB_INCIDENTS_DEFAULT_SCORE=50 # Former confidence_level deprecated in OpenCTI version >= 6.0
      - HARFANGLAB_INCIDENTS_IMPORT_START_DATE=2024-01-01
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - NO_PROXY=${NO_PROXY}
    restart: always
    depends_on:
      - opencti

**Comment by flavienSindou** [comment]
> I looked at the changes and therefore modified the name of the variables, this allowed to move forward in the connection. But now, I have a new error:
> 
> {"timestamp": "2024-12-18T08:25:04.266251Z", "level": "INFO", "name": "HarfangLab", "message": "[API] HTTP GET Request to endpoint", "attributes": {"url": "[https://xxxxx//api/data/alert/alert/Alert?status=new%2Cinvestigating%2Cclosed&alert_type=yara%2Csigma%2Cioc&maturity=stable&ordering=alert_time&limit=100&from=2024-01-01T00%3A00%3A00%2B00%3A00"}}](https://xxxxx//api/data/alert/alert/Alert?status=new%2Cinvestigating%2Cclosed&alert_type=yara%2Csigma%2Cioc&maturity=stable&ordering=alert_time&limit=100&from=2024-01-01T00%3A00%3A00%2B00%3A00%22%7D%7D) {"timestamp": "2024-12-18T08:25:04.667991Z", "level": "INFO", "name": "HarfangLab", "message": "[API] HTTP GET Request to endpoint", "attributes": {"url": "[https://XXXXXXXXXX//api/data/threat_intelligence/SigmaRule"}}](https://XXXXXXXXXX//api/data/threat_intelligence/SigmaRule%22%7D%7D) {"timestamp": "2024-12-18T08:25:04.671117Z", "level": "ERROR", "name": "HarfangLab", "message": "'NoneType' object has no attribute 'name'", "exc_info": "Traceback (most recent call last):\n File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py", line 296, in process_message\n stix_bundle = self.create_stix_bundle()\n ^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py", line 267, in create_stix_bundle\n stix_objects = self._collect_incident_intelligence()\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/connector.py", line 170, in _collect_incident_intelligence\n stix_observables = self.converter_to_stix.create_observables(\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/converter_to_stix.py", line 343, in create_observables\n observable = self._create_file(alert.process)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/opt/opencti-harfanglab-incidents/harfanglab_incidents_connector/converter_to_stix.py", line 67, in _create_file\n name=process.name,\n ^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'name'"} {"timestamp": "2024-12-18T08:25:04.672808Z", "level": "INFO", "name": "HarfangLab", "message": "[INFO] Schedule next run of connector: ", "attributes": {"next_run_datetime": "2024-12-18T08:26:04Z"}}
> 
> My configuration is : harfanglab-incidents: image: opencti/connector-harfanglab-incidents:rolling environment: - OPENCTI_URL=http://opencti:8080 - OPENCTI_TOKEN=${OPENCTI_CONNECTOR_TOKEN} - CONNECTOR_ID=${CONNECTOR_HARFANGLAB_ID} - CONNECTOR_TYPE=EXTERNAL_IMPORT - CONNECTOR_NAME=HarfangLab - CONNECTOR_SCOPE=harfanglab - CONNECTOR_LOG_LEVEL=debug - CONNECTOR_DURATION_PERIOD=PT1M - HARFANGLAB_INCIDENTS_URL=https://xxxxxx/ - HARFANGLAB_INCIDENTS_SSL_VERIFY=true - HARFANGLAB_INCIDENTS_TOKEN=${TOKEN_HARGFANLAB} - HARFANGLAB_INCIDENTS_IMPORT_THREATS=false # If true then threats will be imported too (as Case Incidents), otherwise only alerts will be imported (as Incidents) - HARFANGLAB_INCIDENTS_ALERT_STATUSES=new,investigating,closed # Filters available : new, investigating, false_positive, closed - HARFANGLAB_INCIDENTS_ALERT_TYPES=yara,sigma,ioc # Filters available : yara, sigma, ioc - HARFANGLAB_INCIDENTS_DEFAULT_MARKING=TLP:AMBER # Markings available : TLP:CLEAR - TLP:GREEN - TLP:AMBER - TLP:RED (default: TLP:CLEAR) - HARFANGLAB_INCIDENTS_DEFAULT_SCORE=50 # Former confidence_level deprecated in OpenCTI version >= 6.0 - HARFANGLAB_INCIDENTS_IMPORT_START_DATE=2024-01-01 - HTTP_PROXY=${PROXY} - HTTPS_PROXY=${PROXY} - NO_PROXY=${NO_PROXY} restart: always depends_on: - opencti

Thank you for this other bug report. Could open a dedicated Github Issue please ? We'll try to fix this as soon as possible.
