### ISSUE TITLE
[Sekoia] "403 Client Error: Forbidden for url"

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#315]
## Description

The Connector-Sekoia does not download data. I check the docker log file, it shows the error information "403 Client Error: Forbidden for url".
![image](https://user-images.githubusercontent.com/68931768/114341478-5a2deb80-9b06-11eb-93b9-9ca0ae3bb099.png)
_figure 1_

I visit the url mentioned in the log file, and it returns 
![image](https://user-images.githubusercontent.com/68931768/114342762-e3462200-9b08-11eb-97d9-09e3fe3dff3d.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu server 20.04.2 LTS
2. OpenCTI version: OpenCTI 4.3.5
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Register in the url [https://sekoia.io](url) for 7 day free trial.

2. Generate an API key of 1005-character-length
![image](https://user-images.githubusercontent.com/68931768/114341785-01ab1e00-9b07-11eb-8771-b81d9aa1a1ca.png)
_figure 2_

The API key has such role as below:
![image](https://user-images.githubusercontent.com/68931768/114341844-22737380-9b07-11eb-8ff0-b3c9b9aa8a89.png)
_figure 3_

3. Generate the connector id by clicking the red circle shown in _figure 2_

4. Modify the docker-compose.yml file to add the service of connector-sekoia
![image](https://user-images.githubusercontent.com/68931768/114342603-92362e00-9b08-11eb-9735-f95cf0b8ff58.png)

5.  Add the environment varibles used above in the .env file.

6. "docker-compose up -d"    to start the service. 
## Expected Output

The download work should start.

## Actual Output

![image](https://user-images.githubusercontent.com/68931768/114342710-c9a4da80-9b08-11eb-8670-9b3e3b34f075.png)

## Additional information

I ever doubt whether it is caused by an invalid API key. I modify the API key in the .env file to a wrong value. I then start the service and check the docker log file. And it shows "500 Server Error: Internal Server Error for url". So it is not the wrong API key that causes "403 Client Error".

**Comment by SamuelHassine** [comment]
@Darkheir Any idea?

**Comment by Darkheir** [comment]
The error you get when visiting the url makes sense, `\u0026` should be replaced by `&` in the url (i.e. `?limit=20&cursor=...`). In this case the API should return an HTTP `400` and not a `403`.

As for the error in the connector seeing that this is a `403` I guess the API Key provided is not a valid one.

**Comment by Ken-Abruzzi** [comment]
@Darkheir @SamuelHassine Thank you very much. I need to ask the Sekoia for the permission with "INTHREAT_READ_OBJECTS".
