### ISSUE TITLE
[AWS] Create the connector (Stream)

### ISSUE THREAD

**Issue by Stoffe** [OpenCTI-Platform/connectors#319]
## Problem to Solve

Integration to AWS

## Proposed Solution

Integration to AWS

**Comment by SamuelHassine** [comment]
Hello @Stoffe,

Can yo please be more precise on which AWS Service OpenCTI should be sent on?

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
No input about which service we are talking about here. Please feel free to re-open.
