### ISSUE TITLE
ImportDoc connector not extracting all observables contained within a file

### ISSUE THREAD

**Issue by nhuber0724** [OpenCTI-Platform/connectors#3201]
## Description

The importdoc connector is not extracting all observables listed in a PDF file. 

## Environment

OpenCTI v6.4.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Take the below list of IPs and save as a PDF file
2. Import the file via the ImportDoc connector
3. Review the workbench. IPs 8.8.8.8 and 11.11.11.11 will be included with the import. 
1.1.1.1
2.2.2.2
3.3.3.3
4.4.4.4
5.5.5.5
6.6.6.6
7.7.7.7
8.8.8.8
9.9.9.9
10.10.10.10
11.11.11.11

## Expected Output

All IPs will be extracted and included as observables in the workbench. 

## Actual Output

IPs 8.8.8.8 and 10.10.10.10 are not extracted. 

## Screenshots (optional)
![Image](https://github.com/user-attachments/assets/f95a39a5-105b-490c-8e41-9935ddb7369c)

**Comment by Lhorus6** [comment]
This is normal, we have files in the ImportDocument connector that play the role of filter to avoid adding particular Observables to the workbench (kind of blacklists). 

8.8.8.8 and 10.10.10.10 are part of these files (like 192.168... for example). See the files here: https://github.com/OpenCTI-Platform/connectors/tree/master/internal-import-file/import-document/src/reportimporter/filter_list
