### ISSUE TITLE
[AlienVault] Queues not decreasing

### ISSUE THREAD

**Issue by PandaLyfe** [OpenCTI-Platform/connectors#334]
## Description

It appears the connectors for OpenCTI are functioning, new entities, relationships and observables are populating, but reports are not. Please note, this has been occurring for days at the time of drafting this issue. Most recent report received was dated on 02 April 2021.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.10
2. OpenCTI version: 4.4.0
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
In this case, I just log in and on the home dashboard, everything is populating except reports. I checked the connectors and data appears to be ingested. 

Figure 1: Dashboard displaying everything popluating except Reports
![Dashboard](https://user-images.githubusercontent.com/26508991/115148901-8928ed80-a02f-11eb-9d78-c12615658c0b.png)

Figure 2: New Entities Generating 
![Populating Entities](https://user-images.githubusercontent.com/26508991/115148909-92b25580-a02f-11eb-937e-c4e83837812e.png)

Figure 3: Healthy Connectors
![Connectors](https://user-images.githubusercontent.com/26508991/115148915-9a71fa00-a02f-11eb-9649-7f4121ac7243.png)

## Expected Output

For new reports to populate

## Actual Output

No reports are populating
 
## Additional information

None at the moment. Please let me know if additional information is needed.

**Comment by SamuelHassine** [comment]
Hello @PandaLyfe,

Sorry for the late reply, do you still have the problem? This may be linked to a temporary situation where you was ingesting a "huge" report, creating all the entities/observables before the report itself. 

Please tell us if you still encouter problem to ingest reports, not a lot of connectors are actually providing report "containers" (AlienVault, MISP, Kaspersky, CrowdStrike and a few others).

Kind regards,
Samuel

**Comment by PandaLyfe** [comment]
Hello @SamuelHassine 

Thank you for the follow up. 

I am experiencing issues with the AlienVault connector. In the connectors page, I see data coming in, but it just just stops at 2.18 Million and it stays there.

**Comment by SamuelHassine** [comment]
Hey @PandaLyfe,

Did you read https://github.com/OpenCTI-Platform/opencti/issues/1441?

This is the only thing I know which will silently make the queue not decreasing.

Kind regards,
Samuel

**Comment by PandaLyfe** [comment]
Thanks for the follow up @SamuelHassine. 

I installed OpenCTI using Portainer. In [Issue #1441](https://github.com/OpenCTI-Platform/opencti/issues/1441), someone asked if it is possible if we can make the following modification to the docker-compose.yml file: 

```
[$:/etc/rabbitmq# cat rabbitmq.conf 
consumer_timeout=8600000](url)
```
Is it possible? Or do you have any guidance for making this modification through Portainer? Thank you

**Comment by tigre-bleu** [comment]
I have the same symptoms: Queue not decreasing and Alienvault reports not ingested.

In the error.log file I can see a lot of those:

```json
{"user":{"ip":"127.0.0.1","user_id":"xxx","applicant_id":"xxx","call_retry_number":""},"type":"WRITE_ERROR","operation_query":"mutation MarkingDefinitionAdd($input:MarkingDefinitionAddInput){markingDefinitionAdd(input:$input){id standard_id entity_type parent_types definition_type definition x_opencti_order x_opencti_color created modified created_at updated_at}}","inner_relation_creation":0,"operation":"MarkingDefinitionAdd","time":64679,"variables":{"input":{"definition_type":"TLP","definition":"TLP:WHITE","x_opencti_order":0,"x_opencti_color":null,"stix_id":"marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9","created":"2017-01-20T00:00:00.000Z","modified":null,"update":false}},"size":240,"error":{"data":{"reason":"Execution timeout, too many concurrent call on the same entities","http_status":500,"category":"business","participantIds":["marking-definition--0e75d955-265a-59a5-8ae2-51361befc08e","marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"]},"stacktrace":["LockError: Lock timeout","at error (/opt/opencti/5.0.0/build/src/config/errors.js:8:10)","at LockTimeoutError (/opt/opencti/5.0.0/build/src/config/errors.js:87:3)","at created (/opt/opencti/5.0.0/build/src/database/middleware.js:2792:13)","at addMarkingDefinition (/opt/opencti/5.0.0/build/src/domain/markingDefinition.js:22:9)"]},"category":"APP","version":"5.0.0","level":"error","message":"API Call","timestamp":"2021-09-15T07:13:32.416Z"}
```
