### ISSUE TITLE
Sekoia connector: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/connectors#335]
## Description

On April 15th and 16th, the Sekoia connector has raised many errors, blocking any import.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 4.4.0
3. OpenCTI client: 4.4.0
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Activate Sekoia connector on the default feed 

## Expected Output

No errors

## Actual Output

```
ERROR:root:maximum recursion depth exceeded while calling a Python object
```
 
## Additional information

I have no idea under which conditions these error occur for the moment.
The connector seems to be importing normally this morning.

**Comment by SamuelHassine** [comment]
@amr-cossi,

This is certainly related to a bad STIX 2.1 bundle passed to our STIX splitter. It can be linked to an "unsual" circular dependency. The best would be to have the original STIX bundle at the origin of this error in the connector.

**Comment by Darkheir** [comment]
The issue seems to come from new a new `*_refs` field we introduced as a custom SEKOIA attribute.

The PR aims to fix it.
