### ISSUE TITLE
[All] Propose standardized optional "one-shot" scheduling for connectors

### ISSUE THREAD

**Issue by ckane** [OpenCTI-Platform/connectors#340]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Currently, most (all?) of the external import connectors are written to be persistent services running inside of individual docker containers, or as dedicated processes inside of a shared instance of some sort. They are designed to run in a forever-loop, that wakes up from sleep states periodically, based upon the definitions provided to the environment variables.

Container environments also have the concept of "tasks" that can run as ephemeral containers within a pod (k8s) or service (AWS ECS), with the execution scheduling being provided by an external trigger. In this model, the containers are not running all the time, but instead are created/started only when needed to run a "one-shot" task to completion, and then once it exits, the container is stopped and any clean-up work is done accordingly.

The current execution model for external-import connectors is incompatible with this more on-demand model. Currently, persistent containers that have to be executing all the time incur additional compute costs even when idle, as well as creating additional resource-management overhead in that a bunch more persistent instances requires more manual effort to ensure availability.

## Current Workaround

I'm manually stopping/starting instances as needed, but this is a lot of tedious effort and is also not without its own pitfalls.

## Proposed Solution

Create a new environment variable `CONNECTOR_ONESHOT` (or similar) that is by default `False` (behave as today), but can be set to `True`. This would modify the behavior in the `run()` method of a connector such that it will ignore the `*_INTERVAL` environment variables that are used to implement a scheduling delay, and will run a single cycle of the "external import" process, exiting with a `0` exit code upon completion.

IMO, the work to ensure that multiple concurrent instances/containers of a connector job don't run at the same time should be left up to the admin implementing such a system, rather than trying to solve for that within the connector code. All of the environments (AWS ECS, Azure Containers, k8s, docker swarm, etc.) have varying means of querying the service/pod/enclave to determine if a particular job is currently executing.

As a use-case, in AWS I'd envision each of the connectors having an ECS Task Definition, and then a system like [AWS Scheduled Tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html) would be responsible for executing the connectors on schedules that the admin can configure/define within AWS, rather than using the environment variables and the home-grown scheduler within OpenCTI.

The UI might also require some modifications to account for this, as well. As mentioned earlier, I can see this saving a significant amount of cost for those wanting to deploy this in AWS - especially using Fargate.

## Additional Information

AWS ECS Task Scheduler documentation: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html
Azure ACR capability: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-scheduled

**Comment by SamuelHassine** [comment]
This has been implemented in the Python library and in 3 connectors (CVE / OpenCTI / MITRE ATT&CK). We will continue the implementation in other external import connectors in the next releases.
