### ISSUE TITLE
[Question] Enrichment on demand #question

### ISSUE THREAD

**Issue by romanrusetsky** [OpenCTI-Platform/connectors#360]
I am trying to see if there is a feature available for enrichment using a connector only on demand.
For example, I have a connector to grey noise with a limited query, I want to press on an indicator/observation and run the enrichment logic.

Is there a way to do it via UI? Configuration? 

Thank you.

**Comment by SamuelHassine** [comment]
Hello @romanrusetsky,

All enrichment connectors has a parameter "auto" (true/false) to avoid automatic enrichment.

Docker (env var):
`CONNECTOR_AUTO=true` (env var, Docker)

YAML:
```connector:
  auto: true
```

Kind regards,
Samuel

**Comment by romanrusetsky** [comment]
Yea I have found that.
Let's, will there be a possibility for me to enrich the object later on-demand?
And if so, please give me an example I could not find the right code for that in the repo.   
Thank you.

**Comment by SamuelHassine** [comment]
Yes, it's possible by clicking on the enrich button in the UI

**Comment by SamuelHassine** [comment]
![image](https://user-images.githubusercontent.com/1334279/117143709-69285680-adb1-11eb-90c0-3f05250d2eeb.png)

**Comment by SamuelHassine** [comment]
On the right panel.
