### ISSUE TITLE
[AlienVault] Option to enable/disbale the creation of the relationships

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/connectors#361]
## Problem to Solve

I would like to import Alienvault Report "as-is", without all the SDOs linked together because it is not necessarily representative of the imported reports.

## Current Workaround

Import Alienvault pulses manually (stix 2.1 bundle).

## Proposed Solution

Add an option in the connector config to enable/disable the creation of the relationships.

## Additional Information

https://luatix.slack.com/archives/CHZC2D38C/p1620332254291700

**Comment by SamuelHassine** [comment]
Thanks a lot @maertv!
