### ISSUE TITLE
CVE connector enhancement

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#37]
## Problem to Solve

- All CVE since 2003
- CVE JSON format import

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

{ Please describe the solution you would like OpenCTI to provide, to solve the problem above. }

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by HugoPouliquen** [comment]
Additional Information
https://nvd.nist.gov/vuln/data-feeds
