### ISSUE TITLE
[AbuseIPdb] enormous efficiency increase by correlating relationships

### ISSUE THREAD

**Issue by intelwolf** [OpenCTI-Platform/connectors#371]
## Reduce generated message on enrichment

When using the AbuseIPdb connector a lot of messages are generated. In quite some cases the IP address to be enriched has thousands of sightings and each sighting is generating multiple calls (country, labels etc) resulting in sometimes 5 to 10 thousand calls for enriching 1 IP address

## Proposed Solution

Monitor information before calling the OpenCTI interface reduces the number of calls significantly from several thousands to a few dozen 

## Additional Information

For example for every sighting a call to the platform  for adding a label but there are only about 20 different label possibilities. In case of 3000 sightings the number of calls would be reduced by at least factor 150 (if all labels are being used).
Collecting the different labels as example:

```
            found = []
            for report in data["reports"]:
                for category in report["categories"]:
                    if category not in found:
                        found.append(category)
                        category_text = self.extract_abuse_ipdb_category(category)
                        label = self.helper.api.label.create(value=category_text)
                        self.helper.api.stix_cyber_observable.add_label(
                            id=observable_id, label_id=label["id"]
                        )

```
Sort a like thing would apply to the sightings per country. Collecting the # of sightings before calling the platform would reduce the # of calls significantly

**Comment by nor3th** [comment]
Hello @intelwolf 

Thanks for the idea. Feel free to implement this improvement yourself and submit a PR. This would help us a lot! 

Regards,

**Comment by intelwolf** [comment]
Hi @nor3th
Done that. Code may need some cleaning but its running perfectly fine in my environment with huge performance improvement (> 90%)

**Comment by nor3th** [comment]
Hey @intelwolf 

Awesome, thank you very much. If you have any other improvements for the connector or an refactoring ideas, feel free to push a PR.

Regards,
