### ISSUE TITLE
[MISP] Errors pinging the API and loading ids

### ISSUE THREAD

**Issue by Tyrell20** [OpenCTI-Platform/connectors#372]
## Description

MISP connector (version 4.5.3) sometimes fails to recover events. From the docker logs I see the following errors: 
ERROR:root:Error loading ids
ERROR:root:Error pinging the API

## Environment

OS (where OpenCTI server runs): { Red Hat Enterprise Linux Server release 7.9 (Maipo) with Docker Compose }
OpenCTI version: { OpenCTI 4.5.3 }
OpenCTI client: { Frontend }
Other environment details:
Elasticsearch 7.12.1
RabbitMQ 3.8.12
Redis 6.2.3
MinIO Latest

## Expected Output
Connector always working, as in this case:

```
INFO:root:Connector` successfully run (2 events have been processed), storing last_run
INFO:root:Reporting work update_received opencti-work--9daad8c2-5983-4fbe-a0c1-ab6e6e55d664
INFO:root:Initiate work for 5ed76dda-9a94-4dcd-b372-112c0a1ea115
INFO:root:Connector last run: 2021-04-05 09:43:12
```

## Actual Output
**On GUI, import status always in progress:**
![screenshot 583](https://user-images.githubusercontent.com/64137969/119946298-c53c6000-bf96-11eb-9426-e78cfe5f6eae.jpg)

**On docker log:**
```
ERROR:root:Error loading ids
ERROR:root:Error pinging the API
ERROR:root:Error loading ids
ERROR:root:Error pinging the API
ERROR:root:API Ping back to normal
ERROR:root:Error loading ids
ERROR:root:Error pinging the API
ERROR:root:API Ping back to normal
ERROR:root:Error loading ids
ERROR:root:Error pinging the API
ERROR:root:API Ping back to normal
```
 
## Additional information

On MISP side (on var/www/MISP/app/tmp/logs/error.log) it seems that I have no errors related to the OpenCTI query.

The DB schema seems OK and the MISP workers are all running.

**Comment by nor3th** [comment]
The `Error loading ids` entry usually comes up when there's an issue with the backend database. What do the elastic logs and the error logs say (if you click on the red error button)?

**Comment by Tyrell20** [comment]
![screenshot 609](https://user-images.githubusercontent.com/64137969/121498040-53273a80-c9dc-11eb-9f1c-da3a9d8d6a66.jpg)

![screenshot 610](https://user-images.githubusercontent.com/64137969/121498047-54f0fe00-c9dc-11eb-97ab-70e700e950c0.jpg)

**Comment by nor3th** [comment]
Are there any relevant log entries in the elastic instance? docker logs -f opencti_elasticsearch_1

**Comment by Tyrell20** [comment]
Hello,
attached a sample of elasticsearch docker logs. I don't see any error, only a few of Warning.
[docker_elasticsearch_1.log](https://github.com/OpenCTI-Platform/connectors/files/6636685/docker_elasticsearch_1.log)


In the meantime, on the MISP docker log:
ERROR:root:Error pinging the API
ERROR:root:API Ping back to normal
ERROR:root:Error loading ids
ERROR:root:Error pinging the API
ERROR:root:Error loading ids
ERROR:root:Error pinging the API
ERROR:root:API Ping back to normal
ERROR:root:Error pinging the API
ERROR:root:API Ping back to normal

Thank you

**Comment by richard-julien** [comment]
Please provide the platform error logs. Error reported in the UI doesnt display all the information

**Comment by Tyrell20** [comment]
Hello,
could you please indicate me in details what kind of logs you need and where I can retrieve them?
Thank you

**Comment by richard-julien** [comment]
You can get the logs of your container with the "docker logs" command.
You can also ssh your container and get the error.log files in /logs directory of opencti.

**Comment by Tyrell20** [comment]
Attached the logs of opencti platform docker.

[docker_opencti_1.log](https://github.com/OpenCTI-Platform/connectors/files/6648330/docker_opencti_1.log)

**Comment by richard-julien** [comment]
Your logs is difficult to read.

The main problem I see inside is the constant fail of creation of the marking marking-definition--0e75d955-265a-59a5-8ae2-51361befc08e because of LockError: Lock timeout.

The best in this case is to:
- Stop all your connectors
- Check that you have no connector sharing the same UUID
- Configure each connector on a different user (one connector = one associated user)
- Start your connector one by one and monitor the error logs to find the culprit.

**Comment by Tyrell20** [comment]
I checked the UUID of all the connectors and they are different.
How can I configure each connector on a different user?

Thank you

**Comment by richard-julien** [comment]
You need to create a user for each connector, get the token of this user and use it for your connector.

**Comment by Tyrell20** [comment]
I use these parameters on docker-compose.yml:

      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID} # Valid UUIDv4

The OPENCTI_TOKEN is the same for all the connectors, the CONNECTOR_ID is different (double checked) for all the connectors.
Do you mean I need to change this parameter, by using a different user for each connector?

Thank you

**Comment by richard-julien** [comment]
Its better to have a different OPENCTI_TOKEN (different user) for each connector.
It will be easiest with that to know the connector responsible for the action in the logs

**Comment by Tyrell20** [comment]
We tried to use a different OPENCTI_TOKEN for each connector, by setting them in .env file but in this way all the connectors return this error:

`INFO:root:Listing Threat-Actors with filters null.
ERROR:root:You must be logged in to do this.
Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 1514, in <module>
    mispConnector = Misp()
  File "/opt/opencti-connector-misp/misp.py", line 87, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 409, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 141, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...`

**Comment by nor3th** [comment]
Did you register different users per connector and then using their API Tokens? Based on your logs, either there is something wrong with the network connection to OpenCTI or the TOKENs are not recognized by OpenCTI
