### ISSUE TITLE
Allow CrowdStrike to decrease the score of observables that have a certain label(s)

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/connectors#379]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

By default, all observables imported by the CrowdStrike connector have a pre-defined score value (usually 50).
It can be useful tough, depending on the label of the observables, to allow the score of the observable to be lower than 50.
This will map for a use case where only observables with a score lower than 50 are used by other systems. 

## Current Workaround

Manually decrease the score of those observables that have a specific label.

## Proposed Solution

Introduce 2 new parameters in the configuration of Crowdstrike.
The 2 paramaters to be: 
```
- CROWDSTRIKE_LABELS_SET_LOW_SCORE_LABELS=(multiple lables separated by commas)
- CROWDSTRIKE_LABELS_LOW_SCORE_VALUE=(40)
```

- If the parameters are not definded (used), there should be no change in the way the connector works. 
- If the parameters are defined (used), the observables that have a label that matches any of the values indicated in ```CROWDSTRIKE_LABELS_SET_LOW_SCORE_LABELS``` should automatically have their score decreased to the value indicated by the ```CROWDSTRIKE_LABELS_LOW_SCORE_VALUE```

Ex: Observables with the label "maliciousconfidence/low" to have the score decreased to 40.

## Additional Information

-

**Comment by maertv** [comment]
I think that this can be closed. If there are any problems, then please open a new issue.
