### ISSUE TITLE
cleaning-up bad workers - 0 "In progress" status - delete not working

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/connectors#387]
OS: Ubuntu 20.04 TLS
OpenCTI 4.5.4

AlienVault's worker is building-up. I stop the connector and attempted to clean some 0 "In progress" status but it seems the delete is not working
![image](https://user-images.githubusercontent.com/20463433/121365100-5bad4180-c906-11eb-800f-7032fec06b52.png)

**Comment by nor3th** [comment]
Seems like some bug or issue with the processing queue, rather than the connector itself... Can you move that issue to the OpenCTI platform project? https://github.com/OpenCTI-Platform/opencti

**Comment by Ken-Abruzzi** [comment]
I'm also confronted with this problem many times. Sometimes, the progress bar stops there for days when only 1 operation is left yet. Sometimes, the progress bar gets stuck for days but the "total number of operations" is zero.

**Comment by SamuelHassine** [comment]
To follow this issue this is here: https://github.com/OpenCTI-Platform/opencti/issues/1523.

Closing this one.
