### ISSUE TITLE
cve and ipinfo connectors  - ERRR:root:You are not allowed to do this.

### ISSUE THREAD

**Issue by krelac-bit** [OpenCTI-Platform/connectors#39]
Hi,

everything else is up and running fine however cvs and ipinfo connectors seem not to be working. Configs were copied over from github and added to docker-compose.yml as below.

docker-compose.yml
....
  connector-ipinfo:
    image: opencti/connector-ipinfo:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=xxxxxxxxxxxxxxxx
      - CONNECTOR_ID=xxxxxxxxxxxxxxxxx
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=IpInfo
      - CONNECTOR_SCOPE='ipv4-addr'
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - IPINFO_TOKEN=XXXXXXXXXXXXX
      - HTTP_PROXY=http://x.x.x.x:3128/
      - HTTPS_PROXY=http://x.x.x.x:3128/
      - NO_PROXY=localhost,opencti,grakn,127.0.0.1
    restart: always
 connector-cve:
    image: opencti/connector-cve:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=xxxxxxxxxxxxxxxx
      - CONNECTOR_ID=xxxxxxxxxxxxxxxx
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Common Vulnerabilities and Exposures
      - CONNECTOR_SCOPE=identity,vulnerability
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json.gz
      - CVE_INTERVAL=1 # Days
      - HTTP_PROXY=http://x.x.x.x:3128/
      - HTTPS_PROXY=http://x.x.x.x:3128/
      - NO_PROXY=localhost,opencti,grakn,127.0.0.1
    restart: always

Any idea?
thx

**Comment by krelac-bit** [comment]
Creating opencti_connector-ipinfo_1 ... done
Attaching to opencti_connector-ipinfo_1
connector-ipinfo_1            | INFO:root:Listing Threat-Actors with filters null.
connector-ipinfo_1            | ERROR:root:You are not allowed to do this.
connector-ipinfo_1            | Traceback (most recent call last):
connector-ipinfo_1            |   File "ipinfo.py", line 81, in <module>
connector-ipinfo_1            |     ipInfoInstance = IpInfoConnector()
connector-ipinfo_1            |   File "ipinfo.py", line 16, in __init__
connector-ipinfo_1            |     self.helper = OpenCTIConnectorHelper(config)
connector-ipinfo_1            |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 125, in __init__
connector-ipinfo_1            |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token, self.log_level)
connector-ipinfo_1            |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 102, in __init__
connector-ipinfo_1            |     raise ValueError('OpenCTI API seems down')
connector-ipinfo_1            | ValueError: OpenCTI API seems down

**Comment by SamuelHassine** [comment]
Hello @krelac-bit. Sorry for the delay of our answer. The message `You are not allowed to do this.` indicates that the token provided in the connector config is not correct. Are you sure it is the equivalent to the admin token in the main OpenCTI application?

**Comment by SamuelHassine** [comment]
I close this issue due to inactivity. Please feel free to re-open it if you still encounter problem.
