### ISSUE TITLE
[MITRE]URLOPEN error: Address not available

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#390]
Hello! @richard-julien 
## Description
The connector stops working for many days, even if I reset the connector, reset the container, re-install the container, reboot the container, roll back to the last version 4.5.3, and reboot the host server.
![image](https://user-images.githubusercontent.com/68931768/121626855-ade38500-ca22-11eb-9011-6d84c300e1bd.png)
The log of the container warns many times of "urlopen error: address not availabe"
![image](https://user-images.githubusercontent.com/68931768/121626658-5218fc00-ca22-11eb-9c4d-abcd3ad3b5bc.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.4
3. OpenCTI client: docker, python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I installed the OpenCTI in a virtual machine which connected to the Internet using the bridged mode.
2. The connector ran well for many days since I updated the OpenCTI to version 4.5.4.
3. Someday the network didn't work, and I had to change the virtual machine's network from bridged mode to NAT mode.
4. After this change, other connectors such as alienvault, cybercrime tracker, and vx vault run well.

## Expected Output

Every time I change the yaml file and then run "docker-compose up -d", or I just click the "reset the connector state" button in the web page, the connector will start a new work progress.

## Actual Output

The connector doesn't start any work progress since the network's breakage.
 
## Additional information

I try to visit the URL in a web explorer, and it can show the content.
![image](https://user-images.githubusercontent.com/68931768/121628371-8c37cd00-ca25-11eb-9359-7c14af5bf5f3.png)
And I get into the container to find whether it is connected to the Internet by using "wget", and the container can visit "github.com"
![image](https://user-images.githubusercontent.com/68931768/121626778-8d1b2f80-ca22-11eb-9a8e-e560d188681c.png)
But other tries fail.
![image](https://user-images.githubusercontent.com/68931768/121628606-f9e3f900-ca25-11eb-9f43-2cd6072670e5.png)

Thanks for your help!

**Comment by richard-julien** [comment]
Hi @Ken-Abruzzi ,

Looks like you have a DNS resolution issue in your container.
Unfortunately for me this kind of error is not related to OCTI or the connector. Its a VM (maybe docker) config network problem.
On my side I have 0 experience on VM. @SamuelHassine any help on that? 
You can also try to ask for other users of OCTI using the VM the kind of config they used.

**Comment by Ken-Abruzzi** [comment]
@richard-julien Thanks for your advice. It's very strange because other connectors can work well, so I think it might not be the problem of the virtual machine. And I try to use the "wget" tool in the container of connector-mitre to get some website's html files, and the files downloaded are correct. Can it still be the problem of DNS resolution?

**Comment by richard-julien** [comment]
Can you try to get the entreprise-attack in raw.githbusercontent in another container? I think it will fail the same way because looks like the DNS resolution for this domain is not correctly done.

**Comment by Ken-Abruzzi** [comment]
I cannot visit this url "https://raw.githubusercontent.com" from the web explorer.
![image](https://user-images.githubusercontent.com/68931768/121655851-63c2c980-ca4b-11eb-9a06-51e632cb039b.png)
But I can visit "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json", and "https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json", and "https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json" using the web explorer. 
![image](https://user-images.githubusercontent.com/68931768/121656402-ea77a680-ca4b-11eb-95bb-8d4ee628a2eb.png)

 And I ping "https://raw.githubusercontent.com" in the container, and the right IP address cannot be resolved:
![image](https://user-images.githubusercontent.com/68931768/121656264-c74cf700-ca4b-11eb-90cb-5c6da7264baa.png)

**Comment by Ken-Abruzzi** [comment]
@richard-julien As you say, I ping this domain name in other containers which work well, the failures exist the same way. So may it  be the problem with the website?

**Comment by richard-julien** [comment]
If you have access in the VM but not in containers it looks like a DNS problem inside docker containers.
I really dont know why your containers have problem to resolve raw.github...
According to documentation https://docs.docker.com/config/containers/container-networking/#dns-services you can eventually force a specific dns server or try to fix the resolution in the /etc/resolv.conf file.

**Comment by Ken-Abruzzi** [comment]
@richard-julien Thanks for your advice. It is just the problem with the DNS server. I appoint some DNS servers in my virtual machine. And the problem is solved.
