### ISSUE TITLE
[Synchronizer] Add OpenCTI to OpenCTI synchronization filters 

### ISSUE THREAD

**Issue by Kevingaudi** [OpenCTI-Platform/connectors#398]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

A wide range of filter choices for the OpenCTI instance to OpenCTI instance synchronization connector

**Comment by SamuelHassine** [comment]
Thanks for this issue @Kevingaudi, the synchronization connector will be fully rewritten and tested to work 100% in 5.0.0, also using filters.
