### ISSUE TITLE
MISP event creation date and modification date are not correct on openCTI platform 

### ISSUE THREAD

**Issue by Deventual** [OpenCTI-Platform/connectors#403]
## Description

Creation date and modification date of MISP events gets wrong values after ingesting a report. it gets the openCTI report creation date instead of MISP creation date and modification date)

## Environment

1. OS (where OpenCTI server runs): { ubuntu 18 }
2. OpenCTI version: { e.g. OpenCTI 4.5.3 }
3. OpenCTI client: { frontend }

## Expected Output

Creation date and modification dates should get the dates of the MISP event.

## Actual Output

Creation date and modification date gets the date of the creation date of this plaform (openCTI).

**Comment by nor3th** [comment]
Could you please try again with OpenCTI 4.5.5? This issue should have been fixed with https://github.com/OpenCTI-Platform/connectors/pull/377

**Comment by Deventual** [comment]
> Could you please try again with OpenCTI 4.5.5? This issue should have been fixed with #377

Hi, I have checked the code for the connector in version 4.5.5 and it's not using the right element for the event creation date,
I fixed it in this pull request:
https://github.com/OpenCTI-Platform/connectors/pull/405

**Comment by nor3th** [comment]
Great, thanks for the PR. Could you please fix the format check error? That can be done running `flake8 --ignore=E,W && black .
` in the respective folder.

**Comment by Deventual** [comment]
It seems that the platform doesn't use the created and the modified variable.
The only variable that in used by the system is the published.
I edited the PR with the fix and also with the flake format.

**Comment by nor3th** [comment]
And the `timestamp` value only shows the timestamp of the API request if I understood the issue correctly?

**Comment by Deventual** [comment]
No,
The timestamp shows the latest change in the MISP event (event publish).
Btw 4.5.5 is not consuming most of the events (also 4.5.4), so I returned
to 4.5.3 and committed the changes in my pull request to the docker image
on my instance and now it's working like a charm.
