### ISSUE TITLE
[Abuse.ch URLhaus][Problem]The connector shows "urlopen error [ERRNO 104]: connection reset by peer"

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#404]
Hello! @SamuelHassine @ahmadmkhan1   I appreciate your efforts very much! 
## Description
The urlhaus connector worked well for the first time after I deployed the container.
![image](https://user-images.githubusercontent.com/68931768/123397609-149e8d80-d54f-11eb-9f68-150f22c5d455.png)
But in the following days, the connector failed to import any data, even if I reset the connector in the OpenCTI web browser, or re-deploy the container using the yaml file. I examine the container's log, and I find the connector actually tried to start the fetching progresses for many times, but the progresses were stopped due to "urlopen error [ERRNO 104]: connection reset by peer"
![image](https://user-images.githubusercontent.com/68931768/123398384-ebcac800-d54f-11eb-97c4-509573dbf09f.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
 
## Additional information

I try to visit the URL given in the docker-compose.yml file in a web browser, and it can show the content.
![image](https://user-images.githubusercontent.com/68931768/123399197-cc806a80-d550-11eb-9e96-dc73c6d45ff7.png)
And I come into the container to find whether the domain name can be reached using ping, and it shows that the domain name can be resolved and the web server can be reached.
![image](https://user-images.githubusercontent.com/68931768/123399630-53354780-d551-11eb-874e-744521448f72.png)
Then I try to fetch the web page files using the "wget", but it fails.
![image](https://user-images.githubusercontent.com/68931768/123400282-0dc54a00-d552-11eb-828a-b57246cb7737.png)
I search this problem in "stackoverflow", and someone says the server limits the amount of requests per timeunit (hour, day, second) for a security concern. 
I check the python source code of this connector,  and I find the urlopen function is called, and time.sleep function is also called , , maybe to reduce the request frequency?
![image](https://user-images.githubusercontent.com/68931768/123401298-1d915e00-d553-11eb-973a-ba0262f406b5.png)
![image](https://user-images.githubusercontent.com/68931768/123401835-a14b4a80-d553-11eb-8413-16599c4857b7.png)

So how can I solve this problem? Thanks for your help!

**Comment by nor3th** [comment]
The connector has a 3 day interval by default. I think that this should be enough to not trigger any automated blocking mechanisms
https://github.com/OpenCTI-Platform/connectors/blob/eb14db98d8e1c434120d8f5417ad0588702bdd21/urlhaus/docker-compose.yml#L18

If the request succeeds using the browser, but fails when using wget I assume that URLhaus might block some user agents (random guess). Maybe try running your connector from another IP to see if the error is IP independent?

**Comment by Ken-Abruzzi** [comment]
@nor3th Hello! Thanks for your advice. I mention that "The server limits the amount of requests per timeunit". I think maybe the requests in one miniute are too much to exceed the server's limits. And I will try to change my IP to see whether it is successful.

**Comment by Ken-Abruzzi** [comment]
@nor3th Hello! After I reboot my os, the connector return to normal. The [ERRNO 104] error disappears. It's so strange.

**Comment by nor3th** [comment]
Ok, maybe it was also just a network issue from your host side. You could maybe also try to do a `traceroute` next time to see where the connection ends.

**Comment by Ken-Abruzzi** [comment]
I guess I know what cause the problem. This environmental variable should be set as the instruction! It should be an integer larger than 1. If it is set as 1, it will continuously fetching information from the server so that the server refuse the connection. 
![image](https://user-images.githubusercontent.com/68931768/133578999-f81faca1-e094-4905-a750-2cafd6e2d90f.png)
This environmental variable can lead to the misunderstanding that if it is set as "n", the connector will start new work in every "n" days. But in fact, the connector will start new work in every "n-1" days. The same situation is with the connectors [vxvault] and [mitre].

**Comment by Ken-Abruzzi** [comment]
The connector has worked well for more than a week. Unfortunately, the same error appears again! 
![image](https://user-images.githubusercontent.com/68931768/134316580-7db37834-b970-4852-8e98-59f3c8ff6f3f.png)
I use "docker stop docker_connector-urlhaus_1", then "docker rm docker_connector-urlhaus_1" and then building it up again with "docker-compose up -d". But the same error occurs again.
