### ISSUE TITLE
[Malpedia] Refactor the connector to use stix bundle

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#406]
Hello! @SamuelHassine 
## Description
The connector ran for the first time after I deploy it but no progress bar is shown in the web page.
![image](https://user-images.githubusercontent.com/68931768/123575120-93790d80-d77d-11eb-9cba-72f09b6209ab.png)
And I assure that the connector actually ran via reading the log file
![image](https://user-images.githubusercontent.com/68931768/123575298-f074c380-d77d-11eb-88a8-17ef1cd24929.png)
And I can also prove it by find out the entities created by author "malpedia", the results show that these entities are created when  I first ran the connector.
![image](https://user-images.githubusercontent.com/68931768/123577470-59f5d180-d780-11eb-81ff-94e7b41ffda6.png)
After that, the connector has never run for more than 10 days.

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I installed the connector using docker-compose.
2. I leave the MALPEDIA_AUTH_KEY empty. 
![image](https://user-images.githubusercontent.com/68931768/123598808-64749300-d7a1-11eb-8f83-8430b8a9ec2a.png)

## Expected Output

1. Every time the connector start a new work progress, there should be a progress bar in the web page, such as below:
![image](https://user-images.githubusercontent.com/68931768/123577689-cffa3880-d780-11eb-9865-3b5a044ce6bd.png)
2. The progress should start every 172800 seconds as I set up in the docker-compose.yml file.

## Actual Output

1. No progress bar is shown even if the connector ran successfully once.
2. The connector never runs again.
 
## Additional information

At the end of the first progress, the log shows some errors:
![image](https://user-images.githubusercontent.com/68931768/123578144-a5f54600-d781-11eb-9e9e-b64f74be5657.png)
The docker status is running:
![image](https://user-images.githubusercontent.com/68931768/123578350-1dc37080-d782-11eb-8db7-cb514d46007f.png)

Thanks for your help!

**Comment by Ken-Abruzzi** [comment]
@rhaist Hello! Thanks for your attention. I click the "reset the connector state", nothing happens.
![image](https://user-images.githubusercontent.com/68931768/123887757-86375c80-d8fe-11eb-88d9-446a408b2bcf.png)
I change "MALPEDIA_INTERVAL_SEC" from 179200 to 216000 in the docker-compose.yml file and then deploy the container again. The connector begins to work again. I change the docker-compose.yml file only to update the container. Actually, the "MALPEDIA_INTERVAL_SEC" field does not matter.
![image](https://user-images.githubusercontent.com/68931768/123887861-b7b02800-d8fe-11eb-8162-183250a74cab.png)
You can see that the connector imports new data today (June 29). The last time the connector worked is on June 15.
![image](https://user-images.githubusercontent.com/68931768/123887921-da424100-d8fe-11eb-9a9f-ffbac38b546a.png)
Still no progress bars show on the web page.
![image](https://user-images.githubusercontent.com/68931768/123888146-4d4bb780-d8ff-11eb-8dbd-8aa8fc4d73f3.png)

**Comment by Ken-Abruzzi** [comment]
@rhaist Hello! I find that the read and write operations show effective numbers when the malpedia connector runs.
![image](https://user-images.githubusercontent.com/68931768/123893799-8c7f0600-d909-11eb-9577-b6eef7aaa8c5.png)

**Comment by rhaist** [comment]
Hi @Ken-Abruzz,
Thanks for the detailed analysis. Much appreciated.

The Malpedia connector is from a time where the work API didn't exist yet in OpenCTI, thus no progress in the UI currently.

I am waiting for the STIX output to be finished by the Malpedia team before I work on the connector again and fix this.

I'll update this issue as soon as there's news.

**Comment by nor3th** [comment]
Hey @Ken-Abruzzi 

Based on your other github issue, it seems that this issue is connector independent. Try either doing a `docker restart` or to entirely remove the docker container `docker stop`, `docker rm` and `docker-compose up -d` again. Does this help?

Is the Malpedia connector or the urlhaus connector the problem in your current issue?

Regards,

**Comment by Ken-Abruzzi** [comment]
@nor3th Hello! I'm sorry to make a mistake in the above comment about regarding "urlhaus". But both urlhaus and malpedia share the same problem.

**Comment by nor3th** [comment]
Does simply doing a `docker restart` or `stop` as described above also help?

**Comment by SamuelHassine** [comment]
@rhaist any chance to have this connector updated to generate a bundle?

**Comment by Ken-Abruzzi** [comment]
The problem with "no progress bar" has been explained in #479 .
And now I update the connector to version 5.0.0. The error recorded in the log is not "Failed to establish a new connection [ERRNO 111]: connection refused". The new error is "Failed to establish a new connection: [Errno -3] Try again". This error is mentioned in #467 . And it is promised to be solved in a new version.
![image](https://user-images.githubusercontent.com/68931768/133871450-fe387df1-59d7-4295-b504-d309a3847040.png)
But the timer stops when there is 157890 seconds left, and hence no new work starts.
![image](https://user-images.githubusercontent.com/68931768/133871487-23854d4e-1f9a-4551-bb3d-5ecd7db9c64e.png)

**Comment by Ken-Abruzzi** [comment]
When I reboot my computer, the connector runs again. But it is stopped by a new error:
![image](https://user-images.githubusercontent.com/68931768/134310005-a9fc5ae6-73ab-4243-9277-1a954ebd5134.png)

**Comment by SamuelHassine** [comment]
@rhaist any update for this connector?

**Comment by rhaist** [comment]
Malpedia wanted to do an update this week. Will update the connector right afterwards. Should not take long.

**Comment by SamuelHassine** [comment]
@rhaist Any news on the connector?

**Comment by SamuelHassine** [comment]
@Jipegien @nino-filigran @Megafredo @helene-nguyen we need a full refactor of this connector to generate STIX bundles / works instead of querying API / send stix bundles without works.

**Comment by Jipegien** [comment]
@helene-nguyen @Megafredo to do after other rework on enrichement connectors instead of VMRay one. thanks!

**Comment by SamuelHassine** [comment]
@Megafredo @Jipegien, just FYI, since confidence level modifications this connector is not working anymore which makes urgent to upgrade it to STIX bundle generation.

Short story long: as the connector is trying to directly update things in the platform it crashes everytime it has an insufficent confidence level to do so...
