### ISSUE TITLE
[Import-Report] Create indicators from Observables Failing

### ISSUE THREAD

**Issue by samjackson200** [OpenCTI-Platform/connectors#407]
## Description

After commit 23011709b2e1478c9d49b6cf2b03153edcba3c1b (Added 3rd Party Library support and IPv6/URL support #382) the automatic creation of Indicators from observables seems to be failing, with the import_report_create_indicator set to true. Previous versions (up to release 4.5.4) worked well.

## Environment

1. Ubuntu 20.04 LTS
2. OpenCTI 4.5.5
3. Python Client (connector/worker)
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Using basic OpenCTI docker-compose.yml environment with minimum settings needed to run
2. Import-Report settings: connector-auto: false, only_contextual: false, import_report_create_indicator: true
3. Upload report with ipv4 observables and launch import of file
4. Observables are imported but indicators are not despite settings

## Expected Output

Indicators are created from imported observables

## Actual Output

Only observables are created, no indicators are created.
 
## Additional information

None.

**Comment by nor3th** [comment]
Hello @samjackson200 

Thank you for reporting this. I just noticed that I used the wrong argument. Will fix that right now.
