### ISSUE TITLE
[Import-Report] Not recognising defanged ipv4 & ipv6 addresses.

### ISSUE THREAD

**Issue by samjackson200** [OpenCTI-Platform/connectors#408]
## Description

Defanged ip addresses inside pdf reports are not recognised, re-fanged, and created as observables, e.g. 192[.]168[.]0[.]1. This issue has only been since commit https://github.com/OpenCTI-Platform/connectors/commit/23011709b2e1478c9d49b6cf2b03153edcba3c1b (Added 3rd Party Library support and IPv6/URL support https://github.com/OpenCTI-Platform/connectors/pull/382) 

## Environment

 1. Ubuntu 20.04 LTS
 2. OpenCTI 4.5.5
 3. Python Client (connector/worker)
 4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Using basic OpenCTI docker-compose.yml environment with minimum settings needed to run
2. Import-Report settings: connector-auto: false, only_contextual: false, import_report_create_indicator: true
3. Upload report with ipv4 and ipv6 observables and a mix of defanged and normal addresses and launch import of file
4. Normal addresses are imported but defanged ones are ignored.

## Expected Output

Defanged addresses are extracted, re-fanged, and created as observables.

## Actual Output

Defanged addresses are completely ignored by parser.
 
## Additional information

None

**Comment by nor3th** [comment]
Hello @samjackson200 

Thanks a lot for this bug report. I'll fix this issue for the next release. I have to refactor a bit to properly defang the text in the first place.
