### ISSUE TITLE
MISP Connector response 0 event to import

### ISSUE THREAD

**Issue by realzacharycheng** [OpenCTI-Platform/connectors#414]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

The MISP connector pull 0 events to import into OpenCTI due to the timestamp is not set correctly.

## Environment

1.AWS ubuntu-bionic-18.04-amd64-server
2.OpenCTI Version 4.5.3 & 4.5.5
3.OpenCTI client: frontend
4.Other environment details: OpenCTI is using docker to install & MISP connector version : opencti/connector-misp:4.5.3 & opencti/connector-misp:4.5.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

All the events with the specific tag in MISP are selected and import into OpenCTI

## Actual Output

Due to the timestamp configuration error, the connector cannot get the time value I config in the docker-compose.yml file 
The earliest timestamp is the time that I started the docker to run instead of the MISP_IMPORT_FROM_DATE
 
<img width="604" alt="Screenshot 2021-07-06 at 4 40 08 PM" src="https://user-images.githubusercontent.com/79446411/124569856-e8e9a480-de78-11eb-8771-054819a22413.png">

## Additional information

{ Any additional information, including logs or screenshots if you have any. }
<img width="1737" alt="Screenshot 2021-07-06 at 4 34 11 PM" src="https://user-images.githubusercontent.com/79446411/124569442-898b9480-de78-11eb-9547-55778564ceee.png">

It was successfully running the API "GET /attributes/describeTypes.json" 

I tried to change the time value and ran again on terminal and it was successfully

**Comment by bLackCat-79** [comment]
Did it is fixed? If yes, how did you do it? I have the same problem

**Comment by nor3th** [comment]
Hello @realzacharycheng 

If I understood your issue correctly, the MISP connector doesn't properly recognize the `MISP_IMPORT_FROM_DATE` value and thus doesn't import the MISP reports?

Can you please either reset the connector in the OpenCTI connector page or remove the MISP connector and launch a new one. After doing that please post the output of the MISP connector with the pymisp details as shown in your screenshot.

Thanks

**Comment by realzacharycheng** [comment]
> Hello @realzacharycheng
> 
> If I understood your issue correctly, the MISP connector doesn't properly recognize the `MISP_IMPORT_FROM_DATE` value and thus doesn't import the MISP reports?
> 
> Can you please either reset the connector in the OpenCTI connector page or remove the MISP connector and launch a new one. After doing that please post the output of the MISP connector with the pymisp details as shown in your screenshot.
> 
> Thanks

@bLackCat-79 @nor3th 
I tried and this solution did make it works. Thanks. But it seems like it required to be restarted whenever it is stopped.
