### ISSUE TITLE
MISP pika errors?

### ISSUE THREAD

**Issue by bLackCat-79** [OpenCTI-Platform/connectors#415]
Can anyone tell me what this means? 
I run misp connector via docker-compose up

my docker-compose.yml file:

version: '3'
services:
  connector-misp:
    image: opencti/connector-misp:4.5.5
    environment:
      - OPENCTI_URL=http://192.168.1.15:8080
      - OPENCTI_TOKEN=Thesameasmyadmintokeninmyopenctidocker-compose.ymlfile
      - CONNECTOR_ID=justarandomuuid4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=50 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://192.168.1.15 # Required
      - MISP_REFERENCE_URL= # Optional, will be used to create external reference to MISP event (default is "url")
      - MISP_KEY=mymispauthtokenwhatIwillnotpastehere # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_DATETIME_ATTRIBUTE=timestamp # Required, filter to be used in query for new MISP events
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_CREATE_OBJECT_OBSERVABLES=True # Required, create text observables for MISP objects
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      #- MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      #- MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      #- MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
      #- MISP_IMPORT_CREATOR_ORGS= # Optional, only import events created by this ORG (put the identifier here)
      #- MISP_IMPORT_OWNER_ORGS= # Optional, only import events owned by this ORG (put the identifier here)
      #- MISP_IMPORT_DISTRIBUTION_LEVELS=0,1,2,3 # Optional, only import events with the given distribution levels
      #- MISP_IMPORT_THREAT_LEVELS=1,2,3,4 # Optional only import events with the given threat levels
      - MISP_IMPORT_ONLY_PUBLISHED=False
      #- MISP_IMPORT_WITH_ATTACHMENTS=False # Optional, try to import a PDF file from the attachment attribute
      #- MISP_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always

Attaching to misp_connector-misp_1
connector-misp_1  | INFO:root:Listing Threat-Actors with filters null.
connector-misp_1  | INFO:root:Connector registered with ID: 6abc5fde-1e5e-4b74-8a17-f50de5104723
connector-misp_1  | INFO:root:Starting ping alive thread
connector-misp_1  | INFO:root:Initiate work for 6abc5fde-1e5e-4b74-8a17-f50de5104723
connector-misp_1  | INFO:root:Connector has never run
connector-misp_1  | INFO:root:Fetching MISP events with args: {"limit": 50, "page": 1}
connector-misp_1  | INFO:root:MISP returned 50 events.
connector-misp_1  | INFO:root:Processing event 5464c1d9-3d78-434d-a936-51e4950d210b
connector-misp_1  | INFO:root:Sending event STIX2 bundle
connector-misp_1  | INFO:root:Update action expectations opencti-work--122d2626-3616-410e-a1a7-77f17faace67 - 269
connector-misp_1  | ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(-3, 'Try again')
connector-misp_1  | ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(-3, 'Try again').
connector-misp_1  | ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-3, 'Try again'); first exception - None.
connector-misp_1  | ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-3, 'Try again'); first exception - None
connector-misp_1  | ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-3, 'Try again'); first exception - None
connector-misp_1  | ERROR:pika.adapters.blocking_connection:Error in _create_connection().
connector-misp_1  | Traceback (most recent call last):
connector-misp_1  |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
connector-misp_1  |     raise self._reap_last_connection_workflow_error(error)
connector-misp_1  |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
connector-misp_1  |     result = socket.getaddrinfo(self._host, self._port, self._family,
connector-misp_1  |   File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
connector-misp_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
connector-misp_1  | socket.gaierror: [Errno -3] Try again
connector-misp_1  | Traceback (most recent call last):
connector-misp_1  |   File "/opt/opencti-connector-misp/misp.py", line 1515, in <module>
connector-misp_1  |     mispConnector.run()
connector-misp_1  |   File "/opt/opencti-connector-misp/misp.py", line 253, in run
connector-misp_1  |     self.process_events(work_id, events)
connector-misp_1  |   File "/opt/opencti-connector-misp/misp.py", line 630, in process_events
connector-misp_1  |     self.helper.send_stix2_bundle(
connector-misp_1  |   File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 569, in send_stix2_bundle
connector-misp_1  |     pika_connection = pika.BlockingConnection(pika_parameters)
connector-misp_1  |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
connector-misp_1  |     self._impl = self._create_connection(parameters, _impl_class)
connector-misp_1  |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
connector-misp_1  |     raise self._reap_last_connection_workflow_error(error)
connector-misp_1  |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
connector-misp_1  |     result = socket.getaddrinfo(self._host, self._port, self._family,
connector-misp_1  |   File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
connector-misp_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
connector-misp_1  | socket.gaierror: [Errno -3] Try again

**Comment by nor3th** [comment]
Hello @bLackCat-79 

It seems like the MISP connector container is unable to connect to the RabbitMQ container. Seems more like a network issue. Maybe log into the MISP container and try pinging the RabbitMQ container.

**Comment by bLackCat-79** [comment]
Ok, I added the misp connector to the docker-compose.yml file of opencti and then it works.
