### ISSUE TITLE
[BUG][ALIENVAULT][4.5.5] Workers stop processing AV Tasks after a few hours 

### ISSUE THREAD

**Issue by mwatermolen** [OpenCTI-Platform/connectors#418]
## Description

After a few min to hours the openCTI workers will stop processing Alienvault tasks

## Environment

1. Ubuntu 18.04 - Running on Kubernetes (RKE)
2. OpenCTI Version: 4.5.5
3. OpenCTI client: Frontend / Backend
4. Other environment details: Running in Kubernetes

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set the Alienvault connector to import
2. Wait 2-4 hours and check rabbitmq for the stairs of doom
3. :(

## Expected Output

Tasks processed at a consistent pace

## Actual Output

tasks start to stall and pile up on Alienvault only

![image](https://user-images.githubusercontent.com/73605619/125959568-3930a48a-7618-4a17-b404-99c882a429f3.png)

**Comment by maertv** [comment]
Is it a connector issue or is it a worker issue?

Are there any errors in the AlienVault connector log?
Are there any errors related to this in the worker log?

**Comment by mwatermolen** [comment]
@maertv sorry for the delayed response, I have not seen errors in either

Alienvault last run:
```
NFO:root:Bundle has been sent
INFO:root:Bundle has been sent
INFO:pika.channel:Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f97a88b96d0> params=<ConnectionParameters host=opencti-4-1626356600-rabbitmq port=5672 virtual_host=/ ssl=False>>>
INFO:pika.channel:Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f97a88b96d0> params=<ConnectionParameters host=opencti-4-1626356600-rabbitmq port=5672 virtual_host=/ ssl=False>>>
INFO:root:Pulse importer completed (imported: 8, failed: 0, total: 8), latest fetch 2021-07-16 17:00:16.952000
INFO:root:Storing new state: {'latest_pulse_timestamp': '2021-07-16T17:00:16.952000', 'last_run': 1626454889}
INFO:root:Reporting work update_received opencti-work--2590dc4e-09d5-4384-83eb-60c12ad64886
INFO:root:State stored, next run in: 10800 seconds
INFO:root:Running AlienVault connector...
INFO:root:Loaded state: {'latest_pulse_timestamp': '2021-07-16T17:00:16.952000', 'last_run': 1626454889}
INFO:root:Connector will not run, next run in: 10740 seconds
INFO:root:Running AlienVault connector...
INFO:root:Loaded state: {'latest_pulse_timestamp': '2021-07-16T17:00:16.952000', 'last_run': 1626454889}
INFO:root:Connector will not run, next run in: 10680 seconds
```

**Comment by maertv** [comment]
If the connector keeps fetching new data and sending bundles to the queue, then it does not seem to be a connector issue.

Maybe it is an issue with the RabbitMQ, see https://github.com/OpenCTI-Platform/opencti/issues/1441#issuecomment-865656252.

**Comment by Ken-Abruzzi** [comment]
Hello. From the 5th line of the connector log you presented, you can see that 8 items have been imported. At that moment, only 8 items are available.

**Comment by SamuelHassine** [comment]
Also, please try to use the option `enable_attack_patterns_indicates` and put this option to `false` (default is true) so you can avoid too big pulses/reports in OpenCTI.
