### ISSUE TITLE
[MITRE & Cyber Crime Tracker] The connectors stop working with no errors recorded in the logs.

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#423]
## Description
The MITRE and Cyber Crime Tracker connectors worked well for many days. But they suddenly stopped on July 6th and July 11th.
![image](https://user-images.githubusercontent.com/68931768/126427603-fad58927-a6f3-4384-b8b9-b98e30f22eb8.png)
**Figure 1: The web page of connector MITRE**
![image](https://user-images.githubusercontent.com/68931768/126427547-8845f7ca-437f-46bf-a7f5-a0737913a0e8.png)
**Figure 2: The web page of connector Cyber Crime Tracker**
 I check the logs of the two containers. It shows only "Initiate work for xxx" and nothing else.
![image](https://user-images.githubusercontent.com/68931768/126427327-ef5c72e5-ff0e-4521-a20e-13e9566be0f7.png)
**Figure 3: The log of container MITRE**
![image](https://user-images.githubusercontent.com/68931768/126428477-bfe602a6-13f7-4944-a254-8d220621abc1.png)
**Figure 4: The log of container Cyber Crime Tracker**

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
 
## Additional information
The platform API container restarted 3 days ago. 
![image](https://user-images.githubusercontent.com/68931768/126428790-8eadd1d7-524e-42ac-901f-3a40748bb0ae.png)
**Figure 5: The status of container opencti platform api**
I check its log and find out that on that day a fatal error occurred.
![image](https://user-images.githubusercontent.com/68931768/126427925-e7e997b1-3b6e-4bf6-902c-18691dddf517.png)
**Figure 6: The log of container opencti platform api**
The node options are set as [https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml](url)
![image](https://user-images.githubusercontent.com/68931768/126428041-9a50881b-2f35-49ab-8724-4b0427538a9e.png)
**Figure 7: The configuration of container opencti platform api**

Thanks for your help!

**Comment by Ken-Abruzzi** [comment]
@richard-julien Hello! Can you give some suggestions? Thank you very much!

**Comment by Ken-Abruzzi** [comment]
I delete the stucked "in progress work", and reboot the os, and reset the connector, and then they begin to work. Why are they not stable so that I need to inspect them frequently?

**Comment by Ken-Abruzzi** [comment]
After 2 days of normal work, the mitre connector stopped again. An error "urlopen error [errno -3]" occurs. No details are given about the error.
![image](https://user-images.githubusercontent.com/68931768/126920522-ca0bdb70-5015-4eb9-8b8f-a5eefece8a01.png)

**Comment by nor3th** [comment]
Hey @Ken-Abruzzi 

The "urlopen error" seems like a connection issue in general where the connector is unable to contact the MITRE URL. This issue reminds me a bit of #395 . Are there any issues from a network standpoint between your system and the MITRE server?

Concerning the Javascript memory issue: Is your host system able to provide the additional memory for the node or is it already maxed out?

Regarding the idle `0 operation` works: It seems that the MITRE connector registers the work, but then fails to ship any STIX objects and never tells OpenCTI that it has finished working. It seems very odd though, that the connectors never send anything or at least throw an exception... Could you please let the connectors run with `DEBUG` log mode and post the logs when the issue occurs again? Do you have any logs from OpenCTI or the opencti worker itself from the times when the connectors showed that behavior?

The `last_run` time is stored within the connector itself, hence doing a `docker stop openti_connector-XXX` and then letting it run again with `docker-compose up -d` should be sufficient to have it start from scratch again.

Regards,

**Comment by Ken-Abruzzi** [comment]
@nor3th Thanks for your answer.  The node's old space is set as below. Is there any problem with that? My memory is 24GB. 
![image](https://user-images.githubusercontent.com/68931768/131594209-9ba08284-6c7e-43a7-af5c-d843e6e19d8d.png)
I don't know how to run the connectors with debug log mode. Can you tell me how to? Thanks again!

**Comment by nor3th** [comment]
Hey @Ken-Abruzzi 

For debug logs, change this docker environment variable to `debug`
```
- CONNECTOR_LOG_LEVEL=debug
```

Regards

**Comment by Ken-Abruzzi** [comment]
> Hey @Ken-Abruzzi
> 
> For debug logs, change this docker environment variable to `debug`
> 
> ```
> - CONNECTOR_LOG_LEVEL=debug
> ```
> 
> Regards

Hello, @nor3th . Thanks for your advice, I capture the debug log of the connector urlhaus as below.
![image](https://user-images.githubusercontent.com/68931768/132604664-a0b17d76-88cc-451b-aab9-97cb22a8dbaa.png)
So can you tell me please what the problem is. Thanks again!
