### ISSUE TITLE
Error Connectors status tab

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/connectors#429]
## Description

How to Fix the Connectors status tab?

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1
2. OpenCTI version: 4.5
3. Other environment details: Python 3.8, pip 21.1.3.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run workers
2. Run Connectors
3. Check status !

## Expected Output

Older version we used to check all connectors status.

## Actual Output
**Error:**
![image](https://user-images.githubusercontent.com/37035465/126883054-0ee67cad-ef19-4815-99a4-1c83ecb76657.png)

Reference: Issue https://github.com/OpenCTI-Platform/opencti/issues/1460

Looping @maxifjaved

Regards,
Khalid..

**Comment by richard-julien** [comment]
Duplicate https://github.com/OpenCTI-Platform/opencti/issues/1460
