### ISSUE TITLE
History connector sending ElasticSearch requests non-stop

### ISSUE THREAD

**Issue by hartek** [OpenCTI-Platform/connectors#431]
## Description

After updating OpenCTI and all connectors from version 4.4.0 into 4.5.5, the History connector is sending PUT requests into the associated ElasticSearch instance non-stop. It has been going like this for whole days.

Which is interesting is that the ElasticSearch instance does not seem to be adding any new entity into the `opencti_history-000001` index. The existing and deleted doc counts are stable. 

The only two things done the day the issue started, apart from updating the system and connectors, were the ingestion of some MISP events via the MISP connector and the activation of the OpenCTI connector. 

## Environment

1. OS: RHEL 8.2
2. OpenCTI version: OpenCTI 
3. OpenCTI client: Frontend
4. Other environment details: OpenCTI and associated services running out of docker. Connectors and workes running in docker. 

## Reproducible Steps

I have not been able to reproduce this. 

## Expected Output

I would expect the History connector to stop sending stuff :) 

## Actual Output

The connector keeps on sending PUT requests to ElasticSearch. 
 
![imagen](https://user-images.githubusercontent.com/11649585/127005472-a1cf3ba1-d968-416b-9f64-21ec63292a54.png)

## Additional information

I have tried both restarting, recreating and restarting the connector's state. I have currently stopped the connector's container, as otherwise it overloads the ElasticSearch system and makes OpenCTI inoperable. The OpenCTI service logs do not show error or anything related to the connector.

**Comment by SamuelHassine** [comment]
Hello @hartek,

Can you please look at the "History connector" page and tell me what you have in the "State" part? 

You should have something like: 

```{"connectorLastEventId": "1626251633388"}```

Thanks.

Kind regards,
Samuel

**Comment by hartek** [comment]
Good day @SamuelHassine , 
Thank you for your reply and apologies for my delayed response. As of right now, the value is:

```
{"connectorLastEventId": "1620237885631-0"}
```
Cheers!
