### ISSUE TITLE
Shodan - Pulling Connector Issue [Manifest Unknown Issue]

### ISSUE THREAD

**Issue by hackeristan** [OpenCTI-Platform/connectors#442]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{I just had defined connect configuration detail and attempted to update stack per suggestion but getting error while pulling connector for Shodan with error detail Manifest Unknown}

## Environment

1. OS (where OpenCTI server runs): { VM Template}
2. OpenCTI version: { OpenCTI 4.5.5 }
3. OpenCTI client: { python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

{ Expecting Shodan connector pull properly in OpenCTI 4.5.5 }

## Actual Output

{ Getting error Manifest Unknown
![Shodan Error](https://user-images.githubusercontent.com/24958531/128706440-3cea2c4f-01f9-45aa-959d-1428162d8882.jpg)}
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by nor3th** [comment]
The Shodan connector was after the 4.5.5 release added, hence only the **rolling** version exists so far.
Try this image
```
opencti/connector-shodan:rolling 
```
Details:
https://hub.docker.com/r/opencti/connector-shodan/tags?page=1&ordering=last_updated

**Comment by hackeristan** [comment]
Thank you for this help and I did change only one line in the connector configuration and it worked finally

image : opencti/connector-shodan:4.5.5
