### ISSUE TITLE
[ExportFileCsv] Fix CSV export handling of line breaks (most often in Description field)

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/connectors#443]
## Problem to Solve

When a field (most often, the Description field) contains a line break, exporting that object as a CSV will break the CSV. 

## Current Workaround

Manually open the CSV replace new lines, Find/Replace "LF" line break.

## Proposed Solution

... Not actually sure how to best implement this :) Possibly, transform new lines in the Description field into "\n" character, or a tab?

I'm not sure it's possible the maintain a line break within a single cell when opening in Excel, without making changes in Excel. Perhaps treating line breaks between quotes than line breaks outside of quotes, or CR vs LF line breaks

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Can you please try to reproduce that, I've made some tests with line breaks in description and the CSV is working well, example with the list of Threat Actors on the demo:

[2021-08-11T10_59_36.096Z_TLP_ALL_(ExportFileCsv)_Threat-Actor_full.csv](https://github.com/OpenCTI-Platform/connectors/files/6967866/2021-08-11T10_59_36.096Z_TLP_ALL_.ExportFileCsv._Threat-Actor_full.csv)

Result on online CSV viewer:

![image](https://user-images.githubusercontent.com/1334279/129018247-8f6639bc-95e6-4cf9-b5d4-961afc0fe342.png)

If you have a repro case or a CSV to give me it would be great!

Thanks.

Kind regards,
Samuel

**Comment by securitiz** [comment]
Hi Samuel,

I exported all internal-report Reports from my instance (running 4.5.5). When opening in Excel, I still get the line breaks:
[2021-08-11T17_09_29.365Z_TLP_ALL_(ExportFileCsv)_Report_full.csv](https://github.com/OpenCTI-Platform/connectors/files/6970209/2021-08-11T17_09_29.365Z_TLP_ALL_.ExportFileCsv._Report_full.csv)

**Comment by r0sier** [comment]
@SamuelHassine @securitiz 

Hi Guys,
I was having the same issue and I believe its a regional issue. When opening a CSV with Excel, it uses your regional language list separator as the delimiter. ([See here](https://harvestmedia.zendesk.com/hc/en-us/articles/360023978031-Opening-Excel-files-with-the-correct-CSV-list-separator)) 

To open the CSV without formatting issues, you need to tell Excel not to use your system default which is a comma (in the UK anyway!) and instead use a semi-colon. I assume in France the default separator is a semi-colon and hence was coded that way. 

Not too sure how other applications get around this regional issue, but is just a case of changing your application delimiter. It would be nice if Excel automatically worked out the delimiter! 

Hope that helps!

**Comment by nor3th** [comment]
Closed to inactivity
