### ISSUE TITLE
AbuseIP Connector Issue

### ISSUE THREAD

**Issue by trappersec** [OpenCTI-Platform/connectors#444]
Hi,

I am having the following Issue with my Abuse IP connector. 

Traceback (most recent call last):
  File "/opt/opencti-connector-abuseipdb/abuseipdb.py", line 127, in <module>
    abuseIPDBInstance = AbuseIPDBConnector()
  File "/opt/opencti-connector-abuseipdb/abuseipdb.py", line 17, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 409, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 141, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: a3b0ac9a-2b40-44d5-9959-080bc67d621f
INFO:root:Starting ping alive thread
INFO:pika.adapters.utils.connection_workflow:Pika version 1.2.0 connecting to ('redacted', 5672)
INFO:pika.adapters.utils.io_services_utils:Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('redacted', 55414), raddr=('redacted', 5672)>
INFO:pika.adapters.utils.connection_workflow:Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6f1a5e67c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6f1a5e67c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
INFO:pika.adapters.utils.connection_workflow:AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6f1a5e67c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6f1a5e67c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.blocking_connection:Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6f1a5e67c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.blocking_connection:Created channel=1
INFO:root:Reporting work update_received opencti-work--c3ecd646-42ce-4453-b854-8f9793e1b603
INFO:root:Reading StixCyberObservable {6ff559c6-8959-43c1-82dc-2e3e23b085cd}.
INFO:root:Updating Stix-Observable {ipv4-addr--a3402b4c-0a8f-5696-88a5-9fe6396a3289} field {x_opencti_score}.
INFO:root:Reporting work update_received opencti-work--c3ecd646-42ce-4453-b854-8f9793e1b603
INFO:root:Message (delivery_tag=1) processed, thread terminated

There is no work in progress and no work history for this connector yet it shows "Active". Not too sure what to do next. 

Ps I have checked my docker-compose file and everything seems fine, I think it used to work some time ago.

**Comment by nor3th** [comment]
Hey @trappersec

This error indicates, that there was a connection issue, but it seems that this problem was resolved quickly.
```
Traceback (most recent call last):
File "/opt/opencti-connector-abuseipdb/abuseipdb.py", line 127, in
abuseIPDBInstance = AbuseIPDBConnector()
File "/opt/opencti-connector-abuseipdb/abuseipdb.py", line 17, in init
self.helper = OpenCTIConnectorHelper(config)
File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 409, in init
self.api = OpenCTIApiClient(
File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 141, in init
raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```
The reason behind the absence of the work history is the following. Currently there are two ways for a connector to send new data or updates to OpenCTI:
1. via send_bundle() to send StixObjects
2. interact directly with the API

Connectors which use **1)** register a task which then shows up in the connector history, while connectors which take the shortcut with **2)** don't show up in the connector history. Unfortunately some connectors are still written in way **2)** and the AbuseIP connector is one of them.

Based on the logs you provided, everything seems to work as intended and the IPv4 address `ipv4-addr--a3402b4c-0a8f-5696-88a5-9fe6396a3289` had its `x_opencti_score` attribute updated. Search for that Stix ID in OpenCTI and you should see that the score of this observable has been modified.

All the best

**Comment by trappersec** [comment]
Hi,

Thanks for your answer.
I have been having with my OpenCTI in docker  causing the VM in which it sits to shut down.
I am trying to get to the bottom if this as the CPU seems to have been spiking to 100%. We are investigating a possible memory leak.
I am also trying to see what might be causing the VM to shut down so I though it might be part of the cause.

Thanks for your clarification, I will keep looking at the rest of them.
