### ISSUE TITLE
Automatic Ingest of Threat Feeds

### ISSUE THREAD

**Issue by OzRex08** [OpenCTI-Platform/connectors#45]
It would be good to be able to ingest opensource and commercial threat feeds automatically by choosing a feed url.

## Current Workaround

Indicators need to be imported manually.

## Proposed Solution

- Have the ability to select from a range of opensource feeds and have them automatically ingest either on demand, or once per day etc.
- Be able to categorise feeds being ingested into appropriate categories (i.e. Phishing IP's; C2 Domains; Hashes of Malware etc)

**Comment by SamuelHassine** [comment]
Hello,

For the moment, we've decided to maintain the current implementation of connector with external configurations. Another tool may be created for this purpose.
