### ISSUE TITLE
[import-report] Parse defanged URLs and domains

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/connectors#451]
## Problem to Solve

Parser does not properly parse and/or import defanged URLs and domains

## Current Workaround

Copy defanged domains/URLs to txt file, remove brackets with search/replace, import txt file

## Proposed Solution

Implement parsing of defanged URLs/domains

## Additional Information

Attached - PDF used for testing:
[Tactics, Techniques, and Procedures of Indicted APT40 Actors Associated with China’s MSS Hainan State Security Department _ CISA.pdf](https://github.com/OpenCTI-Platform/connectors/files/7016292/Tactics.Techniques.and.Procedures.of.Indicted.APT40.Actors.Associated.with.China.s.MSS.Hainan.State.Security.Department._.CISA.pdf)

**Comment by nor3th** [comment]
If you are using the docker containers, try the `rolling` version instead of `4.5.5`. I already implemented that feature after the last release (#410).
If you are experiencing any troubles, please let me know.
