### ISSUE TITLE
[import-report] Issue Connector: Import-Report not showing up in enabled connectors.

### ISSUE THREAD

**Issue by PwnisherX** [OpenCTI-Platform/connectors#455]
Just a heads up if anyone else is having the same issue where the Connector: Import-Report is not showing up as enabled.

Current Configuration (Broken)
 "CONNECTOR_ONLY_CONTEXTUAL=true",  

Corrected Configuration (Fixed)
 "CONNECTOR_ONLY_CONTEXTUAL=false",  

This is breaking it. If you set this as false. The connector works as intended and allows you to import .txt etc files.
Not sure how to fix this and leave it as true as intended but setting it to false works and I can import all txt IOC feeds.

**Comment by nor3th** [comment]
Hello @PwnisherX 

Do the connector logs indicate any crash/error? 
The idea behind the import-report connector is to import files attached to a report only, extract the information from the file and add the SCOs/SDOs to the report.

Is the connector not showing up in the general `Data Import` menu or in the report `Files` section?

Regards,
