### ISSUE TITLE
[import-report] Trouble parsing domains / URLs with capital letters

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/connectors#462]
## Description

import-report appears to fail when parsing domains with capital letters. I've attached the txt file of domains I was trying to import below.  The import fails with the error "'list' object has no attribute 'values'". I played with the input file by removing domains that appeared to be causing issues, and the problematic domains were:

- kAty197.chickenkiller[.]com
- Soure7788.chickenkiller[.]com
- Engaction[.]com

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
4. Other environment details: import-connector: rolling

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import txt file with domains/URLs with capital letters

## Expected Output

Domains / URLs are parsed as observables

## Actual Output

Import-report connector crashes, no observables are parsed unless the capital letters become lowercase or the offending domains are removed
 
## Additional information

I've attached 3 files:

- **AA21-200A_domains_failed.txt** : The original txt file, with domains including capital letters
- **AA21-200A_domains_success.txt** : The revised txt file, with no capital letters
- **errorlog.txt** : The error log, from one of the times when I tried to import a version of the original file (this was an iteration of troubleshooting, so the error log shows what happens when I input the txt file having removed the first two offending domains)

[AA21-200A_domains_success.txt](https://github.com/OpenCTI-Platform/connectors/files/7101092/AA21-200A_domains_success.txt)
[errorlog.txt](https://github.com/OpenCTI-Platform/connectors/files/7101093/errorlog.txt)
[AA21-200A_domains_failed.txt](https://github.com/OpenCTI-Platform/connectors/files/7101094/AA21-200A_domains_failed.txt)

**Comment by nor3th** [comment]
Hey @securitiz 

Thank you very much for your amazing bug report. It really helped me when tracking down the issue. 
It bugs me though a bit, because this should have popped up during my own testing phase...

The domains are converted to lower case by an external library, but this doesn't make a really difference in the end, since domains are case insensitive anyways.

Regards,
