### ISSUE TITLE
[VxVault / MITRE ATT&CK / Cyber Crime Tracker] urlopen error [Errno -3] Try again

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#467]
@nor3th Hello! Can you give me some advice? Thank you!

## Description

The connectors including VxVault / MITRE ATT&CK / Cyber Crime Tracker always face this problem every week. They work well for 3 or 4 times and then they go on strike. For example, the connector VxVault should begin its work every day, and it worked well on Sep 7 and Sep 8. But it refuses to work on Sep 9.
![image](https://user-images.githubusercontent.com/68931768/132815963-e7853318-028c-4837-83ea-844cf6876c34.png)
In the log it records "urlopen error [Errno -3] Try again"
![image](https://user-images.githubusercontent.com/68931768/132816579-8ae34297-10fb-4bae-957f-d1aa0601768d.png)
When the connector works normally, the log should show as below
![image](https://user-images.githubusercontent.com/68931768/132817361-cb153cce-d40d-49da-b506-c6a1dbd7fcc6.png)

Here is the case with connector Cyber Crime Tracker. It worked well on Sep 1, 3, 5 and 7. But it failed on Sep 9.
![image](https://user-images.githubusercontent.com/68931768/132835299-a25fe51d-5076-4819-a6ed-19448dcd37d7.png)
The log also records "urlopen error [Errno -3] Try again"
![image](https://user-images.githubusercontent.com/68931768/132835053-8cb09a4f-1672-4753-abe2-e4649901fc6f.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend

## Additional information

When I execute "docker restart docker_connector-vxvault_1", then it returns to normal. But after a few days, the same error occurs again. I have to inspect these connectors frequently to help them recover from the errors.

**Comment by nor3th** [comment]
Hey @Ken-Abruzzi 

The issue seems to be, that the connector has network issues connecting to the API/rss feed. 
Ideally the connector base class would handle issues like those, but that's a TODO. Related: #395 

Regards,

**Comment by Ken-Abruzzi** [comment]
> Hey @Ken-Abruzzi
> 
> The issue seems to be, that the connector has network issues connecting to the API/rss feed.
> Ideally the connector base class would handle issues like those, but that's a TODO. Related: #395
> 
> Regards,
Thanks! I will wait for the new feature.

**Comment by Ken-Abruzzi** [comment]
> Hey @Ken-Abruzzi
> 
> The issue seems to be, that the connector has network issues connecting to the API/rss feed.
> Ideally the connector base class would handle issues like those, but that's a TODO. Related: #395
> 
> Regards,

Thanks! @nor3th I will wait for the new feature.

**Comment by Ken-Abruzzi** [comment]
@nor3th Finally, I guess I know the reason why the error occurs. Today when I log on my computer, it warned me of running out of memory. Then I find that all connectors report "urlopen error [Errno -3] Try again". And accidentally, I find the network adapter's IPv4 address disappears, but it did have an IPv4 address yesterday. The IPv4 address should be assigend by the DHCP service. So I guess that maybe the memory crash caused that the network adapter' IPv4 address disappeared, and then the computer cannot reach the Internet, and hence the connectors report "urlopen error [Errno -3] Try again".
