### ISSUE TITLE
OpenCTI couldn't get a MISP data

### ISSUE THREAD

**Issue by xinfolab** [OpenCTI-Platform/connectors#47]
## Description
When running the MISP connector, OpenCTI couldn't get a MISP data.

## Environment
1. OS (where OpenCTI server runs):  ubuntu 19.10 VirtualBox
2. OpenCTI version : 3.0.2
3. OpenCTI client :  python 3.7.5
4. Other environment details: pymisp==2.4.119.1

#### Clone the repository
```
$ mkdir /path/to/your/app && cd /path/to/your/app
$ git clone https://github.com/OpenCTI-Platform/docker.git
$ cd docker
```

[misp connector download](https://github.com/OpenCTI-Platform/connectors/tree/master/misp)

#### Docker Set configure
+ APP__ADMIN__PASSWORD
+ APP__ADMIN__TOKEN
+ OPENCTI_TOKEN
+ vm.max_map_count

#### MISP configure
+ opencti-url
+ opencti-token
+ misp-url
+ misp-key
+ misp-ssl_verify

#### Run
$ docker-compose --compatibility up
$ python3 misp.py

## Expected Output
I wanted to importing MISP data inside openCTI.

## Actual Output
MISP returned 0 events
```
$ python3 misp.py
INFO:root:Connector last run: 2020-02-26 07:02:25
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "timestamp": "2020-02-26 07:02:25", "limit": 100, "page": 1}
INFO:root:MISP returned 0 events.
```
## Additional information
![image](https://user-images.githubusercontent.com/28777736/75320410-f28cf080-58b1-11ea-8ac5-0fc0b3985b7c.png)

**Comment by mbower** [comment]
Im sort of see this same thing. Although, I get _some_ of the MISP data to come in initially, then it just stops importing anything and I see the above.

**Comment by SamuelHassine** [comment]
@mbower @xinfolab: just fixed this issue. It will be in the next release!
