### ISSUE TITLE
[MISP] Connector successfully run (0 events have been processed)

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#476]
## Description

The MISP connector runs with 0 events been processed. No errors are recorded in the log.
![image](https://user-images.githubusercontent.com/68931768/133388060-6a72768b-90b9-4070-b85a-fa3083d3e3cd.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
4. Other environment details: MISP instance running in ubuntu 18.04.1 LTS

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. The docker-compose.yml file is shown as:
![image](https://user-images.githubusercontent.com/68931768/133388772-a5bec401-b480-4873-b3a7-59833838e121.png)
2. The MISP key is verified using the REST client supplied by the MISP instance. This key belongs to the administrator who have all the authorities.
![image](https://user-images.githubusercontent.com/68931768/133389735-eaa10ffb-b6cb-4bc9-ade7-4940fcb6931e.png)
![image](https://user-images.githubusercontent.com/68931768/133390042-96dc7877-d71e-4119-ad99-a39597282a35.png)
3. I don't know whether the environmental variable "CONNECTOR_ID" should be set to some certain value. In this issue #221 
@khalidrehan pointed out that the "CONNECTOR_ID" should be the organization uuid.

## Additional information
In the MISP instance, there have been many publised events since 2021-01-01
![image](https://user-images.githubusercontent.com/68931768/133391286-075684da-3c40-4bc0-b772-caea6a92821d.png)

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine @nor3th Hello! Can you please give me some instructions? Thank you!

**Comment by nor3th** [comment]
Hey @Ken-Abruzzi 

Please use this approach to verify that your query is correct.
https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/README.md#no-reports-imported

Regards,

**Comment by Ken-Abruzzi** [comment]
> Hey @Ken-Abruzzi
> 
> Please use this approach to verify that your query is correct.
> https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/README.md#no-reports-imported
> 
> Regards,

@nor3th Hello! Thank you for your advice. I use the "curl" command to verify that my query is correct. The server can return events:
![image](https://user-images.githubusercontent.com/68931768/133536488-82078bee-a7d8-4be6-b296-d4551fdfe94b.png)
What can I do else to find the problem?

**Comment by khalidrehan** [comment]
Hi @Ken-Abruzzi 

1. On MISP create a Sync user and login using it.
2. Go to > Sync Actions > Create Sync Config
3. Take the needed UUID's from it as is to OpenCTI.

Double check the connector for "Organization name(s)" mentioned by default.

Regards,
Khalid

**Comment by Ken-Abruzzi** [comment]
> Hi @Ken-Abruzzi
> 
> 1. On MISP create a Sync user and login using it.
> 2. Go to > Sync Actions > Create Sync Config
> 3. Take the needed UUID's from it as is to OpenCTI.
> 
> Double check the connector for "Organization name(s)" mentioned by default.
> 
> Regards,
> Khalid

Hello @khalidrehan  Thanks for your help.
1. I register a Sync user
![image](https://user-images.githubusercontent.com/68931768/133719233-8365eb2c-6612-499e-bb67-6bc030ad8b6d.png)
2. I assign an authkey to the user
![image](https://user-images.githubusercontent.com/68931768/133719858-3665c325-49ec-4075-962c-29a938770785.png)
3. I verify the authkey and the server's url by the way mention by @nor3th  in [https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/README.md#no-reports-imported](url)
The server responds to my request.
![image](https://user-images.githubusercontent.com/68931768/133720160-10a0b849-e4fa-495a-93f0-173a1313c9b5.png)
4. Then I log in using the Sync user identity and go to "Create Sync Config".
![image](https://user-images.githubusercontent.com/68931768/133719371-07ae4e38-8f2d-4ccc-98a0-bf6330260a6b.png)
5. Then I try both the first uuid and the second uuid. But neither takes effect.

**Comment by Ken-Abruzzi** [comment]
> Hey @Ken-Abruzzi
> 
> Please use this approach to verify that your query is correct.
> https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/README.md#no-reports-imported
> 
> Regards,

Hello @nor3th 
I have modified the "MISP_IMPORT_TAGS" to coincide with the https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/README.md#no-reports-imported
![image](https://user-images.githubusercontent.com/68931768/133740339-e5d3ee7d-da83-40d1-b844-49c62ecd80ed.png)
And the connector's log returns that
![image](https://user-images.githubusercontent.com/68931768/133740637-c8f160e6-5f4c-4c3e-925f-dcecb32b3785.png)
It doesn't include the parameter "misp_import_from_date". Can it be the point?

**Comment by Ken-Abruzzi** [comment]
@khalidrehan @nor3th Hello! I solve the problem finally. Thanks for your inspiration. Actually, the "CONNECTOR_ID" need not be identical with the organization's uuid in my case. I just generate a different uuid and it works. The critical point is that I delete some environmental variables as @khalidrehan post on #221 .This line "MISP_DATETIME_ATTRIBUTE=timestamp" is the reason to cause the problem. After I delete this line, the connector works well. The effective configuration is as below:
![image](https://user-images.githubusercontent.com/68931768/133870502-a4b66576-7279-4acd-aef6-5bf947757ccb.png)
