### ISSUE TITLE
[TAXII2] Add Client side cert auth support

### ISSUE THREAD

**Issue by mwatermolen** [OpenCTI-Platform/connectors#477]
## Use case

Using client side cert auth for Taxi like https://www.cisa.gov/ais

## Current Workaround

NA

## Proposed Solution

Implement a ENV based way to provide client certs

## Additional Information

https://www.cisa.gov/ais

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by nor3th** [comment]
Hey @mwatermolen 

Sounds good, please submit a PR once you have the time for this feature :)

Regards,

**Comment by biastogit** [comment]
Hi,
Any new regarding this feature, I'm interested too.
Regards,

**Comment by SamuelHassine** [comment]
This is already done. Just have to add the documentation:

`TAXII2_CERT_PATH`.
