### ISSUE TITLE
[Cybercrime Tracker] The connector version 5.0.0 cannot start.

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#478]
Hello! @SamuelHassine 
## Description
The new version connector cannot start normally even after I reboot my computer. It restarts for more than 100 times.
![image](https://user-images.githubusercontent.com/68931768/133538963-491826c4-aa8b-4803-87ff-20dc65c21c4d.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 5.0.0
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I use the docker-compose.yml file and then deploy the container. It shows recreating is done.
![image](https://user-images.githubusercontent.com/68931768/133540156-a7b12c72-f636-4b3c-9421-75f2175932ff.png)
 
## Additional information
The log file shows the permission is denied!
![image](https://user-images.githubusercontent.com/68931768/133540631-66933f08-c3ac-4c7a-bfba-6c3e51636afc.png)

**Comment by SamuelHassine** [comment]
Hello @Ken-Abruzzi, the problem is now solved, I've launched a rebuild of the 5.0.0 tag, so you can pull the new image directly on the current tag.

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine It now works. Thank you!
