### ISSUE TITLE
[Cryptolaemus / Malpedia] No progress bar

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#479]
## Description

The connectors run but no progress bar is shown on the web page.

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 5.0.0
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I installed the connectors using docker-compose.

## Expected Output

Every time the connectors start new work progress, there should be a progress bar on the web page, such as below:
![image](https://user-images.githubusercontent.com/68931768/133546060-ef41d03d-06b8-44d5-a6d8-4d73bbcd862b.png)

## Actual Output

![image](https://user-images.githubusercontent.com/68931768/133546113-17b12adf-e522-4db7-babb-15817b7d7067.png)
![image](https://user-images.githubusercontent.com/68931768/133546466-22c7eb1a-fd4f-412e-a939-cf4fed3daac8.png)

## Additional information

 I assure that the connector actually ran on this page:
![image](https://user-images.githubusercontent.com/68931768/133546279-a62bc149-0c7e-4466-a20f-b8048f755593.png)

**Comment by nor3th** [comment]
Hey

It's not really a bug, just not ideally implemented. Here's the explanation why:

> The reason behind the absence of the work history is the following. Currently there are two ways for a connector to send new data or updates to OpenCTI:
>1. via send_bundle() to send StixObjects
>2. interact directly with the API

>Connectors which use 1) register a task which then shows up in the connector history, while connectors which take the shortcut with 2) don't show up in the connector history. Unfortunately some connectors are still written in way 2) and the AbuseIP connector is one of them.

https://github.com/OpenCTI-Platform/connectors/issues/444#issuecomment-898714500

Regards,

**Comment by Ken-Abruzzi** [comment]
> Hey
> 
> It's not really a bug, just not ideally implemented. Here's the explanation why:
> 
> > The reason behind the absence of the work history is the following. Currently there are two ways for a connector to send new data or updates to OpenCTI:
> > 
> > 1. via send_bundle() to send StixObjects
> > 2. interact directly with the API
> 
> > Connectors which use 1) register a task which then shows up in the connector history, while connectors which take the shortcut with 2) don't show up in the connector history. Unfortunately some connectors are still written in way 2) and the AbuseIP connector is one of them.
> 
> [#444 (comment)](https://github.com/OpenCTI-Platform/connectors/issues/444#issuecomment-898714500)
> 
> Regards,

@nor3th Hello!
Thanks for your detailed explanation. I also noticed that there are no information like "Bundle has been sent" in such connectors' logs. I recommand that you can notice users in the readme file about the fact that these connectors will not show history bar, in case they are confused about the situation. Haha!
Regards!
