### ISSUE TITLE
ImportfilePDFobservables connector --> PDF not imported as a report and obsrvables not attached to it

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#48]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I tested the connector with PDF file.
Observables seem to be correctly extracted but
- the PDF document is not imported as report
and, consequently
- the observables are not attached to a report
- it is not possible to easily find them in the general set of observables
- it is not possible to remove false positive (e.g. the PDF report include some domain names or email addresses that should NOT be observables. For example the contact email of the organisation that created the PDF, etc)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @Fred-certeu,

As precised here: https://opencti-platform.github.io/docs/usage/knowledge-import, if you want the observables to be associated to a report, you have to create the report and import the file directly from it. Using the "general upload" will conduct to create atomic entities. If it is a STIX2 containing a report, that's not a problem, it if is a PDF (or a CSV in the future), the best is to create the report, upload the file in this report and start the import from it.

**Comment by Fred-certeu** [comment]
Indeed, it is much better like this ;)
Thank you for the clarification.
One remark however:
The observables are attached to the report.
But no indicator is created for them.
So, when the user attached some knowledge to the report (e.g. an intrusion set or a malware), it is not possible - apparently - to record that these observables "indicate" an intrusion set or a malware...

**Comment by SamuelHassine** [comment]
If you want to create indicators from the observables with this connector, as you can see in the [default configuration file](https://github.com/OpenCTI-Platform/connectors/blob/master/import-file-pdf-observables/src/config.yml.sample), you just have to set `create_indicator` to `True`.
