### ISSUE TITLE
[AMITT] The connector imports "country" as "organization".

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/connectors#480]
## Description

![image](https://user-images.githubusercontent.com/68931768/133714229-ec757231-b85c-492e-8233-60701e473e80.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 5.0.0
3. OpenCTI client: frontend

## Expected Output

The "country" entities should be labeled as "country".
![image](https://user-images.githubusercontent.com/68931768/133714358-157acb70-d30f-4ce9-b40d-4186d03c7d73.png)

## Actual Output

The "country" entities imported by the Amitt connector are labeled as "organization".

**Comment by nor3th** [comment]
Hey @Ken-Abruzzi 

That's not the connector's fault, it's the amitt dataset which defined it as such. Example:
```
 {
            "type": "identity",
            "id": "identity--806f665f-9358-4f1b-9854-c5ae290f7835",
            "created": "2020-07-06T17:58:14.404Z",
            "modified": "2020-07-06T21:58:14.405Z",
            "name": "Iran",
            "description": "Iran",
            "identity_class": "organization",
            "sectors": [
                ""
            ],
            "contact_information": "",
            "x_identified_via": ""
        },
```
I'd suggest opening an issue here https://github.com/VVX7/cti

Regards,

**Comment by Ken-Abruzzi** [comment]
> Hey @Ken-Abruzzi
> 
> That's not the connector's fault, it's the amitt dataset which defined it as such. Example:
> 
> ```
>  {
>             "type": "identity",
>             "id": "identity--806f665f-9358-4f1b-9854-c5ae290f7835",
>             "created": "2020-07-06T17:58:14.404Z",
>             "modified": "2020-07-06T21:58:14.405Z",
>             "name": "Iran",
>             "description": "Iran",
>             "identity_class": "organization",
>             "sectors": [
>                 ""
>             ],
>             "contact_information": "",
>             "x_identified_via": ""
>         },
> ```
> 
> I'd suggest opening an issue here https://github.com/VVX7/cti
> 
> Regards,

Thank you @nor3th . I will drag this issue there. [https://github.com/misinfosecproject/amitt_framework/issues](url)
