### ISSUE TITLE
[Cortex] Create the connector

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#5]
## Problem to Solve

Observables enrichment is currently not provided by OpenCTI. People wants to be able to display enrichment direclty in the platform.

## Current Workaround

None.

## Proposed Solution

Create the CORTEX connector for observables enrichment.

## Additional Information

None.

**Comment by ktneely** [comment]
It's not clear to me what the original intent of Cortex Connector feature request would be, but it occurs to me that a useful -and possibly easier to build- approach would be to simply do the following:

1. Pull the IOCs that have been researched by a Cortex user  (i.e. those items that have been enriched using Cortex)
2. Update the History section of the IOC entity in OpenCTI with this info (e.g. CortexOrg1 investigated this observable on 2021-02-12)
3. Optional:  pull in the data retrieved by Cortex.

Knowing that someone in your org has researched an IOC is pretty powerful knowledge, and this may be an easy way to incorporate that.

**Comment by 8ear** [comment]
Hi,
I think this idea is also well.
But I think the original intention from @SamuelHassine was to use cortex to enrich the information in opencti.

kind regards

**Comment by SamuelHassine** [comment]
Indeed it was @8ear. For the moment we've decided to not create this connector. CORTEX Analyzer will be available in the next major release of CORTEX.
