### ISSUE TITLE
[IBM QRadar] Create the connector

### ISSUE THREAD

**Issue by hackeristan** [OpenCTI-Platform/connectors#513]
## Use case

Using OpenCTI observables in QRadar SIEM for detection purposes.

## To implement

A stream connector able to:
- listen a particular stream of events in OpenCTI
- fetch OpenCTI Observables (IPv4, v6, hash, url, mail, etc.)
- populate corresponding Qradar ReferenceSet with them.

**Comment by SamuelHassine** [comment]
Implement QRadar as a stream connector.

**Comment by G4fanhoto** [comment]
Good morning friends, the qradar connector is not available ?!?

**Comment by Jipegien** [comment]
https://www.ibm.com/community/qradar/ce/

**Comment by Jipegien** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/3341
