### ISSUE TITLE
Name change for FireEye connector.

### ISSUE THREAD

**Issue by kanniget** [OpenCTI-Platform/connectors#527]
With the recent sale of the Fireeye product suite and resulting name change for the company to Mandiant its advisable to have the name changed in the connector to avoid confusion at a later date.

**Comment by samjackson200** [comment]
I've been looking at this issue, along with a few other items with the FireEye connector. Although it is a simple tweak to the code to change the Identity that is created to Mandiant, when the Mandiant (FireEye) API returns information, presently that information is returned with the Identity 'FireEye Inc' and OpenCTI creates the FireEye identity and creates the relationship to both the FireEye and Mandiant identities created. I would reccomend that this is not updated until Mandiant update their API and the data returned carries the new Identity.

**Comment by kanniget** [comment]
Thats ok, just wanted it on the radar

**Comment by samjackson200** [comment]
Has this change been tested with the Mandiant API? I only ask because internally the API still uses FireEye, and the searchable types have not been renamed to Mandiant yet, according to the documentation. So I fear this change may break the connector.
