### ISSUE TITLE
[Elastic Security] Incorrect field reference for sighting 

### ISSUE THREAD

**Issue by the-pixel-hunter** [OpenCTI-Platform/connectors#535]
# Description

Using an indictor match rule in elastic, the ["threat"]["indicator"] object will never be in the alerts, the outputs are stored in ["threat"]["enrichments"]["indicator"] as an array of objects. 
https://github.com/OpenCTI-Platform/connectors/blob/1771fd54dc53b2f54afeaf254f9a80694363320a/stream/elastic/elastic/sightings_manager.py#L120

# Enviroment 
elastic -  1.0.0
pyopencti - 5.0.3
elasticsearch - 7.15.0

# Reproducible Steps
1. Produce an indictor match alert
2. Connector pulls alerts
3. fails to parse alert

**Comment by cobsec** [comment]
The effect of this bug is that the connector runs and the stream works fine, but the connector is unable to create sightings to push back to opencti as it throws a KeyError when trying to access the indicators to create the sightings.

**Comment by SamuelHassine** [comment]
@dcode Are you able to take a look to this one?
