### ISSUE TITLE
Connector CAPE not working - missing images

### ISSUE THREAD

**Issue by Fjottis** [OpenCTI-Platform/connectors#538]
Hello,

I'm looking to deploy the CAPE-OpenCTI connector.

When i run the docker-compose up i get the following error :

``` EROOR: manifest for opencti/connecotr-cape:latest not found: manifest unknown: manifest unknown````

But when I lookout on coker hub i found it : https://hub.docker.com/r/opencti/connector-cape

Why so ?

**Comment by nor3th** [comment]
Hey @Fjottis 

Since the CAPE connector was only released after the latest OpenCTI release, only the `rolling` version is available for now.
See:  https://hub.docker.com/r/opencti/connector-cape/tags

Regards,
