### ISSUE TITLE
alienvault connector : always insert URL of the pulse as an external reference

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#55]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

When importing a pulse in the form of a report, the alienvault connector creates an external reference when the orginal alienvault pulse provides an URL under in the field REFERENCE.
However, some alienvault pulses do not populate this REFERENCE field. In this case, no external reference is created in the opencti report and it is impossible, from OpenCTI, to find the origin of the information.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

When importing a pulse from alienvault, the connector should  always add the URL of the alienvault as an external reference
(in addition to any existing URL provided under REFERENCE in the pulse).

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by rhaist** [comment]
Testing with alienvault:rolling the problem seems to be fixed.
Thanks!

**Comment by maertv** [comment]
The URL of the pulse is added to external references. Closing the issue.
