### ISSUE TITLE
Alienvault and Crowdstrike connectors - use author's tag to indicate malware

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#56]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

If the author uses a simple tag to refer to a malware, this information will be imported as a simple tag and not included as "knowledge". Furthermore, there will be no "indicate" relationship between the indicators imported with the report and the malware family.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

Use tags provided by the author of the report and check if they match a malware existing in opencti.
In such case, include the malware in the knowledge of the imported report and create an "indicate" relationship between the imported indicators and the malware.

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by maertv** [comment]
Added option to "guess" which tags represent malwares by making a malware query with the tag value to OpenCTI.

If the tag is identified as a malware then the malware will be used to create relationships with other entities. 

This feature is disabled by default.


To enable this feature in **AlienVault** connector:

* Add following environmental variable to _docker-compose.yml_:
```yaml
- ALIENVAULT_GUESS_MALWARE=true
```
* Add following key-value pair to _config.yml_ under the _alienvault_ key:
```yaml
guess_malware: true
```

To enable this feature in **CrowdStrike** connector:

* Add following environmental variable to _docker-compose.yml_:
```yaml
- CROWDSTRIKE_REPORT_GUESS_MALWARE=true
```
* Add following key-value pair to _config.yml_ under the _crowdstrike_ key:
```yaml
report_guess_malware: true
```

**Comment by maertv** [comment]
Merged to _master_. Closing the issue.
