### ISSUE TITLE
[Mandiant] v5.1.0 connector loops over and over again looking for an entity that doesn't exist on the platform

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#562]
## Description

Running the mandiant connector for the first time in a long time using the following config:
```
OPENCTI_URL=
OPENCTI_TOKEN=
CONNECTOR_ID=
CONNECTOR_TYPE=EXTERNAL_IMPORT
CONNECTOR_NAME=Mandiant
CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
CONNECTOR_CONFIDENCE_LEVEL=15
CONNECTOR_UPDATE_EXISTING_DATA=true
CONNECTOR_LOG_LEVEL=debug
MANDIANT_API_URL=https://api.intelligence.mandiant.com
MANDIANT_API_V3_PUBLIC=
MANDIANT_API_V3_SECRET=
MANDIANT_COLLECTIONS=reports,indicators
MANDIANT_IMPORT_START_DATE=2021-09-01
MANDIANT_INTERVAL:5
```
and looking into the logs of the connector the connector seems to be looping over and over again. Using the global search to lookup the stix-id of the entity doesn't show any relevant entities

<img width="1443" alt="Screen Shot 2021-11-30 at 2 56 30 PM" src="https://user-images.githubusercontent.com/51339113/144119229-d71b8482-79dd-4ca9-b24c-f971898e19b4.png">

**Comment by fitz003** [comment]
@SamuelHassine I'm using this connector for the first time on 5.2.4 and this is creating a loop  as described above.

**Comment by TheImmigrant** [comment]
Having the same issue as well.
```
malware--18828727-67da-52b7-8635-f12d3b9d11b9 
malware--6ce8725b-424c-5af9-b30a-5daffecf9186 
malware--275d2af1-cfac-59a3-8c1b-66ff3f3b4065 
```
