### ISSUE TITLE
Manifest files not found IVRE & import connector

### ISSUE THREAD

**Issue by Bella-chris** [OpenCTI-Platform/connectors#565]
Hello,

I tried to connect IVRE connector but whenever I run it I get the below error:
Pulling connector-ivre (opencti/connector-ivre:5.0.4)...
ERROR: manifest for opencti/connector-ivre:5.0.4 not found: manifest unknown: manifest unknown

Also for import file connector it was working fine in version 5.0.4, but once I made the update to 5.1.1 I got similar error to IVRE:
Pulling connector-import-report (opencti/connector-import-report:5.1.1)...
ERROR: manifest for opencti/connector-import-report:5.1.1 not found: manifest unknown: manifest unknown

**Comment by nor3th** [comment]
Concerning the `import-report` connector, this one has been renamed to `import-document` starting from 5.1.0.

Regards

**Comment by Bella-chris** [comment]
Thank you @SamuelHassine , now it pulled the files correctly, but it seems that the connector is not working.
Can you tell me how can I confirm it is doing the enrichment correctly? 
![image](https://user-images.githubusercontent.com/92671957/144943389-50d56031-f764-448c-87eb-efeb59d5966c.png)

**Comment by Bella-chris** [comment]
Thank you @SamuelHassine, now it pulled the image correctly, but the connector is not working:
![image](https://user-images.githubusercontent.com/92671957/144955694-a3fa02ad-5c9c-478c-86bb-0697741458ba.png)

Can you tell me if there is something else I should add to the .yml file configuration?
