### ISSUE TITLE
[CrowdStrike] Import yara rules master

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#57]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Yara rules master is not imported.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution
The weekly yara rules master shall be imported.

Replace existing rules with rules having the same name, according the the following logic
    

- Crowdstrike yara rules contain a metadata field "last_modified" which is always a Friday
- Crowdstrike yara rules are grouped in master package available every Friday
- So, in the import process, a rule having a name which already exists should replace the existing rule only if last_modified = current import date

Associate each yara rule to relevant intrusion sets or malware family based on meta data:

- actor = "PRIMITIVE BEAR" → intrusion set = "PRIMITIVE BEAR"
- malware_family = "Triceratops" → malware = "Triceratops"

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by maertv** [comment]
Merged to _master_. Closing issue.
