### ISSUE TITLE
MISP connector fails and never gets work done

### ISSUE THREAD

**Issue by AlexSanchezN** [OpenCTI-Platform/connectors#570]
## Description

MISP connector fails and never gets work done
Connector seems to connect to MISP receive some data and afterwards fails with a TypeError
In the GUI it stays 'in progress' and never ends.

## Environment

1. Ubuntu 20 latest patch
2. OpenCTI version: 5.1.2
3. OpenCTI client: Does not apply
4. Manual install, not using docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Restart o reset de connector it connects to our local MISP, and fails with the error below

## Expected Output

Lots of records imported

## Actual Output

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 499f0deb-c7c5-4952-87ee-0dd2250ed21d
INFO:root:Starting ping alive thread
INFO:root:Initiate work for 499f0deb-c7c5-4952-87ee-0dd2250ed21d
INFO:root:Connector has never run
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import", "type:osint"]}, "date_from": "2010-01-01", "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.
INFO:root:Connector successfully run (0 events have been processed), storing last_run as 1638963408, and latest_event_timestamp as None
INFO:root:Reporting work update_received opencti-work--48457785-13fb-4360-8177-71fdf3cb0ee5
INFO:root:Initiate work for 499f0deb-c7c5-4952-87ee-0dd2250ed21d
INFO:root:Connector last run: 2021-12-08 11:36:48
Traceback (most recent call last):
  File "misp.py", line 1734, in <module>
    mispConnector.run()
  File "misp.py", line 203, in run
    + datetime.utcfromtimestamp(latest_event_timestamp).strftime(
TypeError: an integer is required (got type NoneType)

## Additional information

The error was already present in 5.1.0. Tried 5.1.1 and 5.1.2

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/6607235/145202957-7b84a4b6-17fc-4f9c-9c66-3c27141c3d08.png)
The connector stays like this forever

**Comment by AlexSanchezN** [comment]
Forgot to add that other connectors are working

**Comment by AlexSanchezN** [comment]
![image](https://user-images.githubusercontent.com/6607235/145204245-2158e6d1-e01c-4b9d-9287-7b3b9481049c.png)

**Comment by pyred123** [comment]
Hi, out of curiosity, what did you use for MISP_URL? Did you use http://opencti:8080 or your local ip or something else?

**Comment by Shak3** [comment]
I too have the same error your logs after the tracback most recent call last: are the same and it just stops running, it doens't even crash or anything just stops

**Comment by AlexSanchezN** [comment]
> Hi, out of curiosity, what did you use for MISP_URL? Did you use http://opencti:8080 or your local ip or something else?

http://localhost:4000

As in all other connectors

**Comment by AlexSanchezN** [comment]
> Hi, out of curiosity, what did you use for MISP_URL? Did you use http://opencti:8080 or your local ip or something else?

No, I use https://ipofmispserver  MISP is on a diferent machine than OpenCTI. As I see on the log, it connects, it just does not do anything afterwards

**Comment by pyred123** [comment]
> > Hi, out of curiosity, what did you use for MISP_URL? Did you use http://opencti:8080 or your local ip or something else?
> 
> No, I use https://ipofmispserver MISP is on a diferent machine than OpenCTI. As I see on the log, it connects, it just does not do anything afterwards

I see, I was hoping they'd be a way to connect to MISP without running your own separate instance of it.

**Comment by PakitoSec** [comment]
duplicate #578

**Comment by Tyrell20** [comment]
Same error using the MISP connector
