### ISSUE TITLE
Alienvault connector not importing anything, just stays in progress

### ISSUE THREAD

**Issue by AlexSanchezN** [OpenCTI-Platform/connectors#571]
## Description

Alienvault connector not importing anything, just stays in progress. The logs (below) show that connection is stablished and running.

## Environment

1. Ubuntu 20 latest patch
2. OpenCTI version: 5.1.2
3. OpenCTI client: phyton
4. Manual install, not using docker
5. 
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start de connector
2. It keeps in progress

## Expected Output

Lots of pulses imported

## Actual Output

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 2178769e-76ed-42d9-9c44-6af957ea6547
INFO:root:Starting ping alive thread
INFO:root:Starting AlienVault connector...
INFO:root:Running AlienVault connector...
INFO:root:Loaded state: {}
INFO:root:Connector first run
INFO:root:Initiate work for 2178769e-76ed-42d9-9c44-6af957ea6547
INFO:root:Running pulse importer (update data: False, guess malware: False, guess cve: False, relationships: True, patterns_indicates: True)...
 
## Additional information

Updated from 5.1.0 --> 5.1.1-->5.1.2 and it has never worked for me.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/6607235/145203973-70117abb-2f00-4b41-a4c1-ada175cd6fe5.png)

**Comment by AlexSanchezN** [comment]
Forgot to add, that other connectors are working
![image](https://user-images.githubusercontent.com/6607235/145204154-6137b627-9cf8-462a-9fec-a43ee55af3ae.png)

**Comment by smclinden** [comment]
I've seen the same behavior. I've "gotten around" this by creating a cron job to restart the connector a few times a day but  I haven't had time to figure out why it is not working correctly.

**Comment by aniuse** [comment]
Getting same behavior

**Comment by AlexSanchezN** [comment]
> I've seen the same behavior. I've "gotten around" this by creating a cron job to restart the connector a few times a day but I haven't had time to figure out why it is not working correctly.

Tried, but restarting does not work. It just does the same. Hangs there 'in progress'

**Comment by smclinden** [comment]
Have you looked at your rabbitmq logs?

**Comment by AlexSanchezN** [comment]
I don't really know what to look for. :-(
All I see in rabbitmq logs is in the image below.
![image](https://user-images.githubusercontent.com/6607235/145436134-0ebf3d34-2f8c-456f-b68e-054ad8289db7.png)

**Comment by AlexSanchezN** [comment]
I rebooted my server about 11:00AM so time does not fit with the problems the log shows.

**Comment by AlexSanchezN** [comment]
Hi, that solved the issue on our testing machine.
Thanks!
