### ISSUE TITLE
[Mandiant] v5.1.2 Mandiant connector set to Reports only doesn't create any reports and ingests indicators on the Data --> Entities screen in a weird format

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#574]
## Description

Mandiant connector set to Reports only doesn't create any reports and ingests indicators on the Data --> Entities screen in a weird format. 

please refer to screenshot

## Environment
v5.1.2

![Screen Shot 2021-12-09 at 3 40 27 PM](https://user-images.githubusercontent.com/51339113/145598713-272aab4a-0bbb-46b8-9403-8644963ebc09.png)

**Comment by nor3th** [comment]
Hey @kudrew 

The screenshot shows a valid STIX indicator using the STIX Pattern format. See here for details: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_me3pzm77qfnf

Regards

**Comment by kudrew** [comment]
thanks for the link!
