### ISSUE TITLE
New import-document connector doesn't reflect on the platform

### ISSUE THREAD

**Issue by Bella-chris** [OpenCTI-Platform/connectors#575]
I have version 5.1.1 and import documents doesn't reflect on the data ingestion in the platform and the files appear t be attached only with no visual representation of them and listed in the pending files as .txt.jason document. My question is how this connector is working and how can I attach documents that reflect of the data represented over openCTI?

**Comment by nor3th** [comment]
Hey @Bella-chris 

I am not quite sure I understand your question, but here's the documentation on the predecessor of the `import-document` report (which was called `import-report` until 5.0.x)  https://www.notion.so/Import-Export-7dc143dfbb6147b0881080487ed9db33#69298813e2604f7ab98918bfc4d4c92e

Regards

**Comment by Bella-chris** [comment]
@nor3th I tried to follow the steps mentioned but the import document connector is not visible so I can import it as a PDF
<img width="405" alt="image" src="https://user-images.githubusercontent.com/92671957/145830011-f98acf3e-3fce-458a-905d-409a75b134bc.png">

I checked also connectors logs and tit seems it has an issue with the API:
Traceback (most recent call last):
  File "/opt/opencti-connector-import-document/main.py", line 7, in <module>
    connector = ReportImporter()
  File "/opt/opencti-connector-import-document/reportimporter/core.py", line 39, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):

Thanks to suggest if any additional information is needed to be added to the connector so it can reach the API

**Comment by nor3th** [comment]
It seems that the `import-document` connector is not able to contact the opencti instance. Please make sure the URL as well as the TOKEN are correct and that the connector is in the same docker network as the opencti instance.

Regards

**Comment by Bella-chris** [comment]
I think it might be the URL @nor3th .
Can you suggest how I should declare it in the config file.
I tried to make it with the server IP but it didn't work so I made it opencti. Should that do the job?

**Comment by nor3th** [comment]
Hey @Bella-chris 

Could you please share your config file?

Regards

**Comment by nor3th** [comment]
Closed due to inactivity
