### ISSUE TITLE
[MISP] latest_event_timestamp is null first launch

### ISSUE THREAD

**Issue by PakitoSec** [OpenCTI-Platform/connectors#578]
https://github.com/OpenCTI-Platform/connectors/blob/45df0056cf7c34df05282260418e69a6a85299f1/external-import/misp/src/misp.py#L194

=> Could you add the condition below in the if please because the first time this value is None and raise an exception when you convert it in a datetime.
```
and current_state["latest_event_timestamp"]
```

Don't know if this is normal.

**Comment by PakitoSec** [comment]
the first time MISP Connector import events, it crash. but after it doesn't crash because the value won't be None

**Comment by debelyoo** [comment]
I'm not sure to get your point. The if condition you mention is
```
if (
    current_state is not None
    and "last_run" in current_state
    and "latest_event_timestamp" in current_state
)
```
What do you want to change in it ?

**Comment by PakitoSec** [comment]
if (
    current_state is not None
    and "last_run" in current_state
    and "latest_event_timestamp" in current_state
    **and current_state["latest_event_timestamp"]**
)

**Comment by debelyoo** [comment]
I can't reproduce it locally.

The first time the connector runs, the state is None, and the connector fetches the events from the date set in `MISP_IMPORT_FROM_DATE`. At the end of the first run, the connector state is saved in Elasticsearch. The state contains two fields: `last_run` and `latest_event_timestamp`. Then, when the connector runs again, the state contains the two values mentioned above, and the connector polls the events from the `latest_event_timestamp`.

**Comment by pbonfa** [comment]
I have the same error in 5.1.3

**Comment by PakitoSec** [comment]
and also, you should replace 'null' with 'timestamp' in MISP req please:
docker-connector-misp-1  | INFO:root:Fetching MISP events with args: {"tags": {"OR": ["engie:enriched"]}, **"null"**: 1637833959, "limit": 50, "page": 2}
