### ISSUE TITLE
[AlienVault] Report author = alienvault pulse user

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/connectors#58]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Currently, all reports imported wth alienvault connector have author = Alienvault.
However, Alienvault is a community platform where several users shares reports and indicators.
So it is important to know which user s the author of the report (pulse).

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

Set report author = alienvault pulse user

Note: the information that the report comes from the alienvault platform should be recorded thanks to issue https://github.com/OpenCTI-Platform/opencti/issues/566#issuecomment-597526183

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by maertv** [comment]
Merged to _master_. Closing issue.
