### ISSUE TITLE
Cannot query field "platform_url" on type "Settings"

### ISSUE THREAD

**Issue by pbonfa** [OpenCTI-Platform/connectors#587]
## Description
on Elastic Threat Intel Connector docker image (opencti/connector-elastic:5.1.3) error:
Cannot query field "platform_url" on type "Settings". Did you mean "platform_email", "platform_title", or "platform_theme"?

probably due to recent change: https://github.com/OpenCTI-Platform/opencti/commit/2d4a34211c0ac01b10254103b412dc6d153e02a0

Elastic Threat Intel Connector output LOGS on docker:

[2021-12-27T15:44:02.908][INFO] Connected to OpenCTI
[2021-12-27T15:44:02.921][ERROR] Cannot query field "platform_url" on type "Settings". Did you mean "platform_email", "platform_title", or "platform_theme"?
Traceback (most recent call last):
  File "/runtime/bin/elastic", line 8, in <module>
    sys.exit(main())
  File "/runtime/lib/python3.9/site-packages/elastic/console.py", line 199, in main
    ElasticInstance = ElasticConnector(config=config, datadir=datadir)
  File "/runtime/lib/python3.9/site-packages/elastic/elastic.py", line 48, in __init__
    _settings = self.helper.api.query(query)["data"]["settings"]
  File "/runtime/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 314, in query
    raise ValueError(
ValueError: {'name': 'Cannot query field "platform_url" on type "Settings". Did you mean "platform_email", "platform_title", or "platform_theme"?', 'message': 'Cannot query field "platform_url" on type "Settings". Did you mean "platform_email", "platform_title", or "platform_theme"?'}

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20 
2. OpenCTI version: OpenCTI 5.1.3
3. OpenCTI client: python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
docker logs #CONTAINERID 
container NAME: opencti/connector-elastic:5.1.3

## Expected Output

Export to Elastic 

## Actual Output

nothing exported
 
## Screenshots (optional)
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49027974/147488911-27ac6034-bb51-4999-a120-df0d91ff85a0.png">

**Comment by SamuelHassine** [comment]
Hello @pbonfa,

Thanks for having reported this issues and sorry for the inconvenience.

We have rebuilt new 5.1.3 platform images to fix this error. Please re-pull the platform image or take the latest .tar.gz build from the release, the problem should now be solved.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Please let me know if the problem is solved.

**Comment by pbonfa** [comment]
> Please let me know if the problem is solved.

Problem solved, many thanks for your fast reply!
Regards.
