### ISSUE TITLE
[TAXII2 Connector] Unsopported Operant Type when trying to import data (TAXII2.1)

### ISSUE THREAD

**Issue by Ejento** [OpenCTI-Platform/connectors#588]
## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.03 LTS
2. OpenCTI version: OpenCTI 5.1.3
3. OpenCTI client: Python3.8-3.9
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run OpenCTI Docker
2. Wait for interface to load
3. Check the TAXII2 Collector's logs.

## Actual Output
```
INFO:root:Polling all API Roots
INFO:root:Polling entire API root fsisacprd TAXII 2.1 API Root
INFO:root:Polling Collection automated-high-gw
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection automated-high-ragw
INFO:root:Sending Bundle to server with 5 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection automated-low-gw
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection automated-low-ragw
INFO:root:Sending Bundle to server with 7 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection automated-medium-gw
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection automated-medium-ragw
INFO:root:Sending Bundle to server with 9 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection automated-vulnerabilities
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection curated-gw
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection curated-ragw
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection FSISAC Legacy Data
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Run Complete. Sleeping until next run in 2 hours
```

 
## Additional information

The collections are correct but cannot import data.

**Comment by nirmalneupane** [comment]
I am having this issue as well. Looks like the error comes from self.helper.send_stix2_bundle. Any help with this would be appreciated.
INFO:root:Polling Collection Threat Indicators Collection
INFO:root:Sending Bundle to server with 202 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root:Polling Collection Fundamentals Collection
INFO:root:Sending Bundle to server with 0 objects
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by scottzach1** [comment]
I appear to be having the same issue. With some additional logging that I have added I can see the following stack trace.

```log
INFO:root:self.update_existing_data=True
ERROR:root:Traceback (most recent call last):
  File "/opt/opencti-taxii2/taxii2.py", line 241, in send_to_server
    self.helper.send_stix2_bundle(
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 641, in send_stix2_bundle
    file_name = kwargs.get("file_name", work_id + ".json")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I have investigated this a bit further and have tracked this down to `self.helper.send_stix2_bundle` expecting the keyword arguments `work_id` and `file_name` (see [taxii2.py:219](https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/taxii2/src/taxii2.py#L219).

The problem appears to be introduced in the `pycti` commit https://github.com/OpenCTI-Platform/client-python/commit/cbe9026a139fa398e0640d58d537293b1594e444.  This commit was part of the change from the bump from [OpenCTI-Platform/client-python@5.0.3..5.1.0](https://github.com/OpenCTI-Platform/client-python/compare/5.0.3...5.1.0). The most up to date version of the taxii2 connector does not provide such keyword arguments.

For those stuck on this issue I think the best solution might be to rollback Docker containers to https://github.com/OpenCTI-Platform/docker/commit/c7d570a9a39f141ec7af1cd83f33c925f837517f (5.0.3) and [OpenCTI-Platform/connectors@5.0.3](https://github.com/OpenCTI-Platform/connectors/releases/tag/5.0.3)? Unfortunately, I am still encountering some incompatibilities here but I'll try post an update if I get any luck with the rollback tomorrow. 😄

**Comment by scottzach1** [comment]
Thank you @nor3th, I can confirm https://github.com/OpenCTI-Platform/client-python/pull/240 and https://github.com/OpenCTI-Platform/client-python/pull/239 resolve this issue. 😄 

It might be worth keeping this issue open until the changes in client-python are included in the next release tag (and [`external-import/taxii2/src/requirements.txt`](https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/taxii2/src/requirements.txt) points to it)?

**Comment by nor3th** [comment]
Hey @scottzach1 

Great :) Yes I am currently coordinating if we will only release a hotfix or release 1.5.4 during the upcoming weeek.

Regards
