### ISSUE TITLE
New IOCs Connector to implement inside OpenCTI

### ISSUE THREAD

**Issue by Jacopo-Inglese** [OpenCTI-Platform/connectors#589]
Hello everyone, I kindly wanted to ask you if it was possible to have a connector already ready that allows me to collect on the opencti platform
many IOCs for free.
I would need that the connector is not already present in the ecosystem published here "https://www.notion.so/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76". Furthermore, the connector must NOT already be present among these:
-trend micro
- ibm x force exchange
-cluster 25
-yoroi
-fireEye
-blinking computer
-security affairs.
Thank you in advance and wish you happy holidays

**Comment by nor3th** [comment]
Hey @Jacopo-Inglese 

Fireeye/mandiant is already supported. What kind of information would you like to ingest from security affairs or blinking computer?

Regards

**Comment by Jacopo-Inglese** [comment]
Hi @nor3th  , I would like to have a NEW connector which can give me some IOC . The connector cannot be one of the connectors inside the list below ( it CANNOT be choosen from any of this beacuse they are just supported inside OpenCTI) .Can you help me ? Thanks a lot .
 THE LIST OF CONNECTORS IS THIS :
-trend micro
-ibm x force exchange
-cluster 25
-yoroi
-fireEye
-blinking computer
-security affairs.

**Comment by nor3th** [comment]
Closed due to inactivity
