### ISSUE TITLE
connector-abuseipdb: TypeError: 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by pbonfa** [OpenCTI-Platform/connectors#591]
I'm running OpenCti 5.1.3 on docker; I have a problem with connector-abuseipdb:

INFO:pika.adapters.blocking_connection:Created channel=1
INFO:root:Reporting work update_received opencti-work--ec2e9e25-484b-493d-801b-868176320d01
INFO:root:Reading StixCyberObservable {919b82aa-b1e7-40e7-ab95-462c7822b751}.
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 163, in _data_handler
    message = self.callback(json_data["event"])
  File "/opt/opencti-connector-abuseipdb/abuseipdb.py", line 62, in _process_message
    for marking_definition in observable["objectMarking"]:
**TypeError: 'NoneType' object is not subscriptable**
INFO:root:Reporting work update_received opencti-work--ec2e9e25-484b-493d-801b-868176320d01
INFO:root:Message (delivery_tag=1) processed, thread terminated
****

Can you help me?
regards

**Comment by nor3th** [comment]
Hey @pbonfa 

I'll fix this in the upcoming release. As a quick hotfix, add a TLP value to the observable and the enrichment will work.

Regards
