### ISSUE TITLE
New IOCs Connector to implement inside OpenCTI 

### ISSUE THREAD

**Issue by Jacopo-Inglese** [OpenCTI-Platform/connectors#593]
Hello everyone, I kindly wanted to ask you if it was possible to have a connector already ready that allows me to collect on the opencti platform
many IOCs for free.
I would need that the connector is not already present in the ecosystem published here "https://www.notion.so/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76". Furthermore, the connector must NOT already be present among these:
-trend micro

ibm x force exchange
-cluster 25
-yoroi
-fireEye
-blinking computer
-security affairs.
Thank you !

**Comment by nor3th** [comment]
Closing this due to duplicate #589
