### ISSUE TITLE
[MITRE] Despite "report" being removed from Connector Scope, reports are still generated

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/connectors#594]
## Description

The biggest source of "noise" in the Mitre Connector has to do with Reports that only contain a single object. In an effort to just get the object, but not the report, we removed "report" from the "Connector Scope" parameter of the compose file. However, reports were still created when we turned on the connector

## Environment

1. OS (where OpenCTI server runs): Ubunto 18.04
2. OpenCTI version: 5.1.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Remove "report" 

## Expected Output

MITRE objects are created, but not in the context of reports

## Actual Output

MITRE objects are created, and they all come inside a report. A majority of the reports contain a single object.

**Comment by nor3th** [comment]
Hey @securitiz 

We'll look into this. I am not sure though if this is a connector issue and an opencti issue.

Regards

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Can you please share your connector scope?

Please be aware of the  `external-reference-as-report` is also creating reports based on all external references contained in the dataset.

Kind regards,
Samuel

**Comment by securitiz** [comment]
We do have external-reference-as-report enabled - maybe that's what I should've disable. What I'm trying to avoid is reports like this one, where there is only a single object there, like this one: https://demo.opencti.io/dashboard/analysis/reports/703366c0-3cf1-47ff-8409-98dfee3f3dc5
