### ISSUE TITLE
[misp] "Missing reference to handle creation" with MISP Connector when connector_update_existing_data set to True

### ISSUE THREAD

**Issue by elouieibm** [OpenCTI-Platform/connectors#598]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description
After starting with a fresh Elasticsearch database and configuring the MISP Connector with connector_update_existing_data=True, I am getting a "MissingReferenceError" error in the worker log files.  If I set connector_update_existing_data=false then everything is fine.  

## Environment

1. OS (where OpenCTI server runs): RHEL 7.9
2. OpenCTI version: 5.1.3
3. OpenCTI client: Front-end 
4. Other environment details: Running in Docker.  MISP data is coming from an internal MISP server.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Ensure connector_update_existing_data is set to True in the MISP Connector 
2. Reset the MISP Connector state in the UI
3. Wait for bundles to be collected
4. Check Worker logs.  The following appears multiple times...
INFO:root:Processing a new message (delivery_tag=913), launching a thread...
INFO:root:Creating Stix-Cyber-Observable {Domain-Name} with indicator at None.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=913) reprocess (retry nb: 1)
INFO:root:Creating Stix-Cyber-Observable {Domain-Name} with indicator at None.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=913) reprocess (retry nb: 2)
INFO:root:Creating Stix-Cyber-Observable {Domain-Name} with indicator at None.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=913) reprocess (retry nb: 3)
INFO:root:Creating Stix-Cyber-Observable {Domain-Name} with indicator at None.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=913) reprocess (retry nb: 4)
INFO:root:Creating Stix-Cyber-Observable {Domain-Name} with indicator at None.
ERROR:root:Missing reference to handle creation
ERROR:root:{'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}
INFO:root:Report expectation for opencti-work--b8de15d4-c823-4768-9501-ce0f0fdaab0a
ERROR:root:Error updating elastic
ERROR:root:Cannot report expectation
INFO:root:Message processed, thread terminated

From the troubleshooting guide, the error is occurring because an element required to create another element is missing.  When setting the "connector_update_existing_data=true", does the data coming from the MISP server have to be the correct "order" to ensure all required elements are created first?

Thank you.

**Comment by nor3th** [comment]
Hey @elouieibm 

Sorry for the delayed response. `connector_update_existing_data` should only give the connector the right to update existing observables and such. Otherwise they are left alone.
What exactly do the elastic logs say, since there seems to be some elastic issues
```
ERROR:root:Error updating elastic
ERROR:root:Cannot report expectation
```

> does the data coming from the MISP server have to be the correct "order" to ensure all required elements are created first?

Hmm, I think the connector library should figure that out by itself.

Regards
