### ISSUE TITLE
ExportReportPdf Connector Does Not Exist in DockerHub

### ISSUE THREAD

**Issue by leetn00b** [OpenCTI-Platform/connectors#600]
## Description

I can see there is an ExportReportPdf Connector at https://www.notion.so/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76?p=8fd18895674448128da212b4548aa3e0 yet it does not exist in Dockerhub.

**Comment by nor3th** [comment]
Hey @leetn00b 

Thanks for reporting this. We'll fix it for the upcoming release.
https://github.com/OpenCTI-Platform/connectors/commit/04ba52a9ceac4c314bbf6b102580ee4317d0bea7

Regards

**Comment by nor3th** [comment]
The docker image exists again. Until the release of 1.5.4, only the `rolling` version will be avaliable.

Regards
