### ISSUE TITLE
Riskiq Connector throwing errors

### ISSUE THREAD

**Issue by labtest06** [OpenCTI-Platform/connectors#606]
## Description

RiskIQ connector is not working as expected with the correct credentials defined.

## Environment

1. OS - Ubuntu 
2. OpenCTI version: 5.1.3

## Riskiq Connector Logs:
INFO:root:Listing Threat-Actors with filters null.,
INFO:root:Connector registered with ID: c455a3a4-cc8f-4133-9f8d-4098fa984de8,
INFO:root:Starting ping alive thread,
INFO:riskiq.client:URL: https://api.riskiq.net/pt/v2,
INFO:root:Starting RiskIQ connector...,
INFO:root:Running RiskIQ connector...,
INFO:root:Connector interval sec: 60,
INFO:root:[RiskIQ] loaded state: {},
INFO:root:RiskIQ connector clean run,
INFO:root:Initiate work for c455a3a4-cc8f-4133-9f8d-4098fa984de8,
INFO:root:[RiskIQ] workid opencti-work--2c314a8c-484e-4a68-9b31-bb782b3b22ed initiated,
INFO:root:[RiskIQ] last run: None,
**ERROR:root:Parser must be a string or character stream, not NoneType **

![image](https://user-images.githubusercontent.com/92973503/151704741-cd22d3ec-4963-4f7f-becd-d4930a9d0798.png)

++Config File++

  connector-riskiq:
    image: opencti/connector-riskiq:5.1.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=c9dc7053-6bdf-44ca-9dfd-c0e3ff249eb8
      - CONNECTOR_ID=c455a3a4-cc8f-4133-9f8d-4098fa984de8
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=RISKIQ
      - CONNECTOR_SCOPE=riskiq
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - RISKIQ_BASE_URL=https://api.riskiq.net/pt/v2
      - RISKIQ_USER=xxx@testing.com
      - RISKIQ_PASSWORD=xxxxxxx
      - RISKIQ_INTERVAL_SEC=86400
    restart: always

It was working before, after a reboot the riskiq connector started logging the above error as "ERROR:root:Parser must be a string or character stream, not NoneType".

Please help to fix the same.

Thanks

**Comment by nor3th** [comment]
@axelfahy : Any idea where that error could come from?

**Comment by axelfahy** [comment]
I can reproduce, it seems the API is not providing the `publishedDate` anymore. I'll fix it.
