### ISSUE TITLE
Cyber Threat Coalition URL unreachable

### ISSUE THREAD

**Issue by Zhindonm** [OpenCTI-Platform/connectors#613]
## Description

The [Cyber Threat Coalition connector](https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/cyber-threat-coalition) is not working because the URL https://blacklist.cyberthreatcoalition.org/vetted is unreachable.

## Expected Output

Import data

## Actual Output

No data imported. Error log from container see below.

```
INFO:root:Listing Threat-Actors with filters null.

INFO:root:Connector registered with ID: a842d1e2-84f2-11ec-a8a3-0242ac120002

INFO:root:Starting ping alive thread

INFO:root:Fetching Cyber Threat Coalition vetted blacklists...

INFO:root:Loaded state: {}

INFO:root:Initiate work for a842d1e2-84f2-11ec-a8a3-0242ac120002

ERROR:root:('Unable to fetch {0} blacklist, server returned status: {1}', 'domain', 522)
```
 
## Screenshot

Website is unreachable in a browser as well

![image](https://user-images.githubusercontent.com/32451415/152351563-53314c90-ae11-429e-8dd0-f6dc64966350.png)

**Comment by nor3th** [comment]
Hey @Zhindonm 

Thanks for reporting this issue. Since this is a backend issue on the Cyber Threat Coalition's side and nothing directly connected to the connector, there's nothing we can do. Please contact the CTC team regarding this issue.

Regards
