### ISSUE TITLE
Alienvault connector not importing anything, just stays in progress

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/connectors#615]
## Description

Hello,

I have issues with AV connector.
Alienvault connector not importing anything, just stays in progress, day after day.

## Environment

1. Ubuntu 20.04
2. OpenCTI version: 5.1.4
3. OpenCTI client: python
4. Other environment details: Docker

## Screenshots (optional)

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/50768/153169203-d6020199-5618-4f15-99c4-7654f857163d.png">

**Comment by richard-julien** [comment]
Hi @AntoninHL ,

Looks like the connector successfully push stix bundle into the queue.
Do you have any worker deployed?

**Comment by AntoninHL** [comment]
Don't know...
To be honest, I'm a CTI expert... Not a dev specialist.
😉

**Comment by rabbipigeon** [comment]
@richard-julien 

Hey Richard, I had the same issue and your comment led me to the fix, had 1 worker up and queue was filling up but ingestion was days delayed. So Thank you for the tip.

### Questions

- workers service connectors only or connectors and users?
- how many workers is a good number, does it depend on number of connectors or their activity?
