### ISSUE TITLE
Failed to reactivate/reinstall connector

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/connectors#616]
## Description

Because I had too many issues with Crowdstrike connector, I clicked on "Clear this connector" icon on the GUI connectors page.
In the yml conf file, config is still here.
I tried 
`docker-compose.yml -d` 

to restart everything... but nothing.

I removed the CS connector in the config file
and `docker-compose.yml -d` 
and redo the CS connector in the config file
and `docker-compose.yml -d` 

Still nothing.
Reboot.
Still nothing.

Do you have any idea?

Thanks

## Environment

1. Ubuntu 20.04
2. OpenCTI version: 5.1.4
3. OpenCTI client: python
4. Other environment details: docker

**Comment by richard-julien** [comment]
HI @AntoninHL ,

Clear button is here to cleanup the connector state only.

Please check your connector logs to see if you have some errors.

**Comment by AntoninHL** [comment]
Don't know how to do this. 

To be honest, I'm a CTI expert... Not a dev specialist.
😉

**Comment by AntoninHL** [comment]
Hello,

found the problem.
