### ISSUE TITLE
Kaspersky Certificate Path

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/connectors#617]
## Description

I try to configure Kaspersky Connector.
I have creds + pem certificate file.
Configuration is made for the connector:

`- KASPERSKY_CERTIFICATE_PATH=/home/opencti/kaspersky.pem`

When I start, here is what I have in logs:

`ERROR:root:Kaspersky connector internal error: Could not find the TLS certificate file, invalid path: /home/opencti/kaspersky.pem`

For information, I removed
```
    secrets:
      - kaspersky_certificate

secrets:
  kaspersky_certificate:
    file: /home/opencti/kaspersky.pem  # Change to correct path.
```

because of systematic error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "secrets". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```

## Environment

1. OS Ubuntu 20.04
2. OpenCTI 5.1.4
3. OpenCTI client: python
4. Other environment details: docker

**Comment by nor3th** [comment]
Hey @AntoninHL 

Google gave me a good lead based on the error log:
https://stackoverflow.com/questions/48154093/invalid-top-level-property-external-links

Regards
