### ISSUE TITLE
AlienVault Connector

### ISSUE THREAD

**Issue by adis3421** [OpenCTI-Platform/connectors#622]
HI,

I have a problem with connector alienvault via proxy because my server network is isolated from internet and all comunication to internet go via proxy. Connector is running and worker too but nothing to do. I have config proxy in my Rocky Linux. I use manual deployment in my enviroment. Mayby I reconfig file config.yml?? I don't know

Regards,
AN

**Comment by SamuelHassine** [comment]
Hello,

The Python connector should be able to use the global Linux proxy environment variables. Did you try that?

Kind regards,
Samuel

**Comment by adis3421** [comment]
Hi,

Thanks for reply. The problem was with my proxy, it didn't trust otx... cert. 
When I try set:
https_proxy=http:my_proxy:port in /etc/enviroment
then i recived error connect connector to OpenCTI:
"OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
so I use temporary solution and i run command:
export https_proxy=...

If you have another idea I will be glad to know. 

Regards,
AN
