### ISSUE TITLE
[Elastic Security] Connector fails to launch

### ISSUE THREAD

**Issue by navardituned** [OpenCTI-Platform/connectors#633]
## Description
I have attempted to install Elastic Connector for OpenCTI, but I am getting errors upon starting the connector as it attempts to connect and create ILM policy in Elasticsearch.

## Environment

1. Ubuntu Server 21.10
2. OpenCTI version: 5.2.1
3. OpenCTI environment: Docker
4. Other environment details: ELK Stack running on host, ELK Stack Version: 8.1.0

Connector is fed the config.yml in the docker compose file.
I am using the Elastic CertUtil Self signed certs, and have linked them into the config.yml
I have configured all the hosts, disabled ssl verify. 
The connector establishes a connection to OpenCTI and Elasticsearch, but fails on making the index - using default ILM settings (have tried disabling ILM but the Elastic index creation fails with a different error)

everything else in OpenCTI and my ELK stack appear to be running correctly. Any advice would be greatly appreciated.
In Kibana, I can see the Index Template created by the connector as well as the indicies and Index Lifecycle Policy.

Attached is the Error Log:
>[2022-03-20T01:30:10.200][INFO] Using default data directory: /runtime/lib/python3.9/site-packages/elastic/data
[2022-03-20T01:30:10.646][INFO] Connected to OpenCTI
/runtime/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py:209: UserWarning: Connecting to https://192.168.51.11:9200 using SSL with verify_certs=False is insecure.
  warnings.warn(
[2022-03-20T01:30:10.695][INFO] Connected to Elasticsearch
[2022-03-20T01:30:10.696][INFO] Setting up Elasticsearch for OpenCTI Connector
[2022-03-20T01:30:10.706][WARNING] GET https://192.168.51.11:9200/_ilm/policy/opencti [status:404 request:0.001s]
[2022-03-20T01:30:10.706][WARNING] HTTP 404: Lifecycle policy not found: opencti
[2022-03-20T01:30:10.706][INFO] Creating ILM policy opencti
[2022-03-20T01:30:10.836][INFO] Installing index template: opencti
[2022-03-20T01:30:11.025][INFO] Parsing index pattern: opencti-{now/d}-000001
[2022-03-20T01:30:11.025][INFO] Initial index: <opencti-{now/d}-000001>
Alias: opencti
[2022-03-20T01:30:11.027][INFO] Creating alias 'opencti' to pattern '<opencti-{now/d}-000001>'
[2022-03-20T01:30:11.691][INFO] Initial index <opencti-{now/d}-000001> created.
Traceback (most recent call last):
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 73, in traverse
    value = value[key]
TypeError: 'NoneType' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/runtime/bin/elastic", line 8, in <module>
    sys.exit(main())
  File "/runtime/lib/python3.9/site-packages/elastic/console.py", line 199, in main
    ElasticInstance = ElasticConnector(config=config, datadir=datadir)
  File "/runtime/lib/python3.9/site-packages/elastic/elastic.py", line 58, in __init__
    self.sightings_manager = SignalsManager(
  File "/runtime/lib/python3.9/site-packages/elastic/sightings_manager.py", line 49, in __init__
    _interval: str = self.config.get("elastic.signals.query_interval", "5m")
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 199, in get
    return self[path]
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 142, in __getitem__
    item = traverse(data=self.data, keys=keys, original_path=path)
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 79, in traverse
    raise type_error(key, original_path, value)
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 37, in type_error
    raise TypeError(
TypeError: Cannot access key 'signals' in path 'elastic.signals.query_interval': the element must be a dictionary or a list but is of type '<class 'NoneType'>'.

Attached are my docker Compose and Config.yml files:
```opencti:
  url: 'http://192.168.51.11:8080'
  token: '875f62ac-52ab-40ea-87b5-67b4cb22e7a4'
  ssl_verify: False
connector:
  id: '64ed7d87-98d9-49ab-8085-67e36680911f'
  type: 'STREAM'
  name: 'OpenCTI Elastic Connector'
  scope: 'elastic'
  confidence_level: 80 # From 0 (Unknown) to 100 (Fully trusted). Used for Sightings reported to OpenCTI
  log_level: 'info'
  entity_name: 'Elastic Detection Cluster'
  entity_description: 'Elasticsearch detection engine cluster'
  live_stream_id: 'live'
  mode: ecs # Options are 'ecs' (indicators only) or 'stix' (raw STIX documents)
# =============================== Elastic Cloud ================================
# The cloud.id setting overwrites the `elastic.hosts`
# You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:
# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
# API key is recommended
#cloud.auth:
output.elasticsearch:
  # ---------------------------- Elasticsearch Output ----------------------------
  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify an additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  hosts: ["https://192.168.51.11:9200"]
  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  #username: "elastic"
  #password: "redacted"
  ssl_verify: false
  ssl.certificate_authorities: ["/app/certs/ca/ca.crt"]
  ssl.certificate: "/app/certs/ca/ca.crt"
  ssl.key: "/app/certs/ca/ca.key"
  # Optional index name. The default is "opencti" plus the date. Uses Elastic date math syntax.
  # Custom index settings are ignored when ILM is enabled.  Be sure to update
  # `setup.template.pattern` if you change the output index.
  #index: "opencti-{now/d}"
# ====================== Index Lifecycle Management (ILM) ======================
# Configure index lifecycle management (ILM). These settings create a write
# alias and add additional settings to the index template. When ILM is enabled,
#output.elasticsearch.index
setup:
  ilm:
    enabled: true
    policy_name: opencti
    rollover_alias: opencti
    # This pattern uses datemath. See https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html
    pattern: "{now/d}-000001"
    overwrite: true
  template:
    enabled: true
    name: opencti
    # This pattern value is used when applying the template, but also used when applying
    # document updates. Make sure this matches the output indices in all cases.
    pattern: opencti-*
    overwrite: true
elastic:
  # ---------------------------- Sightings Settings ----------------------------
  # (optional) This is to fine tune how we find signals generated by the detection engine
  # These are all the defaults, you don't need to change anything or even include it.
  # You could modify the query if you wanted to add some additional criteria.
  # You could also change the signal_index pattern if you had a non-default space in
  # Kibana that you wanted to use to limit the results
  # signals:
  #   query_interval: '5m'
  #   lookback_interval: '5m'
  #   signal_index: '.siem-signals-*'
  #   query: >
  #     {
  #       "query": {
  #         "bool": {
  #           "must": {
  #             "match": { "signal.rule.type": "threat_match" }
  #           }
  #         }
  #       }
  #     }
  # (optional) TLP to use when importing sightings from Elastic, defaults to empty
  #sightings_tlp:
```

```
version: '3'
services:
  connector-elastic:
    image: opencti/connector-elastic:latest
    network_mode: "host"
    depends_on:
      - opencti
    volumes:
      - cyber_certs:/app/certs
    restart: unless-stopped
    command:
      --config=/app/certs/config.yml 
volumes:
  cyber_certs:
    external: true
```

**Comment by SamuelHassine** [comment]
@dcode Any idea on this one?

**Comment by dcode** [comment]
@navardituned, I know this is older, but uncomment the line section under `elastic`. Those are the default values anyway. I just ran across this with another team that was trying to use it. `elastic.sightings` doesn't get initialized as it should.

**Comment by bakhtawarw** [comment]
Hi @navardituned did this bug get resolved?
@dcode @SamuelHassine  I'm getting the same error. I uncommented the line section under elastic but still the bug didn't resolve.

**Comment by dcode** [comment]
I'll take a look at this today.

**Comment by bakhtawarw** [comment]
> I'll take a look at this today.

Alright, thanks. I am looking forward to it.
