### ISSUE TITLE
CVE connectors ERROR

### ISSUE THREAD

**Issue by LinShiG0ng** [OpenCTI-Platform/connectors#640]
### This is the ERROR message

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: ChangeMe
INFO:root:Starting ping alive thread
INFO:root:Fetching CVE knowledge...
INFO:root:Connector has never run
INFO:root:Initiate work for ChangeMe
INFO:root:Requesting the file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
INFO:root:Unzipping the file
INFO:root:Converting the file
INFO:root:Update action expectations opencti-work--913379fc-e7eb-413d-bf80-ae69bc8a50aa - 561
ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(8, 'nodename nor servname provided, or not known')
ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(8, 'nodename nor servname provided, or not known').
ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(8, 'nodename nor servname provided, or not known'); first exception - None.
ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(8, 'nodename nor servname provided, or not known'); first exception - None
ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(8, 'nodename nor servname provided, or not known'); first exception - None
ERROR:pika.adapters.blocking_connection:Error in _create_connection().
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
ERROR:root:[Errno 8] nodename nor servname provided, or not known
INFO:root:Connector stop

### ENV
version: '3'
services:
  connector-cve:
    image: opencti/connector-cve:5.2.1
    environment:
      - OPENCTI_URL=http://xxx.xxx.xxx.xxx:8080/graphql
      - OPENCTI_TOKEN=xxxxxxx-3fd8-4bd2-xxxxx-xxxxxxxx
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Common Vulnerabilities and Exposures
      - CONNECTOR_SCOPE=identity,vulnerability
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - CVE_IMPORT_HISTORY=true # Import history at the first run (after only recent), reset the connector state if you want to re-import
      - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
      - CVE_HISTORY_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/
      - CVE_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always

networks:
  opencti-default:
    external:
      name: opencti-default

**Comment by nor3th** [comment]
Hey @LinShiG0ng 

```
ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(8, 'nodename nor servname provided, or not known')
ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(8, 'nodename nor servname provided, or not known')
```
The CVE connector is unable to interact with RabbitMQ, due to the way opencti lets the connectors know how to connect to RabbitMQ. The issue is that the RabbitMQ hostname is defined here https://github.com/OpenCTI-Platform/docker/blob/4a274c53f694734cbfd9302a222ab67443f351f3/docker-compose.yml#L64 , but the connector which is hosted in a different docker-compose file is unable to resolve `rabbitmq`.

Either rename the line mentioned above in the opencti docker compose file to maybe `opencti_rabbitmq`, merge the new connector to the existing opencti docker compose file or (least pretty) use the docker IP for the rabbitmq hostname. This way the cve should be able to connect to RabbitMQ. However a restart of the opencti connectors might change the IPs and then request a manual IP change again.

Regards
