### ISSUE TITLE
URLHaus Errors data import

### ISSUE THREAD

**Issue by innerfirebg** [OpenCTI-Platform/connectors#644]
## Description

The Connector "Abuse.ch URLhaus"  keep creating errors when's import data!

## Environment

1. OS  Ubuntu 21.10
2. OpenCTI version: 5.2.2 (all)
4. Other environment details:
Redis 6.2.6
RabbitMQ 3.9.13

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Restart the server and wait. Connector start automatically to pull the data and start to generate errors…

## Expected Output

Finish without any errors.

## Actual Output

![image](https://user-images.githubusercontent.com/47434937/160369680-e56a51aa-c07e-48f0-96a7-48f978c6d2e2.png)
![image](https://user-images.githubusercontent.com/47434937/160369756-e734f8ff-0834-435f-a74e-52a20758c2da.png)
 
## Additional information

I try to re-pull the images and restart everything, but won't work.
Then try to delete the jobs, but won't work.

**Comment by richard-julien** [comment]
Hi @innerfirebg,
Looks like you have an id in the platform associated to multiple instance, that is not a normal situation.
Can you search for the ID of the created_by_ref in the platform to check if you have multiple results for it?
![image](https://user-images.githubusercontent.com/285555/160374859-4346503f-fba4-4e5b-8925-448d7ed5ed7c.png)

**Comment by innerfirebg** [comment]
Hi @richard-julien I check it, and it's only one. I will try to regenerate Connector_ID.

**Comment by innerfirebg** [comment]
Yes, i think is Ok now, Thanks!

**Comment by innerfirebg** [comment]
Hi @richard-julien the problem still persist, after I recreate the connector this ID still shows (0303206b…) in errors log.
