### ISSUE TITLE
[MITRE] relationships errors in connector

### ISSUE THREAD

**Issue by axelfahy** [OpenCTI-Platform/connectors#647]
## Description

The connector generates some errors when creating relationships. 

They are two types of errors: 
```
{'name': 'UnsupportedError', 'message': 'Relation cant be created with the same source and target'}
```
and 
```
{'name': 'FunctionalError', 'message': 'The relationship type uses is not allowed between Tool and Attack-Pattern'}
```
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.2.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start the MITRE connector
2. Look for error in the frontend, on the connector page. 
3. 
![image](https://user-images.githubusercontent.com/7095119/160822708-450a0f53-ef4d-4e5f-be37-367edce1b355.png)

## Expected Output

No errors when creating relationships. 

## Actual Output

```
{'name': 'UnsupportedError', 'message': 'Relation cant be created with the same source and target'}
```
and 
```
{'name': 'FunctionalError', 'message': 'The relationship type uses is not allowed between Tool and Attack-Pattern'}
```

**Comment by nor3th** [comment]
Hey @axelfahy 

Sorry about that inconvenience, this relationship has already been reintroduced for the next milestone.
https://github.com/OpenCTI-Platform/opencti/commit/c11da3f13e0cd2d229e89b3f6601cb192d91a033

Regards
