### ISSUE TITLE
[MITRE Datasets]Migrate to STIX 2.1

### ISSUE THREAD

**Issue by nor3th** [OpenCTI-Platform/connectors#650]
Use https://github.com/mitre-attack/attack-stix-data repository for STIX 2.1 ATT&CK instead of https://github.com/mitre/cti which is STIX 2.0

**Comment by SYNchroACK** [comment]
_If you are looking for ATT&CK represented in STIX 2.1, please see the [attack-stix-data](https://github.com/mitre-attack/attack-stix-data) GitHub repository. Both MITRE/CTI (this repository) and attack-stix-data will be maintained and updated with new ATT&CK releases for the foreseeable future, but the data model of attack-stix-data includes quality-of-life improvements not found on MITRE/CTI. Please see the [attack-stix-data USAGE document](https://github.com/mitre-attack/attack-stix-data) for more information on the improved data model of that repository._
