### ISSUE TITLE
[Mandiant] Connector config to allow the filter of reports that get ingested. 

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#652]
## Use case

Currently the Mandiant connector pulls all reports from the mandiant api. 
We would like the ability to configure the types of reports that the connector can filter out (ie: do not include vulnerabilities, only include threat intelligence and related reports/ threat actor, threat report, etc).

**Comment by nor3th** [comment]
That's currently not possible, but this feature will be part of https://github.com/OpenCTI-Platform/client-python/issues/206

Regards

**Comment by SamuelHassine** [comment]
Hello @kudrew,

Please can you tell me if this issue is still relevant with the new version of the Mandiant connector?

Thanks.

Kind regards,
Samuel

**Comment by TheImmigrant** [comment]
@kudrew I have implemented this feature, will you be willing to test it ?
