### ISSUE TITLE
[MISP] First start timestamp bug

### ISSUE THREAD

**Issue by nullparasite** [OpenCTI-Platform/connectors#656]
## Description

MISP connector does not use the "MISP_IMPORT_FROM_DATE" value provided by the configuration file.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20
2. OpenCTI version: 5.2.4
3. OpenCTI client: python, frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure MISP importer, and set "MISP_IMPORT_FROM_DATE" to different value.
2. MISP importer will start from the 1970.
 
## Additional information

The problem related with the below codeblock (https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp/src/misp.py#L264):

```
kwargs["date_from"] = import_from_date.strftime("%Y-%m-%d")
```

We need to change it to something like:

```
kwargs[self.misp_datetime_attribute] = import_from_date.strftime("%s")
```
Now, it works. What do you think?

**Comment by nor3th** [comment]
@SamuelHassine What are your thoughts on the proposition?
