### ISSUE TITLE
OpenCTI Mandiant Connector

### ISSUE THREAD

**Issue by annoyingapt** [OpenCTI-Platform/connectors#685]
## Prerequisites

- [Y] I read the [Deployment and Setup](https://luatix.notion.site/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://luatix.notion.site/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [Y] I went through old GitHub issues and couldn't find anything relevant
- [Y] I googled the issue and didn't find anything relevant

## Description

I'm having issues authenticating against the Mandiant API. I have a paid subscription and access to APIv4 ID and Key.
I think I'm doing something stupid, but can't figure out what it is. I basically want to confirm that this service isn't limited to the free subscription and works with version4.

Using their Swagger page (https://api.advantage.mandiant.com/#/) I can confirm the following page pulls indicators.
https://api.intelligence.fireeye.com/v4/indicator?start_epoch=1650252749&limit=10

## Environment

1. OS (where OpenCTI server runs): Portainer stack
2. OpenCTI version: OpenCTI 5.2.4
3. Mandiant Connector version: 5.2.4

## Mandiant Connector

connector-mandiant:
    image: opencti/connector-mandiant:5.2.4
    environment:
      - OPENCTI_URL=${OPENCTI_GUI_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MANDIANT}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Mandiant
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=debug
      - MANDIANT_API_URL=https://api.intelligence.mandiant.com
      - MANDIANT_API_V3_PUBLIC=${MANDIANT_API_ID}
      - MANDIANT_API_V3_SECRET=${MANDIANT_API_SECRET}
      - MANDIANT_COLLECTIONS=reports,indicators
      - MANDIANT_IMPORT_START_DATE=2022-01-01
      - MANDIANT_INTERVAL=5 # Required, in minutes
    restart: always
    depends_on:
      - opencti

Steps to create the smallest reproducible scenario:
1. Add connector to OpenCTI stack
2. Check logs on container

## Output

INFO:root:Listing Threat-Actors with filters null.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): opencti:8080
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 144
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 454
INFO:root:Connector registered with ID: 014f2f6e-1e87-4a56-b4e9-db9a9d8320d6
INFO:root:Starting ping alive thread
INFO:root:Creating Identity {Mandiant}.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): opencti:8080
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 264
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 512
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 98
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.intelligence.mandiant.com:443
DEBUG:urllib3.connectionpool:https://api.intelligence.mandiant.com:443 "POST /token HTTP/1.1" 200 None
INFO:root:Synchronizing with Mandiant API...
INFO:root:Initiate work for 014f2f6e-1e87-4a56-b4e9-db9a9d8320d6
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 81
INFO:root:Get indicators created after None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.intelligence.mandiant.com:443
DEBUG:urllib3.connectionpool:https://api.intelligence.mandiant.com:443 "GET /collections/indicators/objects?added_after=1640995200.0&length=100 HTTP/1.1" 403 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.intelligence.mandiant.com:443
DEBUG:urllib3.connectionpool:https://api.intelligence.mandiant.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.intelligence.mandiant.com:443
DEBUG:urllib3.connectionpool:https://api.intelligence.mandiant.com:443 "GET /collections/indicators/objects?added_after=1640995200.0&length=100 HTTP/1.1" 403 None
ERROR:root:Query failed, permission denied
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 225

**Comment by SamuelHassine** [comment]
Connector has been fully reworked in 5.3.0.
