### ISSUE TITLE
[import-document] 5.3.0 import document error

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#689]
5.3.0 on reproduced on Demo: 

https://demo.opencti.io/dashboard/analysis/reports/7f5928a1-7a42-43d6-bebd-83a164e6429b/files

**Comment by nor3th** [comment]
@SamuelHassine Any chance ReportImporter is referencing to `self.file` when this if condition isn't met https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-document/src/reportimporter/core.py#L89-L96 ?
