### ISSUE TITLE
History connector removal

### ISSUE THREAD

**Issue by mattseymour** [OpenCTI-Platform/connectors#701]
## Description

I noticed that the connector connector-history has been removed from the repository as of commit 8d30cce539a5edddc

I also notice Issue https://github.com/OpenCTI-Platform/connectors/issues/675

The change log / release notes do not seem to make mention of this removal, has the connector now been removed as its in Opencti core? How important is it this connector is deactivated prior to upgrade and what should the upgrade path be?

## Environment

Opencti 5.3.0+

**Comment by SamuelHassine** [comment]
Re @mattseymour,

By the way, the release note is actually mentioning the removal of the connector: https://github.com/OpenCTI-Platform/opencti/releases/tag/5.3.0.

**Comment by mattseymour** [comment]
Is it possible to update the release notes for connectors to reflect this? It seems like something which should be stated in the notes but is not.

**Comment by mattseymour** [comment]
Thanks I am sure it's something others will hit without realising. Thanks for your help.
