### ISSUE TITLE
MISP Connector cannot consume events in 5.3.5 release

### ISSUE THREAD

**Issue by Deventual** [OpenCTI-Platform/connectors#708]
## Description
After trying the new version (5.3.5) of openCTI, it seems that the MISP connector doesn't behave as expected (cannot consume events).

## Environment

1. OS (where OpenCTI server runs): { ubuntu18 }
2. OpenCTI version: { OpenCTI 5.3.5 }
3. OpenCTI client: { frontend }

## Expected Output

The connector should fetch events that are tagged for consumption.

## Actual Output

The connector restart every minute with an error
 
## Additional information

Error log of the MISP container:
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: ef8db378-733b-4e96-a349-b4e16d3e82b3
INFO:root:Starting ping alive thread
INFO:pymisp:The version of PyMISP recommended by the MISP instance (response['version']) is older than the one you're using now (2.4.159). If you have a problem, please upgrade the MISP instance or use an older PyMISP version.
INFO:root:Initiate work for ef8db378-733b-4e96-a349-b4e16d3e82b3
INFO:root:Connector last run: 2022-06-11 10:08:44
INFO:root:Connector latest event timestamp: 2022-06-12 14:29:32
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["opencti:import"]}, "timestamp": 1653056973, "limit": 50, "page": 1}
INFO:root:MISP returned 4 events.
INFO:root:Processing event 213f0513-ede4-44ff-b4b9-f8a21a8bb8e6
Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 2044, in <module>
    mispConnector.run()
  File "/opt/opencti-connector-misp/misp.py", line 377, in run
    event_timestamp = self.process_events(work_id, events)
  File "/opt/opencti-connector-misp/misp.py", line 543, in process_events
    event_external_reference = stix2.ExternalReference(
  File "/usr/local/lib/python3.10/site-packages/stix2/base.py", line 157, in __init__
    raise ExtraPropertiesError(cls, custom_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for ExternalReference: (id).
Killed

**Comment by SamuelHassine** [comment]
Hello @Deventual,

Sorry for the regression, the bug has been fixed and Docker image has been rebuilt! Can you please re-pull 5.3.5 and tell me if it's now working well?

**Comment by Deventual** [comment]
Hi @SamuelHassine,

Thanks for the quick fix!
It is working as it should now.
