### ISSUE TITLE
[MITRE] Beta version of MITRE ATT&CK ® Matrix with sub-techniques

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/connectors#72]
## Problem to Solve

Beta version of MITRE ATT&CK ® Matrix with sub-techniques is not available in OpenCTI.

## Proposed Solution

Create a new connector with the beta version of the matrix.

OR 

Update the mitre connector with a BETA flag to easily switch from stable to beta version of the matrix.

## Additional Information

* [ATT&CK with Sub-Techniques — What You Need to Know ](https://medium.com/mitre-attack/attack-subs-what-you-need-to-know-99bce414ae0b#79ca )
  * "With sub-techniques published in beta, the next two efforts we will focus on from our 2020 roadmap are revamping the Data Sources used by Enterprise and taking **the next step to merge PRE-ATT&CK into ATT&CK.**"
* [MITRE ATT&CK ®: Design and Philosophy ](https://attack.mitre.org/docs/ATTACK_Design_and_Philosophy_March_2020.pdf )

**Comment by Patriot1b4** [comment]
@SamuelHassine @2xyo Just as a small two cents. I went and pointed the old Pre and Enterprise ATT&CK links to the new MITRE beta links and it loaded in all the new sub-techniques. It worked so I assume its okay. The new link reaches their raw jsons on github just in a different location with the new stuff in it.

**Comment by SamuelHassine** [comment]
Solved in the upcoming V4.
