### ISSUE TITLE
[Elastic Security] Update connector to use a valid state initialization

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/connectors#724]
Consuming stream can use a from parameter to start from a specific point.
2 format are currently supported:
* UTC Date like from=2016-04-06T19:58:16.000Z
* Event id like from=1655845732086-0 (TIMESTAMP-INDEX)

The current elastic connector initialize a starting point only with a timestamp.
https://github.com/OpenCTI-Platform/connectors/blob/7b1b0a80dd28fb2fcf73e5f4d70d98a5d49c6f3f/stream/elastic/elastic/elastic.py#L39

If this behavior want to be kept, an index "-0" must now be added at the end of the timestamp

Maybe this init state could be added in the configuration or just removed if not really needed to start with 5 secs delay.

**Comment by TheImmigrant** [comment]
@richard-julien @SamuelHassine are we also adding this capability to the Splunk Stream connector?

**Comment by TheImmigrant** [comment]
If it's not planned or has not been added, I can work next week adding it to the Spunk Stream connector
