### ISSUE TITLE
MISP Connector 0 Events Processed

### ISSUE THREAD

**Issue by OpenSecureCo** [OpenCTI-Platform/connectors#725]
Hey Team,

I am running OpenCTI version 5.3.7 via Docker and when attempting to import MISP events I am seeing data appear to be fetched but then see a "0 events have been processed" message within the Docker logs:

![image](https://user-images.githubusercontent.com/74164997/174937210-c2f49170-d385-437a-8d31-f7ef28b7d902.png)

This also results in no data being brought into the platform:

![image](https://user-images.githubusercontent.com/74164997/174937270-99792b76-94fc-431e-8dfb-b6db2a8108e2.png)

Below are my connector settings: 

  connector-misp:
    image: opencti/connector-misp:5.3.7
    deploy:
      placement:
        constraints:
          - node.role == worker
    privileged: true
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=cfa1b34c-4f07-4920-bd39-5b162eb8ae6e
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=REDACTED
      - MISP_KEY=REDACTED
      - MISP_SSL_VERIFY=False # Required
      - MISP_DATETIME_ATTRIBUTE=timestamp # Required, filter to be used in query for new MISP events
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_CREATE_OBJECT_OBSERVABLES=True # Required, create text observables for MISP objects
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2020-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS= # Optional, list of tags used for import events
      - MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
      - MISP_IMPORT_CREATOR_ORGS= # Optional, only import events created by those orgs (put the identifiers here)
      - MISP_IMPORT_CREATOR_ORGS_NOT= # Optional, do not import events created by those orgs (put the identifiers here)
      - MISP_IMPORT_OWNER_ORGS= # Optional, only import events owned by those orgs (put the identifiers here)
      - MISP_IMPORT_OWNER_ORGS_NOT= # Optional, do not import events owned by those orgs (put the identifiers here)
      - MISP_IMPORT_KEYWORD=opencti:import # Optional, search only events based on a keyword
      - MISP_IMPORT_DISTRIBUTION_LEVELS= # Optional, only import events with the given distribution levels
      - MISP_IMPORT_THREAT_LEVELS= # Optional only import events with the given threat levels
      - MISP_IMPORT_ONLY_PUBLISHED=False
      - MISP_IMPORT_WITH_ATTACHMENTS=False # Optional, try to import a PDF file from the attachment attribute
      - MISP_IMPORT_TO_IDS_NO_SCORE=10 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=False #  Optional, import unsupported observable as x_opencti_text
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always
    networks:
      - opencti_net
    depends_on:
      - opencti

I also have MISP events being tagged with the "opencti:import" tag:

![image](https://user-images.githubusercontent.com/74164997/174937756-b2386570-91a2-45d3-aebc-a20f38f0efb6.png)

I tried resetting the connector state a few times but still no luck. Initially it seems that the connector is able to fetch data but then nothing seems to be processed and uploaded to view within the WebUI. Anything I am missing here?

Appreciate the help and the awesome tool :)

Best Regards,
Taylor

**Comment by 0q1627** [comment]
I have experienced that something goes wrong if you define env variables without a value. Remove or comment-out those lines like this:

`## - MISP_IMPORT_TAGS= # Optional, list of tags used for import events`

**Comment by OpenSecureCo** [comment]
Hey @0q1627, thanks for getting back to me. Unfortunately I am still getting same results. I verified that MISP is returning JSON back as part of the request:
![image](https://user-images.githubusercontent.com/74164997/175991906-789fe87d-ba46-4963-8c2f-b21849cefa9b.png)

But still getting "0 events have been processed" message. Any other thoughts?

Thanks,
Taylor

**Comment by bakhtawarw** [comment]
Did your issue get resolved? I am getting the same error.

**Comment by OpenSecureCo** [comment]
Hey @bakhtawarw - Unfortunately I am still getting the same error. I have tried resetting and deleting the connector and re running again but never seem to have luck. Hopefully the OpenCTI team will be able to assist further. Let me know if you ever find a solution.

Thanks

**Comment by SamuelHassine** [comment]
By the way, we have modified the way empty variables are handled in connectors in the last version -5.3.7) so be sure to be in the latest version. If you still  have problem, please copy/paste here your configuration.

**Comment by SamuelHassine** [comment]
@OpenSecureCo In your screenshot, it seems you've a tag "opencti:import", can you try to put in in the import_tags and not in the import keyword parameter?

**Comment by bakhtawarw** [comment]
Hi, this is the misp-connector configuration.

**connector-misp:
    image: opencti/connector-misp:5.3.7
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=bb9a05fb-719c-4463-ac31-448df5310f00
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=25 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=http://10.0.2.4 # Required
      - MISP_REFERENCE_URL= # Optional, will be used to create external reference to MISP event (default is "url")
      - MISP_KEY=xxxxxxxxxxxxxx # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_DATETIME_ATTRIBUTE=timestamp # Required, filter to be used in query for new MISP events
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_CREATE_OBJECT_OBSERVABLES=True # Required, create text observables for MISP objects
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2020-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS= # Optional, list of tags used for import events
      - MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
      - MISP_IMPORT_CREATOR_ORGS= # Optional, only import events created by those orgs (put the identifiers here)
      - MISP_IMPORT_CREATOR_ORGS_NOT= # Optional, do not import events created by those orgs (put the identifiers here)
      - MISP_IMPORT_OWNER_ORGS= # Optional, only import events owned by those orgs (put the identifiers here)
      - MISP_IMPORT_OWNER_ORGS_NOT= # Optional, do not import events owned by those orgs (put the identifiers here)
      - MISP_IMPORT_KEYWORD= # Optional, search only events based on a keyword
      - MISP_IMPORT_DISTRIBUTION_LEVELS=0,1,2,3 # Optional, only import events with the given distribution levels
      - MISP_IMPORT_THREAT_LEVELS=1,2,3,4 # Optional only import events with the given threat levels
      - MISP_IMPORT_ONLY_PUBLISHED=False
      - MISP_IMPORT_WITH_ATTACHMENTS=False # Optional, try to import a PDF file from the attachment attribute
      - MISP_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=False #  Optional, import unsupported observable as x_opencti_text
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always
    depends_on:
      - opencti**


These are the logs : 
![image](https://user-images.githubusercontent.com/104062347/177262164-8f2d6266-ee7e-4869-aeac-f13371f154ab.png)

**Comment by OpenSecureCo** [comment]
Unfortunately same issue. See config below:

`connector-misp:
    image: opencti/connector-misp:5.3.7
    deploy:
      placement:
        constraints:
          - node.role == worker
    privileged: true
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=cfa1b34c-4f07-4920-bd39-5b162eb8ae6e
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=25 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://xxxxx
      - MISP_REFERENCE_URL=https://xxxxx
      - MISP_KEY=xxxxx
      - MISP_SSL_VERIFY=False # Required
      - MISP_DATETIME_ATTRIBUTE=timestamp # Required, filter to be used in query for new MISP events
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_CREATE_OBJECT_OBSERVABLES=True # Required, create text observables for MISP objects
      - MISP_REPORT_CLASS=misp-event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2020-06-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import # Optional, list of tags used for import events
      - MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
      - MISP_IMPORT_CREATOR_ORGS= # Optional, only import events created by those orgs (put the identifiers here)
      - MISP_IMPORT_CREATOR_ORGS_NOT= # Optional, do not import events created by those orgs (put the identifiers here)
      - MISP_IMPORT_OWNER_ORGS= # Optional, only import events owned by those orgs (put the identifiers here)
      - MISP_IMPORT_OWNER_ORGS_NOT= # Optional, do not import events owned by those orgs (put the identifiers here)
      - MISP_IMPORT_KEYWORD= # Optional, search only events based on a keyword
      - MISP_IMPORT_DISTRIBUTION_LEVELS= # Optional, only import events with the given distribution levels
      - MISP_IMPORT_THREAT_LEVELS= # Optional only import events with the given threat levels
      - MISP_IMPORT_ONLY_PUBLISHED=False
      - MISP_IMPORT_WITH_ATTACHMENTS=True # Optional, try to import a PDF file from the attachment attribute
      - MISP_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=False #  Optional, import unsupported observable as x_opencti_text
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always
    networks:
      - opencti_net
    depends_on:
      - opencti`

Still seems to be that MISP is returning data but OpenCTI is not processing it

![misp return](https://user-images.githubusercontent.com/74164997/178066531-5ed146ca-960c-4f02-a759-f0e82ec68e5f.PNG)

Thanks for the help!

**Comment by OpenSecureCo** [comment]
@SamuelHassine I noticed some other things when putting the MISP connector into debug mode.

I see that the POST request includes a timestamp key with an epoch value:

![misp request](https://user-images.githubusercontent.com/74164997/178075066-bc424f5c-4320-4380-a5ff-ec33cc78c470.PNG)

If I make that same request to MISP via a curl, I see no data returned (`curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: xxxx" --data '{"tags": {"OR": ["opencti:import"]}, "timestamp": 1657312128, "with_attachments": true, "limit": 50, "page": 1}' -X POST https://xxxx --insecure`) :

![misp cli](https://user-images.githubusercontent.com/74164997/178075327-c4497669-dd33-4171-aa73-5a365a41d0e4.PNG)


However, if I remove the timestamp as part of the request, I get data back (`curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: xxx" --data '{"tags": {"OR": ["opencti:import"]}, "with_attachments": true, "limit": 50, "page": 1}' -X POST https://xxx --insecure`)

![misp return2](https://user-images.githubusercontent.com/74164997/178075572-20da74dc-d9c2-4dea-b16c-90909e656770.PNG)

Does that epoch need to be converted to a normal timestamp? Does the timestamp field need to be removed? 

Thanks,
Taylor

**Comment by 0q1627** [comment]
@bakhtawarw 

> - CONNECTOR_LOG_LEVEL=info

You can increase verbosity of the connector log to "debug" level. Anyway your issue is related to the response you get from MISP since the connector complains it is not receiving a JSON. Try the curl direct call as shown in a comment above:

`curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: xxx" --data '{"tags": {"OR": ["opencti:import"]}, "with_attachments": true, "limit": 50, "page": 1}' -X POST https://xxx --insecure`

This is my configuration that is working 

connector-misp2:
    image: opencti/connector-misp:5.3.7
    environment:
      - OPENCTI_URL=http://opencti.local:8080
      - OPENCTI_TOKEN=xxx
      - CONNECTOR_ID=yyy
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP_TLP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=False
      - CONNECTOR_LOG_LEVEL=debug
      - MISP_URL=http://10.X.Y.Z/ # Required
      - MISP_REFERENCE_URL= # Optional, will be used to create external reference to MISP event (default is "url")
      - MISP_KEY=zxyzxyzxy # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_DATETIME_ATTRIBUTE=timestamp # Required, filter to be used in query for new MISP events
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_CREATE_OBJECT_OBSERVABLES=True # Required, create text observables for MISP objects
      - MISP_REPORT_CLASS="MISP Event" # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2020-01-02 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=tlp:green,tlp:white # Optional, list of tags used for import events
      - MISP_IMPORT_ONLY_PUBLISHED=False
      - MISP_IMPORT_WITH_ATTACHMENTS=False # Optional, try to import a PDF file from the attachment attribute
      - MISP_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=False #  Optional, import unsupported observable as x_opencti_text
      - MISP_INTERVAL=5 # Required, in minutes
    restart: always


Filtering works since I set MISP_IMPORT_TAGS instead of MISP_IMPORT_CREATOR_ORGS that never matched an Org. As you can see I removed all unused variables (I don't care anymore if that matters or not as long as I can import events that I want).

**Comment by OpenSecureCo** [comment]
@SamuelHassine One thing I have noticed is that manually running the curl command 

`curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: xxxxx" --data '{"tags": {"OR": ["opencti:import"]}, "with_attachments": true, "limit": 50, "page": 1}' -X POST https://xxxx/events/restSearch --insecure`

returns the json as expected but there is about a 18 second delay from the time of me making the curl request and the time that MISP responds with the json. Is it possible that the MISP connector is timing out before MISP has responded? So even though the search query is correct, the MISP container exists out before the MISP server responds?

Thanks,
Taylor

**Comment by ArifeVural** [comment]
I happen to have the same issue with OpenCTI not to be able to pull any events from MISP instance. Just wondering whether any progress on that. The curl cmd used by API can fetch entries when I ran it from shell. But, somehow the OpenCTI instance  says 0 event returned. 

When I first configured, a single event was fetched and then it stopped.

This is my config:

connector-misp:
    image: opencti/connector-misp:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MISP_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=${CONNECTOR_MISP_URL} # Required
      - MISP_KEY=${CONNECTOR_MISP_API} # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_INTERVAL=5 # Required, in minutes
    restart: always      

Any help is appreciated. 

Thanks.
