### ISSUE TITLE
Abuseipdb connector shows no result.

### ISSUE THREAD

**Issue by bakhtawarw** [OpenCTI-Platform/connectors#734]
## Description

Abuseipdb internal enrichment connector starts but shows no results.

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: 5.3.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I added the connector configuration in docker-compose.yml file.

**connector-abuseipdb:
    image: opencti/connector-abuseipdb:5.3.7
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=b100455a-99cb-422b-b814-3b646d0765d9
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=AbuseIPDB
      - CONNECTOR_SCOPE=IPv4-Addr
      - CONNECTOR_AUTO=true
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - ABUSEIPDB_API_KEY=xxxxxxxxxxxxxxxxxxxxxx
      - ABUSEIPDB_MAX_TLP=TLP:AMBER
    restart: always
    depends_on:
      - opencti**

2. The connector started but I can't see any results in opencti ui.
    Here are the container logs.
    
**INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: b100455a-99cb-422b-b814-3b646d0765d9
INFO:root:Starting ping alive thread
INFO:root:Creating Label {whitelist}.**

The connector is stuck here and after that no logs are generated or no work progress is being shown.

**Comment by ReadyElbow** [comment]
This is because you are not performing any 'enrichment' processes.
Upload an observable that AbuseIPDB targets such as an IP address and you should be able to perform enrichment on that IOC. 

The connector should log this request.
