### ISSUE TITLE
[Kaspersky] Connector is creating dups

### ISSUE THREAD

**Issue by 0x7fff9** [OpenCTI-Platform/connectors#743]
## Description

The kaspersky connector is creating duplicated content on the platform

## Environment

1. OS: Debian 11
2. OpenCTI version: 5.3.7
3. OpenCTI client: frontend
4. Other environment details: Docker install

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Kaspersky connector is set to auto-ingest every 24hrs.
2. it's returning messages to the console related to creating duplicates.
3. Error: 
`ERROR:root:This update will produce a duplicate
ERROR:root:Kaspersky connector internal error: {'name': 'FunctionalError', 'message': 'This update will produce a duplicate'}`
4. Duplicates seen on platform UI under reports.

## Expected Output

It is expected to not see duplicates.

## Actual Output

The UI is showing duplicate reports coming from Kaspersky (only)

![afbeelding](https://user-images.githubusercontent.com/24276463/177540270-09d8dc65-d647-4909-89e3-7133d96477f6.png)

 
## Additional information

The Kaspersky queue is also increasing a lot!
<img width="1185" alt="afbeelding" src="https://user-images.githubusercontent.com/24276463/177540465-e327a01c-d144-4eb9-9b0d-cf3836d505b9.png">

**Comment by SamuelHassine** [comment]
Hellon @0x7fff9,

Thanks a lot for reporting this issue. Can you please give us the "published" date of 2 reports that are actually duplicated?

The de-deplucation process of the OpenCTI platform on the "Report" entity type relies on "name" and "published" attributes.

Thanks a lot.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Closed due to inactivity.

**Comment by yanover** [comment]
It seems that we are facing the same error as the one specified in this thread :

![Screenshot 2022-10-27 at 08 49 18](https://user-images.githubusercontent.com/35560499/198211457-8b5574c2-0e75-4bf0-80d1-e69596ba1f2b.png)

The publication date of these reports is :
* October 1, 2022 at 11:29:01 PM
* October 1, 2022 at 2:00:00 AM
