### ISSUE TITLE
[ImportDocument] Enhance the connector to be able to exclude fields, entity types

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#753]
## Use case

Enhance the connector to be able to exclude fields, entity types.

**Comment by nor3th** [comment]
Should be doable by simply adapting the .ini configs. https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-document/README.md#configuration-reportimporterconfig

What's the use case you are looking for
