### ISSUE TITLE
[ImportDocument] Modify default country resolution (no aliases)

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#754]
## Use case

Modify default country resolution (no aliases)

**Comment by nor3th** [comment]
hey @SamuelHassine 

That is done by simply removing this line: https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-document/src/reportimporter/config/entity_config.ini#L62

The idea behind also using the alias, is that some countries use different names which might then not be extracted from the text. For example ("USA", "United State of America", ...)

Regards

**Comment by SamuelHassine** [comment]
Hey @nor3th,

Thanks a lot! I saw where to modify this one. Problem is that the OpenCTI Countries datasets contains 2 letters ISO codes in aliases of countries. This mean "US" as the word "us" (just an example but same for DE, IR, etc.

As far as I know, all organization using this connector has the problem that countries are definitely not correct in imports.

I will just comment it in the default config with a proper description so people can understand what does it means.

Kind regards,
Sam
