### ISSUE TITLE
[VirusTotal LiveHunt Connector] Proxy environment variables are not inherited by the connector

### ISSUE THREAD

**Issue by sorenopsy** [OpenCTI-Platform/connectors#769]
## Description

Proxy environment variables are not inherited by the connector, probably because of missing  "trust_env" in
self.vt_client = vt.Client(api_key)

## Environment

1. OS (where OpenCTI server runs): Redhat
2. OpenCTI version:OpenCTI  5.3.7
3. OpenCTI client: 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Install VirusTotal LiveHunt connector with defaults settings in docker-compose.yml

## Expected Output

Succesful connection
## Actual Output

ERROR:root:Cannot connect to host www.virustotal.com:443 ssl:default [Connect call failed ('74.125.34.46', 443)]

**Comment by SamuelHassine** [comment]
Can you please try to pass HTTP_PROXY envvar in your Docker config?

**Comment by sorenopsy** [comment]
Already there, but same error:

connector-virustotal-livehunt-notifications:
    image: opencti/connector-virustotal-livehunt-notifications:5.3.16
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=xxxxxxxxxxxxxxxxx
      - HTTPS_PROXY=http://xx.xx.xx.xx:8080
      - HTTP_PROXY=http://xx.xx.xx.xx:8080
