### ISSUE TITLE
Bug connector malpedia

### ISSUE THREAD

**Issue by V1D1AN** [OpenCTI-Platform/connectors#78]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

The connector malpedia don't work

## Environment

1. OS (where OpenCTI server runs): CentOs 7
2. OpenCTI version: OpenCTI 3.1.0
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. cd /root
2. git clone https://github.com/OpenCTI-Platform/connectors.git
3. cd connectors/malpedia/
4. docker build -t connector-malpedia:3.1.0 .
5. I start my docker-compose with this connector

## Actual Output

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Starting ping alive thread
INFO:root:Fetching Malpedia datasets...
INFO:root:Connector has never run
INFO:root:Connector will run!
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by V1D1AN** [comment]
I must change the config.yml.sample with config.yml ;)

**Comment by SamuelHassine** [comment]
@rhaist is currently working on the Malpedia connector (#49), so the connector is currently not ready for production. Please re-open this issue once the connector will be officially released in the [OpenCTI ecosystem](https://www.notion.so/luatix/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76).
