### ISSUE TITLE
Request new enrichment of an Internal-Enrichment connector 

### ISSUE THREAD

**Issue by mariodcosta** [OpenCTI-Platform/connectors#781]
Hello guys,

Anyone know how to code in python a request for a internal-enrichment connector run again in an observable id??

Something like this:
```
`def enrichmentConnector(self, obs_id):
       #here I give the argument of the observable to the conector
       self.opencti_connector_helper....(obs_id)`
```

The connector run always that is detected a new IPv4 observable, however I want to run again in specific conditions for the observable I already added.

In the OpenCTI interface available online , I can click in the enrichment button and select the connector as you can see in the image in attachment, however I don't know how to make it in code.

![Button for enrichment](https://user-images.githubusercontent.com/13469672/183058669-75d78a59-3906-4b41-a9af-815589c30b43.png)

![Enrichment connector to run again](https://user-images.githubusercontent.com/13469672/183058764-4b81ec8d-5c93-48a6-b773-011986f21ce7.png)

**Comment by SamuelHassine** [comment]
Hello @mariodcosta,

The availability of enrichment connectors in the UI is defined in the connector configuration parameter `scope`.

Please see those examples:

- https://github.com/OpenCTI-Platform/connectors/blob/master/internal-enrichment/ipinfo/src/config.yml.sample
- https://github.com/OpenCTI-Platform/connectors/blob/master/internal-enrichment/virustotal/src/config.yml.sample

Depending on the scope (a list of entity types), the connector is displayed if the observable type you are viewing is present in the connector scope.

Hope it will help.

Kind regards,
Samuel
