### ISSUE TITLE
[mandiant] Running the connector for the first time results in wrong epoch when trying to get reports

### ISSUE THREAD

**Issue by rabbipigeon** [OpenCTI-Platform/connectors#799]
## Description

When Running the connector for the first time the epoch is set to 
```
start_epoch = current_state["report"]
end_epoch = start_epoch + 3600
```

which results in the query with the parameters such as below 

`"GET /v4/reports?limit=1000&start_epoch=3600&end_epoch=7200 HTTP/1.1" `

which are not valid parameters according to the documentation. Reports timestamp to epoch should be based on the config variable `MANDIANT_IMPORT_START_DATE` seems like a simple fix. 

Please confirm bug and i will submit a PR for this issue if its a valid issue.

**Comment by SamuelHassine** [comment]
Hello @rabbipigeon,

I think this has been fixed in 5.3.8 (due September 1st). Please re-open if it is not the case after the next release.

Kind regards,
Samuel
