### ISSUE TITLE
[AlienVault,CrowdStrike] Connector crash after stix library update through pycti

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/connectors#80]
Hello,

`stix2` library is imported in the project because it is a dependency of `pycti` but is used in the AlienVault connector.

`pycti` does not stick the versions of its dependencies, so `stix2` may be in the last version. `stix2` 1.4.0 has been released on April 3, 2020. By upgrading `stix2` lib with `pip3 install --upgrade stix2` or by doing a fresh installation of `pycti`, `stix2` 1.4.0 will be installed.

With `stix2` 1.4.0, the AlienVault connector crashes:

```
ImportError: cannot import name 'SCO21_EXT_REGEX' from 'stix2.utils' 
```

**Comment by maertv** [comment]
The same issue affected CrowdStrike connector.

**Comment by maertv** [comment]
Merged to _master_. Closing issue.
