### ISSUE TITLE
User with knowledge permission can't see any data

### ISSUE THREAD

**Issue by symsal** [OpenCTI-Platform/connectors#802]
## Description
A user with all permission on Knowledge section can't see any data into.
## Environment

1. OS Ubuntu 21
2. OpenCTI version: 5.3.7
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create user with specified profile
2. Login into opencti
3. click on kwowledge link
4. check if old data is present

**Comment by richard-julien** [comment]
By default a user only see data without markings.
If your data have marking definition you need to create a group, grant the marking in the group and then assign the user to this group.
You can also use the option to default assign the group to newly created user if needed.
