### ISSUE TITLE
[Mandiant] Adding Malware and Threat Actor Names as Labels to Indicators

### ISSUE THREAD

**Issue by ay1988** [OpenCTI-Platform/connectors#822]
## Description

We would like to add a feature of displaying the associated malware or threat actor of the indicators as labels in Observables, they are already returned in the API indicator endpoint output under:
indicators -> attributed_associations -> name

## Environment

OpenCTI version 5.3.10

**Comment by SamuelHassine** [comment]
Hello,

The fundamental OpenCTI philosophy is to try to modelize everything as precisely as possible. Indicators should be linked to malware and threat actors using "indicates" relationships. 

Then it's possible to use this relationship in dashboards, investigations, filtering etc. If something is missing in filtering so you're not able to find indicators related to specific threats please let us know and we will add it. 

Kind regards,
Samuel
