### ISSUE TITLE
[external-import/restore-files] fails with KeyError on get_state["current"]

### ISSUE THREAD

**Issue by kmcmahon1959** [OpenCTI-Platform/connectors#828]
## Description

When running external-import/restore-files.py against data acquired via stream/backup-files.py the script fails due to the return from get_state not containing a "current" element.

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI version: 5.3.11
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Instance A: run python ./connectors-master/stream/backup-files/src/backup-files.py
2. Instance B: run python ./connectors-master/external-import/restore-files/src/restore-files.py
3. KeyError (see below)

## Expected Output

Process the input files.

## Actual Output

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 673ba380-d229-4160-9213-ac5afdaabf96
INFO:root:Starting ping alive thread
Traceback (most recent call last):
  File "/opt/opencti-highside-sync/connectors-master/external-import/restore-files/src/restore-files.py", line 177, in <module>
    RestoreFilesInstance.start()
  File "/opt/opencti-highside-sync/connectors-master/external-import/restore-files/src/restore-files.py", line 170, in start
    self.restore_files()
  File "/opt/opencti-highside-sync/connectors-master/external-import/restore-files/src/restore-files.py", line 86, in restore_files
    start_directory = state["current"] if state is not None else None
KeyError: 'current'
Killed

## Additional information

Changing the line in question above to the following seems remove issue:

         if (state is not None) and ("current" in state):
            start_directory = state["current"]
        else:      
            start_directory = None

I also added line to output the output of get_state() and it prints the following:
INFO:root:get_state output: {"connectorLastEventId": "1657035162709-0"}

**Comment by SamuelHassine** [comment]
Hello @kmcmahon1959,

Just for you to know, it seems you're using the same connector ID as a the backup files connector (or any other stream connector), this is why you have a "connectorLastEventId" in your state, which should be null / none at start.

I will enforce the check on the key presence but please double check you are not using the same ID.

Kind regards,
Samuel

**Comment by kmcmahon1959** [comment]
Samuel,

Thanks, I was just looking at this code late last week while further testing the restore-files. It’s all starting to make sense.  😊

Best regards,
Kevin


From: Samuel Hassine ***@***.***>
Sent: Saturday, September 17, 2022 6:55 AM
To: OpenCTI-Platform/connectors ***@***.***>
Cc: Kevin J McMahon ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OpenCTI-Platform/connectors] [external-import/restore-files] fails with KeyError on get_state["current"] (Issue #828)


Hello @kmcmahon1959<https://github.com/kmcmahon1959>,

Just for you to know, it seems you're using the same connector ID as a the backup files connector (or any other stream connector), this is why you have a "connectorLastEventId" in your state, which should be null / none at start.

I will enforce the check on the key presence but please double check you are not using the same ID.

Kind regards,
Samuel
