### ISSUE TITLE
[Malpedia] 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by V1D1AN** [OpenCTI-Platform/connectors#83]
## Description

The connector maldpedia don't work

## Environment

1. OS (where OpenCTI server runs): CentOs 7
2. OpenCTI version: OpenCTI 3.1.0
3. OpenCTI client: frontend
4. Other environment details: docker 19.03.5

## Actual Output

When I start the docker ..
I have this error :

INFO:root:{"errors":[{"message":"An unknown error has occurred!  Please try again later.","name":"Unknown","time_thrown":"2020-04-08T11:13:46.377Z","data":{"type":"technical","level":"error"}},{"message":"An unknown error has occurred!  Please try again later.","name":"Unknown","time_thrown":"2020-04-08T11:13:46.378Z","data":{"type":"technical","level":"error"}}]}

ERROR:root:'NoneType' object is not subscriptable

**Comment by cvdsouza** [comment]
I'm getting this same error as well after pulling in the new update

```
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["rule aix_fastcash_w2 {\n  meta:\n    author = \"Paul Melson @pmelson\"\n    description = \"HIDDEN COBRA AIX FastCash pvpa binary (may not be malicious, low attribution confidence)\"\n    reference_0 = \"https://www.us-cert.gov/ncas/alerts/TA18-275A\"\n    reference_1 = \"https://github.com/fboldewin/FastCashMalwareDissected/\"\n    sample_sha256 = \"f3e521996c85c0cdb2bfb3a0fd91eb03e25ba6feef2ba3a1da844f1b17278dd2\"\n    malpedia_reference = \"https://malpedia.caad.fkie.fraunhofer.de/details/aix.fastcash\"\n    malpedia_version = \"20181219\"\n    malpedia_license = \"CC BY-NC-SA 4.0\"\n    malpedia_sharing = \"TLP:WHITE\"\n  strings:\n    $symbol_static = { 00 5f 24 53 54 41 54 49 43 00 }\n    $symbol_pvpa = { 00 00 00 00 70 76 70 61 00 00 00 00 }\n    $symbol_get_pvpa = { 00 2e 67 65 74 5f 70 76 70 61 00 }\n    $symbol_get_posn = { 00 2e 73 65 74 5f 70 6f 73 6e 00 }\n    $symbol_init_pvpa = { 00 2e 69 6e 69 74 5f 70 76 70 61 00 }\n    $string0 = \"/dev/mem\"\n    $string1 = \"set_posn\"\n    $string2 = \"get_pvpa\"\n    $string3 = \"init_pvpa\"\n    $string4 = \"high_cpuid=%d\"\n    $string5 = \"open kernel mem\"\n    $string6 = \"cpu %d, old value = 0x%02x\"\n    $string7 = \"Usage: pvpa [<new_value> <old_value>]\"\n    $string8 = \"Invalid PVPA read, magic = 0x%08x, len = %d, cpu = %d\"\n  condition:\n    uint16(0) == 0xf701 and (all of ($symbol*) or all of ($string*))\n}"], "operator": "match"}].
INFO:root:Listing stix_relations with {type: indicates, from_id: fe23dcf2-368b-42fc-8fde-94aa0e901d23, to_id: b789bf8c-101b-4542-91c5-fbcf128bd522}
INFO:root:Creating stix_relation {indicator: fe23dcf2-368b-42fc-8fde-94aa0e901d23, characterize: b789bf8c-101b-4542-91c5-fbcf128bd522}.
INFO:root:{"errors":[{"message":"An unknown error has occurred!  Please try again later.","name":"Unknown","time_thrown":"2020-04-17T15:23:28.712Z","data":{"type":"technical","level":"error"}}]}

ERROR:root:'NoneType' object is not subscriptable
```

**Comment by rhaist** [comment]
Hi - as stated int the Readme the Malpedia connector is "in development" at the moment and not considered to be stable for production use. I am working on a new version at #90 (also work in progress).

**Comment by SamuelHassine** [comment]
@rhaist is currently working on the Malpedia connector (#49), so the connector is currently not ready for production. Please re-open this issue once the connector will be officially released in the [OpenCTI ecosystem](https://www.notion.so/luatix/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76).
