### ISSUE TITLE
[Mandiant] Reports are not replacing the Threat Actor to Instrusion Set based in the parameter

### ISSUE THREAD

**Issue by TheImmigrant** [OpenCTI-Platform/connectors#837]
## Use case

 Reports are not replacing the Threat Actor to Intrusion Set based on the parameter

## Proposed Solution

Replace the Threat-Actor in the Stix object with Intrusion Set.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
Hello @TheImmigrant,

I think this was solved in 5.3.13: https://github.com/OpenCTI-Platform/connectors/commit/ab5203e0c356941c9afebb49d3678e0cf17f43ab.

Is this modification not enough?

Kind regards,
Samuel

**Comment by TheImmigrant** [comment]
Hello @SamuelHassine ,

Yes, its the same solution I created. In that case Ill pull my branch. 

Thanks !
