### ISSUE TITLE
[CrowdStrike] Doesn't create an state until it finishs the job.

### ISSUE THREAD

**Issue by RaulSokolova** [OpenCTI-Platform/connectors#863]
## Description

When collecting indicators due to the amount and the time it takes to process around 200,000 per day, even if we set the interval to 4 hours since it takes longer to process , it does start creating a huge backlog of messages. 

## Environment

1. OS Docker Deployment
2. OpenCTI version: 5.3.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enabled CrowdStrike connector with only indicators
2. CROWDSTRIKE_INDICATOR_START_TIMESTAMP couple of days behind

## Expected Output

To set the state on parallel , instead of waiting for the job to complete.

## Actual Output

Doesn't set the state and it starts creating multiple repetitive jobs , plus the increment of the new IOCs. 
 
## Screenshots (optional)
![image](https://user-images.githubusercontent.com/30608998/194072741-a44a1a20-e4ff-4bad-ba7f-08c8adbf6c19.png)

**Comment by helene-nguyen** [comment]
Hi @RaulSokolova,
Since your message, we have made a lot of changes and are about to change Crowdstrike feed connector to use FalconPy library.
Could you tell us if you still have this issue ? Have update the platform and connector ?

**Comment by Jipegien** [comment]
Closing the issue. It needs reassessment of the initial problem.
