### ISSUE TITLE
[Splunk Stream] Fails with self signed certs

### ISSUE THREAD

**Issue by RaulSokolova** [OpenCTI-Platform/connectors#876]
## Description

Splunk doesn't stream data if OpenCTI is using a self-signed cert.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enable HTTPS on OCTI with a self-signed cert.
2. Add the HTTPS URL to the Splunk Connector

## Expected Output

Have in the dockerfile a parameter for the listen_stream to load verify_ssl=False

Tested this successfully, I can submit a PR if needed.

splunk.py 
```

def start(self):
    self.helper.listen_stream(self._process_message, verify_ssl=False)

```

**Comment by SamuelHassine** [comment]
Hello,

Did you try to set the environment variable `OPENCTI_SSL_VERIFY=false` (or the configuration YAML:

```
opencti:
  ssl_verify: false
```

Kind regards,
Samuel

**Comment by RaulSokolova** [comment]
Hello Samuel,

Thanks, it worked... Closing the question.
