### ISSUE TITLE
[ImportExternalReference] Failed to import with pdf format

### ISSUE THREAD

**Issue by gregorygui** [OpenCTI-Platform/connectors#877]
## Description

Running import-external-reference connector to fetch an url and get a PDF failed with the released connector image (v5.3.17). Error is : ```Fatal error compiling builtin function 'apply':```. After some research, I identify this thread https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4743 where a comment says ```wkhtmltopdf with Qt patches isn't supported on Alpine yet```. Trying with python3.10-buster fix the issue.

## Environment

1. Docker - Debian 11
2. OpenCTI version: 5.3.17
3. OpenCTI client: python3.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run OpenCTI with connector import-external-reference
2. Add external reference to a test report, then try enrichment to get the pdf
3. Get ```Fatal error compiling builtin function 'apply':``` in logs, even with log verbosity sets to DEBUG

## Expected Output

using the connector ```import-external-reference``` should generate markdown andpdf files from the url in external reference.

## Actual Output

Only the markdown file is correctly generated
 
## Additional information

Moving to python3.10-buster docker image and modifying package manager (apt) fix the issue

**Comment by w1ld3r** [comment]
Having the same issue
