### ISSUE TITLE
VirusTotal Enrichment Connector Doesn't enrich Observables

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/connectors#885]
## Description

The current implementation of the VT Enrichment connector only enriches Indicators.  This functionality needs to be extended to observables.

## Environment

1. OS (where OpenCTI server runs): AWS Linux2
2. OpenCTI version: 5.3.17
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Try to enrich an observable with VT

## Expected Output

Enrich the observable with the connector

## Actual Output

None

**Comment by YungBinary** [comment]
What entity types @TechBurn0ut are you referring to? Currently, the connector's scope is setup to IPv4, URL, Domain-Name, and File entity types.

**Comment by SamuelHassine** [comment]
Hello,

Don't understand the issue, the VT connector is already working only on observable. Do you mean we should extend to indicators?

Kind regards,
Samuel
