### ISSUE TITLE
'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/connectors#89]
## Description

I am trying run OpenCTI on docker container (not docker-compose) but every connector shows error while being running

'NoneType' object has no attribute 'upper'

## Environment

1. OS (macos 10.13)
2. OpenCTI version: { latest }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { clone any connector }
2. { build using `docker build -t tag/name .` }
3. { `docker run -d --link opencti:opencti tag/name` }

## Actual Output

2020-04-16T14:18:41.269754200Z 'NoneType' object has no attribute 'upper'
2020-04-16T14:19:35.151173700Z 'NoneType' object has no attribute 'upper
 
## Additional information
This may related to pycti lib. 

Thanks for taking a look at this.

**Comment by SamuelHassine** [comment]
Hello @phucsnguyenv,

Can you give more details, which connector are you testing?

Kind regards,
Samuel

**Comment by phucsnguyenv** [comment]
Hi Samuel, 

Virustotal, I tried to run other connector and got the same issue, but this log I get from Virustotal connector. 
It's lack of information from the log, but it's only what I get from stdout put from docker container. 

Thanks for taking a look..

**Comment by rhaist** [comment]
This error is usually raised if you didn't copy the `config.yml.sampe` to a valid `config.yml`
When there is no valid `config.yml` the OpenCTI helper initialization.
Note: you also need to change `ChangeMe` to valid values.

We might need to improve error output for the python sdk here.
