### ISSUE TITLE
Cryptolaemus Connector Error - Error on first run: Missing reference to handle creation

### ISSUE THREAD

**Issue by cvdsouza** [OpenCTI-Platform/connectors#901]
## Description

Hi, 
Currently running the Cryptolaemus connector and seem to be getting into this error when it starts up. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04 
2. OpenCTI version: 5.3.17
3. OpenCTI client: python
4. Other environment details: Connector

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start Cryptolaemus connector using docker compose
2. Tail docker logs. 

## Expected Output

Ingestion of Cryptolaemus IoCs

## Actual Output

INFO:root:Connector has never run
INFO:root:Connector will run!
INFO:root:Creating Identity {Cryptolaemus Team}.
INFO:root:Creating External Reference {Cryptolaemus Team's Emotet C2 update of 2021-01-25T23:59:00+00:00}.
INFO:root:Creating Malware {Emotet}.
INFO:root:Creating Indicator {84.232.229.24}.
INFO:root:Creating Stix-Cyber-Observable {IPv4-Addr} with indicator at False.
INFO:root:Creating stix_core_relationship 'based-on' {3d1b5ad4-13b7-4423-96c0-5eff78919614, 5fd646b9-4f55-4c1f-be59-95234da074c5}.
INFO:root:Creating stix_core_relationship 'indicates' {3d1b5ad4-13b7-4423-96c0-5eff78919614, 503aabc6-da22-41c6-9736-1ae35e79a47c}.
ERROR:root:Missing reference to handle creation
ERROR:root:{'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

## Additional information

Cryptolaemus specifically provides threat feeds on Emotet that has recently become active. It would be great if this connector could be fixed as it would be beneficial for those who ingest this feed.

**Comment by SamuelHassine** [comment]
Connector is deprecated.
