### ISSUE TITLE
[MITRE] Update MITRE Connector to create Infrastructure objects.

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/connectors#905]
## Use case

As a Cyber Threat Analyst, I require the representation of the MITRE Data Sources and Components within the OpenCTI platform.

## Current Workaround

Manually create and manage objects.

## Proposed Solution

In order to fully operationalize MITRE ATT&CK data, the MITRE Connector needs the following:

STIX Infrastructure object for each Data Source and Data Component
Relationship between Data Component and Data Source
<Data Source> `consists-of` <Data Component>

Once the data sets are created, then the fields `Platform` (Indicators), `Log Sources` (Courses of Action) can be mapped to infrastructure objects within the graph.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
Currently implementing this: https://github.com/OpenCTI-Platform/opencti/issues/680. Will be available in 5.5.0.
