### ISSUE TITLE
Recorded Future Connector Live?

### ISSUE THREAD

**Issue by bigverm23** [OpenCTI-Platform/connectors#938]
## Prerequisites

- [x ] I read the [Deployment and Setup](https://filigran.notion.site/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://filigran.notion.site/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ x] I went through old GitHub issues and couldn't find anything relevant
- [ x] I googled the issue and didn't find anything relevant

## Description

Where is the Recorded Future connector information? I see a Nov 1 blog post referencing the integration but I dont see it anywhere on OpenCTI's git.

**Comment by RaulSokolova** [comment]
HI @bigverm23, see the link for the connector below.

https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/recordedfuture-notes

Feel free to close it, if this is what you were looking for.
