### ISSUE TITLE
MISP connector: tags/galaxy NOT imported

### ISSUE THREAD

**Issue by garanews** [OpenCTI-Platform/connectors#94]
## Description

using the misp connector the galaxy and tags of misp events are not imported in opencti

## Environment

docker
## Reproducible Steps

create an event, tag it
add some attribute (tag also)
add galaxy

## Expected Output

attributes, tags, galaxy retrieved in opencti

## Actual Output

attributes are retrieved but no galaxy and no tags

**Comment by garanews** [comment]
![image](https://user-images.githubusercontent.com/16938405/79573325-c413e080-80be-11ea-8011-184d8c50016e.png)
![image](https://user-images.githubusercontent.com/16938405/79573361-d3932980-80be-11ea-8c97-ae3a06671874.png)
![image](https://user-images.githubusercontent.com/16938405/79573418-ea398080-80be-11ea-9b3f-54341647e4cb.png)

**Comment by SamuelHassine** [comment]
@garanews can you check please the indicator linked to the observable and its relationships to threats?

**Comment by SamuelHassine** [comment]
For other galaxies that are not representing a threat (intrusion set, malware, etc.). I put your question as a feature so we can add corresponding tags.

**Comment by garanews** [comment]
![image](https://user-images.githubusercontent.com/16938405/79579644-232a2300-80c8-11ea-8952-7653862b7916.png)
![image](https://user-images.githubusercontent.com/16938405/79579669-2b825e00-80c8-11ea-9f16-58fddce5f295.png)
![image](https://user-images.githubusercontent.com/16938405/79579697-350bc600-80c8-11ea-85bf-b9895ef97454.png)
![image](https://user-images.githubusercontent.com/16938405/79579724-3f2dc480-80c8-11ea-9df5-3b97e191bf71.png)
![image](https://user-images.githubusercontent.com/16938405/79579796-5bc9fc80-80c8-11ea-8fe3-2613f93cfcd5.png)

**Comment by SamuelHassine** [comment]
Could you please give me your MISP version number as well as the information about the galaxy you are using (ID, name, namespace, UUID, etc.).

Thanks!

**Comment by garanews** [comment]
![image](https://user-images.githubusercontent.com/16938405/79580425-443f4380-80c9-11ea-83e5-a921c1505d65.png)

about galaxy, tell me one that should work and I try

**Comment by garanews** [comment]
![image](https://user-images.githubusercontent.com/16938405/79581307-8d43c780-80ca-11ea-947d-4b966de6bc33.png)

**Comment by garanews** [comment]
So galaxy working only what you told  (intrusion set, malware, etc.)
What about tags (on event and on attributes?)

**Comment by garanews** [comment]
Hello @SamuelHassine , did you find some time to review this behavior?

**Comment by garanews** [comment]
same behavior also with v3.2.0:
misp event tlp is imported
galaxy is imported
misp event tags are not imported
misp attribute tags are not imported

**Comment by SamuelHassine** [comment]
I am working on it for the next release.

**Comment by SamuelHassine** [comment]
Fixed: https://demo.opencti.io/dashboard/reports/MISP_event. 

Will be in the 3.2.1.

**Comment by garanews** [comment]
I'm testing it, so with 3.2.1:
misp event tlp is imported
galaxy is imported
misp event tags are imported
misp attribute tags are **not** imported



![image](https://user-images.githubusercontent.com/16938405/80705414-abf08800-8ae6-11ea-9615-85abb3bfbd50.png)

**Comment by garanews** [comment]
ok probably got it: attribute tags not present under observables:

![image](https://user-images.githubusercontent.com/16938405/80706722-14d8ff80-8ae9-11ea-9372-04699ca025fe.png)


but under indicators:

![image](https://user-images.githubusercontent.com/16938405/80706833-4356da80-8ae9-11ea-983e-17881f62de2c.png)

**Comment by SamuelHassine** [comment]
Ok, this will be fixed in the next release.

**Comment by SamuelHassine** [comment]
The attribute tags will be added in indicators AND observables.

**Comment by garanews** [comment]
There is a way to update all data after this feature (in order to do not delete and import again)?

**Comment by SamuelHassine** [comment]
Solved in https://github.com/OpenCTI-Platform/client-python/issues/80.

**Comment by SamuelHassine** [comment]
@garanews: In the next version, the tags will be updated if you re-inject the data. So you will need to reset the import but do not delete anything.

**Comment by garanews** [comment]
Do you mean in 3.2.3?
I would try it:  any chance to bump the docker version?
