### ISSUE TITLE
MISP connector: does it need to see the rabbitmq port?

### ISSUE THREAD

**Issue by garanews** [OpenCTI-Platform/connectors#95]
## Description

{ Please provide a clear and concise description of the bug. }

## Environment
opencti docker
misp connector launched manually

## Reproducible Steps

Steps to create the smallest reproducible scenario:
launch misp.py

## Expected Output
working

## Actual Output
AMQPConnectorSocketConnectError: timeout("TCP connection attempt timed out: '172.16.2.62'/(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.16.2.62', 5672))"); first exception - None
 
## Additional information

Esposing rabbitmq port it seems working, so added 

```
    ports:
      - 5672:5672  
```

in docker-compose.yml

Is this a known behavior? 
Tried client-python creating some entry and it works also if rabbitmq is not exposed.

**Comment by SamuelHassine** [comment]
The answer is yes! All connectors must see the RabbitMQ port. They get their configuration through the API, so they will use the RabbitMQ parameters of the main platform configuration.
