### ISSUE TITLE
 AMQPConnectionWorkflowFailed: gaierror(-3, 'Temporary failure in name resolution'); 

### ISSUE THREAD

**Issue by Umamahesh-Loginsoft** [OpenCTI-Platform/connectors#972]
## Description

I configured and installed OpenCTI Latest version and wanting to create a new connector. After creating the new connector using the pre-defined template and after configuration then if I try to run the connector using standalone (python3 main.py) then I got the AMQPConnectionWorkflowFailed Issue.

## Environment

1. Linux ubuntu-virtual-machine 20.04
2. OpenCTI version: 5.5.2
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Install OpenCTI latest with docker
2. Configure it to a local use (localhost)
3. git clone https://github.com/OpenCTI-Platform/connectors
4. cd connectors/internal-enrichment/ipinfo
5. sudo pip3 install -r requirements.txt
6. Configuring config.yml 

opencti:
  url: 'http://localhost:8080'
  token: 'ChangeMe'

connector:
  id: 'ChangeMe'
  type: 'INTERNAL_ENRICHMENT'
  name: 'IpInfo'
  scope: 'IPv4-Addr'
  auto: true # Enable/disable auto-enrichment of observables
  confidence_level: 75 # From 0 (Unknown) to 100 (Fully trusted)
  log_level: 'info'

ipinfo:
  token: 'ChangeMe'
  max_tlp: 'TLP:AMBER'

## Error
Run it using python command python ipinfo.py:

![image](https://user-images.githubusercontent.com/63586146/212261109-6eddf3a5-3335-4478-a326-7367006d8783.png)

## Additional information

When I see the logs of rabbitmq, I see

[info] <0.6104.0> accepting AMQP connection <0.6104.0> (172.19.0.6:60962 -> 172.19.0.3:5672)
[info] <0.6104.0> connection <0.6104.0> (172.19.0.6:60962 -> 172.19.0.3:5672): user 'guest' authenticated and granted access to vhost '/'
[info] <0.6104.0> closing AMQP connection <0.6104.0> (172.19.0.6:60962 -> 172.19.0.3:5672, vhost: '/', user: 'guest')

All the docker containers are running with no crashes

**Comment by Umamahesh-Loginsoft** [comment]
@richard-julien or @SamuelHassine Can you please help me on this

**Comment by SamuelHassine** [comment]
Hello @Umamahesh-Loginsoft,

Log is pretty clear here, the connector is not able to access to RabbitMQ.

Kind regards,
Samuel

**Comment by Umamahesh-Loginsoft** [comment]
Hello @SamuelHassine It's worked already I forgot to close it Thanks!
