### ISSUE TITLE
GET EVERY MISP EVENT CREATED WITHOUT ADDING TAGS FOR IMPORT

### ISSUE THREAD

**Issue by shahidakhter786** [OpenCTI-Platform/connectors#986]
UNABLE TO FETCH DATA FROM MISP WITHOUT MENTIONING TAG OF IMPORT;OPENCTI OR OTHERS WHICH ARE MENTIONED IN DOCKER FILE. HOW CAN I DEAL WITH THIS ISSUE TO IMPORT EVERYTHING THAT I OWN FROM MISP TO OPENCTI//\\\

**Comment by SamuelHassine** [comment]
Hello,

This configuration in our production environments import everything from a MISP platform:

```
    - name: MISP_IMPORT_FROM_DATE
      value: "2010-01-01"
    - name: MISP_IMPORT_TAGS
      value: ""
    - name: MISP_IMPORT_TAGS_NOT
      value: ""
    - name: MISP_IMPORT_CREATOR_ORGS
      value: ""
    - name: MISP_IMPORT_CREATOR_ORGS_NOT
      value: ""
    - name: MISP_IMPORT_OWNER_ORGS
      value: ""
    - name: MISP_IMPORT_OWNER_ORGS_NOT
      value: ""
    - name: MISP_IMPORT_KEYWORD
      value: ""
    - name: MISP_IMPORT_DISTRIBUTION_LEVELS
      value: ""
    - name: MISP_IMPORT_THREAT_LEVELS
      value: ""
```

**Comment by shahidakhter786** [comment]
Thank you for your response.
Let me try it.
One more thing, map is also not working, not showing anything.
How to set their dataset? Any idea?
