### ISSUE TITLE
[MISP] Separate Display URL for connectors connecting to external threat source

### ISSUE THREAD

**Issue by cvdsouza** [OpenCTI-Platform/connectors#99]
## Problem to Solve

Going to use MISP as an example : 
MISP config file has one config for the url , this URL is utilized to display links to MISP events on the front-end of OpenCTI , as well as used by the connector to hook into MISP and pull events in. 

However, in a distributed deployment , there is a possibility that MISP sits on the same or different network or sub-net as OpenCTI, and hence a URL is not utilized , but rather the internal IP is utilized so that no special firewall rules need to be added for OpenCTI to talk to MISP. 

Since the MISP URL now contains an internal IP , this same internal IP is shown as the URL link on the front end of OpenCTI for when users want to access the original event of a report. 

The feature request is to separate the configs in the config file for such connectors allowing for a Web URL and connector URL , thereby allowing users to easily access events linked into a Report on the OpenCTI frontend. 

## Current Workaround

When a URL with the Internal IP is clicked, the user needs to replace the internal IP with the URL for the MISP instance manually. 

## Proposed Solution

The feature request is to separate the configs in the config file for such connectors allowing for a Web URL and connector URL , thereby allowing users to easily access events linked into a Report on the OpenCTI frontend. 

## Additional Information

Example : 
![image](https://user-images.githubusercontent.com/1090828/79915480-fdb55600-83f4-11ea-8ae3-c09ed6974fd7.png)

**Comment by SamuelHassine** [comment]
Thanks for this very clear feature requests, we will work on it.
