### ISSUE TITLE
Mitre Pre Attack removed

### ISSUE THREAD

**Issue by SYNchroACK** [OpenCTI-Platform/connectors#990]
Why Pre-Attack was removed from MITRE connector?

`MITRE_PRE_ATTACK_FILE_URL` at https://github.com/OpenCTI-Platform/connectors/commit/b4ed146b9d7d5b6c8a5106451f70cc5a3a69e5c6

**Comment by ckane** [comment]
I believe this was all combined into a single common ATT&CK framework in 2020: https://medium.com/mitre-attack/the-retirement-of-pre-attack-4b73ffecd3d3
